guardian/editions

- projects/native/App.js
- projects/native/package.json
- projects/native/yarn.lock
- install `react-navigation-fluid-transitions`
- fix a syntax error
Oh great, and why not, let's replace tabs with spaces 🤷‍♂
> Hotfixes in Native

- projects/EditionsIgnite/app/components/styled-text.tsx
- projects/EditionsIgnite/app/screens/article-screen.tsx
- projects/EditionsIgnite/package.json
First pass at an article:
- fetching dummy data from backend
- injecting raw HTML from dummy data
- basic styling of headline and body copy
c/c @jlieb10
> Preliminary article fetch and styling

- editions.code-workspace
- projects/backend/.vscode/launch.json
this just makes vscode play nicer with our somewhat monorepo
> Use workspaces to allow running projects

- projects/Mallard/README.md
The README has some indirect links and needs a bit more structure
* Improved structure to make the docs flow better
* Clarified links
> Clarify app readme

- .gitignore
- projects/Mallard/package.json
> add an android shake command to package.json

- .eslintrc.js
- package.json
- projects/Mallard/src/components/lists/grid.tsx
- projects/Mallard/src/components/lists/helpers.ts
- projects/Mallard/src/components/lists/list.tsx
- projects/Mallard/src/hooks/use-fetch.ts
- projects/Mallard/src/screens/article-screen.tsx
- projects/Mallard/src/screens/download-screen.tsx
- projects/Mallard/src/screens/front-screen.tsx
- projects/Mallard/src/screens/home-screen.tsx
- projects/Mallard/src/screens/issue-screen.tsx
- projects/backend/fronts.ts
- projects/backend/index.ts
- projects/backend/package.json
- projects/backend/s3.ts
- projects/backend/types/object.fromentries.d.ts
Backend has no code style rules currently, potentially leading to inconsistency and errors that could be caught by static analysis.
* Add validation scripts to backend
* Fix validation errors in backend
> Validate backend

- projects/backend/s3.ts
get s3 credentials from named profile
> S3 auto credentials

- .eslintrc.js
- projects/Mallard/src/types/common.d.ts
- projects/Mallard/tsconfig.json
- projects/backend/fronts.ts
- projects/backend/index.ts
- projects/backend/types/common.d.ts
Add shared types for API responses from backend.
> Aw shared types

- projects/Mallard/src/common.ts
- projects/Mallard/src/types/common.d.ts
- projects/Mallard/tsconfig.json
- projects/backend/common.ts
- projects/backend/fronts.ts
- projects/backend/index.ts
- projects/backend/s3.ts
- projects/backend/tsconfig.json
- projects/backend/types/object.fromentries.d.ts
This fixes the backend and inlines article paths into it.
> Fix backend

- riff-raff-android.yaml
To get Android things in build.gutools.co.uk
> Add riffyaml for android build

- projects/Mallard/src/helpers/files.ts
- projects/Mallard/src/hooks/use-fs.tsx
- projects/Mallard/src/screens/settings/download-screen.tsx
The download % was acting funny and this fixes it! By implementing a download manager like thing
> More robust download %

- projects/Mallard/src/screens/front-screen.tsx
A tiny change to test CD
* Fix typo
* Add opinion pillar to front
> Add opinion pillar (tiny change)

- projects/aws/lib/aws-stack.ts
- projects/aws/package.json
- projects/aws/yarn.lock
- projects/backend/package.json
- projects/backend/yarn.lock
This puts everything behind a cloudfront distribution, this is needed due to the apigateway changing url if changed too much. And frees us from the problem of path changes. 
todo: figure out how to send urls
> Use cloudfront

- projects/aws/lib/aws-stack.ts
Deployed on both prod and code, serving our backend.
> Fix cloudfront origin

- projects/aws/lib/aws-stack.ts
- projects/aws/package.json
- projects/aws/yarn.lock
- projects/backend/capi.ts
- projects/backend/controllers/article.ts
- projects/backend/controllers/fronts.ts
- projects/backend/controllers/issue.ts
- projects/backend/fronts.ts
- projects/backend/index.ts
- projects/backend/lastModified.ts
- projects/backend/package.json
- projects/backend/s3.ts
- projects/backend/tsconfig.json
- projects/backend/yarn.lock
To make the backend slightly neater and work with on device caching.
> Move the backend into controllers so it's easier to work with and add lastmodified as a nice surprise!

- .eslintrc.js
- projects/Mallard/package.json
- projects/Mallard/src/App.tsx
- projects/Mallard/src/components/article/article-header.tsx
- projects/Mallard/src/components/lists/grid.tsx
- projects/Mallard/src/components/lists/helpers.ts
- projects/Mallard/src/components/lists/list.tsx
- projects/Mallard/src/helpers/files.ts
- projects/Mallard/src/hooks/use-fetch.ts
- projects/Mallard/src/hooks/use-fs.tsx
- projects/Mallard/src/screens/article-screen.tsx
- projects/Mallard/src/screens/front-screen.tsx
- projects/Mallard/src/screens/settings/download-screen.tsx
- projects/Mallard/src/theme/appearance.ts
- projects/Mallard/yarn.lock
- projects/backend/common.ts
- projects/backend/index.ts
- projects/backend/package.json
- projects/backend/tsconfig.json
This fixes most of the lint issues, but there's still a lot of complaining from tsc.
> fix lint errors

- projects/Mallard/src/helpers/files.ts
- projects/Mallard/src/hooks/use-fs.tsx
- projects/Mallard/src/screens/settings/download-screen.tsx
This thing was driving me bonkers. Now it'll report mb downloaded if it doesn't know the %
> Fix download %

- projects/Mallard/package.json
- projects/backend/capi/elements.ts
- projects/backend/common.ts
- projects/backend/controllers/article.ts
- projects/backend/fronts.ts
This will parse CAPI block elements into something we can more easily render in Mallard. 
Also fixes front response. (I think I must have deleted my fixes by mistake)
>  Parse CAPI data to more easily renderable JSON

- projects/Mallard/src/components/layout/slide-card/index.tsx
This is a holdover of a previous experiment and we don't use it
> Remove cardOffset in slidecard

- projects/Mallard/Makefile
- projects/Mallard/package.json
Prep for iOS debug build pipeline
[**Trello Card**](https://trello.com/c/vsA7DzZB/182-editions-build-pipeline-ios)
* Add an iOS debug script
> Add iOS debug build command

- projects/Mallard/src/components/article/article-standfirst.tsx
- projects/Mallard/src/components/multiline.tsx
You can only make 4 multilines now, this lets you have as many as you want!
> Multilines of any length

- projects/Mallard/src/components/article/article-header.tsx
- projects/Mallard/src/components/chevron.tsx
- projects/Mallard/src/components/layout/slide-card/header.tsx
- projects/Mallard/src/components/layout/slide-card/index.tsx
- projects/Mallard/src/theme/spacing.ts
Have you seen the new designs? it's TINY this makes it tiny
> Smaller header

- projects/Mallard/Makefile
> Add xcode archive step to ios build process

- projects/Mallard/src/App.tsx
- projects/Mallard/src/components/article/index.tsx
> Make article responsive

- projects/backend/capi/assets.ts
- projects/backend/capi/elements.ts
- projects/backend/common.ts
add more element types to the backend
> add more element types!

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
we dont use geo or anticipate to use it and it's raising itunes connect warnings. we can always bring it back later?
> Remove geolocation

- projects/backend/s3.ts
> set creds for s3 only

- projects/Mallard/src/helpers/settings.ts
- projects/Mallard/src/screens/settings/api-screen.tsx
> default & code backend urls

- .eslintrc.js
- projects/Mallard/src/screens/article-screen.tsx
> Disable the display name

- projects/Mallard/src/App.tsx
- projects/Mallard/src/components/front/card-group.tsx
- projects/Mallard/src/components/front/card-group/card.tsx
- projects/Mallard/src/components/front/card-group/row.tsx
- projects/Mallard/src/components/front/cards.tsx
- projects/Mallard/src/components/front/index.tsx
- projects/Mallard/src/components/highlight.tsx
- projects/Mallard/src/screens/issue-screen.tsx
> Side by side cards

- editions.code-workspace
I want to stop accidentally breaking the build!
> Eslint in vs code

- projects/Mallard/src/components/article/article-header.tsx
- projects/Mallard/src/components/article/index.tsx
- projects/Mallard/src/components/layout/slide-card/header.tsx
- projects/Mallard/src/components/layout/slide-card/index.tsx
- projects/Mallard/src/navigation/index.ts
- projects/Mallard/src/screens/article-screen.tsx
- projects/Mallard/src/theme/spacing.ts
These are getting kinda slow to animate and this is a first pass at simplifying their view hierarchy and lazy loading the webview
> Optimise article cards a bit and remove unused code

- projects/Mallard/android/app/src/main/res/values/strings.xml
- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
- projects/Mallard/ios/Mallard/Info.plist
- projects/Mallard/src/helpers/words.ts
- projects/Mallard/src/screens/home-screen.tsx
- projects/Mallard/src/screens/settings-screen.tsx
For beta and such.
Do not merge yet, waiting for @blongden73 to provide us final graphics
> Rename 'Mallard' to 'Daily Edition'

- projects/backend/capi/articles.ts
- projects/backend/capi/atoms.ts
- projects/backend/fronts.ts
- projects/backend/s3.ts
- projects/backend/utils/try.ts
Somehow managed to unwire eslint from vscode for a while there. This fixes all lint issues in the backend.
> fix linter issues

- projects/Mallard/src/components/front/card-group/card.tsx
- projects/Mallard/src/components/front/card-group/text-block.tsx
- projects/Mallard/src/components/front/index.tsx
- projects/Mallard/src/theme/appearance.ts
- projects/Mallard/src/theme/spacing.ts
> Some demo polishes

- projects/Mallard/src/screens/home-screen.tsx
Annoying debug messages!
* Just use the `key` from the issues data rather than the data
> Fix duplicate key with issues

- projects/Mallard/src/components/front/item/item.tsx
- projects/Mallard/src/components/layout/slide-card/index.tsx
- projects/Mallard/src/helpers/positions.ts
- projects/Mallard/src/navigation/index.ts
- projects/Mallard/src/navigation/interpolators.ts
I'm not even sure tbh but here we go!!
Tech-wise I'm storing the last known screen space position of items on cards on a mutable global (`helpers/positions`) and using that to know where to animate an article from. if there's no known position it will just animate from the bottom which still kinda looks nice!
> Screen transitions

- projects/Mallard/fastlane/Fastfile
- projects/Mallard/ios/Mallard-tvOS/Info.plist
- projects/Mallard/ios/Mallard-tvOSTests/Info.plist
- projects/Mallard/ios/Mallard/Info.plist
- projects/Mallard/ios/MallardTests/Info.plist
As per discussion with @LATaylor-guardian this is required to allow the build to be pushed to internal beta testers and appropriate documentation is being prepared.
> Add ITSAppUsesNonExemptEncryption:false to all plists

- projects/Mallard/src/hooks/use-fetch.ts
- projects/Mallard/src/screens/home-screen.tsx
- projects/backend/index.ts
- projects/common/src/index.ts
Consume luke's flashy new `/issues` endpoint
> Pull issues from backend

- projects/backend/common.ts
- projects/backend/fronts.ts
> Break up articles for a collection into cards of a specific size.

- projects/Mallard/fastlane/Fastfile
this changes the testflight settings to run the external beta
> testflight settings

- projects/Mallard/src/components/article/article-header.tsx
- projects/Mallard/src/components/button/button.tsx
- projects/Mallard/src/screens/article-screen.tsx
> hide button in article

- package.json
don't do anything with the assets
...yet
> run metro bundler in the main build

- projects/Mallard/src/components/onboarding/onboarding-card.tsx
- projects/Mallard/src/components/styled-text.tsx
- projects/Mallard/src/onboarding/index.tsx
Let's leave this on hold until we have the final email but:
> More onboarding

- projects/Mallard/src/components/article/index.tsx
- projects/Mallard/src/screens/article-screen.tsx
- projects/backend/capi/articles.ts
- projects/backend/fronts.ts
- projects/common/src/index.ts
Support crossword article type.
- Makes changes to return crossword articles on the backend.
- Introduces an ArticleController within the app to decide how to render an article based on its type.
> Support crossword article type

- projects/Mallard/package.json
to test the app on ipad more easily
> yarn run-ipad to run the app on an ipad

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
- projects/Mallard/src/components/front/collection-page/collection-page.tsx
- projects/Mallard/src/components/front/helpers.ts
- projects/Mallard/src/components/front/item/item.tsx
- projects/Mallard/src/components/front/layouts.ts
Adds two new card types to fronts, and styles up some items like standfirst on the standard card.
> Bl new cards

- projects/Mallard/src/components/article/article-header.tsx
- projects/Mallard/src/components/article/article-standfirst.tsx
- projects/Mallard/src/components/article/index.tsx
- projects/Mallard/src/components/front/collection-page/collection-page.tsx
- projects/Mallard/src/components/front/item/item.tsx
- projects/Mallard/src/components/layout/clipFromTop/clipFromTop.tsx
- projects/Mallard/src/helpers/positions.ts
- projects/Mallard/src/navigation/index.ts
- projects/Mallard/src/navigation/interpolators.ts
- projects/Mallard/src/screens/article-screen.tsx
- projects/Mallard/src/theme/appearance.ts
Sorry no screenies but it looks SO SMOOTH
> Link the card clipping to the animation state

- console.d.ts
- projects/Mallard/src/components/article/index.tsx
- projects/Mallard/src/components/article/types/gallery.tsx
- projects/backend/capi/articles.ts
- projects/backend/capi/elements.ts
- projects/backend/utils/html.ts
> "Display" "galleries"

- projects/Mallard/src/helpers/transform.ts
> Make tsc happy

- projects/Mallard/src/components/article/article-header.tsx
- projects/Mallard/src/components/front/collection-page/collection-page.tsx
- projects/Mallard/src/components/front/collection-page/row.tsx
- projects/Mallard/src/components/front/index.tsx
- projects/Mallard/src/components/front/item/item.tsx
- projects/Mallard/src/components/layout/clipFromTop/clipFromTop.tsx
- projects/Mallard/src/components/layout/slide-card/header.tsx
- projects/Mallard/src/components/layout/slide-card/helpers.ts
- projects/Mallard/src/components/layout/slide-card/index.tsx
- projects/Mallard/src/helpers/transform.ts
- projects/Mallard/src/hooks/use-issue.ts
- projects/Mallard/src/navigation/helpers.tsx
- projects/Mallard/src/navigation/interpolators.ts
- projects/Mallard/src/screens/article-screen.tsx
> Actually scroll through the articles

- docs/03-✅-backend-principles.md
Adding the principles we discussed to the docs giving this somewhere to live.
> Add todays discussion to docs

- package.json
fix the server build by not doing this
> dont ci bundling

- projects/Mallard/src/components/weather.tsx
- projects/Mallard/src/components/weather/weatherIcon.tsx
> Aw bad weather fix

- projects/Mallard/src/components/layout/ui/issue-row.tsx
- projects/Mallard/src/helpers/issues.ts
- projects/Mallard/src/paths/index.ts
- projects/Mallard/src/screens/issue-screen.tsx
- projects/backend/controllers/fronts.ts
- projects/backend/controllers/issue.ts
- projects/backend/fronts.ts
- projects/backend/fronts/issue.ts
- projects/backend/index.ts
- projects/backend/s3.ts
- projects/backend/utils/try.ts
- projects/common/src/index.ts
This is my first attempt at using the new fronts api, it's a bit naïve. Also starts to change dates to ISO strings internally. 
TODO (but not in this pr):
> Use the new fronts api 🎈

- projects/Mallard/src/components/layout/ui/issue-row.tsx
- projects/Mallard/src/helpers/issues.ts
- projects/Mallard/src/paths/index.ts
- projects/Mallard/src/screens/issue-screen.tsx
- projects/backend/controllers/fronts.ts
- projects/backend/controllers/issue.ts
- projects/backend/fronts.ts
- projects/backend/fronts/issue.ts
- projects/backend/index.ts
- projects/backend/s3.ts
- projects/backend/utils/try.ts
- projects/common/src/index.ts
> Revert "Revert "Use the new fronts api 🎈""

- projects/backend/controllers/issue.ts
> update available issue

- projects/backend/capi/articles.ts
linter fixes so we can build again
> lint fix build

- projects/Mallard/ios/exports-plists/release.plist
> Use production icloud on testflight release

- projects/backend/controllers/issue.ts
- projects/common/src/index.ts
because the app expects key to be the issue path
> feed the app the keys it expects.

- projects/Mallard/src/components/front/item/item.tsx
- projects/Mallard/src/components/styled-text.tsx
> Clean up showcase cards

- projects/Mallard/package.json
- projects/Mallard/src/App.tsx
- projects/Mallard/yarn.lock
The warnings were upsetting me 😢 
* Upgrading React Navigation to `3.11.0`
* Update persistence mechanism for `__DEV__` only
> feature: Update React Navigation

- .github/pull_request_template.md
To fix the spelling mistake in the Pull Request Template.
> fix: Update spelling mistake

- projects/aws/package.json
- projects/aws/yarn.lock
- projects/backend/package.json
- projects/backend/yarn.lock
- yarn.lock
this upgrades deps in backend and aws
also aws-cdk which is now v1.0 (with no breaking changes https://github.com/aws/aws-cdk/blob/master/CHANGELOG.md)
>  upgrade deps

- projects/backend/controllers/issue.ts
- projects/backend/s3.ts
- projects/common/src/index.ts
This pr lists the issues in the published bucket.
> List of issues!

- .eslintrc.js
- projects/archiver/local.ts
gets rid of annoying react version not set error
> small linter fixes

- projects/Mallard/src/App.tsx
Fixes navigation breaking on `dev` when routes change. Uses a fairly "pragmatic" hack to handle the error, react to it, and ditch the previous persisted route.
> Handle react navigation errors

- projects/Mallard/src/components/front/collection-page/collection-page.tsx
- projects/Mallard/src/components/front/wrapper.tsx
Design snagging
[**Trello Card ->**](https://trello.com/c/opEncVf0/286-clean-up-design-debt-first-set-of-snags-timebox)
> Reduce spacing around sliders

- projects/Mallard/src/theme/color.ts
Updated for snagging:
[**Trello Card ->**](https://trello.com/c/opEncVf0/286-clean-up-design-debt-first-set-of-snags-timebox)
> Change background to be slightly darker

- projects/Mallard/src/screens/article-screen.tsx
Something broke article scrolling recently ... this fixes it 👌
> Fix article scroll

- projects/backend/.gitignore
- projects/backend/capi/__tests__/kickerPicker.spec.ts
- projects/backend/capi/kickerPicker.ts
- projects/backend/package.json
- projects/backend/yarn.lock
Fixes a problem where missing tags would throw an error in the kicker picker. This still needs tests, but as it's still a WIP that is prone to a lot of change I've let it for now.
> Fix issue where missing tags would fail the picker

- projects/Mallard/src/components/issue/issue-row.tsx
- projects/Mallard/src/components/issue/issue-title.tsx
- projects/Mallard/src/components/layout/ui/row.tsx
- projects/Mallard/src/screens/home-screen.tsx
- projects/Mallard/src/screens/issue-screen.tsx
- projects/Mallard/src/theme/appearance.ts
> First pass at settings header and issue screen redesign.

- projects/Mallard/src/hooks/use-alpha-in.ts
- projects/archiver/downloader.ts
- projects/archiver/main.ts
- projects/archiver/media.ts
- projects/archiver/upload.ts
- projects/archiver/zipper.ts
- projects/backend/image.ts
- projects/common/src/index.ts
that doesn't work.
This PR makes the bucket respect the API layout.
> Don't have /data and /media in s3

- projects/Mallard/src/components/button/button.tsx
- projects/Mallard/src/components/layout/ui/row.tsx
- projects/Mallard/src/components/layout/ui/switch.tsx
- projects/Mallard/src/components/link.tsx
- projects/Mallard/src/components/styled-text.tsx
- projects/Mallard/src/helpers/settings.ts
- projects/Mallard/src/helpers/settings/defaults.ts
- projects/Mallard/src/helpers/words.ts
- projects/Mallard/src/screens/settings-screen.tsx
- projects/Mallard/src/screens/settings/gdpr-consent-screen.tsx
- projects/Mallard/src/theme/appearance.ts
- projects/Mallard/src/theme/typography.ts
This is how it looks like now:
> Update GDPR settings according to mockup

- projects/Mallard/src/helpers/webview.ts
> fix crossies in PROD

- projects/Mallard/src/hooks/use-api.ts
> Open on the latest issue instead of on the newest one

- projects/Mallard/src/components/article/article-byline/__tests__/__snapshots__/article-byline.spec.tsx.snap
- projects/Mallard/src/components/article/article-byline/index.tsx
- projects/Mallard/src/components/article/article-header/__tests__/__snapshots__/long-read-header.spec.tsx.snap
- projects/Mallard/src/components/article/article-header/__tests__/__snapshots__/news-header.spec.tsx.snap
- projects/Mallard/src/components/article/article-header/__tests__/__snapshots__/opinion-header.spec.tsx.snap
- projects/Mallard/src/components/article/article-header/news-header.tsx
- projects/Mallard/src/components/article/article-header/opinion-header.tsx
- projects/Mallard/src/components/article/article-headline/__tests__/__snapshots__/article-headline.spec.tsx.snap
- projects/Mallard/src/components/article/article-kicker/__tests__/__snapshots__/article-kicker.spec.tsx.snap
- projects/Mallard/src/components/article/article-kicker/index.tsx
- projects/Mallard/src/components/article/article-multiline/__tests__/__snapshots__/article-multiline.spec.tsx.snap
- projects/Mallard/src/components/article/article-multiline/index.tsx
- projects/Mallard/src/components/article/index.tsx
- projects/Mallard/src/components/article/styles.ts
- projects/Mallard/src/components/button/button.tsx
- projects/Mallard/src/components/front/item/item.tsx
- projects/Mallard/src/components/front/item/text-block.tsx
- projects/Mallard/src/components/issue/issue-title.tsx
- projects/Mallard/src/components/layout/ui/errors/error-message.tsx
- projects/Mallard/src/components/layout/ui/row.tsx
- projects/Mallard/src/components/onboarding/onboarding-card.tsx
- projects/Mallard/src/components/styled-text.tsx
- projects/Mallard/src/screens/article-screen.tsx
- projects/Mallard/src/screens/settings-screen.tsx
- projects/Mallard/src/screens/settings/api-screen.tsx
- projects/Mallard/src/theme/appearance.ts
- projects/Mallard/src/theme/color.ts
- projects/Mallard/src/theme/typography.ts
it matches the latest designs. I also moved some paddings/etc outside of `appearance` and into the views
> Use type scale for everything

- projects/archiver/main.ts
- projects/archiver/summary.ts
- projects/aws/lib/aws-stack.ts
/issues now works on the archive
> Make indexes for s3!

- projects/archiver/main.ts
- projects/aws/lib/aws-stack.ts
Add invocation policy for tools to run the archiver.
@akash1810
> Allow Archiver lambda to be invoked by a bucket in the cmsFronts account

- projects/archiver/media.ts
need to add slideshows and bylines to the archive
> archive aux images

- projects/Mallard/.env.production.js
Removed it for testing and never added it back in!
> Add missing env var

- projects/Mallard/.env.production.js
- projects/Mallard/android/app/build.gradle
- projects/Mallard/android/app/src/main/java/com/guardian/editions/MainApplication.java
- projects/Mallard/android/settings.gradle
- projects/Mallard/index.js
- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
- projects/Mallard/ios/Mallard/AppDelegate.m
- projects/Mallard/package.json
- projects/Mallard/src/components/login-overlay.tsx
- projects/Mallard/src/hooks/use-alpha-in.ts
- projects/Mallard/yarn.lock
We need to provide logging to the app for both crash reporting and our own custom logging.
How to use Sentry:
https://docs.sentry.io/clients/react-native/config/
> Integrate with Sentry.

- projects/backend/image.ts
- projects/common/src/index.ts
to make available a bigger range of image sizes to save on download
> new image sizes

- docs/04-✅-paths.md
- docs/05-✅-archiver-s3-event.md
- editions.code-workspace
Just documenting the path and archiver slightly more.
> Add some new docs

- projects/backend/capi/articles.ts
- projects/common/src/index.ts
fetch the star rating from CAPI for #279
> Get star rating from CAPI

- projects/Mallard/package.json
- projects/Mallard/src/authentication/__tests__/auth-context.spec.ts
- projects/Mallard/src/authentication/auth-context.tsx
- projects/Mallard/src/components/article/article-multiline/__tests__/__snapshots__/article-multiline.spec.tsx.snap
- projects/Mallard/src/services/__tests__/content-auth-service.spec.ts
- projects/Mallard/yarn.lock
Android was broken due to incompatibilities in AndroidX. Downgrading NetInfo solves this.
> fix: Android now works with downgraded netinfo

- projects/Mallard/src/components/front/collection-page.tsx
- projects/Mallard/src/components/front/index.tsx
- projects/Mallard/src/screens/issue-screen.tsx
[look at this](https://github.com/facebook/react-native/issues/13316)
> i think this fixes the fronts disappearing?

- projects/Mallard/ios/Podfile.lock
forgot to update my podfile lock
> podfile lock

- projects/Mallard/ios/Podfile
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
Automagically install cocoa pods
> I'd rather auto install cocoa pods

- projects/archiver/media.ts
- projects/backend/capi/articles.ts
- projects/backend/capi/atoms.ts
- projects/backend/capi/consts.ts
- projects/backend/capi/elements.ts
- projects/backend/image.ts
- projects/backend/package.json
- projects/backend/s3.ts
- projects/backend/yarn.lock
- projects/common/src/index.ts
This makes everything discussed from mediaAtoms available in the backend.
> support media atom in backend

- projects/Mallard/src/helpers/__tests__/screen.spec.ts
- projects/Mallard/src/helpers/screen.ts
In order to download the correct Image zip, we need to know the maximum breakpoint for the device. This is the starting point for that
* Added helper function
* Tested it!
> feat: Max Screen Size helper

- projects/Mallard/src/components/article/html/render.ts
- projects/Mallard/src/components/article/index.tsx
- projects/Mallard/src/helpers/webview.ts
> Initial pass to render media atoms within article body.

- projects/Mallard/src/authentication/auth-context.tsx
- projects/Mallard/src/components/article/article-header/opinion-header.tsx
- projects/Mallard/src/components/article/article-header/types.ts
- projects/Mallard/src/components/article/index.tsx
- projects/Mallard/src/components/login/login-overlay.tsx
> Add cutout images toOpinion header.

- projects/Mallard/src/navigation/navigators/header.tsx
> Make 'Back' button display an arrow.

- projects/Mallard/src/components/article/html/render.ts
> Render inline images within article (works online only)

- projects/Mallard/ios/Podfile
> Restore fishhook dep as it is needed after all.

- docs/05-✅-archiver-s3-event.md
- docs/06-✅-to-use-step-functions.md
- projects/archiver/main.ts
- projects/archiver/s3.ts
- projects/archiver/src/invoke.ts
- projects/archiver/src/issueTask.ts
- projects/archiver/upload.ts
- projects/aws/lib/aws-stack.ts
- projects/aws/lib/step-function.ts
- projects/aws/lib/tools.ts
- projects/aws/package.json
- projects/aws/yarn.lock
- projects/backend/utils/try.ts
- riff-raff.yaml
We want to know when the archiver fails and succeeds and be able to control sending notifications. This allows that.
> Use step function for archiving

- projects/aws/lib/aws-stack.ts
> fix broken deploy

- projects/Mallard/android/app/src/main/AndroidManifest.xml
- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
- projects/Mallard/ios/Mallard/Info.plist
To ensure orientation
[**Trello Card ->**](https://trello.com/c/fhQCu4WN/468-orientation-implementation)
* Update the Android manifest to lock it to portrait
* Update the info.plist to lock only iPhones to portrait.
> Feat: Orientation

- projects/Mallard/src/screens/settings/cas-sign-in-screen.tsx
Otherwise you're stuck on the login screen with no knowledge you've succeeded ...
> Exit CAS sign in screen after successful login

- projects/Mallard/src/authentication/__tests__/credentials-chain.spec.ts
- projects/Mallard/src/authentication/__tests__/fixtures.ts
- projects/Mallard/src/authentication/__tests__/helpers.spec.ts
- projects/Mallard/src/authentication/__tests__/test-helpers.ts
- projects/Mallard/src/authentication/credentials-chain.ts
- projects/Mallard/src/authentication/helpers.ts
- projects/Mallard/src/authentication/storage.ts
Fixes a small logout bug in login and add tests. I know I could use mocks and I know people prefer mocks but I'll refactor that another time ... it's on my personal to do.
> Fix for login (reset credentials) and add tests

- projects/backend/capi/articles.ts
- projects/backend/fronts.ts
- projects/backend/fronts/issue.ts
- projects/common/src/index.ts
this adds sports score and makes swatch non optional as it's been live in facia for long enough now
> update from fronts data model

- projects/archiver/src/invoke.ts
> name step function executions

- projects/backend/capi/articles.ts
As discussed with Blishen and Katy.
> Use trail for standfirst

- projects/Mallard/src/components/login/login-layout.tsx
- projects/Mallard/src/components/toast/toast.tsx
- projects/Mallard/src/screens/article-screen.tsx
- projects/Mallard/src/screens/settings/cas-sign-in-screen.tsx
> Make CAS sign up screen look like design.

- projects/Mallard/src/components/article/html/render.ts
- projects/Mallard/src/components/article/index.tsx
- projects/Mallard/src/components/article/types/article.tsx
- projects/Mallard/src/components/article/wrap/max-width.tsx
- projects/Mallard/src/components/article/wrap/wrap.tsx
- projects/Mallard/src/components/layout/slide-card/index.tsx
- projects/Mallard/src/screens/article-screen.tsx
- projects/Mallard/src/screens/article/body.tsx
- projects/Mallard/src/screens/article/slider.tsx
This was originally just the support for iPad images but as I was making it I extracted some components to prevent rerenders and overall have a nicer codebase to grok
Haven't actually implemented image types, that will come in later, but here's how they could look like:
> [Health] Refactor article + [Feat] Support for ipad images

- projects/Mallard/src/components/layout/animators/clipFromTop.tsx
- projects/Mallard/src/components/layout/slide-card/index.tsx
- projects/Mallard/src/navigation/navigators/article/transition.tsx
The slidecard was a bit wonky, this fixes parts of it
> Fix some slide behaviors

- projects/Mallard/src/components/front/items/base/item-tappable.tsx
- projects/Mallard/src/components/front/items/base/text-block.tsx
- projects/Mallard/src/components/front/items/items.tsx
- projects/Mallard/src/theme/typography.ts
> Slightly smaller fonts on tablet fronts

- projects/backend/capi/elements.ts
- projects/common/src/index.ts
To display images per their roles in the app
> add roles to inline images

- projects/Mallard/android/app/src/main/java/com/guardian/editions/MainApplication.java
- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
- projects/Mallard/ios/Mallard/Ophan/Ophan.swift
- projects/Mallard/ios/MallardTests/MallardTests.m
> Make build fixes and make ophan a noop

- projects/Mallard/src/App.tsx
- projects/Mallard/src/components/layout/ui/errors/error-message.tsx
- projects/Mallard/src/helpers/words.ts
- projects/Mallard/src/screens/home-screen.tsx
- projects/Mallard/src/screens/issue-screen.tsx
> Change copy of offline screen.

- projects/Mallard/src/App.tsx
- projects/Mallard/src/components/issue/issue-row.tsx
- projects/Mallard/src/helpers/words.ts
> Show toast when trying to download issue from picker offline.

- projects/Mallard/index.js
> Disable font scaling on Text components.

- projects/Mallard/src/components/layout/ui/row.tsx
- projects/Mallard/src/components/lists/list.tsx
- projects/Mallard/src/screens/settings/already-subscribed-screen.tsx
> Correct design for 'Already a subscriber' settings page.

- projects/Mallard/src/components/article/article-image.tsx
- projects/Mallard/src/components/front/image-resource.tsx
- projects/Mallard/src/screens/issue-screen.tsx
i hid some subviews and changed the image rescaling and scrolling is hella smooth on my pixel 3 now
> better android perf

- projects/Mallard/src/components/sign-in-failed-modal-card.tsx
Update title
[**Trello Card ->**](https://trello.com/c/kHPFsjME/588-activation-flow-title-of-subscription-not-found-dialog-incorrect)
> Change title

- projects/Mallard/src/components/article/html/pull-quote.ts
- projects/Mallard/src/components/article/html/render.ts
- projects/Mallard/src/theme/typography.ts
> Pullquotes

- projects/backend/capi/articleTypePicker.ts
Tone tag for letters fixed, and changing the stack to make sure long reads are correctly identified
* tone/letterstotheeditor changed to tone/letters 
* promoted long reads above immersives in all cases
> Indy Ana and the templates of doom

- projects/Mallard/src/components/onboarding/onboarding-card.tsx
- projects/Mallard/src/theme/typography.ts
> Ensure location of close cross is consistent across devices.

- projects/Mallard/src/screens/article-screen.tsx
- projects/Mallard/src/screens/article/body.tsx
Fix crosswords not appearing and fix slight overflow on article body.
> Tweak heights

- projects/Mallard/src/components/missing-iap-modal-card.tsx
- projects/Mallard/src/components/onboarding/onboarding-card.tsx
- projects/Mallard/src/components/sign-in-failed-modal-card.tsx
- projects/Mallard/src/components/sign-in-modal-card.tsx
- projects/Mallard/src/components/sub-found-modal-card.tsx
> Fix 'Subscription found' modal across devices.

- projects/Mallard/android/app/src/main/java/com/guardian/editions/ophan/RNOphanModule.java
- projects/Mallard/ios/Mallard/Ophan/Ophan.m
- projects/Mallard/ios/Mallard/Ophan/Ophan.swift
- projects/Mallard/ophan/src/commonMain/kotlin/ophan/Ophan.kt
- projects/Mallard/src/App.tsx
- projects/Mallard/src/components/issue/issue-row.tsx
- projects/Mallard/src/components/sign-in-modal-card.tsx
- projects/Mallard/src/screens/article-screen.tsx
- projects/Mallard/src/screens/home-screen.tsx
- projects/Mallard/src/services/__tests__/ophan.spec.ts
- projects/Mallard/src/services/ophan.ts
Implement Ophan tracking in the app based on the spreadsheet. Please see the following tickets for the work that has been completed
[Log Screen Views](https://trello.com/c/mgDW7PO6/317-ophan-analytics-log-screen-views)
[Centralised TS Library](https://trello.com/c/583tgspz/526-ophan-centralised-ts-library)
As a result of this work, there are some incompleted items listed below:
[Set User Id Implementation](https://trello.com/c/Nd4wLlvx/637-ophan-setuserid-implementation)
[Native tidy up](https://trello.com/c/Sv3N2QEf/636-ophan-native-tidy-up)
* Add API for Ophan in services
* Test this API
* Add required native functionality for that
* Add Kotlin Multiplatform code to interface with the API.
* Implemented the analytics based on the spreadsheet
> feat: Ophan implementation

- projects/Mallard/src/components/article/article-header/index.tsx
- projects/Mallard/src/components/article/article-header/opinion-header.tsx
> Implement 'Analysis' header design.

- projects/Mallard/package.json
- projects/Mallard/src/components/article/article-header/obituary-header.tsx
This was causing the app to crash on Android.
@RichieAHB told me that this was agreed to be removed. Therefore is now removed.
> fix: Remove Image Filter

- projects/Mallard/package.json
- projects/Mallard/src/helpers/diagnostics.ts
- projects/Mallard/yarn.lock
This was causing some issues with Testflight as I didn't read the README properly from this project. Additionally, silent notifications don't require notification permissions so this was redundant anyway.
> Remove permissions as we don't require them

- projects/Mallard/src/components/front/items/helpers/text-block.tsx
[**Trello Card ->**](https://trello.com/c/GmV0KZ3G/597-cards-disable-headline-hyphenation-on-android)
> feat: Stop hyphenation on Android

- projects/Mallard/ophan/build.gradle
- projects/Mallard/ophan/src/commonMain/kotlin/ophan/Ophan.kt
Updates Ophan Multiplatform to fix the PageView URL issue and provides a Debug flag.
> feat: Put Ophan into Debug and fix PageView URL

- projects/Mallard/android/app/src/main/res/values/strings.xml
- projects/Mallard/ios/Mallard/Info.plist
We have been chatting about the name and seeing how it fits on a screen. This is to indulge and invoke conversation.
> feat: Change the App Name

- projects/Mallard/src/components/issue/issue-row.tsx
This removes the ability to accidentally download an issue twice
> Fix issue where issues can be redownloaded

- projects/Mallard/src/screens/settings/gdpr-consent-screen.tsx
Required copy updates for the Privacy Settings screen.
[**Trello Card ->**](https://trello.com/c/JHx9MmTP/562-minor-copy-updates-for-the-privacy-settings-screen)
> chore: Update Privacy Settings copy

- projects/Mallard/src/components/article/html/pull-quote.ts
- projects/Mallard/src/components/article/html/render.ts
- projects/Mallard/src/theme/spacing.ts
- projects/backend/capi/elements.ts
- projects/common/src/collection/card-layouts.ts
- projects/common/src/index.ts
Some minor design nits to the PQs
> Fix pull quotes

- projects/Mallard/src/screens/article/body.tsx
- projects/Mallard/src/screens/article/slider.tsx
This seemed to cause less GC events on Android.
> Memoize the articlescreenbody

- projects/Mallard/src/components/slider/draw/lozenge.tsx
> Fix lozenge on small front names

- projects/Mallard/src/App.tsx
- projects/Mallard/src/helpers/files.ts
- projects/Mallard/src/helpers/push-notifications.ts
- projects/Mallard/src/helpers/settings.ts
- projects/Mallard/src/helpers/settings/defaults.ts
- projects/Mallard/src/screens/settings/dev-zone.tsx
As a result of the #451 refactor, this removed the download functionality. This reinstates it and uses the new API.
> fix: Downloads

- projects/Mallard/src/App.tsx
- projects/Mallard/src/components/update-ip-address.tsx
- projects/Mallard/src/components/weather.tsx
- projects/Mallard/src/helpers/fetch.ts
- projects/Mallard/src/helpers/fetch/cache.ts
- projects/common/src/index.ts
- IP address on mobile devices in not the perfect solution for location based services,
but for launch it allows us to display the weather for a users approximate location
without having to use geolocation and lat,lon which would take more time to implement
given the need to ask for permission to use location services. To be revisited post launch.
> Implement location aware Weather using IP address.

- projects/Mallard/src/authentication/__tests__/helpers.spec.ts
- projects/Mallard/src/authentication/helpers.ts
- projects/Mallard/src/screens/settings-screen.tsx
Hide the 🦆 a bit more 👇 
[**Trello Card ->**](https://trello.com/c/Bs9IwO56/563-dont-ship-duck-menu-access-to-the-public)
> Tuck away the duck

- projects/Mallard/src/helpers/__tests__/files.spec.ts
- projects/Mallard/src/helpers/files.ts
- projects/Mallard/src/helpers/push-notifications.ts
- projects/Mallard/src/helpers/settings.ts
- projects/Mallard/src/helpers/settings/defaults.ts
- projects/common/src/__tests__/fixtures/IssueSummary.ts
@LATaylor-guardian mentioned that there was a bit of duplication in #522. This centralises and tests this removal of duplication.
> test: implement matchSummaryToKey and test

- projects/Mallard/README.md
- projects/backend/README.md
Onboarding is a pain, this doesn't make things _much_ better ... but it's something.
> Add some more build steps to Mallard README

- projects/backend/controllers/__tests__/issue.spec.ts
Fixes a backend test, which will mean we can run tests in CI.
> Fix issue test

- projects/editions-crossword-renderer-app/package.json
We don't care that this has no tests ... thanks `yarn init` 🙄
> Don't error on crossword test

- projects/Mallard/src/screens/settings/default-info-text-webview.tsx
Webview was not changing the height of the webview based on the content within it.
[**Trello Card ->**](https://trello.com/c/iFiqyQnc/633-bug-privacy-policy-tcs-and-faqs-not-loading-properly-on-ipad-iphone-and-on-android)
> fix: Terms and Privacy scrolling

- projects/Mallard/ios/Mallard/Info.plist
Due to the app submission being successful, the App Store wont allow us to keep the same version. As a result i have increased it.
> Fix Update the version

- projects/Mallard/src/components/layout/ui/row.tsx
- projects/Mallard/src/navigation/navigators/underlay/transition.tsx
I've done this by eye across as many of the simulators on ios as possible after noticing it overlapping on iPhone 8.
> Improve issue picker display across more ios devices.

- projects/Mallard/package.json
- projects/Mallard/yarn.lock
Update the zipping package to remove a vulnerability
[**Trello Card ->**](https://trello.com/c/z4JNxsJX/763-security-alert-appearing-on-the-google-play-store)
> fix: Update Package to fix vulnerability

- projects/Mallard/src/components/front/collection-page.tsx
- projects/Mallard/src/components/front/items/helpers/text-block.tsx
- projects/Mallard/src/components/front/items/helpers/types.tsx
- projects/Mallard/src/components/front/items/image-items.tsx
- projects/Mallard/src/components/front/items/super-items.tsx
otherwise they'll show up orange but as news, this matches almost all the design specs except obits, which can be a followup
> Only style opinion cards for opinion articles

- projects/Mallard/src/components/front/index.tsx
- projects/Mallard/src/hooks/use-article.tsx
- projects/Mallard/src/screens/article/body.tsx
> Grey obits

- projects/aws/lib/step-function.ts
ELK is a great place to view the step function logs but being able to filter or view the log origin is even better. Tagging lambdas means that the logs are tagged appropriately too.
> Add tags to the lambdas to make it nicer in ELK

- projects/Mallard/package.json
- projects/Mallard/yarn.lock
> Update package to work with Xcode 11

- projects/aws/lib/aws-stack.ts
At the moment the whole world can see the preview endpoints. This locks it down the the guardian office. This is still not ideal but it's a very cheap starting point that we can get out very quickly for beta.
[**Trello Card ->**](https://trello.com/c/i0tRpICn)
* Add a resource policy to the API gateway
> Add access control by IP for preview

- projects/Mallard/src/helpers/diagnostics.ts
Give us more information as a large part of our App is around downloading editions.
[**Trello Card ->**](https://trello.com/c/rligoCZC/753-disk-space-being-used-on-users-device-add-it-in-the-diagnostic-data-received-from-users)
> feat: Disk Space Diagnostics

- projects/Mallard/README.md
README change: fixing order of yarn commands in Mallard
> README change: fixing order of yarn commands in Mallard

- projects/Mallard/src/helpers/action-sheet.ts
- projects/Mallard/src/helpers/diagnostics.ts
- projects/Mallard/src/helpers/release-stream.ts
- projects/Mallard/src/helpers/words.ts
This adds some opt out text to beta users:
@blishen @LATaylor-guardian - thoughts?
> Add beta opt out text to bug action sheet

- projects/Mallard/src/hooks/use-api.ts
A couple of functions not being used and getting in the way.
> chore: Remove Unused Hooks

- projects/Mallard/src/components/article/html/render.ts
- projects/Mallard/src/components/article/wrap/multiline-wrap.tsx
- projects/Mallard/src/components/layout/animators/fader.tsx
> Fix scrolling on android

- projects/Mallard/src/components/article/html/header.ts
> White immersive HTML

- projects/common/src/index.ts
The crossies react app needs the crossword id as a string to match [this](https://github.com/zetter/react-crossword/blob/6a1631bd4deb5400d13660a3b8b0fbf6a134cba9/src/stylesheets/crosswords/_vars.scss) css file
I have no idea what dian is sadly so that one won't be rendered for now? but if anybody can tell me the row numbers I can add it to the react app
> Name crossies

- projects/Mallard/src/helpers/settings/defaults.ts
In lieu of the webview headers being at parity we are flicking this back on ...
> Default to the wobble for now

- projects/Mallard/src/services/errors.ts
> Add dev environment to sentry

- projects/Mallard/src/components/article/html/header.ts
- projects/Mallard/src/components/article/types/article-new.tsx
> Design snags on the headers

- projects/Mallard/src/components/article/article-header/types.ts
- projects/Mallard/src/components/article/html/header.ts
- projects/Mallard/src/components/article/html/icon/quotes.ts
- projects/Mallard/src/components/article/html/pull-quote.ts
- projects/Mallard/src/components/article/html/rating.ts
- projects/Mallard/src/components/article/html/render.ts
- projects/Mallard/src/components/stars/stars.tsx
- projects/Mallard/src/helpers/webview.ts
> analysis! stars! quotes! reviews! swipe to close!

- projects/Mallard/src/screens/article/slider.tsx
> Re-instate article slider on Android.

- projects/Mallard/src/components/article/html/header.ts
- projects/Mallard/src/components/article/html/render.ts
> More random design snags

- projects/Mallard/src/components/article/types/article/webview.tsx
This fixes the missing webview header images.
> Set empty `baseUrl`

- projects/Mallard/src/helpers/settings/defaults.ts
👇 
[**Trello Card ->**](https://trello.com/c/Yk8T4Bw4/850-swap-the-default-to-html-headers)
> feat: Use HTML headers by default

- projects/Mallard/src/components/article/article-header/types.ts
- projects/Mallard/src/components/article/html/header.ts
- projects/archiver/src/tasks/image/helpers/media.spec.ts
- projects/backend/__tests__/helpers/fixtures.ts
- projects/backend/capi/articles.ts
- projects/common/src/index.ts
Contributor name in bold, role in italics and default colour.
> Use bylineHtml for bylines to support correct design.

- projects/Mallard/src/components/article/html/header.ts
> Make sure standfirst isn't in italics.

- projects/Mallard/src/helpers/fetch.ts
- projects/Mallard/src/helpers/push-notifications.ts
- projects/Mallard/src/helpers/settings/defaults.ts
Not sure if users are actually receiving push notifications. This will help us debug issues with downloads.
> feat: Notification tracking

- projects/Mallard/src/components/layout/slide-card/header.tsx
- projects/Mallard/src/components/layout/slide-card/index.tsx
- projects/Mallard/src/hooks/use-dismiss-article.ts
- projects/Mallard/src/hooks/use-dismiss-responder.ts
- projects/Mallard/src/navigation/navigators/article.tsx
- projects/Mallard/src/screens/article-screen.tsx
- projects/Mallard/src/screens/article/slider.tsx
As per the reasonable demands of others, we now have the slider bar wired up so that you can dismiss the article from it 🎉
> Wire up dismiss to slider bar

- projects/Mallard/src/components/article/html/header.ts
- projects/Mallard/src/theme/typography.ts
One last tweak after speaking with Alex, bump the standfirst size ...
> Bump the standfirst font weight

- projects/Mallard/src/helpers/push-notifications.ts
Fixing background download on iOS.
> fix: Wait for background notifications to finish before letting iOS know

- projects/Mallard/src/components/article/html/render.ts
- projects/Mallard/src/helpers/webview.ts
- projects/Mallard/src/theme/typography.ts
To make @paperboyo happy cuz the designers either didn't notice or gave up on this 😜
> Use real italics & bold in webview

- projects/Mallard/src/helpers/__tests__/files.spec.ts
- projects/Mallard/src/helpers/files.ts
- projects/Mallard/src/helpers/push-notifications.ts
- projects/Mallard/src/helpers/settings.ts
- projects/Mallard/src/helpers/settings/defaults.ts
Fix push notifications
* Sender Id is now code vs prod for android
* Using correct key to download
* Use error service to help capture problems
> fix: Push notififcation fixes

- projects/Mallard/ios/Mallard/Info.plist
> feat: Update iOS version

- projects/Mallard/Makefile
- projects/Mallard/android/app/build.gradle
- projects/Mallard/fastlane/Fastfile
Also: 
- Update build version automatically.
> Add release_to_production command to fastfile.

- projects/Mallard/src/components/front/items/super-items.tsx
you can read the yellow bit now!!
> Fix sports card on tablet

- projects/Mallard/src/screens/settings/dev-zone.tsx
Adds build number and the file list to the dev zone to aid diagnostics
> feat: Build Number and File list in Dev Zone

- projects/Mallard/src/components/article/html/css.ts
> Fix dark articles

- projects/Mallard/src/helpers/files.ts
Due to changes in the paths, this was never deleting old issues.
Also it shouldn't attempt to delete `issues`
> fix: Delete old issues past seven days

- projects/Mallard/src/authentication/AccessContext.tsx
- projects/Mallard/src/authentication/lib/AccessController.ts
- projects/Mallard/src/authentication/lib/Authorizer.ts
- projects/Mallard/src/authentication/services/iap.ts
- projects/Mallard/src/navigation/index.ts
- projects/Mallard/src/navigation/routes.ts
- projects/Mallard/src/screens/settings-screen.tsx
- projects/Mallard/src/screens/settings/subscription-details-screen.tsx
Allows users to better understand how they're logged in. Feel free to suggest alternatives but the plumbing is in here. Couldn't get a screen shot of IAP but it should make sense from the code.
> Add rudimentary subscription details screen

- projects/archiver/src/tasks/image/helpers/media.spec.ts
- projects/backend/__tests__/helpers/fixtures.ts
- projects/backend/capi/articles.ts
- projects/common/src/index.ts
This will let us know how much content comes from live.
> Add a flag to print sent articles showing them as such 

- projects/Mallard/ios/Mallard/Info.plist
Need a new version to go out to testflight.
> chore: Upgrade to fix beta build

- projects/Mallard/src/components/front/items/helpers/text-block.tsx
> Add crossword setter to crossword front cards (if present).

- projects/Mallard/src/components/article/html/components/header.ts
- projects/Mallard/src/components/article/html/components/sport-score.ts
- projects/Mallard/src/components/article/html/css.ts
- projects/Mallard/src/components/front/items/small-items.tsx
- projects/Mallard/src/components/front/items/trail-image-view.tsx
- projects/Mallard/src/components/sportscore/sportscore.tsx
- projects/Mallard/src/theme/typography.ts
- projects/common/src/index.ts
> Add sports scores to match report front cards.

- projects/Mallard/src/App.tsx
- projects/Mallard/src/helpers/files.ts
The logic in clear issues was requiring each issue to delete to also equal the string `issues`. This means there was never anything to delete other than issues... which we never want to delete.
In addition to this, I have added some better logging.
> Fix: clear issues 

- projects/Mallard/ios/Mallard/Info.plist
> Feat: Stop the build from breaking

- projects/Mallard/src/helpers/diagnostics.ts
- projects/Mallard/src/helpers/files.ts
- projects/Mallard/src/screens/settings/dev-zone.tsx
Add the file list and push logs to the diagnostic emails
[**Trello Card ->**](https://trello.com/c/Edbegw8h/968-more-push-notification-tracking)
Press the bug and send an email with included diagnostics
> feat: Push Logs and Files to Diagnostic Information

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
- projects/Mallard/ios/Podfile
Downgrade to iOS9 for testing
[**Trello Card ->**](https://trello.com/c/O22TPKAO/986-release-a-single-internal-build-on-ios-9)
> feat: Downgrade to iOS9 for testing

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
- projects/Mallard/ios/Podfile
Putting things back how they were.
[**Trello Card ->**](https://trello.com/c/O22TPKAO/986-release-a-single-internal-build-on-ios-9)
> feat: Upgrade from iOS9

- projects/Mallard/android/build.gradle
Upgrade to Android 9 and look to roll back when we can guarantee performance.
[**Trello Card ->**](https://trello.com/c/AutYiq1i/985-bump-android-version-to-9)
> feat: Force Android 9

- projects/Mallard/src/screens/article/slider.tsx
This fixes an error where (unlike on Android) the current page could go outside of the index bounds.
> Fix undefined error

- projects/Mallard/src/navigation/index.ts
- projects/Mallard/src/navigation/routes.ts
- projects/Mallard/src/screens/home-screen.tsx
- projects/Mallard/src/screens/settings-screen.tsx
- projects/Mallard/src/screens/settings/manage-editions-screen.tsx
Add manage issues screen and add button to delete all issues
[Trello card](https://trello.com/c/MGsqsDf6/681-edition-management-1-delete-all-issues-delete-cache)
> Add manage issues screen

- projects/Mallard/src/screens/issue-screen.tsx
When we receive different issue data in the issue screen, we then scroll to the top of the flatlist.
[**Trello Card ->**](https://trello.com/c/FNTSqDTo/939-latest-build-566-switch-between-editions-and-your-position-doesnt-change)
> feat: Scroll to top on Issue Change

- projects/Mallard/src/helpers/push-tracking.ts
Ophan is upset we are sending so many events. This removes that.
> chore: Remove Ophan from push tracking

- projects/Mallard/src/components/weather.tsx
- projects/Mallard/src/helpers/__tests__/weather.spec.ts
- projects/Mallard/src/helpers/weather.ts
- projects/Mallard/src/hooks/apollo.ts
- projects/Mallard/src/hooks/use-settings.ts
- projects/Mallard/src/navigation/index.ts
- projects/Mallard/src/navigation/routes.ts
- projects/Mallard/src/screens/issue-screen.tsx
- projects/Mallard/src/screens/onboarding/cards.tsx
- projects/Mallard/src/screens/settings-screen.tsx
- projects/Mallard/src/screens/settings/dev-zone.tsx
- projects/Mallard/src/screens/settings/gdpr-consent-screen.tsx
- projects/Mallard/src/screens/weather-geolocation-consent-screen.tsx
- projects/common/src/index.ts
@RichieAHB  mentioned usability complexity about this function, this simplifies things by just having a boolean instead of an enum, much easier to put conditions on. Is that better?
No logic change, essentially, just check the app runs correctly.
> useQuery: simplify API

- projects/Mallard/android/app/src/main/AndroidManifest.xml
- projects/Mallard/ios/Mallard/Info.plist
- projects/Mallard/ios/Podfile
- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/apollo.ts
- projects/Mallard/src/components/weather.tsx
- projects/Mallard/src/helpers/location-permission.ts
- projects/Mallard/src/screens/weather-geolocation-consent-screen.tsx
- projects/Mallard/yarn.lock
This add the location permissions setup and ask for permission when pressing "Okay show me the weather"
Both for iOS and Android:
1. Sign in and enable dev move
2. Press "Set Location" on weather
3. Press "Okay show me the weather". Notice it asks for permission
4. Deny permission. Observe it doesn't dismiss the modal.
5. Press "Okay show me the weather". Accept the permission. Notice it dismisses the modal and proceeds.
> ask for location permission (for weather)

- projects/Mallard/src/screens/settings-screen.tsx
- projects/Mallard/src/screens/settings/dev-zone.tsx
I dunno, everytime I'm annoyed by the wrong message 😆 it's actually fine if people open this on their devices…
> cleanup message for dev menu

- projects/Mallard/src/screens/weather-geolocation-consent-screen.tsx
https://trello.com/c/Ii5WqyrA/895-make-weather-in-app-use-geolocation-data-lat-long-rather-than-ip-address
The Header component is kind of broken in the sense it doesn't properly have margins for the text so "Location-based weather" overflows under the close button, etc. That's a problem I'll deal with separately, let's move the title in the HTML for now.
> nit fix weather location consent copy

- projects/Mallard/src/screens/article/slider.tsx
This brings the slider back in line with the photo and article
> Exta slider padding

- projects/Mallard/metro.config.js
> fix: Metro config update

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/authentication/services/cas.ts
- projects/Mallard/src/helpers/diagnostics.ts
- projects/Mallard/src/helpers/screen.ts
- projects/Mallard/src/hooks/use-deprecation-screen.ts
- projects/Mallard/src/screens/settings-screen.tsx
- projects/Mallard/src/screens/settings/dev-zone.tsx
- projects/Mallard/src/services/content-auth-service.ts
- projects/Mallard/yarn.lock
Upgrading this tricky package to make the transition to yarn workspaces easier.
The API has changed again.
Each element changed has been tested manually.
> feat: Upgrade React Native Device Info

- projects/Mallard/src/screens/article/slider.tsx
This means we only to declare it once _and_ it works for Android too
> Move padding out

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/src/helpers/weather.ts
- projects/Mallard/src/screens/weather-geolocation-consent-screen.tsx
https://trello.com/c/vw48GKpG/1026-ipad-weathrer-location-consent-screen-not-working
Tested both Android, iOS when location services are disabled.
> show proper error message when location is unavailable

- projects/Mallard/src/screens/article/slider.tsx
> Fix padding again

- projects/Mallard/ios/Podfile.lock
> fix: Update the podfile.lock for sentry

- projects/Mallard/ios/Podfile.lock
> chore: Update pod.lockfile to fix sentry

- projects/Mallard/src/services/errors.ts
> chore: Import sentry differently

- projects/Mallard/android/build.gradle
Drop down to Android 5.
Was tested on an HTC One by Shraddha and Ana.
> feat: Android 5

- projects/Mallard/src/screens/settings/manage-editions-screen.tsx
> fix: Delete editions amends

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/src/helpers/weather.ts
Addresses this crash: https://sentry.io/organizations/the-guardian/issues/1356978595/?project=1519156&query=is%3Aunresolved
Automated tests.
> handle case where accuweather return no location

- projects/Mallard/src/helpers/files.ts
Last bit of tracking that is causing the spike
> chore: Remove Ophan Push Tracking

- projects/Mallard/src/components/weather.tsx
- projects/Mallard/src/helpers/weather.ts
- projects/Mallard/src/screens/issue-screen.tsx
- Prevent showing an empty container when weather cannot be fetched.
- Small tweaks to weather labels.
- Fixed a FIXME in the code.
> Weather tweaks.

- projects/Mallard/src/screens/settings/manage-editions-screen.tsx
Change the order of the options
[**Trello Card ->**](https://trello.com/c/JAMTnr2t/1066-edition-management-order-of-options)
> chore: Change order of manage editions

- projects/Mallard/src/screens/home-screen.tsx
- projects/Mallard/src/screens/issue-screen.tsx
It was decided to do this design change: https://trello.com/c/2RYcBOY1/1069-section-nav-icons-burger-and-close-button
<div>
</div>
> Editions list: switch to hamburger and cross icons

- projects/archiver/src/tasks/indexer/helpers/summary.ts
- projects/archiver/test/tasks/indexer/helpers/summary.spec.ts
- projects/backend/controllers/__tests__/issue.spec.ts
- projects/backend/controllers/issue.ts
Updates the backend to output 30 issues.
Updates the archiver to index 30 issues
> feat: Up the number of issues to 30

- projects/archiver/src/utils/s3.ts
Copy process must set ACL correctly.
> Make copied files public

- projects/Mallard/package.json
- projects/Mallard/yarn.lock
Previous version uses deprecated features, the new version fixes that.
Open issue list, press download button, notice the progress bar fills up as expected.
> upgrade react-native-progress-circle

- projects/Mallard/src/helpers/files.ts
This just adds a bit of extra logging around fetching the issue summary.
[**Trello Card ->**](https://trello.com/c/wsPW1dgW/1090-app-logs-unexpected-issue-list-or-zip-absence-to-sentry)
I've tested this locally and checked it logs to sentry. Otherwise just loading the app and checking the issue loads.
> Log to sentry when issue summary fails to download

- projects/Mallard/src/App.tsx
- projects/Mallard/src/components/article/html/components/images.ts
Oops - I think both of these lines are unnecessary
> remove redundant console.log

- projects/Mallard/src/hooks/use-issue.ts
Small one. We have a function that does nothing. This removes it.
> chore: use-issue optimisation

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
- projects/Mallard/ios/Podfile
- projects/Mallard/ios/Podfile.lock
> chore: iOS 9

- projects/Mallard/src/helpers/diagnostics.ts
- projects/Mallard/src/helpers/screen.ts
- projects/Mallard/src/hooks/use-config.ts
- projects/Mallard/src/screens/settings/dev-zone.tsx
On devices with a low amount of RAM, deliver the smallest images we have. Aim to improve performance on lower end devices.
> feat: Force smaller images on lower power devices

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/components/article/types/article.tsx
- projects/Mallard/src/components/article/types/article/webview.tsx
- projects/Mallard/src/screens/settings/default-info-text-webview.tsx
- projects/Mallard/yarn.lock
Small update to Webview to attempt to speed it up.
> chore: Small update to Webview

- projects/Mallard/src/screens/issue-screen.tsx
This animation pops behind the issue menu in its current state. Removing this to help improve performance a tad.
> chore: Remove hidden animation

- projects/Mallard/src/navigation/navigators/sidebar.tsx
- projects/Mallard/src/screens/article/slider/index.tsx
1. Memoize the slider to avoid re-renders
2. Remove animated view thats not being used.
> chore: Small perf improvements

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/components/article/html/components/icon/native-arrow.tsx
- projects/Mallard/src/components/icons/__tests__/__snapshots__/Quote.spec.tsx.snap
- projects/Mallard/yarn.lock
Upgraded React Native SVG as suggested here:
https://github.com/react-native-community/react-native-svg/issues/1198
> chore: Remove imageloader warnings

- projects/Mallard/src/App.tsx
- projects/Mallard/src/components/layout/header/header.tsx
The statusbar animation is not adding much and it has a minor performance impact. Therefore its being removed.
> chore: Drop statusbar animation

- projects/Mallard/android/app/build.gradle
- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/App.tsx
- projects/Mallard/src/components/issue/issue-title.tsx
- projects/Mallard/src/navigation/navigators/article.tsx
- projects/Mallard/src/navigation/navigators/sidebar.tsx
- projects/Mallard/yarn.lock
This adds native navigation screens for the menu and article screen for iOS devices less than iOS12.
> Chore: update rnscreens a.k.a Native React Navigation

- projects/Mallard/src/screens/article/slider/index.tsx
Duplicate code for high end iOS devices. Serves no purpose.
> fix: Remove duplicate header

- projects/Mallard/android/build.gradle
Fixes the beta build for Android
> fix: Android Beta Build

- projects/Mallard/src/components/front/collection-page.tsx
Remove the small bit of padding at the bottom.
Seems to be caused by some odd negative and float margin...
> fix: Remove card padding

- projects/Mallard/README.md
On our laptop builds there seems to be a recurring error with the sytem ruby install. Installing rvm works around that
> Add RVM install link

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
...in preparation for ios9 release.
> Bump marketing version from 5.4 to 6.0

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
- projects/Mallard/ios/Podfile
- projects/Mallard/ios/Podfile.lock
The _last_ PR to enable iOS9 in the project.
> chore: iOS9 returns

- projects/Mallard/src/components/article/html/components/images.ts
Disable lightbox whilst we're fixing some bugs in it (in case we want to release master)
[**Trello Card ->**](https://trello.com/c/d6XXQPgW/1203-ligthbox-bugs)
> disable lightbox

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
This includes:
- Resolving JSDom to a higher version
- Updating Sentry.
Things seem to continue to work...
> chore: Resolve dependency issues

- projects/Apps/crosswords/package.json
- projects/Apps/yarn.lock
To remove the security warnings
> chore: Crossword dep bump

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
- projects/Mallard/ios/Mallard.xcodeproj/xcshareddata/xcschemes/Mallard-tvOS.xcscheme
- projects/Mallard/ios/Mallard.xcodeproj/xcshareddata/xcschemes/Mallard.xcscheme
- projects/Mallard/ios/Podfile.lock
Reverts guardian/editions#1069
> Revert "xcode11 migration"

- projects/Mallard/Makefile
Reverts guardian/editions#1092
> Revert "Update DEVELOPER_DIR to xcode 11."

- projects/Mallard/src/components/lists/DualButton.tsx
- projects/Mallard/src/components/lists/FullButton.tsx
- projects/Mallard/src/components/lists/styles.ts
- projects/Mallard/src/screens/settings-screen.tsx
- Re-implemented buttons with reusable components to break the inflexible list
- Uses text ellipsis if the email is too long
- Separate button for sign out and membership link
[**Trello Card ->**](https://trello.com/c/JkkpLZQ6/1208-change-the-information-we-display-on-the-sign-in-are-when-users-are-signed-in-from-name-username-to-email)
> Feat: Improved sign in button

- projects/Mallard/src/helpers/files.ts
The blue tick being the completed download. This now looks for the front folder, as well as the thumbs to ensure everything required for complete working offline is in the folder.
> chore: Blue Tick requires more files

- projects/Mallard/src/components/issue/issue-row.tsx
> feat: Thicker Download border

- projects/Mallard/package.json
- projects/Mallard/storybook/index.js
- projects/Mallard/storybook/rn-addons.js
- projects/Mallard/yarn.lock
Knobs allow users to be able to change the prop of a component. This aids with manual testing and showing the limits of that specific component.
> feat: Add knobs to storybook

- docs/08-✅-releases.md
As per our Retro, here is some docs on our release process as it stands.
This will aid new devs on-boarding on to the project.
> chore: Release documentation

- projects/Mallard/src/components/Lightbox/LightboxCaption.stories.tsx
- projects/Mallard/src/components/Lightbox/LightboxCaption.tsx
- projects/Mallard/src/components/Lightbox/__tests__/LightboxCaption.spec.tsx
- projects/Mallard/src/components/Lightbox/__tests__/__snapshots__/LightboxCaption.spec.tsx.snap
- projects/Mallard/src/screens/lightbox.tsx
- projects/Mallard/storybook/storyLoader.js
Lightbox is a rather large component with several components in the same file. It makes sense to split this out for easier testing and readability - probably not for reusability.
This PR does this, adds tests and a storybook story to view it in isolation.
> feat: Lightbox Caption

- projects/Mallard/fastlane/Fastfile
Sounds like we're missing some info in our upload_to_testflight step - sadly it's not clear what but this post : https://github.com/fastlane/fastlane/issues/16294#issuecomment-612728220 suggests that what I've got here should do the trick
> (Attempt to) fix testflight upload

- .github/workflows/main.yml
- projects/Mallard/ios/Podfile.lock
This PR attempt to update the pod version to 1.9.0
> Updated pod version

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
This PR updated the zip library that fixes a security issue reported by Google Play store (see screenshot)
> Updated zip library that fixes a security issue

- .github/workflows/main.yml
I forgot to revert the tmp change that I made in this [PR](https://github.com/guardian/editions/pull/1131/files)
> Reverted yaml change

- projects/Mallard/src/helpers/diagnostics.ts
- projects/Mallard/src/helpers/push-notifications.ts
- projects/Mallard/src/helpers/push-tracking.ts
Looks to take the first and last tracking events in the push download process and make those available in the diagnostic emails
> feat: Push Notification Diagnostics

- projects/Mallard/src/helpers/files.ts
One issue we have is missing images for users. This PR aims to drill down into the downloaded zip folders and look at specifically the image folders. If they exist, they will show one image from that folder. The aim is to make sure that the image folders are not empty.
The benefit of using just one image per image folder means the diagnostic doesn't get too long.
Available to be viewed from the Dev Zone and Diagnostic emails.
> feat: Image file diagnostic

- projects/Mallard/android/app/build.gradle
Updated Android version code to match with the max version from the play store. This change make sure the next apk we upload to the play store has the bigger version code than any existing version code in play store (across variant tracks).
> updated android build version code

- projects/Apps/common/src/logging.ts
- projects/Mallard/src/__mocks__/react-native-device-info.js
- projects/Mallard/src/authentication/helpers.ts
- projects/Mallard/src/helpers/diagnostics.ts
- projects/Mallard/src/helpers/files.ts
- projects/Mallard/src/helpers/push-download-failsafe.ts
- projects/Mallard/src/helpers/push-notifications.ts
- projects/Mallard/src/helpers/push-tracking.ts
- projects/Mallard/src/helpers/settings.ts
- projects/Mallard/src/helpers/settings/defaults.ts
- projects/Mallard/src/helpers/storage.ts
- projects/Mallard/src/services/__tests__/__snapshots__/logging.android.spec.ts.snap
- projects/Mallard/src/services/__tests__/__snapshots__/logging.spec.ts.snap
- projects/Mallard/src/services/__tests__/logging.android.spec.ts
- projects/Mallard/src/services/__tests__/logging.offline.spec.ts
- projects/Mallard/src/services/__tests__/logging.spec.ts
- projects/Mallard/src/services/logging.ts
This lays the ground work for the logging implementation. This includes:
- Logging Service
- Dev and Prod Environments (when we have them)
- Log queuing system
- Offline management
- Log post failure management 
- Tests
- Example implementation
What is missing?
- Potentially a bit more testing
- Consent
The aim is to get the code into Master so it can be reviewed in isolation as its already pretty big.
[**Trello Card ->**](https://trello.com/c/HtQIR5Dp/1222-logging)
> Feat: Logging

- projects/Mallard/android/app/google-services.json
- projects/Mallard/android/app/src/debug/google-services.json
Edition app only had debug firebase config which used by both DEV and PROD versions of the app.
This PR fixes that issue by providing appropriate google-services.json for different app variants.
> Firebase now has correct google-services

- projects/Mallard/src/helpers/push-tracking.ts
Now we have all the consent in, logging within push tracking can be enabled.
> feat: Enable logging in Push Tracking

- projects/Mallard/src/navigation/navigators/article/transition.tsx
- projects/Mallard/src/theme/spacing.ts
Updated and agreed with Product and Design
> feat: Updated article animation

- projects/Mallard/src/screens/onboarding/cards.tsx
- projects/Mallard/src/screens/settings/gdpr-consent-screen.tsx
1. Shows cleared consent now if asked to re-consent
2. If you press "Im okay with that" it will set all consent to "on"
3. Pressing the X without setting consent will prompt you for consent.
[**Trello Card ->**](https://trello.com/c/93YdLTz8/1276-consent-management)
> fix: Consent clearing on new version

- projects/Mallard/src/screens/settings/gdpr-consent-screen.tsx
Change of wording as provided by Caspar
> chore: Consent Wording Change

- projects/Mallard/src/components/front/items/helpers/text-block.tsx
- projects/Mallard/src/components/front/items/super-items.tsx
- projects/Mallard/src/components/icons/Icons.stories.tsx
- projects/Mallard/src/components/icons/Quote.tsx
- projects/Mallard/src/components/icons/__tests__/Quote.spec.tsx
- projects/Mallard/storybook/storyLoader.js
Exposing Icons so they can be viewed in Storybook
> chore: Adding some stories to Icons

- projects/Mallard/src/helpers/fetch.ts
- projects/Mallard/src/push-notifications/notification-service.ts
- projects/Mallard/src/push-notifications/notification-tracking.ts
- projects/Mallard/src/push-notifications/push-notifications.ts
Move the notification related helpers into the push notification folder
> chore: Move notification helpers

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
Had an email from Sentry this morning suggesting a security update, this is the result of that.
> fix: Sentry security upgrade

- projects/backend/package.json
- projects/backend/yarn.lock
There's a new version of capi-ts. I've tested it and it seems to work fine so let's start using it. 
I don't expect any changes as a result of this change.
> Bump capi-ts version.

- projects/logging/application.ts
Reverts guardian/editions#1210
> Revert "Fix less than sign wrong way round"

- projects/Mallard/src/authentication/apple-oauth.ts
- projects/Mallard/src/authentication/authorizers/IdentityAuthorizer.ts
- projects/Mallard/src/authentication/services/identity.ts
- projects/Mallard/src/authentication/webview-modal.tsx
- projects/Mallard/src/screens/identity-login-screen.tsx
- projects/Mallard/src/screens/log-in.tsx
WIP: this PR implements Apple SignIn for android using vanilla webview. It is based on @philmcmahon 's initial spike but off master branch without any additional dependencies. Still work in progress, raising this for visibility.
> Apple SignIn for Android (Webview)

- projects/Mallard/ios/Podfile.lock
Spotted by @mohammad-haque - this was unintentionally reverted.
> fix: Reinstating the podfile back to 1.9.0

- projects/Mallard/src/screens/settings/privacy-policy-screen.tsx
Updates to the privacy policy
[**Trello Card ->**](https://trello.com/c/sy64EfX7/1311-privacy-policy-wording-changes-in-the-editions-app)
> chore: Update Privacy Policy

- projects/Mallard/firebase.json
This is what is suggested in the documentation. Im not sure it adds up though. Worth an internal test
> fix: Remove firebase analytics

- projects/Mallard/src/download-edition/clear-issues.ts
I've seen a few instances of 'unhandled promise rejection' errors coming from the temporary file cleanup process. whilst this is wrapped in a try catch that doesn't deal with when the promise throws an error. 
Release this, run android emulator and check for no 'unhandled promise rejection' errors from clear-issues.ts
> Handle promise failure when deleting temp files.

- projects/Mallard/src/helpers/settings.ts
- projects/Mallard/src/screens/settings/gdpr-consent-screen.tsx
Consent update for Firebase. This will also request the user to re-consent.
> chore: Add Firebase to consent

- projects/Mallard/README.md
> chore: Update Cocoapods version in readme

- projects/Mallard/src/helpers/settings.ts
- projects/Mallard/src/screens/settings/gdpr-consent-screen.tsx
More consent changes. Bumps consent version and modifies title and description of Essential and title of Performance.
> Add Crashlytics to consent, describe Firebase better in essential

- projects/logging/application.ts
The backend logging service is returning a lot of 4XX errors, mostly because the payload of requests being sent is too large. At the moment returning 4XX errors causes performance problems client side so this PR aims to reduce the number of errors the backend throws by:
- bumping payload limit to 1MB (default is 100kb)
- returning a 200 even when a log has been ignored because it's too big
Deploy, wait for this graph to go down https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#metricsV2:graph=~(metrics~(~(~'AWS*2fApiGateway~'4XXError~'ApiName~'editions-logging~'Stage~'prod))~period~300~stat~'Sum~region~'eu-west-1~start~'2020-05-26T09*3a04*3a00Z~end~'2020-06-10T09*3a04*3a00Z)
> Logging service: Increase max payload size, return 200 when body too big

- projects/Mallard/android/app/src/debug/google-services.json
- projects/Mallard/src/helpers/settings/defaults.ts
- Adds new debug `google-services.json` file
- Update sender id in push notifications
> chore: Update CODE Firebase Details

- projects/Mallard/src/screens/settings/dev-zone.tsx
- projects/Mallard/src/screens/settings/gdpr-consent-screen.tsx
- Provides a fixed header in the Privacy consent
- Adds a button to the dev menu to make this easier to access.
Both shown in the gif below
> chore: Update consent screen with fixed header

- projects/Mallard/src/helpers/diagnostics.ts
This will help us know which edition the user was looking at when they get in touch.
> chore: Include edition with diagnostics

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> bump ios version number

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
- projects/Mallard/ios/Podfile
Raising the minimum version on iOS as agreed to 12.4
> chore: Raise the iOS floor to 12.4

- projects/Mallard/ios/Podfile.lock
Reverting a change that occurred during a merge conflict resolution
@philmcmahon Thanks for spotting this
> Reverting an unintended change in Podfile

- projects/Mallard/src/download-edition/clear-issues.ts
This PR fixes error handling that not handled properly with existing code and show red error message (see screenshot)
> Custom error handling for file deletion error

- projects/Mallard/src/components/EditionsMenu/RegionButton/RegionButton.tsx
- projects/Mallard/src/components/EditionsMenu/RegionButton/__tests__/__snapshots__/RegionButton.spec.tsx.snap
- projects/Mallard/src/components/EditionsMenu/SpecialEditionButton/SpecialEditionButton.tsx
- projects/Mallard/src/components/EditionsMenu/SpecialEditionButton/__tests__/__snapshots__/SpecialEditionButton.spec.tsx.snap
Improves the accessibility on Regional and Special Edition buttons
> chore: Make Regional and Special Edition buttons accessible

- projects/Mallard/src/download-edition/download-via-notification.ts
- projects/Mallard/src/push-notifications/push-notifications.ts
Reduces the Push Tracking logging to its essential parts
> chore: Reduced Push Logging Size

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> bump-ios-version

- projects/Mallard/src/components/EditionsMenu/EditionsMenuButton/EditionsMenuButton.tsx
- projects/Mallard/src/components/EditionsMenu/EditionsMenuButton/__tests__/__snapshots__/EditionsMenuButton.spec.tsx.snap
- projects/Mallard/src/components/icons/Editions.tsx
- projects/Mallard/src/components/icons/Icons.stories.tsx
- projects/Mallard/src/components/icons/__tests__/Editions.spec.tsx
- projects/Mallard/src/components/icons/__tests__/__snapshots__/Editions.spec.tsx.snap
This PR provides an updated Editions Button. See below
> feat: New Editions Button

- projects/Apps/common/src/index.ts
- projects/Mallard/src/__mocks__/react-native-device-info.js
- projects/Mallard/src/components/EditionsMenu/EditionsMenu.stories.tsx
- projects/Mallard/src/components/EditionsMenu/EditionsMenu.tsx
- projects/Mallard/src/components/EditionsMenu/__tests__/EditionsMenu.spec.tsx
- projects/Mallard/src/components/EditionsMenu/__tests__/__snapshots__/EditionsMenu.spec.tsx.snap
- projects/Mallard/src/components/ScreenHeader/ScreenHeader.stories.tsx
- projects/Mallard/src/components/ScreenHeader/ScreenHeader.tsx
- projects/Mallard/src/components/ScreenHeader/__tests__/ScreenHeader.spec.tsx
- projects/Mallard/src/components/ScreenHeader/__tests__/__snapshots__/ScreenHeader.spec.tsx.snap
- projects/Mallard/src/components/issue/issue-title.tsx
- projects/Mallard/src/components/layout/header/header.tsx
- projects/Mallard/src/screens/article/header.tsx
- projects/Mallard/src/screens/issue-screen.tsx
- projects/Mallard/storybook/storyLoader.js
When header styles are passed through this will change the colour of the header on the Fronts Screen. With tests and stories.
[**Trello Card ->**](https://trello.com/c/pNOUwhv2/1398-change-the-colour-of-the-fronts-header-when-requested)
> Feat: Special Editions Header change when request

- projects/Apps/common/src/editions-defaults.ts
- projects/Mallard/src/components/EditionsMenu/RegionButton/RegionButton.tsx
- projects/Mallard/src/components/EditionsMenu/RegionButton/__tests__/__snapshots__/RegionButton.spec.tsx.snap
- projects/Mallard/src/components/EditionsMenu/__tests__/__snapshots__/EditionsMenu.spec.tsx.snap
As requested and approved by @pradasa 
> chore: Add line break to Region Buttons

- projects/Mallard/src/helpers/words.ts
So that emails go to the right place
> Use correct feedback email.

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
6.4 has been release, it's time to update
> bump ios version to 6.5

- docs/08-✅-releases.md
Our release process has changed a bit, let's update the docs accordingly!
> Update release docs with notes for Github actions, github releases

- projects/Mallard/src/services/remote-config.ts
> Default Locale is OFF

- projects/Mallard/.gitignore
- projects/Mallard/README.md
- projects/Mallard/package.json
This PR allows us to make android PROD build
> How to make local Prod build for android

- projects/archiver/src/tasks/copier/index.ts
- projects/archiver/src/utils/s3.ts
Get rid of compile warnings; otherwise no-op
Nothing should change when run in CODE
> Fix compile warnings on undefined S3 keys

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> chore: Bump iOS version to 6.6.

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> Uddated iOS app version to 6.7

- projects/Mallard/src/components/article/types/article/webview.tsx
Added file access permission to the webview so it can (possibly) load images from file system
> Added file permission to the webview

- projects/Mallard/src/components/article/html/article.ts
- projects/Mallard/src/components/article/html/components/__tests__/__snapshots__/header.spec.ts.snap
- projects/Mallard/src/components/article/html/components/__tests__/__snapshots__/headline.spec.ts.snap
- projects/Mallard/src/components/article/html/components/__tests__/header.spec.ts
- projects/Mallard/src/components/article/html/components/header.ts
- projects/Mallard/src/components/article/html/components/headline.ts
- projects/Mallard/src/components/article/html/components/helpers/getBylineText.ts
- projects/Mallard/src/components/article/html/helpers/css.ts
- projects/Mallard/src/helpers/transform.ts
- projects/Mallard/src/helpers/webview.ts
Worked with Ana to have tackle initial snags.
[**Trello Card ->**](https://trello.com/c/2l7c9oVU/1406-template-interview)
This can be tested by adding Interview articles in code. Or by editing `webview.tsx` line 79 and forcing `type` to be the Interview type.
> Feat: Interview template

- projects/Apps/common/src/index.ts
- projects/Mallard/src/components/article/html/article.ts
- projects/Mallard/src/components/article/html/components/__tests__/__snapshots__/header.spec.ts.snap
- projects/Mallard/src/components/article/html/components/header.ts
- projects/Mallard/src/components/article/html/components/headline.ts
Applies the showcase template based on the designs in the trello card.
Also more horrible hacking...
[**Trello Card ->**](https://trello.com/c/toCtvPTB/1402-showcase-template-implementation)
> feat: Showcase template

- projects/backend/capi/articleTypePicker.ts
Interview template didn't used to exist, this change will hopefully start showing it now that it does.
> Assigns interview template now we have one

- projects/Mallard/android/app/src/main/res/values/strings.xml
- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
- projects/Mallard/ios/Mallard.xcodeproj/xcshareddata/xcschemes/Mallard.xcscheme
- projects/Mallard/ios/Mallard/Info.plist
- projects/Mallard/src/helpers/words.ts
As per the latest branding, with more detail in the Trello card
[**Trello Card ->**](https://trello.com/c/J46BTPym/1480-change-the-app-name-ios-android)
> feat: Bundle Name / App Icon name change

- projects/backend/__tests__/fronts.spec.ts
- projects/backend/utils/article.ts
Working with @pradasa this sets the dropcap assignment to the correct templates.
[**Trello Card ->**](https://trello.com/c/xEzYgFwF/1299-drop-caps-full-snagging-list)
> feat: New Dropcap Assignment

- projects/Mallard/src/components/article/html/css.ts
This looks to fix some of the issues on Drop cap including:
1. Incorrect font
2. Incorrect font weights, italic etc.
3. Spacing
[**Trello Card ->**](https://trello.com/c/xEzYgFwF/1299-drop-caps-full-snagging-list)
> feat: Dropcap fixes

- projects/backend/controllers/editions.ts
Since we removed the support of the US edition the validation logic needs to reflect that, this PR is just to exclude the US edition.
> Updated edition list logic to exclude US edition

- projects/Mallard/src/helpers/words.ts
- projects/Mallard/src/navigation/index.ts
- projects/Mallard/src/navigation/routes.ts
- projects/Mallard/src/screens/settings-screen.tsx
- projects/Mallard/src/screens/settings/beta-programme-faqs.tsx
- projects/Mallard/src/screens/settings/join-beta-button.tsx
We are adding the beta programme faqs to the settings screen to give people more information about the beta programme.
[**Trello Card ->**](https://trello.com/c/tu98kNjL/1487-beta-testers-recruitment-add-beta-faqs)
> About beta program

- projects/backend/s3.ts
This PR adds missing cache-control for s3 objects
> Added cache control for s3 put

- projects/Apps/common/src/index.ts
- projects/Apps/common/src/logging.ts
- projects/Mallard/src/components/EditionsMenu/EditionsMenu.stories.tsx
- projects/Mallard/src/components/EditionsMenu/EditionsMenu.tsx
- projects/Mallard/src/components/EditionsMenu/__tests__/EditionsMenu.spec.tsx
- projects/archiver/src/services/editions-mappings.ts
- projects/archiver/src/services/pub-status-notifier.ts
- projects/archiver/src/tasks/indexer/helpers/get-issues.ts
- projects/archiver/src/tasks/indexer/helpers/summary.ts
- projects/archiver/src/tasks/notification/helpers/device-notifications.ts
- projects/backend/controllers/issue.ts
- projects/backend/utils/__tests__/issue.spec.ts
- projects/backend/utils/issue.ts
As this is a more sensible name for this property, as suggested by @mohammad-haque 
This should have no user facing changes
> Rename Edition type EditionId

- projects/Mallard/src/hooks/__tests__/use-edition-provider.spec.tsx
Fixes a bug introdued in https://github.com/guardian/editions/pull/1500/files
> Fix build (Edition is now EditionId)

- projects/Mallard/src/components/Button/ReloadButton.tsx
- projects/Mallard/src/components/Button/__tests__/__snapshots__/ReloadButton.spec.tsx.snap
This will make it easier to operate the editions menu!
Before:
After:
Tested in simulator
> Move reload button to the right.

- projects/Mallard/jest-setup.js
- projects/Mallard/src/App.tsx
- projects/Mallard/src/hooks/use-edition-provider.tsx
- projects/Mallard/src/notifications/push-notifications.ts
Pedantic: typo in pushNotifcationRegistration
> typo: Notifcations -> Notifications

- projects/Mallard/src/screens/settings/faq-screen.tsx
Updating the FAQs and adding some copy.
Updating the FAQs and adding some copy as part of the new rebranding.
[**Trello Card ->**](https://trello.com/c/nV56DMBe/1472-faqs-update-in-the-app-ready-to-be-added-to-the-app)
Review copy and check if anything is broken.
> FAQs update

- projects/Mallard/src/helpers/settings.ts
- projects/Mallard/src/screens/settings/gdpr-consent-screen.tsx
Removes Braze wording in essential, bump privacy version
> Removes Braze wording in essential, bump privacy version

- projects/aws/package.json
- projects/aws/yarn.lock
CDK has some dependencies that have security vulnerabilities. This updates to a patch release and tested as much as possible in the local environment.
> chore: Update AWS project

- projects/backend/application.ts
- projects/backend/package.json
- projects/backend/yarn.lock
Fixes the dependency issue. When updating there was a problem with the types used as well, so resolved those.
> chore(deps): Update ts-node-dev on backend

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Now that we have submitted 7.0 for review let's bump version to 7.1
> bump version number iOS

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Bump version to fix scheduled beta
> bump to 7.2

- README.md
Update README with correct iOS deployment steps
> update ios deployment steps

- projects/Apps/ophan/build.gradle
As it says on the tin.
The previous version has an issue (crash & not reporting correctly) which should be fixed by this new version of the Ophan lib.
> Updated to latest version of the Ophan lib

- projects/backend/README.md
Some additional details about running the 'backend' locally
> Updated ReadMe

- projects/Mallard/src/helpers/__tests__/files.spec.ts
small PR to update names and descriptions in files tests (files.spec.ts)
> update names correctly in files test suite

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
After release of 7.3 bump version number to 7.4
> bump version number to 7.4

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Bump version to 7.5 for next release (beta and prod)
> bump version to 7.5

- projects/Mallard/src/screens/article/body.tsx
This PR updated the editions rendered banner to use Guardian brandAlt colour palette.
> Update editions rendered banner style

- projects/Mallard/src/components/EditionsMenu/EditionsMenuButton/EditionsMenuButton.tsx
- projects/Mallard/src/components/EditionsMenu/EditionsMenuButton/__tests__/__snapshots__/EditionsMenuButton.spec.tsx.snap
- projects/Mallard/src/components/ScreenHeader/IssueScreenHeader/__tests__/__snapshots__/IssueScreenHeader.spec.tsx.snap
- projects/Mallard/src/components/ScreenHeader/__tests__/__snapshots__/EditionMenuScreenHeader.spec.tsx.snap
- projects/Mallard/src/components/ScreenHeader/__tests__/__snapshots__/ScreenHeader.spec.tsx.snap
- projects/Mallard/src/components/icons/LeftChevron.tsx
- projects/Mallard/src/components/icons/__tests__/__snapshots__/LeftChevron.spec.tsx.snap
- projects/Mallard/src/theme/typography.ts
This PR adds an editions label under the switcher button.
[**Jira Ticket ->**](https://theguardian.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=LIVE&modal=detail&selectedIssue=LIVE-1764)
| before | after |
| --- | --- |
| <img src="" width="300" /> | <img src="https://user-images.githubusercontent.com/20416599/109000336-7b906080-769b-11eb-9d3a-5e9d2229394f.png" width="300" /> |
| --- | --- |
| <img src="" width="300" /> | <img src="https://user-images.githubusercontent.com/20416599/109000206-4e43b280-769b-11eb-8144-2de6572ed6b1.png" width="300" /> |
| --- | --- |
| <img src="" width="300" /> | <img src="https://user-images.githubusercontent.com/20416599/109000305-6f0c0800-769b-11eb-9b20-18483aa06ff0.png" width="300" /> |
> LIVE-1764: Add editions label under the switcher button

- .github/workflows/scheduled-ios-beta.yml
- projects/Mallard/fastlane/Fastfile
This PR fixed 2FA failing issue for the Fastlane by providing Appstore Connect api key.
> Added AppStore connect api to solve 2FA issue

- projects/archiver/src/services/editions-mappings.ts
> Add training editions to the editions-mapping.

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Update MARKETING_VERSION to 7.8 after successful release of 7.7
> bump version to 7.8

- .github/pull_request_template.md
Update PR template inline with what we have on AR.
> CHORE: bring pr template inline with AR

- projects/Mallard/src/test-helpers/test-helpers.ts
This fixes all errors in the /Test-helpers folder. Total errors resolved = 2
> LIVE-1968-test-helpers

- projects/Mallard/src/components/article/html/components/header.ts
- projects/Mallard/src/components/article/html/components/images.ts
- projects/Mallard/src/components/article/html/components/line.ts
- projects/Mallard/src/components/article/html/components/pull-quote.ts
- projects/Mallard/src/components/article/html/css.ts
- projects/Mallard/src/components/front/items/trail-image-view.tsx
- projects/Mallard/src/components/issue/issue-title.tsx
- projects/Mallard/src/components/layout/header/header.tsx
- projects/Mallard/src/components/layout/ui/modal-for-tablet.tsx
- projects/Mallard/src/components/toast/toast.tsx
- projects/Mallard/src/components/weather.tsx
- projects/Mallard/src/hooks/use-aspect-ratio.ts
- projects/Mallard/src/hooks/use-config-provider.tsx
- projects/Mallard/src/navigation/navigators/sidebar.tsx
- projects/Mallard/src/navigation/navigators/sidebar/transition.tsx
- projects/Mallard/src/screens/issue-screen.tsx
- projects/Mallard/src/theme/breakpoints.ts
- projects/Mallard/src/theme/spacing.ts
- projects/Mallard/src/theme/typography.ts
Fix errors in the theme folder. Fixes 4 errors, one of which is a naming change which is why this PR touches so many files outside of /Theme.
> Live 1967 theme

- projects/Mallard/src/components/issue/issue-row.tsx
- projects/Mallard/src/components/sign-in-modal-card.tsx
- projects/Mallard/src/navigation/helpers/base.tsx
- projects/Mallard/src/screens/settings/manage-editions-screen.tsx
- projects/Mallard/src/services/__tests__/ophan.spec.ts
- projects/Mallard/src/services/content-auth-service.ts
- projects/Mallard/src/services/errors.ts
- projects/Mallard/src/services/logging.ts
- projects/Mallard/src/services/ophan.ts
Resolving errors in the Services folder. This includes name changes which is why this PR touches files outside of /services Errors resolved = 13
> Live 1970 - Services

- projects/Mallard/.eslintrc.js
- projects/Mallard/src/components/article/html/components/header.ts
- projects/Mallard/src/components/article/html/components/images.ts
- projects/Mallard/src/components/article/html/components/pull-quote.ts
- projects/Mallard/src/components/article/html/css.ts
- projects/Mallard/src/components/front/items/trail-image-view.tsx
- projects/Mallard/src/components/toast/toast.tsx
- projects/Mallard/src/components/weather.tsx
- projects/Mallard/src/hooks/use-aspect-ratio.ts
- projects/Mallard/src/hooks/use-config-provider.tsx
- projects/Mallard/src/screens/article-screen.tsx
- projects/Mallard/src/screens/article/body.tsx
- projects/Mallard/src/screens/article/slider/SliderTitle.tsx
- projects/Mallard/src/screens/article/slider/index.tsx
- projects/Mallard/src/screens/home-screen.tsx
- projects/Mallard/src/screens/identity-login-screen.tsx
- projects/Mallard/src/screens/issue-screen.tsx
- projects/Mallard/src/screens/lightbox.tsx
- projects/Mallard/src/screens/settings-screen.tsx
- projects/Mallard/src/screens/settings/api-screen.tsx
- projects/Mallard/src/screens/settings/cas-sign-in-screen.tsx
- projects/Mallard/src/screens/settings/default-info-text-webview.tsx
- projects/Mallard/src/screens/settings/dev-zone.tsx
- projects/Mallard/src/screens/settings/gdpr-consent-screen.tsx
- projects/Mallard/src/screens/settings/subscription-details-screen.tsx
Fixing those errors.
There's a few changes I wasn't sure about, I'll highlight them in the code with GitHub comments.
> Live 1971 fix eslint errors

- projects/Mallard/src/components/EditionsMenu/EditionsMenu.tsx
- projects/Mallard/src/components/EditionsMenu/__tests__/__snapshots__/EditionsMenu.spec.tsx.snap
- projects/Mallard/src/screens/identity-login-screen.tsx
Fix edition menu height on android.
- add height value
> Live 2139: menu cut in half

- Makefile
The Makefile ESlint and TSC scripts had gone wrong.
> CHORE-fix-makefile

- projects/Mallard/src/AppNavigation.tsx
The modal background was black rather than transparent and the Y-axis modal animation was missing.
> LIVE-2143: fix animation and overlay style

- projects/Mallard/src/AppNavigation.tsx
Amends transition so the lightbox transitions in and out vertically
> Live 2182 :  Lightbox Transition

- projects/Mallard/fastlane/Fastfile
Update fastlane configs so we can release a beta build
> Live 2254 fastlane signing

- projects/Mallard/src/App.tsx
- projects/Mallard/src/authentication/AccessContext.tsx
- projects/Mallard/src/components/layout/slide-card/header.tsx
- projects/Mallard/src/screens/article/body.tsx
Remove unused code / comments from the spike branch
> remove unused code

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/src/screens/settings/gdpr-consent-screen.tsx
Privacy settings were repeating.
- remove duplicate flatlist
- add Separator components where needed
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/122777800-4b04b000-d2a4-11eb-9ea1-accc3779bf99.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/122777012-8a7ecc80-d2a3-11eb-8a0b-03f55c70e7bb.png"  width="300px"/>
| <img src="https://user-images.githubusercontent.com/77005274/122777872-5b1c8f80-d2a4-11eb-93f1-b538290e1ca0.png" width="300px" />  | <img src="https://user-images.githubusercontent.com/77005274/122777145-a8e4c800-d2a3-11eb-9c08-009dced7f607.png" width="300px" /> |
> LIVE-2627: remove duplicate flatlist

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Bumping iOS Version 7.9 -> 8.0
> Bump version number to 8.0

- projects/Mallard/src/screens/issue-screen.tsx
Fixes console warning.
- Pull component JSX inline.
No UI changes.
> LIVE-2674: fix component error

- projects/Mallard/src/components/article/types/article/webview.tsx
- projects/Mallard/src/components/article/types/crossword.tsx
- Removed some console log
- Setting `isReady` when it is actually ready
- Setting empty view to avoid error msg
> Some minor refactoring

- projects/backend/controllers/render.ts
We were overriding all tags which was breaking article template styles.
- fix getTags function
> Live 2835 fix tags

- package.json
- projects/Mallard/ios/Gemfile.lock
- yarn.lock
In preps for merging mega-pr into `master`, we want to make sure there aren't any unexpected things in the master branch.
The branch `sync-master` has changes from the `master` branch
> Sync with master

- README.md
- projects/Apps/scripts/src/fetch-dev-env.js
- projects/Mallard/README.md
- projects/archiver/package.json
- projects/aws/README.md
- projects/backend/README.md
- projects/backend/capi/atoms.ts
Updated outdated ReadMe and removed all the references of 'frontend' and replaced with 'mobile' as we no longer use 'frontend'
Test:
please run the apps and backend locally from this branch just to make it does not break local development process
> ReadMe update + refactoring

- projects/Apps/scripts/src/fetch-dev-env.js
- projects/Mallard/package.json
> Updated dev creds fetching commands

- projects/Mallard/README.md
Editions app has multiple stages and environments and they explained in a separate [doc](https://docs.google.com/document/d/1fopf0JamGZb1rswj2rFRgpYbtBj5OW9Kkieb1LJEnlw/edit?usp=sharing) and this PR updates the ReadMe
> Updated ReadMe with Stages & Environments

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Updating iOS release version to 8.1
> bump version to 8.1

- projects/backend/controllers/render.ts
- Change 1
- Change 2
| --- | --- |
| <img src="" width="300px" /> | <img src="" width="300px" /> |
> LIVE-2952: fix a matcher

- .github/workflows/android-beta.yml
> First Github Action for android build

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Updating iOS release version to 8.2.
> bump version to 8.2

- .github/workflows/scheduled-ios-beta.yml
- projects/Mallard/fastlane/Fastfile
Attempting to fix the ios beta build
The error appeared after an update to React Native
I googled the error and got this: https://gist.github.com/ashokds/ac49e6f9e98755365abf3096dadb5a00
This lead me to this: https://github.com/actions/virtual-environments/issues/2638
> fix: Increase Mac OS version to support XCode 12.5

- projects/Mallard/src/screens/settings-screen.tsx
> Fix: Hide duck menu

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Update Marketing version to 8.4
> bump version to 8.4

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Update marketing version to 8.5
> bump version 8.5

- projects/Mallard/package.json
- projects/Mallard/yarn.lock
Dependabot wanted to upgrade a dependency linked to this. Searching through the code, this dependency doesnt appear to be used.
> chore: Remove nodegit

- package.json
- projects/Apps/common/package.json
- projects/Apps/common/src/index.ts
- projects/Apps/common/src/logging.ts
- projects/Apps/yarn.lock
- projects/archiver/local.ts
- projects/archiver/main.ts
- projects/archiver/package.json
- projects/archiver/src/utils/s3.ts
- projects/archiver/yarn.lock
- projects/backend/backend.ts
- projects/backend/package.json
- projects/backend/s3.ts
- projects/backend/utils/try.ts
- projects/backend/yarn.lock
- projects/logging/index.ts
- projects/logging/package.json
- projects/logging/yarn.lock
- yarn.lock
#1906 was moaning at me to do this. I thought I would upgrade it across the whole project so it is in sync
- Minor tweaks to the types. Tests and Validators all run correctly, but some of the changes will have a run time effect. So worth checking its all ok.
- Dotenv needed a version upgrade to include the types. They are all now on the same version.
- linters needed an upgrade to be compatible. They are all now on the same version.
> chore: Update Typescript

- projects/archiver/package.json
- projects/archiver/yarn.lock
This is a fix for #1880
- Updated the required Jest dependencies and ran the tests.
> chore: Update Jest for archiver

- projects/logging/package.json
- projects/logging/yarn.lock
As a fix for #1883
- Updates to the required jest packages. Ran test and validate and all seems well.
> chore: Update jest for logging

- projects/Apps/common/package.json
- projects/Apps/yarn.lock
Designed to resolve #1882
- Updated the required Jest packages and all run as expected
> chore: Update jest in the Apps folder

- projects/Mallard/src/apollo.ts
- projects/Mallard/src/helpers/screen.ts
Searching through the code, looks like its never used and the computed value function is called each time.
- Removed the image resolver which looks like dead code, worth a double check.
> chore: Remove Image Resolver

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> Bump version to 8.6

- projects/Mallard/package.json
- projects/Mallard/src/AppNavigation.tsx
- projects/Mallard/src/navigation/NavigationModels.tsx
- projects/Mallard/src/screens/settings-screen.tsx
- projects/Mallard/src/screens/settings/dev-zone.tsx
- projects/Mallard/src/screens/settings/join-beta-button.tsx
- projects/Mallard/yarn.lock
When upgrading to RN66, an error occurred on nested flatlists. This was affecting the Settings section
- Moved away from `List` and used `Row` and `Seperator` instead.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/935975/142989293-9843bb89-cdad-4770-8ba7-e523e9c05077.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/935975/142989361-0d3335ed-4960-4089-8bce-198345c530db.png" width="300px" /> |
> Fix: Settings menu error

- package.json
- yarn.lock
Putting back the correct version of node-fetch to allow this to work. Have run a branch build and confirmed it works.
- Putting back node-fetch v2
> Fix: iOS Build

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> Bump version to 8.7

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Updated MARKETING_VERSION from 8.7 to 8.8
> Bump version to 8.8

- projects/Mallard/android/app/build.gradle
- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/__mocks__/react-native-iap.js
- projects/Mallard/src/authentication/services/iap.ts
- projects/Mallard/yarn.lock
Reverts guardian/editions#1918
> Revert "chore: Update React Native IAP"

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Update Marketing Version to 8.9
> Bump version number 8.9

- projects/Mallard/src/hooks/use-issue-provider/index.tsx
- projects/Mallard/src/screens/home-screen.tsx
Cache or Promise removal impacted the performance of the menu. This PR looks to put things back as they used to be. This moves the performance hit from the choice of edition to the choice of front. Giving better perceived loading time.
This sees the greatest benefit on mobile devices.
**Please Note:**
To make this better would be to update/have a new endpoint where we can get all the issues and their fronts in one request. Then we could show and hide on the menu to give greater performance. Then on choice of the front we could update the issue hook. This could potentially be done on the Issue Summary endpoint
- Bypass the hook so that issue can be fetched from source (as it was with cache or promise)
- Store the result in local state in the menu component.
- Once the user has chosen the …
> fix: Menu Performance

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> Bump version number to 9.0

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Update Marketing Version to 9.1
> bump version 9.1

- projects/Mallard/src/components/ScreenHeader/IssueScreenHeader/IssueScreenHeader.tsx
Issue title wasn't correctly rendering the title, removing the `useCallback` fixes this
> fix: Issue Header

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Update Marketing version to 9.2
> Bump version 9.2

- projects/Mallard/src/AppNavigation.tsx
- projects/Mallard/src/navigation/NavigationModels.tsx
- projects/Mallard/src/screens/in-app-purchase-screen.tsx
- projects/Mallard/src/screens/settings/dev-zone.tsx
Adding the ability to make a purchase to enable alternative testing for IAP.
This is now available via a button in the dev menu as previously demoed.
> feat: In App Purchase

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Update Marketing Version to 9.3
> Bump version to 9.3

- projects/Apps/crosswords/package.json
- projects/Apps/yarn.lock
To fix the vulnerability highlighted in #2009
> chore: Update Webpack Dev Server

- package.json
- projects/Apps/common/jest.config.js
- yarn.lock
Resolve the following dependency update #1932
Also the Jest file is a cheeky extra on the linting side
> chore: Update project eslint

- projects/Mallard/package.json
- projects/Mallard/yarn.lock
Originally an attempt to resolve #1990 however, the package doesn't have the latest dependencies updated. However, this is a patch change and everything continues to work as expected so worth putting in.
> chore: Update Bottom Sheet

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
Small bump to React Native Webview to hopefully resolve some user issues
> chore: Update RN Webview

- projects/Mallard/src/hooks/use-issue-provider/index.tsx
- projects/Mallard/src/screens/issue-screen.tsx
Reload button is not refreshing the issue. This is most likely due to the Memoisation of the issue screen. Previously there was a check to see if the issue path had changed on that component, I have reinstated that but slightly differently.
This will need checking with the production team
> fix: Reload button in preview

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
Manually changed and tested #2038
> chore: Update Moment

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> chore: 9.4 Version update

- projects/Mallard/src/components/front/image-resource.tsx
Left in a bit of test code, that needs removing
> fix: Image Placeholder Styling

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> Bump version to 9.5

- projects/Mallard/src/hooks/use-issue-downloads.tsx
Production staff are having problems when editing issues and the issue itself keeps downloading. In Preview, the team need the latest changes always. As a result, auto download through the daily download, push notification downloads and the fail safe have been turned off for Preview.
Production users should still be able to manually download an issue through the issue select menu.
> chore: Don't auto download in preview

- projects/Mallard/src/screens/issue-screen.tsx
Accidentally committed a log during testing.
> chore: Tidy Log

- projects/Mallard/src/components/front/index.tsx
When moving around on Fronts, when changing an issue, your position was kept. That was unnatural for a user as they expect the issue to reset when viewing a different day
- Resets the positioning on each front when the issue changes
> feat: Scroll Back on Front when Issue Changes

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> chore: Bump version to 9.6

- projects/Apps/ophan/build.gradle
- projects/Apps/ophan/gradle/wrapper/gradle-wrapper.properties
- projects/Apps/ophan/settings.gradle
- projects/Mallard/android/build.gradle
- projects/Mallard/android/gradle.properties
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
> Fix the Android Build

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> bump version 9.7

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> chore: Bump to 9.8

- projects/Mallard/package.json
- projects/Mallard/yarn.lock
Good to keep dependencies up to date.
> chore: Update mockdate

- projects/Mallard/package.json
- projects/Mallard/yarn.lock
> chore: Remove GraphQL

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
To help resolve an issue in Team City.
> chore: Update React Native Keychain

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/components/EditionsMenu/EditionsMenuButton/__tests__/__snapshots__/EditionsMenuButton.spec.tsx.snap
- projects/Mallard/src/components/Lightbox/__tests__/__snapshots__/LightboxCaption.spec.tsx.snap
- projects/Mallard/src/components/ScreenHeader/IssueScreenHeader/__tests__/__snapshots__/IssueScreenHeader.spec.tsx.snap
- projects/Mallard/src/components/icons/__tests__/__snapshots__/AppLogo.spec.tsx.snap
- projects/Mallard/src/components/icons/__tests__/__snapshots__/BurgerMenu.spec.tsx.snap
- projects/Mallard/src/components/icons/__tests__/__snapshots__/Editions.spec.tsx.snap
- projects/Mallard/src/components/icons/__tests__/__snapshots__/EditionsMenu.spec.tsx.snap
- projects/Mallard/src/components/icons/__tests__/__snapshots__/Newspaper.spec.tsx.snap
- projects/Mallard/src/components/icons/__tests__/__snapshots__/Quote.spec.tsx.snap
- projects/Mallard/src/components/icons/__tests__/__snapshots__/SettingsCog.spec.tsx.snap
- projects/Mallard/yarn.lock
Keep it in line with the dependencies that use it.
> chore: Update React Native SVG

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> Bump version 9.9

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/App.tsx
- projects/Mallard/src/components/ScreenHeader/IssuePickerHeader/__tests__/__snapshots__/IssuePickerHeader.spec.tsx.snap
- projects/Mallard/src/components/ScreenHeader/IssueScreenHeader/__tests__/__snapshots__/IssueScreenHeader.spec.tsx.snap
- projects/Mallard/yarn.lock
Updates Gesture handler to prevent the following bug:
https://github.com/software-mansion/react-native-gesture-handler/issues/1675
- Follows latest installation instructions
> chore: React Native Gesture Handler update

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Version bump for next iOS Release
> chore: 9.11 Version Bump

- projects/Mallard/src/screens/article/slider/index.tsx
Seems that we need to find a middle ground. This removes the need for it being an animated component, which should improve performance, and reduces the number of articles that live off screen. Will mean fast scrollers will have a loading experience, but that is not different to the PagerView implementation.
> chore: FlatList perf

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Update Marketing version to 9.12
> Bump version 9.12

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Bumps for the next release version
> chore: 9.13 Version Bump

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
As per Snyk report, this required an upgrade.
I have built the app and the app continues to work.
> chore: Upgrade Sentry

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> Bump version 9.14

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> Bump version to 9.15

- projects/Mallard/package.json
- projects/Mallard/src/components/weather.tsx
- projects/Mallard/src/helpers/date.ts
- projects/Mallard/yarn.lock
Due to the original work and the subsequent revert on #2176, it seems prudent to take a more careful approach to `Date`
This is a start of a `Date` abstraction that will look to remove `Moment` and replace it with `date-fns`. I plan to do this step by step so we can monitor feedback.
This starts at the simplest point, with the Weather.
- Adds `format` abstraction to `date` utils.
- Installs `date-fns`
- Apples the abstraction to the weather.
> chore: Date Format Abstraction

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> Bump version to 9.16

- projects/Mallard/src/components/article/types/article/webview.tsx
We occasionally see `error -1100` when a local article is not loading. As a result, this PR changes the URI to be a stateful value. If there is an error, we show the API url instead. This does not take into account if the user incurs a problem and is offline.
> feat: Backup Article URI

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> Bump version 9.17

- projects/Mallard/ios/Podfile.lock
Updates the podfile to be in sync with the previous changes to Hermes in RN 0.70.8
> fix: Hermes Podfile Sync

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Bump the version to 9.18 after the release
> feat: 9.18 Version bump

- projects/Mallard/src/components/EditionsMenu/EditionsMenu.tsx
- projects/Mallard/src/components/EditionsMenu/__tests__/EditionsMenu.spec.tsx
- projects/Mallard/src/components/ScreenHeader/IssueScreenHeader/IssueScreenHeader.tsx
- projects/Mallard/src/components/ScreenHeader/IssueScreenHeader/__tests__/IssueScreenHeader.spec.tsx
- projects/Mallard/src/components/issue/issue-row.tsx
- projects/Mallard/src/components/weather.tsx
- projects/Mallard/src/screens/editions-menu-screen.tsx
- projects/Mallard/src/screens/settings-screen.tsx
- projects/Mallard/src/screens/settings/gdpr-consent-screen.tsx
- projects/Mallard/src/screens/settings/manage-editions-screen.tsx
- projects/Mallard/src/screens/weather-geolocation-consent-screen.tsx
A selection of events that should cover most of the user interactions not already covered.
Please bear in mind that screen views are automatically recorded via React Navigation
- Added and updated events where appropriate
> feat: Analytics events

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> Bump version 9.19

- projects/Apps/crosswords/package.json
- projects/Apps/yarn.lock
Crossword bundling failing due to an outdated deep dependency of Babel Core.
> fix: Crossword Bundling

- projects/Mallard/android/app/src/main/java/com/guardian/editions/MainApplication.java
Change that allows us to remote debug Android webviews in the app so we can get to the bottom of the crosswords issue.
> chore: Inspect release webview

- projects/Mallard/android/app/build.gradle
- projects/Mallard/android/build.gradle
- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
Installs the Okta's native dependency and their quirks
> feat: Okta Native Install

- projects/Mallard/.gitignore
- projects/Mallard/android/app/build.gradle
- projects/Mallard/android/app/src/main/java/com/guardian/editions/MainApplication.java
- projects/Mallard/android/sentry.properties
- projects/Mallard/android/settings.gradle
- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
- projects/Mallard/ios/Podfile.lock
- projects/Mallard/ios/sentry.properties
- projects/Mallard/package.json
- projects/Mallard/src/download-edition/clear-issues-and-editions.ts
- projects/Mallard/src/hooks/use-gdpr.tsx
- projects/Mallard/src/screens/settings/gdpr-consent-screen.tsx
- projects/Mallard/src/services/__tests__/errors.spec.ts
- projects/Mallard/src/services/errors.ts
- projects/Mallard/yarn.lock
As discussed, this removes Sentry from the App. Both iOS and Android build locally.
> chore: Remove Sentry

- projects/backend/package.json
- projects/backend/yarn.lock
Updating to the latest minor version,
> chore: Update Jest for Backend

- projects/Mallard/package.json
- projects/Mallard/src/AppNavigation.tsx
- projects/Mallard/src/components/front/index.tsx
- projects/Mallard/yarn.lock
Looking to resolve: https://github.com/guardian/editions/pull/2158, by updating the eslint import rule
> chore: Update ESLint import

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> Bump version to 9.20

- projects/Mallard/package.json
- projects/Mallard/yarn.lock
This was only used in the Identity code and is now not used
> chore: Remove Query String

- projects/Apps/crosswords/package.json
- projects/Apps/yarn.lock
To help resolve the security dependency listed here: https://github.com/guardian/editions/security/dependabot/260
- Update React to its Minor version (which is still pretty out of date)
> chore: Update React in Crosswords project

- projects/Apps/common/package.json
- projects/Apps/yarn.lock
Update the Jest versions in the common package to resolve: https://github.com/guardian/editions/security/dependabot/228
Tests pass
> chore: Update Jest in Common

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> Bump version to 9.21

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/helpers/diagnostics.ts
- projects/Mallard/src/services/content-auth-service.ts
- projects/Mallard/yarn.lock
Updates `react-native-device-info`. Few functions changed return type so updated that through the code.
> chore: Update React Native Device Info

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> Bump version to 9.22

- projects/Mallard/android/app/src/main/AndroidManifest.xml
- projects/Mallard/android/build.gradle
- projects/Mallard/ios/Podfile
- projects/Mallard/ios/Podfile.lock
Following the instructions below to ensure Advertising ID is removed from iOS and Android.
- https://rnfirebase.io/analytics/usage#disable-ad-id-usage-on-ios
- https://stackoverflow.com/questions/52380615/is-my-app-or-its-dependencies-violating-the-android-advertising-id-policy/52393188#52393188
> fix: Remove Ad Id

- projects/Mallard/src/hooks/use-issue-provider/index.tsx
It appears that sometimes when downloading an issue, there are the data files missing (html, issue, front). This is causing the menu to not work leading to customer complaints.
This fix doesn't solve the root cause, but it does allow the app to be useable again if you have an internet connection.
- If there is a failure to get files from the file system, then we try the API again
> fix: Issue not downloading plaster

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> Bump version 9.23

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Update next version of Editions to 9.24
> Bump version to 9.24

- projects/Mallard/src/download-edition/prepare-and-download-issue.ts
- projects/Mallard/src/hooks/use-config-provider.tsx
Currently have to be logged in for devtools to show. Nice to see them all the time when working with the simulator.
> Chore: Devtools in dev

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Bump Editions iOS version to 9.25
> Bump version to 9.25

- projects/Apps/common/src/helpers.ts
- projects/Apps/common/src/index.ts
- projects/Mallard/src/hooks/use-okta-sign-in.tsx
Linting is failing, this will fix it!
> fix: Linting Fixes

- .github/workflows/snyk.yml
- README.md
- docs/08-✅-releases.md
- docs/09-fronts-layout.md
- projects/backend/README.md
- script/upload-ios-build.sh
I've already updated the branch name in the repo settings, and this PR updates references throughout the code.
I've also updated the riff raff continuous deployment config for the server-side build.
> Rename default branch to main

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> Bump version 9.26

- projects/archiver/package.json
- projects/archiver/src/invoke/__tests__/index.spec.ts
- projects/archiver/src/invoke/__tests__/parser.spec.ts
- projects/archiver/src/services/__tests__/task-handler.spec.ts
- projects/archiver/src/tasks/front/helpers/__tests__/media.spec.ts
- projects/archiver/src/tasks/indexer/helpers/__tests__/_tests_/get-issues.spec.ts
- projects/archiver/src/tasks/indexer/helpers/__tests__/get-issue-summary.spec.ts
- projects/archiver/src/tasks/indexer/helpers/__tests__/get-published-version.spec.ts
- projects/archiver/src/tasks/indexer/helpers/__tests__/summary.spec.ts
- projects/archiver/src/tasks/notification/helpers/__tests__/_tests_/device-notifications-helpers.spec.ts
- projects/archiver/src/tasks/notification/helpers/__tests__/device-notifications.spec.ts
- projects/archiver/src/utils/__tests__/backend-client.spec.ts
- projects/archiver/yarn.lock
- projects/backend/utils/try.ts
Another dev dependency blitz, this time on the archiver
- Updated packages and followed the errors
- Ran `test` and `validate` only as I couldnt get the rest to work
> chore: Archiver dev dependencies

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/download-edition/__tests__/clear-issues.spec.ts
- projects/Mallard/src/download-edition/__tests__/download-and-unzip.spec.ts
- projects/Mallard/src/helpers/__tests__/files.spec.ts
- projects/Mallard/src/hooks/__tests__/use-issue-summary-provider.spec.tsx
- projects/Mallard/yarn.lock
In an attempt to keep things up to date, and to hopefully address download related issues
> chore: Update FS related packages

- .github/workflows/android-release.yml
Follows the changes made in Android Beta workflow to get the release workflow working correctly.
- Update nvm command
- Update `install` command
> fix: Android Release

- projects/backend/package.json
- projects/backend/yarn.lock
Looking to solve this vulnerability: https://github.com/guardian/editions/security/dependabot/333
- Upgrade Chai
- Tests pass
> chore: Upgrade Chai

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Update next iOS version to 9.29
> Bump version 9.29

- .github/workflows/snyk.yml
Moving to a separate guardian-editions project
> Update snyk.yml (guardian-editions)

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Update the next ios version to 9.31
> Bump version to 9.31

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
Update React Native Localize
- Update the package
- Tested the build
> chore: Update React Native Localize

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> Bump version 9.34

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Update next iOS version to 9.35
> Bump version to 9.35

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Update Marketing version to 9.36
> Bump version to 9.36

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Update next version of iOS to 9.37
> Bump version to 9.37

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/yarn.lock
With a mixture of changes to the dependecies, it seems a few were missed out. This caused the iOS build to fail
- Updated dependencies
> chore: Missing Dependencies

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> Bump version to 9.38

- projects/Mallard/src/components/Modals/MissingIAPModal.tsx
- projects/Mallard/src/components/Modals/SubFoundModal.tsx
- projects/Mallard/src/components/SignInFailedModalCard.tsx
- projects/Mallard/src/components/sign-in-modal-card.tsx
- projects/Mallard/src/components/sub-not-found-modal-card.tsx
- projects/Mallard/src/components/weather.tsx
- projects/Mallard/src/helpers/words.ts
- projects/Mallard/src/screens/external-subscription.tsx
- projects/Mallard/src/screens/home-screen.tsx
- projects/Mallard/src/screens/issue-screen.tsx
- projects/Mallard/src/screens/onboarding/cards.tsx
- projects/Mallard/src/screens/settings-screen.tsx
- projects/Mallard/src/screens/settings/already-subscribed-screen.tsx
- projects/Mallard/src/screens/settings/join-beta-button.tsx
- projects/Mallard/src/screens/settings/manage-editions-screen.tsx
- projects/Mallard/src/screens/settings/subscription-details-screen.tsx
- projects/Mallard/src/screens/weather-geolocation-consent-screen.tsx
`npx knip` pointed out some unused exports. This lead to a code cleanup of the copy across the app
- Remove unused exports
- used correct casing to not confuse with components
Wokring as expected. Tests and validation all pass.
> chore: Copy tidyup

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> Bump version to 9.40

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> Bump version 9.42

- projects/Apps/crosswords-bundle/.gitignore
- projects/Apps/crosswords-bundle/README.md
- projects/Apps/crosswords-bundle/package.json
- projects/Apps/crosswords-bundle/public/index.html
- projects/Apps/crosswords-bundle/src/components/CrosswordView.jsx
- projects/Apps/crosswords-bundle/src/index.css
- projects/Apps/crosswords-bundle/src/index.tsx
- projects/Apps/crosswords-bundle/src/setupTests.ts
- projects/Apps/crosswords-bundle/tsconfig.json
- projects/Apps/crosswords/scripts/bundle-html.js
- projects/Apps/crosswords/scripts/manifest.js
- projects/Apps/crosswords/src/html-bundle-info.json
- projects/Apps/yarn.lock
- projects/Mallard/html/manifest.js
- projects/Mallard/src/components/article/types/crossword.tsx
- projects/Mallard/src/html-bundle-info.json
Due to issues with bundling within the old Apps package, this takes a simpler approach of using `create-react-app` to deliver the crossword solution.
This is just the package on its own, not implemented into Mallard
- `create-react-app`
- `package.json` changes to get it to bundle so that it can be run locally
- Copied across and improved implementation
> feat: Crosswords bundle

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> bump version 9.44

- projects/Mallard/src/screens/lightbox.tsx
When pressing on an image in the lightbox, the current functionality is to toggle the controls. However, this feels very harsh. This adds a soft fade.
- Simplifying the state managment
- Adding the animation and wrapper
- As this is a "hiding" animation, the close button is still pressable when hidden. So this disables it when hidden.
https://github.com/guardian/editions/assets/935975/935a057f-265c-4fc7-9ac7-05ce578b1c3f
> Feat: Lightbox soft fade

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Updating version to 10.0 (Quick Cryptic)
> bump version 10.0

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> bump version 10.1

- projects/Mallard/ios/Podfile.lock
Build was not able to complete as it had an older version of hermes in the Pods.
- Updated the Pods
> fix: Hermes Podfile.lock upgrade

- docs/11-yarn-modern.md
Documenting the recent investigation into yarn modern and why it was rejected at this time
> docs: Yarn Modern

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> Bump version 10.2

- projects/Mallard/package.json
- projects/Mallard/yarn.lock
With talk of Identity support, it seemed prudent to update Okta to the latest library
- Update Okta npm package
https://github.com/user-attachments/assets/e294c0f5-efea-4f14-b557-493d40f668fc
> chore: Upgrade Okta

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
Required for the next React Native upgrade
- Updated the package
Tested with some of the persisted options and they continue to work.
> chore: Update async storage

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> Bump version to 10.4

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> Bump version 10.5

- projects/Mallard/src/helpers/words.ts
Updared IAP Migration message copy
- Updated copy
> chore: Updated IAP message copy

- projects/Mallard/src/helpers/words.ts
- projects/Mallard/src/screens/issue-screen.tsx
- projects/Mallard/src/screens/settings/dev-zone.tsx
Message was suffering from a race condition, this is now resolved.
- Added in some helpers to make it easier to test
- Fixed the Message showing
> chore: Message Helpers and Message Fix

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
> Bump version 10.6

- projects/Mallard/src/helpers/words.ts
> chore: Migration copy update
