guardian/editions

- projects/Mallard/src/components/EditionsMenu/RegionButton/RegionButton.stories.tsx
- projects/Mallard/src/components/EditionsMenu/RegionButton/RegionButton.tsx
- projects/Mallard/src/components/EditionsMenu/RegionButton/__tests__/__snapshots__/RegionButton.spec.tsx.snap
Background colour on the Region Button was too dark. After consultation with Ana, this fixes it.
Also noticed the `text` function from Storybook Knobs is causing a problem, so removed this.
> chore: Region Button Background Colour Change

- projects/Mallard/src/components/article/html/components/header.ts
This is to fix a bug introduced by updating the main media image crop. 
[**Trello Card ->**](https://trello.com/c/AhP0tx3T/1219-main-media-images)
View a review article in the Culture section. 
| --- | --- |
> fix-star-rating-main-image

- projects/Mallard/src/components/Button/Button.stories.tsx
- projects/Mallard/src/components/EditionsMenu/EditionsMenuButton/EditionsMenuButton.stories.tsx
- projects/Mallard/src/components/EditionsMenu/EditionsMenuButton/EditionsMenuButton.tsx
- projects/Mallard/src/components/EditionsMenu/EditionsMenuButton/__tests__/EditionsMenuButton.spec.tsx
- projects/Mallard/src/components/EditionsMenu/EditionsMenuButton/__tests__/__snapshots__/EditionsMenuButton.spec.tsx.snap
- projects/Mallard/src/components/EditionsMenu/Header/Header.stories.tsx
- projects/Mallard/src/components/EditionsMenu/RegionButton/RegionButton.stories.tsx
- projects/Mallard/src/components/EditionsMenu/SpecialEditionButton/SpecialEditionButton.stories.tsx
- projects/Mallard/src/components/icons/Icons.stories.tsx
- projects/Mallard/src/components/icons/LeftChevron.tsx
- projects/Mallard/src/components/icons/__tests__/LeftChevron.spec.tsx
- projects/Mallard/src/components/icons/__tests__/RightChevron.spec.tsx
- projects/Mallard/src/components/icons/__tests__/__snapshots__/LeftChevron.spec.tsx.snap
- projects/Mallard/src/components/icons/__tests__/__snapshots__/RightChevron.spec.tsx.snap
- projects/Mallard/storybook/storyLoader.js
Editions menu button with storybook stories and tests.
This has a selected state rather than a separate button but this might change when it's all hooked up.
I also did a little housekeeping to get all the Editions menu stories together.
> feat: Editions Menu Button

- projects/Mallard/package.json
- projects/Mallard/yarn.lock
We suspect Sentry is causing issues as a result of a bug fixed by https://github.com/getsentry/sentry-android/releases/tag/2.1.2
This PR upgrades sentry to get a more recent version of the sentry android client
If you have access to the google play console you can see the associated crash here https://play.google.com/apps/publish/?account=5145003088508502793#AndroidMetricsErrorsPlace:p=com.guardian.editions&appid=4975692525202031393&appVersion=PRODUCTION&clusterName=apps/com.guardian.editions/clusters/ea826e68&detailsAppVersion=PRODUCTION&detailsSpan=7
These commits fixed it in the Sentry android client we think https://github.com/getsentry/sentry-android/pull/415/commits
> Upgrade sentry in previous release branch to 1.4.4.

- projects/Mallard/src/services/errors.ts
This adds the work in https://github.com/guardian/editions/pull/1270 to the release/2.0.9 release branch for an urgent patch release
> Patch into release: Remove the logging from the Error service (#1270)

- projects/Apps/common/src/index.ts
- projects/Mallard/src/components/EditionsMenu/EditionsMenu.stories.tsx
- projects/Mallard/src/components/EditionsMenu/EditionsMenu.tsx
- projects/Mallard/src/components/EditionsMenu/Header/Header.tsx
- projects/Mallard/src/components/EditionsMenu/Header/__tests__/__snapshots__/Header.spec.tsx.snap
- projects/Mallard/src/components/EditionsMenu/ItemSeperator/ItemSeperator.tsx
- projects/Mallard/src/components/EditionsMenu/ItemSeperator/__tests__/ItemSeperator.spec.tsx
- projects/Mallard/src/components/EditionsMenu/ItemSeperator/__tests__/__snapshots__/ItemSeperator.spec.tsx.snap
- projects/Mallard/src/components/EditionsMenu/__tests__/EditionsMenu.spec.tsx
- projects/Mallard/src/components/EditionsMenu/__tests__/__snapshots__/EditionsMenu.spec.tsx.snap
- projects/Mallard/storybook/storyLoader.js
This combines the previous PRs components together to create the design. 
Please note that the `onPress` in these components hasn't been hooked up yet as this will probably require passing in a React Navigation which will be better to do at the screen implementation stage.
> Feat: Editions menu composed

- projects/Mallard/package.json
- projects/Mallard/yarn.lock
Following from https://github.com/guardian/editions/pull/1282 let's apply the same fix to the master branch. The current version of sentry we're using has a bug where it causes the app to crash on android 5
##Test plan
This version of sentry is live in the latest version of android. We should double check on ios
> Upgrade sentry to 1.4.4.

- projects/Mallard/package.json
Since we have lifted the floor to iOS 12.4 this updates the ipad simulaor to run on iOS 13.3
> am-update-ipad-simulator

- projects/Mallard/firebase.json
It seems like if we turn off the Crashlytics Auto Collection feature in `firebase.json` file then on the first launch it crashes the app when sending any event through `crashlytics` interface (see screenshot)
This might be a bug in crashlytics RN package (not sure) and a possible workaround that I can see for now is keeping the auto collection feature `on` and then turn it `off` in runtime. A side effect of this change might be (which I'm not sure about) that Crashlytics may collect some data on App launch before we turn it off. I don't see any easier solution to this right now.
App crash error:
> Fix for crash on first launch - Crashlytics

- projects/Mallard/src/components/EditionsMenu/EditionsMenu.stories.tsx
- projects/Mallard/src/components/EditionsMenu/EditionsMenu.tsx
- projects/Mallard/src/components/EditionsMenu/EditionsMenuButton/__tests__/__snapshots__/EditionsMenuButton.spec.tsx.snap
- projects/Mallard/src/components/EditionsMenu/__tests__/EditionsMenu.spec.tsx
- projects/Mallard/src/components/icons/LeftChevron.tsx
- projects/Mallard/src/components/icons/__tests__/__snapshots__/LeftChevron.spec.tsx.snap
- projects/Mallard/src/components/layout/header/header.tsx
- projects/Mallard/src/helpers/settings/debug.ts
- projects/Mallard/src/helpers/storage.ts
- projects/Mallard/src/hooks/use-config-provider.tsx
- projects/Mallard/src/navigation/helpers/base.tsx
- projects/Mallard/src/navigation/index.ts
- projects/Mallard/src/navigation/navigators/sidebar/transition.tsx
- projects/Mallard/src/navigation/routes.ts
- projects/Mallard/src/screens/editions-menu-screen.tsx
- projects/Mallard/src/screens/issue-screen.tsx
- projects/Mallard/src/screens/settings/dev-zone.tsx
This hooks up the components 
- Uses the config context to enable a toggle switch in the dev menu to turn this on.
- Refactored `debug.ts` to be more generic for more switch use in the dev menu
- Wired up `EditionsMenu` and made the buttons clickable and have a selected state
- Updated the SideBar Navigator to accept the new menu, detect it and offer a reverse animation making it come out from the left.
- Updated tests and stories
As seen below:
> feat: Working Editions Menu with Feature Switch

- projects/Mallard/src/components/SportScore/SportScore.tsx
- projects/Mallard/src/components/sportscore/__tests__/__snapshots__/SportScore.spec.tsx.snap
> chore: Make Sport Score Trail Image Yellow

- projects/Mallard/src/helpers/__tests__/weather.spec.ts
- projects/Mallard/src/helpers/weather.ts
The weather was failing to load on android (prod) because the API was using an insecure protocol. This PR fixes that issue.
[**Trello Card ->**](https://trello.com/c/41q5wmzc/908-android-launched-app-no-weather-showing)
> Fix https issue for weather api

- projects/Mallard/src/App.tsx
- projects/Mallard/src/helpers/__tests__/async-queue-cache.spec.ts
- projects/Mallard/src/helpers/async-queue-cache.ts
- projects/Mallard/src/services/__tests__/logging.spec.ts
- projects/Mallard/src/services/logging.ts
Based on the discussion we had yesterday, we need to protect the logging endpoint a bit more.
This takes the previous logging approach and does the following:
- `log` purpose is to take in a log, check for consent and store it in the async storage queue
- `postLog` has become `postLogs` and is a function that attempts to post the async queue of logs. If there is no connection, don't try. If there is attempt. If successful clear the logs. If unsuccessful then the attempts logic kicks in and will stop attempting at the threshold (5) and clear the async queue.
- `postLogs` is now called on start up and when the user wakes up the app from the background vastly reducing the amount of times logs are sent.
- Tests on the new logic.
- This removes the need to make the Push Downloads 1 log as they …
> feat: Refactor Logging

- projects/Mallard/src/components/issue/issue-row.tsx
- projects/Mallard/src/components/issue/issue-title.tsx
- projects/Mallard/src/components/layout/header/header.tsx
- projects/Mallard/src/navigation/navigators/sidebar/transition.tsx
- projects/Mallard/src/screens/editions-menu-screen.tsx
Fixes the following:
- Moves the editions menu button to the far left
- Update the transition to come from the left rather than the middle
- Fills the menu so it fills the whole vertical rather than just where the menu sits
Please note: Tested on iPhone and Android as well.
> fix: Editions Menu iPad

- projects/Mallard/src/navigation/navigators/sidebar.tsx
Attempted to remove the restrictions on Android menus and seems pretty good even on Android 5.0. And worked quite well in a simulator suggesting performance should be fine.
> feat: Transparent Menu on Android

- projects/Mallard/src/navigation/navigators/modal.tsx
> Fix: Transparent background on Settings menu for Android

- projects/Mallard/src/components/EditionsMenu/RegionButton/RegionButton.tsx
- projects/Mallard/src/components/EditionsMenu/RegionButton/__tests__/__snapshots__/RegionButton.spec.tsx.snap
- projects/Mallard/src/components/EditionsMenu/__tests__/__snapshots__/EditionsMenu.spec.tsx.snap
As per @pradasa request, this is to now align.
> fix: Editions Menu Alignment

- projects/Mallard/jest-setup.js
- projects/Mallard/jest.config.js
- projects/Mallard/src/authentication/authorizers/__tests__/identity-authorizer.spec.ts
- projects/Mallard/src/authentication/lib/__tests__/AccessController.spec.ts
- projects/Mallard/src/components/EditionsMenu/__tests__/EditionsMenu.spec.tsx
- projects/Mallard/src/components/Lightbox/__tests__/LightboxCaption.spec.tsx
- projects/Mallard/src/components/article/html/__tests__/images.spec.ts
- projects/Mallard/src/download-edition/__tests__/clear-issues.spec.ts
- projects/Mallard/src/download-edition/__tests__/download-and-unzip.spec.ts
- projects/Mallard/src/helpers/__tests__/async-queue-cache.spec.ts
- projects/Mallard/src/helpers/__tests__/fetch.spec.ts
- projects/Mallard/src/helpers/__tests__/files.spec.ts
- projects/Mallard/src/helpers/__tests__/issues.spec.ts
- projects/Mallard/src/helpers/__tests__/settings.spec.ts
- projects/Mallard/src/helpers/settings/__tests__/defaults.android.spec.ts
- projects/Mallard/src/helpers/settings/__tests__/defaults.ios.spec.ts
- projects/Mallard/src/paths/__tests__/index.spec.ts
- projects/Mallard/src/push-notifications/__tests__/push-notifications.spec.ts
- projects/Mallard/src/push-notifications/__tests__/push-tracking.spec.ts
- projects/Mallard/src/screens/settings/__tests__/gdpr-consent.spec.ts
- projects/Mallard/src/services/__tests__/errors.spec.ts
- projects/Mallard/src/services/__tests__/logging.offline.spec.ts
- projects/Mallard/src/services/__tests__/logging.spec.ts
Had a little brainwave the other day to avoid mocking `locale` everywhere. We just do the mocking in a test setup file and off we go.
As it is essentially all native functions we cant really test `locale` itself so it all works out
> feat: Simplified Locale Mocking

- projects/Mallard/src/App.tsx
- projects/Mallard/src/push-notifications/push-notifications.ts
After testing at the weekend, I confirmed that @mohammad-haque issue with his Android device. The device was receiving a notification but not downloading anything. It turns out the contract has changed and now the `key` sits inside a `data` object which is the same for iOS. This fixes that.
Additionally we are calling download twice on startup for Android which I believe is causing our promise rejection message in dev.
> fix: Android Push Downloads

- projects/Mallard/src/components/ScreenHeader/IssuePickerHeader/IssuePickerHeader.stories.tsx
- projects/Mallard/src/components/ScreenHeader/IssuePickerHeader/IssuePickerHeader.tsx
- projects/Mallard/src/components/ScreenHeader/IssuePickerHeader/__tests__/IssuePickerHeader.spec.tsx
- projects/Mallard/src/components/ScreenHeader/IssuePickerHeader/__tests__/__snapshots__/IssuePickerHeader.spec.tsx.snap
- projects/Mallard/src/components/ScreenHeader/IssueScreenHeader/IssueScreenHeader.stories.tsx
- projects/Mallard/src/components/ScreenHeader/IssueScreenHeader/IssueScreenHeader.tsx
- projects/Mallard/src/components/ScreenHeader/IssueScreenHeader/__tests__/IssueScreenHeader.spec.tsx
- projects/Mallard/src/components/ScreenHeader/IssueScreenHeader/__tests__/__snapshots__/IssueScreenHeader.spec.tsx.snap
- projects/Mallard/src/components/ScreenHeader/ScreenHeader.stories.tsx
- projects/Mallard/src/components/ScreenHeader/ScreenHeader.tsx
- projects/Mallard/src/components/ScreenHeader/__tests__/ScreenHeader.spec.tsx
- projects/Mallard/src/components/ScreenHeader/__tests__/__snapshots__/ScreenHeader.spec.tsx.snap
- projects/Mallard/src/components/ScreenHeader/fixtures.tsx
- projects/Mallard/src/components/layout/header/header.tsx
- projects/Mallard/src/screens/home-screen.tsx
- projects/Mallard/src/screens/issue-screen.tsx
- projects/Mallard/storybook/storyLoader.js
- ScreenHeader has been split out so that its a base level component that can be used across the app
- Created a IssueScreenHeader component that uses ScreenHeader but manages all the navigation and inputs for the various different use cases
- Created a IssuePickerHeader components that again uses ScreenHeader for reusability and then repurposed back into the IssuePicker. This then has the `headerStyles` implementation required for the ticket
- Tests and stories
Please note: I would like to Refactor IssuePickerHeader further moving the buttons out into their own components, but this PR already feels to big so that will come next
[**Trello Card ->**](https://trello.com/c/CwmvTcT7/1397-changes-to-headers-on-fronts-and-issue-picker-screen)
> Feat: ScreenHeader refactor and IssuePickerHeader implementation

- projects/Apps/common/src/editions-defaults.ts
- projects/Apps/common/src/index.ts
- projects/Mallard/src/components/EditionsMenu/__tests__/EditionsMenu.spec.tsx
- projects/Mallard/src/components/EditionsMenu/__tests__/__snapshots__/EditionsMenu.spec.tsx.snap
- projects/Mallard/src/hooks/use-config-provider.tsx
For the header work we need the ability to add a subtitle and title for the issue picker header. It makes sense to keep it with the data for the edition.
[**Trello Card ->**](https://trello.com/c/CwmvTcT7/1397-changes-to-headers-on-fronts-and-issue-picker-screen)
> feat: Support Title and Subtitle in Regional Editions

- projects/Mallard/src/screens/log-in.tsx
- projects/Mallard/src/services/remote-config.ts
This PR removes the switch for apple sign in now that has been permanently released. It also removes the lightbox_enabled default value as we never used that switch. 
It also introduces a 'RemoteConfigProperty' type to reduce the number of unchecked string types used with this service. 
[**Trello Card ->**](https://trello.com/c/m8XuTVvr/1410-remove-the-apple-sign-in-feature-flag)
Release, check that the app still starts and apple sign in button is still there!
> Remove apple sign in switch

- projects/Mallard/src/components/ScreenHeader/IssuePickerHeader/IssuePickerHeader.stories.tsx
- projects/Mallard/src/components/ScreenHeader/IssuePickerHeader/IssuePickerHeader.tsx
- projects/Mallard/src/components/ScreenHeader/IssuePickerHeader/__tests__/IssuePickerHeader.spec.tsx
- projects/Mallard/src/components/ScreenHeader/IssuePickerHeader/__tests__/__snapshots__/IssuePickerHeader.spec.tsx.snap
- projects/Mallard/src/screens/home-screen.tsx
This provides support for the `IssuePickerHeader` to have `title` and `subTitle` passed into it. This is required for the Editions work to customise the Issue Picker
[**Trello Card ->**](https://trello.com/c/CwmvTcT7/1397-changes-to-headers-on-fronts-and-issue-picker-screen)
> feat: Title and Subtitle support for IssuePickerHeader

- projects/Apps/common/src/index.ts
- projects/Mallard/src/components/EditionsMenu/EditionsMenu.stories.tsx
- projects/Mallard/src/components/EditionsMenu/EditionsMenu.tsx
- projects/Mallard/src/components/EditionsMenu/__tests__/EditionsMenu.spec.tsx
- projects/Mallard/src/components/EditionsMenu/__tests__/__snapshots__/EditionsMenu.spec.tsx.snap
- projects/Mallard/src/screens/editions-menu-screen.tsx
Again in the spirit of breaking up my mega PR into smaller bits, this does the work to move `EditionsMenu` to a presentational component and move the hooks up to the parent.
I have also mocked out child components in the tests to make the snapshots smaller. When `RegionButton` changes, we don't need to see a snapshot change in a parent component like this, we just ensure the API is maintained through TS giving better hierarchical snapshot tests.
> feat: Editions Menu ready for wiring up

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/App.tsx
- projects/Mallard/src/navigation/navigators/sidebar.tsx
- projects/Mallard/yarn.lock
Crashes in Sentry seem to be related to React Native Screens. This was only required for iOS9.
It was in before the iOS9 work which suggests its implementation was there for performance reasons. So we will need to keep an eye on if there are many crashes due to memory
> chore: Remove RN Screens

- .github/workflows/scheduled-ios-beta.yml
- .github/workflows/upload-build.yml
- package.json
- projects/Mallard/android/app/build.gradle
- projects/Mallard/fastlane/Fastfile
- script/make-release.js
- yarn.lock
This is following from the idea raised by @mohammad-haque to try and keep track of releases. I've added a script called make-release.js to be run after publishing to one of the app stores. It:
- searches github for  a pre-existing release on the current commit
- if one exists, it patches that release and adds the version number of whatever just built
- if one doesn't exist, create a release with the name <branch_name>-<os>-<versionCode/build number>
So in the happy path we would expect:
- 2pm: builds triggered for android in teamcity, ios in github actions for commit `abc123`
- 2.10: android build finishes, creates a release for `abc123` called `master-android-<android version code>`
- 2:45: ios build finishes, finds the release and updates the name to `master-android-<android version …
> Add script to generate github release tags for each build

- projects/Mallard/src/components/Lightbox/LightboxCaption.tsx
Remove's linebreak before credit
> caption-no-breaking-space

- projects/Apps/common/src/collection/card-layouts.ts
This kind of card:
Is no longer required. This change modifies the backend so that future issues will no longer contain this card type. In a month we can then remove the associated code to render them client side (probably not that much code as we still have `threeStoryPageWithSidekick`)
These cards now look like this:
[**Trello Card ->**](https://trello.com/c/PSX1xC1X/1286-easy-win-get-rid-of-front-card-with-hed-on-square)
Release, check out 2 story cards in top stories/news containers. The above card is in the coronavirus front of issue sunday 28 June 2020
> Stop using twoStoryPageWithSidekick (backend)

- projects/Mallard/src/components/lists/DualButton.tsx
- projects/Mallard/src/components/lists/FullButton.tsx
- projects/Mallard/src/screens/settings-screen.tsx
_As a user using a screen reader, I want to know that the options on the settings are buttons so that I know that I can tap on it_
**Issues:**
The button options on the Settings do not read 'button', so users might not know that can tap on it to do something. It just reads the title.
[**Trello Card ->**](https://trello.com/c/Gf0d3gck/1380-accessibility-tell-users-using-screen-readers-that-the-buttons-on-the-setttings-are-buttons)
Switch on VoiceOver on iOS and TalkBack on Android on the device settings. Tap the settings options and check if it's telling users that the options are buttons.
> Accessibility: Tell users using screen readers that the buttons on the Settings are buttons pam_accessibility_buttons

- projects/Mallard/src/helpers/weather.ts
This PR changes how we decide the temperature unit on android. There is universal way to get user preference for temperature from an android device. This PR applies a simple logic to determine the unit:
1. User device local is the US: unit is F
2. Anything else: unit is C
[**Trello Card ->**](https://trello.com/c/S4pX3YIk/1404-locale-weather-unit-should-be-determined-by-os-settings-for-android)
> Fix: correct temperature unit on android

- projects/Mallard/src/components/article/html/css.ts
- projects/Mallard/src/helpers/webview.ts
- projects/Mallard/src/theme/spacing.ts
- projects/Mallard/src/theme/typography.ts
This PR:
- reduces headline font size on the smallPhone breakpoint to 20pt
- reduces the trail text size to 14pt on smallPhones
- implements a max card height of 520px, down from 530. In the designs this was originally 500px, baby steps... I have checked through one edition and I don't think this is a problem
The main motivation is to stop text overflow on small phones, and reduce the large space that sometimes appears below cover cards (to fix it completely we need taller cover cards)
I've also moved the `getScaledFont` function out of webview as it's not really got anything to do with webviews (though that's the main place it's used at the moment)
Before:
After:
[**Trello Card ->**](https://trello.com/c/z2kykKjb/1171-5s-cover-cards-draw-extra-padding)
Lots of scrolling through fronts on …
> Fix small phone styling issues. Drop card height

- projects/Mallard/src/helpers/settings/defaults.ts
Following from https://github.com/guardian/editions/pull/1309 we should show the preview controls - in particular the red 'reload' button for proofed issues so that the production team or anyone else using the app can re-fetch an issue after it has been re-proofed without restarting/reinstalling the app. 
[**Trello Card ->**](https://trello.com/c/PkjPqlFR/1336-production-edition-switching)
Verify that when the proof API is selected from the duck menu that the red reload button is visible
> Show preview controls when proof api selected.

- projects/Mallard/src/components/login/login-layout.tsx
iOS 13 introduced a new feature - [floating keyboard](https://support.apple.com/en-gb/HT210758) where users can 'undock' their keyboard and type with one hand. Unfortunately this doesn't play nicely with react native [KeyboardAvoidingView](https://reactnative.dev/docs/keyboardavoidingview) - I found [this](https://stackoverflow.com/questions/59871352/is-is-possible-on-ipad-os-to-detect-if-the-keyboard-is-in-floating-mode) stackoverflow post  complaining about the issue.
This currently results in a login screen that looks like this: 
The only solution for detecting whether the keyboard is floating or not at the moment seems to be to detect the width of the keyboard. This PR does that, and disables the KeyboardAvoidingView if a floating keyboard is detected (only for ios tablets)
[**Trello …
> Fix login screen when iPad 'floating keyboard' enabled

- projects/Apps/crosswords/package.json
- projects/Apps/yarn.lock
This updates the project to use the `v0.2.0` of the crossword package which accommodates special instructions. 
[**Trello Card ->**](https://trello.com/c/LRatVLul/1372-crossword-special-instructions)
Open Prize crossword on 27th June and you should see special instructions. 
| phone | tablet |
| --- | --- |
> Update crosswords to include special instructions

- projects/Mallard/src/helpers/diagnostics.ts
- projects/Mallard/src/helpers/storage.ts
- projects/Mallard/src/push-notifications/notification-service.ts
- projects/Mallard/src/push-notifications/push-notifications.ts
- projects/Mallard/src/screens/settings/dev-zone.tsx
To help investigate issues we may need to see that topics a user is registered to. This PR makes that information available in Duck Menu and in Diagnostic info.
[**Trello Card ->**](https://trello.com/c/qGL4Izsq/1373-push-downloads-display-registered-topics-in-dev-menu-and-diagnostics)
Duck Menu:
> Registered push tokens are now visible in Duck Menu and diagnostic info

- projects/Mallard/src/App.tsx
- projects/Mallard/src/download-edition/clear-issues.ts
- projects/Mallard/src/download-edition/prepare-and-download-issue.ts
Fixes the following issue: https://sentry.io/organizations/the-guardian/issues/1731217197/?project=1519156&query=is%3Aunresolved+dist%3A770&statsPeriod=14d
This was due to a race condition between downloading and periodic cleaning of downloads. This now will only clean when the edition is downloaded and towards the end of deleting issues.
> fix: Downloads missing folders

- projects/Mallard/src/components/Button/Button.stories.tsx
- projects/Mallard/src/components/Button/SettingsButton.tsx
- projects/Mallard/src/components/Button/__tests__/SettingsButton.spec.tsx
- projects/Mallard/src/components/Button/__tests__/__snapshots__/SettingsButton.spec.tsx.snap
- projects/Mallard/src/components/ScreenHeader/IssuePickerHeader/IssuePickerHeader.tsx
Adds a settings button to Storybook, a test and reimplements this back into the `IssuePickerHeader`
> feat: Settings button

- projects/Mallard/src/helpers/files.ts
This relates to the following error: https://sentry.io/organizations/the-guardian/issues/1355238363/events/9dd45998f434468a8d0eba6d536eb9f9/?project=1519156&query=is%3Aunresolved+dist%3A763&statsPeriod=14d
This is actually sending too many events as its anytime we don't get what we want from the endpoint. What we care about is if someone actually receives an issue summary. So now we only log an error if there is nothing from the endpoint and nothing in the cache.
Also the cache was returning a promise rather than the result. It resolved fine but was wonky.
> fix: Issue Summary error in Sentry

- projects/Apps/common/src/collection/card-layouts.ts
Followinig from #1324 we also want to get rid of the 3 story version of the 'sidekick' card type.
[**Trello Card ->**](https://trello.com/c/PSX1xC1X/1286-easy-win-get-rid-of-front-card-with-hed-on-square)
This is a backend change which will impact future issues, resulting in the 3 story sidekick card no longer appearing. Here is an example of such a card in Books, Saturday 11th July:
> Remove 3 story sidekick card from backend.

- projects/Mallard/src/components/issue/issue-row.tsx
From:
'Manage editions' to 'Manage downloads'
'Ok' to 'OK'
Copy consistency.
[**Trello Card ->**](https://trello.com/c/oVra53YG/1430-download-blocked-toast)
On Manage downloads screen, turn on 'wi-fi only' switch.
On the list of issues screen, tap on the download button to try to download it.
Can you see the modal? Are the copy changes applied?
> Change on the modal 'Unable to download'

- projects/Mallard/android/build.gradle
We had a conflicting firebase version that was causing android app to crash. It was due to pulling down a buggy version of the Firebase SDK. 
It would be better to have one source of truth for firebaes dependencies but that does require big refactoring.  
Details of the error can be found here:
https://stackoverflow.com/questions/62767041/firebase-messaging-on-android-suddenly-started-crashing-when-message-received
[**Trello Card ->**](https://trello.com/c/Atklc0nj/1434-fix-firebase-crash-on-android)
> Fixed conflicting firebase version

- projects/Mallard/src/download-edition/download-and-unzip.ts
We are logging "Download Blocked" in Sentry. Downloads are blocked when a user doesn't have enough signal. This is not a bug, this is intentional.
I have raised a UX/Design ticket so that we can communicate this blocking to a user as they are the ones that should be aware.
This event is already being stored in logging.
https://sentry.io/organizations/the-guardian/issues/1728310969/?project=1519156&query=is%3Aunresolved
> chore: Remove capturing Download Blocked event in Sentry

- projects/Apps/crosswords/package.json
- projects/Apps/yarn.lock
This PR locks the crossword package version to v0.1.8 as changes made for special instructions in later versions have broken some of the controls. 
The breaking PR was https://github.com/guardian/editions/pull/1333 .
Open crosswords and ensure that the Reveal all and Check all buttons are visible. 
| --- | --- |
> fix-crossword-controls

- projects/Apps/crosswords/package.json
- projects/Apps/yarn.lock
Implements https://github.com/guardian/editions/pull/1351 on the branch for our current [relase build](https://github.com/guardian/editions/releases/tag/b654e5cc)
> Hotfix for release: Fix crossword controls (copied from #1351)

- projects/Apps/crosswords/package.json
- projects/Apps/yarn.lock
We previously reverted an update to the crossword package as the `Reveal all` and `Check all` buttons were missing. 
A breaking [change](https://github.com/guardian/react-crossword/pull/7) was reverted on `react-crossword`and a new version of the package was  published, this PR updates to the latest package.
[**Trello Card ->**](https://trello.com/c/LRatVLul/1372-crossword-special-instructions)
The crosswords should now have the `Reveal all` and `Check all` buttons as well as special instructions when necessary, to test please check the Prize crossword on Saturday 27th June. 
| Special instructions | Solution buttons |
| --- | --- |
> update crosswords for special instructions

- .github/workflows/scheduled-ios-beta.yml
- .github/workflows/validate-app.yml
There is a new feature for Github actions to support manually triggering builds. This enables that for our ios build and validate-app builds. If this works then we can remove the upload-build workflow and associated script https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/ 
Check that we can trigger builds manually
> Add workflow_dispatch as build trigger.

- projects/Apps/common/src/index.ts
- projects/archiver/src/invoke/index.ts
- projects/archiver/src/tasks/issue/index.ts
- projects/archiver/src/tasks/notification/helpers/device-notifications-helpers.ts
- projects/archiver/src/tasks/notification/helpers/device-notifications.ts
- projects/archiver/src/tasks/notification/index.ts
- projects/archiver/test/tasks/notification/helpers/_tests_/device-notifications-helpers.spec.ts
- projects/archiver/test/tasks/notification/helpers/device-notifications.spec.ts
Pre-requisite: https://github.com/guardian/editions/pull/1355 which passes a Notification UTC Offset value in to each step of the step function.
This matching PR will respect that value when calculating the notification time.
Run in code.  I have: it worked.
And for the US edition, with a different offset:
> Respect notification offset from input

- projects/Mallard/package.json
- projects/Mallard/src/screens/settings/manage-editions-screen.tsx
- projects/Mallard/yarn.lock
This PR fixes broken editions buttons. See screenshots.
@prisalcalde please let me know if they need further adjustments
> Fixed broken edition button on small screen

- projects/Mallard/src/screens/settings/manage-editions-screen.tsx
To support multiple editions we're referring to an individual Issue as an Issue rather than an Edition. As a result we have some copy tweaks to make it easier to understand that you are downloading an 'issue' rather than an 'edition'. 
[**Trello Card ->**](https://trello.com/c/9PwOORmI/1442-update-the-copy-of-the-manage-download-screen)
Open the settings -> Manage Downloads -> Check the content is as expected
> Update manage editions copy

- projects/Mallard/android/app/src/main/AndroidManifest.xml
- projects/Mallard/ios/Mallard/Mallard.entitlements
We want to provide a way to open the app from an email link if the app is installed or open the Play/App store if not. This PR implements client-side change.
We have added corresponding files in the edition subdomain:
iOS: https://editions.theguardian.com/.well-known/apple-app-site-association
Android: https://editions.theguardian.com/.well-known/assetlinks.json
The way I tested it as follows:
Send an email to myself that contains a link `https://editions.theguardian.com`
Android: link open the Edition app when it is installed, or, open the Play Store when not installed
iOS: link open the Edition app when it is installed, or, open the App Store when not installed
Just adding @davidfurey
> Deeplink to open Edition app or Play/App Store

- package.json
- projects/Apps/common/package.json
- projects/Apps/crosswords/package.json
- projects/Apps/yarn.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
- yarn.lock
Apparently there's a vulnerability in the version of lodash that our babel libraries pull in. This appears to have been [resolved](https://github.com/babel/babel/pull/11818) in recent versions of babel. This PR bumps our babel versions. I've tested in the simulator and babel is only used for building the app so hopefully this is a safe change.
> Bump babel version to resolve lodash vulnerability

- projects/Mallard/src/components/article/html/components/__tests__/__snapshots__/header.spec.ts.snap
- projects/Mallard/src/components/article/html/components/__tests__/header.spec.ts
- projects/Mallard/src/components/article/html/components/header.ts
Editing this area of the code is required for the Showcase template work. Its a bit of a scary place and I feel more comfortable if it is tested beforehand to make sure i'm not affecting the look and feel on potentially obscure template/pillar combinations.
As a result I have written tests to cover the Standfirst area as this will need refactoring to pull the Headline out of it
> test: getStandfirst in the header html build

- projects/Mallard/src/helpers/fetch.ts
- projects/Mallard/src/hooks/use-issue.ts
- projects/Mallard/src/screens/issue-screen.tsx
The 'refresh' button doesn't currently work for the proof backend. This is because for each new version of a proofed edition there is a new 'publishedId'. This change forces the app to refetch the /issues list to pick up the new ID. 
The 'local id' of an edition is just the date it was published (without time). This causes problems for the proof endpoint as once the issue is downloaded it will only re-download if the local id is different, so I've added a 'forceApiFetch' parameter to skip the fetch from file system step for thsi endpoint.
[**Trello Card ->**](https://trello.com/c/PkjPqlFR/1336-production-edition-switching)
Release, check that the refresh button works, and that issue switching still works!
> When using preview api, always return to API when refreshing issue.

- .github/workflows/scheduled-ios-beta.yml
I broke this in https://github.com/guardian/editions/pull/1378/files - this fixes the ios build!
> Correct trigger name in github workflow

- projects/archiver/src/tasks/notification/helpers/device-notifications.ts
- projects/archiver/test/tasks/notification/helpers/device-notifications.spec.ts
Currently, we explicitly do not send notifications for non-Daily Editions.
When the app can support re-subscribing to appropriate topics (where topic and Edition have a one-to-one mapping), we can safely remove this.
Test in CODE, confirm that notifications work correctly in the app for any Edition.
> Remove short circuit for notifications

- projects/Apps/common/src/index.ts
- projects/archiver/src/invoke/index.ts
- projects/archiver/src/invoke/parser.ts
- projects/archiver/test/invoke/parser.spec.ts
- projects/backend/utils/try.ts
When the fronts tool puts an editions list file into S3, this code ensures it is picked up, parsed and processed, up to a point.
The backend endpoint is not currently present, so it fails at the last second where it should execute a PUT.
Use the fronts tool to push a new editions list file, then observe the eventual failure message in the logs.
> Read and handle edition list

- projects/Mallard/src/components/article/html/components/__tests__/__snapshots__/header.spec.ts.snap
- projects/Mallard/src/components/article/html/components/__tests__/__snapshots__/headline.spec.ts.snap
- projects/Mallard/src/components/article/html/components/__tests__/headline.spec.ts
- projects/Mallard/src/components/article/html/components/header.ts
- projects/Mallard/src/components/article/html/components/headline.ts
In order to do the new template, the standfirst and headline need to not be tightly coupled. This does this work.
The header.spec.snap file is updated with only white space changes due to template strings maintaining spacing. This happens because of our implementation of the `html` function and Prettier.
[**Trello Card ->**](https://trello.com/c/toCtvPTB/1402-showcase-template-implementation)
> Feat: Separate Headline from Standfirst in HTML Articles

- projects/Apps/common/src/index.ts
- projects/archiver/src/invoke/parser.ts
- projects/archiver/src/tasks/notification/helpers/device-notifications-helpers.ts
- projects/archiver/src/tasks/notification/helpers/device-notifications.ts
- projects/archiver/src/tasks/notification/index.ts
- projects/archiver/test/invoke/index.spec.ts
- projects/archiver/test/invoke/parser.spec.ts
- projects/archiver/test/tasks/notification/helpers/_tests_/device-notifications-helpers.spec.ts
- projects/archiver/test/tasks/notification/helpers/device-notifications.spec.ts
Currently the notification topic is hard coded as 'uk', which is not very helpful when publishing a US or AU issue of an edition.
This PR requires the topic to be specified as part of the publish notification, and uses it to construct the request to the notification service.
> Pass notification topic

- projects/Mallard/fastlane/Fastfile
- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
As part of the changes in the [deep links feature]() we needed to add 'associated domains' to our provisioning profile. Regenerating the profile resulted in the name changing from `match AppStore uk.co.guardian.gce 1586248549` to just `match AppStore uk.co.guardian.gce`. I'm not certain why this is but it seems easier to not worry about what that number is on the end! This PR needs to be merged for github actions ios builds to start working again. 
[**Trello Card ->**](https://trello.com/c/iGkBQHm8/1448-fix-ios-builds)
Check ios builds work
> Fix code signing

- projects/Apps/common/src/collection/card-layouts.ts
This change allows for cover cards to be used on the sport front. 
Following from https://github.com/guardian/editions/pull/1029 many months later, this takes a more conservative approach of enabling cover cards on one extra front. Now that we have removed the sidekick card https://github.com/guardian/editions/pull/1340 the problems identified in https://github.com/guardian/editions/pull/1042 are now hopefully less of a concern
Warn production before release! Tested on CODE.  For testing release, publish an edition and double check that the first card on the sport front hasn't suddenly become a cover card.
> Allow cover cards on the sport front.

- projects/Apps/common/src/collection/card-layouts.ts
Following from https://github.com/guardian/editions/pull/1386 which I've checked with Katy, also allow cover cards on the journal front. 
I've tested this briefly on code, Katy is on hand to test in PROD. This is a backend only change and will only affect issues that are republished after it is merged
> Allow cover cards on the journal front.

- projects/Mallard/src/components/article/html/components/header.ts
- projects/Mallard/src/components/article/html/components/helpers/__tests__/getBylineText.spec.ts
- projects/Mallard/src/components/article/html/components/helpers/getBylineText.ts
The current templates are incorrect. There should be a newline at the end of the byline after the last author. This is shown in the Showcase designs and is a regression in the current design. This fixes this and writes tests to support this and its previous implementation.
Some screenshots:
> feat: getBylineText adds newline where appropriate

- projects/Apps/common/src/collection/card-layouts.ts
Following from https://github.com/guardian/editions/pull/1390, this is a final bit of work to allow cover cards wherever there is currently a 1 story card in  the dense layour
Backend only change - check that cover cards can be added in world/national/financial
> Allow cover cards  in dense layout.

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/components/article/types/article.tsx
- projects/Mallard/src/screens/settings/default-info-text-webview.tsx
- projects/Mallard/yarn.lock
@jimhunty please discard the previous PR
This PR updates the webview dependency and makes relevant changes. Local testing looks fine and now we need to release this to internal beta for further testing.
This is a big jump in terms of library version and there are lots of minor and major changes between 6.9.0 and 10.3.2. We may need some adjustments after we get feedback from beta users.
This is the release where `react-native-webview` switched to WKWebview:
https://github.com/react-native-community/react-native-webview/releases/tag/v7.0.1
> Updated webview version

- projects/Mallard/src/helpers/diagnostics.ts
Just a small PR to show disk size info that appears in diagnostics data in Mb instead of bytes.
It was:
`Free disk space: 256901120,000`
Now:
`Free disk space (Mb): 245,000`
No Trello ticket
> Show disk size in Mb

- projects/Mallard/src/screens/issue-screen.tsx
This will only show the illustration on the Daily and not on other editions
> feat: Illustration shown only on Daily

- projects/Mallard/src/components/Button/BugButtonHandler.tsx
- projects/Mallard/src/helpers/diagnostics.ts
- projects/Mallard/src/screens/settings/help-screen.tsx
Support email dialog 'title' always had a fixed title "Found a bug?"
This PR change that behaviour and uses that title only for bug related feedback email dialog.
[**Trello Card ->**](https://trello.com/c/KXmM3Z8w/819-user-help-bug-contact-us-dialog-copy)
> Show dialog title only for bug related feedback

- projects/Mallard/src/screens/settings-screen.tsx
As it says on the tin.
(no ticket)
> Display app build number in settings page

- projects/Mallard/src/screens/settings/dev-zone.tsx
As we now have this in the Settings menu, its not needed in the dev menu
> chore: Remove build number from Dev Menu

- projects/archiver/src/services/pub-status-notifier.ts
Improve the proof / publish /post-processing messaging for user clarity.
https://trello.com/c/QmUtu0rw/286-improve-descriptions-on-proof-publish-messages
To be merged alongside https://github.com/guardian/facia-tool/pull/1234
This has been deployed in CODE, an edition issue proofed and published and messages checked ✔️
> Improve notification messages

- projects/archiver/src/tasks/copier/index.ts
- projects/archiver/src/tasks/editions-list/index.ts
- projects/archiver/src/tasks/front/index.ts
- projects/archiver/src/tasks/indexer/index.ts
- projects/archiver/src/tasks/issue/index.ts
- projects/archiver/src/tasks/notification/index.ts
- projects/archiver/src/tasks/upload/index.ts
- projects/archiver/src/tasks/zip/index.ts
- projects/archiver/src/utils/sleep.ts
Insanely, the Facia database (which ultimately stores the messages from editions proof / publish) only supports one message per second.
Occasionally, in testing with small issues, we end up losing messages as a result.  This is a trivial fix.  Sorry.
https://trello.com/c/GNinraji/285-add-1s-delay-to-each-archiver-step
The lambda has been deployed in code, and proof/publish still works consistently with small issues, and we do not observe any dropped messages.  ✔️
> Add sleep and improve logging

- projects/aws/lib/aws-stack.ts
This change just adds some new environment variables to the backend lambda.
I've pulled the cloudformation changes out of https://github.com/guardian/editions/pull/1392 so that we can get this merged. It's general good practice to separate infrastructure vs application code changes, and will make testing easier as the cloudformation stack won't keep getting overwritten when people deploy their own branches to the CODE environment.
Release, verify that the editions backend is still working :D - there should be no behaviour changes as
> Allowing preview content in editions part 1 - infra changes

- projects/archiver/src/tasks/notification/helpers/device-notifications.ts
We have a short circuit for _not_ sending notifications if the edition is _not_ daily-edition and the stage is prod.
This can be removed (which is what this PR does) *only* when we have tested notifications work correctly.
Create a non-daily-edition (eg US Weekend edition) in CODE and ensure that the notification is received by a CODE device subscribed to that edition.  Simultaneously, check that a CODE device subscribed to daily-edition _does not_ receive a notification.
> Remove notification short circuit for non-daily-editions in Prod

- projects/Mallard/src/screens/settings-screen.tsx
**Issue**
Once signed in, the Subscription details option has no arrow indicating there is another screen.
**Work to be done**
Add a right chevron to the Subscription details option on the Settings.
[**Trello Card ->**](https://trello.com/c/TAPPiaHi/1486-add-an-arrow-chevron-to-the-subscription-details-option-on-the-settings)
Once signed in, check if the Subscription details option has a chevron.
> Adding a chevron icon to Subscription details on the Settings for consistency

- projects/Mallard/src/components/article/html/components/lists.ts
- projects/Mallard/src/components/article/html/css.ts
This PR adds custom styling to unordered lists to match what is visible on dotcom. 
[**Trello Card ->**](https://trello.com/c/XBFxWJzw/1270-snaggin-bullet-points)
| --- | --- |
> apply bullet styling to match dotcom

- projects/Apps/common/src/editions-defaults.ts
- projects/Apps/common/src/index.ts
- projects/Mallard/src/components/EditionsMenu/EditionsMenu.stories.tsx
- projects/Mallard/src/components/EditionsMenu/__tests__/EditionsMenu.spec.tsx
- projects/Mallard/src/components/EditionsMenu/__tests__/__snapshots__/EditionsMenu.spec.tsx.snap
Following from https://github.com/guardian/editions/pull/1421 there are a few fields the fronts too provides which don't currently exist in our edition list type. This PR adds them, as well as adding some inheritance to the different edition types to avoid some repetition
Check that editions menu is still working..!
> Add new fields to EditionsList type

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
As we have pushed version 6.8 to get approval we need to bump this to 6.9 in order for builds to continue working.
> Bump marketing version to 6.9

- projects/archiver/src/invoke/index.ts
- projects/aws/lib/aws-stack.ts
- projects/aws/lib/listener.ts
- projects/backend/__tests__/application.spec.ts
- projects/backend/application.ts
- projects/backend/backend.ts
- projects/backend/controllers/editions.ts
- projects/backend/s3.ts
Implemented POST endpoint to store edition-list into edition s3 and make it available for the app/clients. Currently, when front tools publish edition-list it does not come through to the edition backend to make it available for the mobile apps. This work fills that gap by the store the published 'edition list' into relevant s3 bucket.
[**Trello Card ->**](https://trello.com/c/Is0CxWix/1449-put-endpoint-to-consume-editions-json-from-fronts-tool)
Need to deploy this to code first and see everything is working as expected.
> Implemented POST endpoint

- projects/Mallard/src/helpers/settings/defaults.ts
- projects/Mallard/src/hooks/__tests__/use-edition-provider.spec.tsx
- projects/Mallard/src/hooks/use-edition-provider.tsx
This PR changes the edition provider to respect whatever backend has been set via the dev menu. Previously this was set to always use the prod published backend.
This is useful to allow for testing edition list changes on CODE. 
I've tested this in the simulator and it looks ok to me.
> Respect apiUrl from dev menu when fetching the editions list.

- projects/Mallard/src/screens/article/slider/SliderHeaderLowEnd.tsx
In an attempt to hunt down the errors in the app, this stood out as not required as navigation props are not used in this component.
This highlighted a conditional `useEffect` which is not allowed. This condition was around iOS devices under V12 which we now don't support. So it was safe to remove this condition.
> chore: Remove unused withNavigation

- projects/Mallard/src/components/article/html/components/header.ts
This is a second very tiny regression found from the interview template work after fixing the standfirst. 
This PR reduces the margin-top for the kicker within the header 
[**Trello Card ->**](https://trello.com/c/XaNCRpFh/1495-weve-lost-the-standfirst-on-the-long-read-template-also-possibly-galleries)
| --- | --- | 
Interviews should remain unchanged:
> lower kicker within header

- projects/Mallard/src/download-edition/clear-issues.ts
Sentry ticket: https://sentry.io/organizations/the-guardian/issues/1736134906/?project=1519156&query=is%3Aunresolved+dist%3A777&sort=freq&statsPeriod=14d
We record an error every time we try to delete an issue and it does exist in full when clearing old issues. This does an extra check that the issue exists and if it does it then attempts to delete it. This should resolve this error.
> fix: Sentry - EDITIONS-MXX

- projects/Mallard/src/download-edition/clear-issues.ts
- projects/Mallard/src/helpers/files.ts
We get the occasional error that the `download/daily-edition` folder does not exist. See image below
As a result, this PR creates the required folders for each edition ahead of time. 
When downloads are cleared, we do delete those folders but recreate them straight after.
> feat: Less aggressive download clean

- projects/Mallard/src/navigation/index.ts
Those `Error not implemented` crashes are to do with Storybook. I don't think this is the route cause of the crashing problems we see, but certainly improves Android development for the time being.
Storybook needs upgrading, here is the ticket for it: https://trello.com/c/hZOHI4E4/1498-enable-and-upgrade-storybook
> chore: Disable Storybook

- projects/aws/lib/aws-stack.ts
We have a cloudfront endpoint set up for editions which we're not using. This removes that infrastructure.
My evidence that it's not being used:
Deploy to CODE, check that https://preview.editions.code.dev-guardianapis.com/issues still returns what we'd expect (VPN required), then do the same for PROD.
> Remove unused cloudfront CDN

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/hooks/use-settings.ts
- projects/Mallard/src/screens/issue-screen.tsx
- projects/Mallard/yarn.lock
This is another attempt at the work in https://github.com/guardian/editions/pull/1374 to get the 'Refresh' button to work properly for the 'proof' endpoint. I spent a long time trying to write some code to refetch the issues list (to get the publishedId of the new proof version) and then refetch the issue, but without success. 
This is a lazier approach which uses the [react native restart](https://www.npmjs.com/package/react-native-restart) library to force a full app restart. In proof mode the refresh button now also deletes all issues downlodaed as otherwise even with the app restart you still end up on the previously fetched issue. 
Currently, this button works on ios, but crashes the app on android. Since the editorial team would need to restart the app anyway as a manual alternative …
> Fix proof reload button

- projects/Mallard/src/authentication/services/__tests__/iap.spec.ts
- projects/Mallard/src/authentication/services/iap.ts
Despite typescript, empty receipt values are passed through further down the object. I believe this is because `latest_receipt_info` is not required by the iAP library. So this firms it up and has tests around it.
[**Sentry Card ->**](https://sentry.io/organizations/the-guardian/issues/1672718141/?project=1519156&query=release%3Auk.co.guardian.gce%406.8%2B797&sort=freq&statsPeriod=24h
> fix: Sentry - EDITIONS-HSK

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Bump iOS version to V7 to get the build to run and prepare for Editions launch.
> feat: Bump to V7 for Editions

- projects/Apps/common/src/editions-defaults.ts
- projects/Mallard/src/components/EditionsMenu/__tests__/EditionsMenu.spec.tsx
- projects/Mallard/src/components/EditionsMenu/__tests__/__snapshots__/EditionsMenu.spec.tsx.snap
- projects/Mallard/src/components/ScreenHeader/IssuePickerHeader/__tests__/IssuePickerHeader.spec.tsx
- projects/Mallard/src/components/ScreenHeader/IssuePickerHeader/__tests__/__snapshots__/IssuePickerHeader.spec.tsx.snap
- projects/Mallard/src/helpers/weather-hider.ts
- projects/Mallard/src/hooks/use-edition-provider.tsx
This changes it in the backup array if the endpoint is down and in some tests and comments for consistency.
[**Trello Card ->**](https://trello.com/c/mT67lHYI/1507-rename-the-daily-to-uk-daily)
> chore: UK daily name change

- projects/Mallard/src/components/article/html/article.ts
- projects/Mallard/src/components/article/html/components/__tests__/__snapshots__/header.spec.ts.snap
- projects/Mallard/src/components/article/html/components/__tests__/header.spec.ts
- projects/Mallard/src/components/article/html/components/header.ts
- projects/Mallard/src/components/article/html/components/images.ts
- projects/Mallard/src/components/article/types/article/webview.tsx
- projects/Mallard/src/hooks/use-image-paths.ts
Following users reports of missing images...
1. Update to the `getImagePath` function to force an API path if you request it.
2. Use a "backup" url on the `onerror` of the HTML image wherever possible
3. Removal of the error thrown on `origin` as we will always backup to the API url.
4. Use backup for `background-image` for immersive style headers in case the first image does not load
> fix: Missing images backup strategy

- projects/Mallard/src/components/article/html/components/images.ts
- projects/Mallard/src/helpers/webview.ts
Font scaling (in device accessibility settings) is causing captions to overlap sometimes. This disables font scaling to stop this from happening.
There's a bigger question as to whether these captions should perhaps be inline instead, as was done in https://github.com/guardian/editions/pull/974/files but seems to have stopped working
Before:
After
[**Trello Card ->**](https://trello.com/c/fpSlx6m1/1509-disable-font-scaling-on-captions)
> Stop scaling gallery caption fonts.

- projects/Apps/common/src/editions-defaults.ts
- projects/Mallard/src/components/EditionsMenu/__tests__/__snapshots__/EditionsMenu.spec.tsx.snap
As title.
[**Trello Card ->**](https://trello.com/c/B8qguVYN/1514-ensure-local-back-up-of-the-editions-metadata-matches-the-settings-provided-by-tooling)
> Fix: Editions defaults match endpoint

- projects/Mallard/src/screens/settings/gdpr-consent-screen.tsx
Privacy policy will now show the inline one rather than the page.
[**Trello Card ->**](https://trello.com/c/a21Cn65X/1519-privacy-settings-can-be-bypassed-issue-on-first-install)
> fix: Show Inline Privacy on Consent Options

- projects/Mallard/src/helpers/files.ts
Sentry error:
https://sentry.io/organizations/the-guardian/issues/1747362358/?project=1519156&query=is%3Aunresolved+files&statsPeriod=14d
We are seeing lots of `read timeout` exceptions on a daily basis (400-500 events per day) related to zip download. This PR increases some timeout values with aim to reduce those exceptions.
> Increased some download timeout values

- projects/Mallard/src/components/EditionsMenu/__tests__/EditionsMenu.spec.tsx
- projects/Mallard/src/components/EditionsMenu/__tests__/__snapshots__/EditionsMenu.spec.tsx.snap
- projects/Mallard/src/components/ScreenHeader/IssuePickerHeader/IssuePickerHeader.stories.tsx
Minor one this. We changed the branding from `weekender` to `weekend`. This just removes this from stories and tests.
> chore: Weekender removal

- projects/Mallard/src/components/article/html/css.ts
This PR changes the colour of h2+strong (the second level of h2 styling) to always use the pillar colour, regardless of article type. This was a change requested by design. 
[**Trello Card ->**](https://trello.com/c/1R3yfko0/1505-h2-and-h2-bold-to-render-pillar-colours)
The third article in CODE published August 31st in the Life section should have both layers of h2 styling. (see screenshots below)
| --- | --- |
> Ensure h2+strong use pillar colour regardless of article type

- projects/Mallard/src/components/article/html/article.ts
- projects/Mallard/src/components/article/html/components/lists.ts
- projects/Mallard/src/components/article/html/css.ts
There are two types of bullet points that can be used in composer, we previously added styling for list items but this PR styles "alt+8" bullet points as specified in the ticket. 
[**Trello Card ->**](https://trello.com/c/XBFxWJzw/1270-snaggin-bullet-points)
| --- | --- |
> Add styling to unicode bullets

- projects/Mallard/src/components/article/html/components/headline.ts
Removes the quote from the Interview template.
[**Trello Card ->**](https://trello.com/c/m0uVo0NB/1534-remove-leading-quote-mark-on-interview-headline-styling)
> chore: Remove interview quote

- projects/Mallard/src/notifications/__tests__/helpers.spec.ts
- projects/Mallard/src/notifications/helpers.ts
Currently, the app does re-register with notification service every time app launches and resulted in extra load on the backend service and failure of the registration requests. This is due to a bug where we compare the old and new list of topics.
`[{"type":"editions","name":"uk"}]`
`[{"name":"uk","type":"editions"}]`
The above two sets of topics are essentially the same just in a different order. This PR updated the logic to handle this scenario.
[**Trello Card ->**](https://trello.com/c/aKRVTIPg/1526-the-app-seems-to-fail-to-register-with-push-notification)
unit tested
> Handled topic difference for notification registration

- projects/Mallard/src/helpers/settings/defaults.ts
Rather than refer to the S3 bucket directly we should use a domain name. This way if we want to change the backend in the future we can do so without releasing the app. The two editions-proof domains included below are set up in fastly.
> Use proper domain names for proof endpoints.

- projects/Mallard/src/components/article/html/components/header.ts
After reviewing the showcase template @pradasa noticed a few minor issues. 
1. Use the dark pillar colour for the headline instead of main
2. Add extra padding to share button and reduce horizontal length below byline (only on tablet)
[**Trello Card ->**](https://trello.com/c/TN3e0niI/1503-article-type-picker-change-to-support-showcase-template)
| --- | --- |
> tweak-showcase-template

- projects/backend/capi/articleImgPicker.ts
- projects/backend/capi/articleTypePicker.ts
- projects/backend/capi/assets.ts
- projects/backend/s3.ts
We have a new showcase template. We want to use it (I think) for all content that has main media with role: 'showcase'. This PR adds a function to detect such content, and adds it to the type picker. I'm not certain whethere the 'else if' statements are in the right position at the moment - currently it is set up so that we only use showcase if it's none of the other templates, which I suspect isn't quite right.
Motivation for this draft PR is to get the ordering right, and to get ready to test on CODE to see what the impact of adding a new 'article type' is on old versions of the client that don't know about showcase templates, which were added in https://github.com/guardian/editions/pull/1428
[**Trello Card ->**](https://trello.com/c/TN3e0niI/1503-article-type-picker-change-to-support-sh …
> WIP: Add isShowcase property to article type picker.

- projects/Apps/common/src/editions-defaults.ts
- projects/Apps/common/src/index.ts
- projects/Mallard/jest-setup.js
- projects/Mallard/src/components/EditionsMenu/__tests__/EditionsMenu.spec.tsx
- projects/Mallard/src/components/EditionsMenu/__tests__/__snapshots__/EditionsMenu.spec.tsx.snap
- projects/Mallard/src/hooks/__tests__/use-edition-provider.altlocale.spec.tsx
- projects/Mallard/src/hooks/__tests__/use-edition-provider.spec.tsx
- projects/Mallard/src/hooks/use-edition-provider.tsx
- projects/Mallard/src/notifications/helpers.ts
This looks to remove the dependency for locally retrieved editions values. This makes `Locale` and `Topic` come from the editions list.
This applies the backend changes as mentioned in the Trello ticket.
[**Trello Card ->**](https://trello.com/c/7ubNJqO6/1529-update-local-app-preferences-to-match-the-backend)
> feat: Locale mapping via endpoint and general US cleaning

- projects/Mallard/src/hooks/use-edition-provider.tsx
Fixes the edition endpoint caching. Sets a max age to 5 minutes.
> fix: Clears the cache on editions endpoint

- projects/Mallard/src/screens/article/slider/SliderTitle.tsx
- projects/Mallard/src/screens/article/slider/__tests__/SliderTitle.android.spec.tsx
- projects/Mallard/src/screens/article/slider/__tests__/SliderTitle.android.tablet.spec.tsx
- projects/Mallard/src/screens/article/slider/__tests__/SliderTitle.ios.spec.tsx
- projects/Mallard/src/screens/article/slider/__tests__/SliderTitle.ios.tablet.spec.tsx
- projects/Mallard/src/theme/typography.ts
The font-size of section titles on the fronts and article headlines on the article pages are too big on iPhone SE. On 1st of September, the Coronavirus Education titles were not fully visible on the screen.
[**Trello Card ->**](https://trello.com/c/lvwBYVG1/1525-font-size-of-section-and-sub-section-titles-too-big-on-iphone-se)
- Open iPhone SE, check if the section titles are smaller
> iPhone SE: Font-size reduction (section titles and article headlines)

- projects/Apps/common/src/index.ts
- projects/Mallard/src/components/EditionsMenu/EditionsMenu.stories.tsx
- projects/Mallard/src/components/EditionsMenu/EditionsMenu.tsx
- projects/Mallard/src/components/EditionsMenu/SpecialEditionButton/SpecialEditionButton.stories.tsx
- projects/Mallard/src/components/EditionsMenu/SpecialEditionButton/SpecialEditionButton.tsx
- projects/Mallard/src/components/EditionsMenu/SpecialEditionButton/__tests__/SpecialEditionButton.spec.tsx
- projects/Mallard/src/components/EditionsMenu/SpecialEditionButton/__tests__/__snapshots__/SpecialEditionButton.spec.tsx.snap
- projects/Mallard/src/components/EditionsMenu/__tests__/EditionsMenu.spec.tsx
- projects/Mallard/src/components/EditionsMenu/__tests__/__snapshots__/EditionsMenu.spec.tsx.snap
- projects/Mallard/src/components/front/image-resource.tsx
Images in special editions won't go through the archiver, and therefore won't be served by the editions API. This modifies the editions menu to take this into account - no longer using `ImageResource` - which is really for generating API/filesystem urls and using `Image` directly. With this, we can then replace `devUri` and `image` with a single property - `buttonImageUri`
This is an example image:
[**Trello Card ->**](https://trello.com/c/ALUUZ9uH/1521-prove-special-editions-basically-work)
I've tested that storybook is still happy! 
We don't have any live special editions at the moment so this should be fairly safe. Testing steps would be: 
- update facia tool with new buttonImageUri property
- Republish editions using facia tool on CODE
- Run a simulator pointed at CODE and check that …
> Simplify special edition images

- projects/Apps/common/src/index.ts
- projects/archiver/src/services/editions-mappings.ts
- projects/archiver/src/tasks/indexer/helpers/get-issue-summary.ts
- projects/archiver/src/utils/backend-client.ts
- projects/archiver/test/tasks/indexer/helpers/get-issue-summary.spec.ts
- projects/aws/lib/proof-step-function.ts
- projects/backend/controllers/editions.ts
- projects/backend/utils/__tests__/issue.spec.ts
- projects/backend/utils/issue.ts
To make it easier to publish new special editions, we should remove as many of the hard coded references to editions as possible from the app. This change updates the editions-mappings function so that it no longer has a hard coded list of editions but instead queries the editions backen (/editions) to get this information.
The editions backend (/editions) mentioned above currently returns a hard coded list of editions. This PR changes that behaviour so that that endpoint now returns the editions list directly from the fronts tool.
NOTE: This also contains CLIENT SIDE changes as I've removed the 'Editions' list from the common types file, made the 'Edition' type a string, as we want this to be driven by the API.
[**Trello Card ->**](https://trello.com/c/ALUUZ9uH/1521-prove-special-editions …
> Archiver/Backend: Drive editions lists from fronts tool. Mallard: 'Edition' is now a string

- projects/Mallard/src/helpers/files.ts
Just raising this following from https://github.com/guardian/editions/pull/1477 - we can't rely on having a hard coded list of editions in the app, here I'm exploiting the editions list cache to work round the problem - though I'm not sure this is a safe operation - @mohammad-haque and @jimhunty might have some thoughts? 
[**Trello Card ->**](https://trello.com/c/ALUUZ9uH/1521-prove-special-editions-basically-work)
Tested on ios simulator, my android simulator isn't working at the moment. Main thing to test would be deleting and downloading editions from a clean install of the app.
> Don't rely on hard coded editions list when checking directories exist

- projects/Mallard/src/hooks/__tests__/use-edition-provider.spec.tsx
- projects/Mallard/src/hooks/use-edition-provider.tsx
This PR modifies the use-editions provider so that it filters out expired special editions. 
[**Trello Card ->**](https://trello.com/c/ALUUZ9uH/1521-prove-special-editions-basically-work)
I wrote a unit test! Oh my! I've also tested this using the simulator pointed at the special edition we currently have on CODE.
> Remove expired special editions

- projects/Mallard/src/helpers/storage.ts
- projects/Mallard/src/hooks/use-edition-provider.tsx
- projects/Mallard/src/screens/settings/dev-zone.tsx
It's going to be useful when testing special editions if we can launch them in PROD but keep them hidden unless they are enabled via the dev menu. This PR adds a flag to the dev menu to show/hide 'all editions' - using asyncstorage to store the value. Currently this is just used to show expired editions, but with a new flag set in the fronts tool we could use it to show/hide arbitrary editions.
[**Trello Card ->**](https://trello.com/c/ALUUZ9uH/1521-prove-special-editions-basically-work)
You can test this now - if you switch backend to CODE and set the flag in the dev menu to 'true' then reload (to reset the editions cache) you should see the expired test edition
> Add dev menu flag to show all editions.

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
We have noticed errors in Keychain in Sentry. But it was not reproducible locally. Our current library is from May 2019 which is a bit old. This PR updates to the latest library (up until a breaking change), 5.0.1. There are lots of fixes between 3.1.3 and 5.0.1 and hopefully, this will help to resolve the issue we are seeing in Sentry  
[**Trello Card ->**](https://trello.com/c/etJdu6Rl/1555-android-error-in-public-beta)
Testing:
I have tested the login/cas code subscription feature and they are working as expected
> Updated Keychain library

- projects/Mallard/src/screens/settings/dev-zone.tsx
Tiny PR to show "false" rather than "null" to tidy up duck menu.
[**Trello Card ->**](https://trello.com/c/G3jeSo75/1548-gdpr-values-in-the-duck-menu)
> GDPR values in duck menu

- projects/Mallard/src/components/article/html/components/header.ts
Beta users have reported that the interview template is cut off on the left margin on small tablets in portrait mode. 
This PR fixes the calculation we use for determining the margins on tablet, instead, we now check that the window is wider than the `maxWidth` constant before we use it in the calculation to avoid getting a negative margin on smaller devices.
[**Trello Card ->**](https://trello.com/c/qn2WiQPF/1551-interview-template-left-margins-seems-to-be-cut-tablet-portrait)
I have tested this on an iPad mini and small android tablet, see screenshots. 
| --- | --- |
> Fix interview template small tablets in portrait

- projects/Mallard/src/hooks/use-issue-summary.tsx
Relates to this error: https://sentry.io/organizations/the-guardian/issues/1396286427/?project=1519156&query=dist%3A817&statsPeriod=7d
Its clear the issueSummary is not an array. But it cannot be null with all the fallbacks in place. If it is, we need to replace the file system logic with async storage. If it isn't, we should get a better idea of what is going on from this PR.
> chore: getIssueSummary needs more info to debug

- projects/Mallard/src/components/EditionsMenu/SpecialEditionButton/SpecialEditionButton.tsx
- projects/Mallard/src/components/EditionsMenu/SpecialEditionButton/__tests__/__snapshots__/SpecialEditionButton.spec.tsx.snap
This PR is a small fix to use the device locale to format the expiry date for special editions, it seems `moment` wasn't working as expected so I have chosen to use the `toLocaleDateString` which defaults to use the devices locale and the short format we require. 
[**Trello Card ->**](https://trello.com/c/kHD3DpG4/1571-respect-locale-on-expiry-of-special-editions)
There was no special edition at the time of testing so I tested it by displaying the localized string in the regional buttons and by changing device locales (see screenshots)
| UK | US |
| --- | --- |
> Use device locale for date formatting

- projects/Mallard/src/screens/log-in.tsx
Emails are invalid if they have a space in them. This removes whitespace on email entry.
[**Trello Card ->**](https://trello.com/c/WdfTMnyd/1444-blank-spaces-not-removed-from-email-address-field-in-subscription-form)
> fix: Remove whitespace on email input

- projects/Mallard/src/helpers/features.ts
- projects/Mallard/src/navigation/navigators/article.tsx
- projects/Mallard/src/navigation/navigators/sidebar.tsx
- projects/Mallard/src/screens/article/slider/index.tsx
When investigating the issue with tops of some articles being cropped on android I noticed that there is a legacy `supportsAnimation` method which was only required for older devices specifically < iOS 12, which we no longer support.
This PR cleans up the related code.
> Remove animation method to support < iOS 12

- projects/Mallard/src/components/article/html/article.ts
This PR formats all alt-8 bullets and not just the first 🤦🏻‍♀️
[**Trello Card ->**](https://trello.com/c/XBFxWJzw/1270-snaggin-bullet-points)
Go to Journal and view 3rd last article Eric obituary and check both bullet points render correctly. (see screenshots) 
| --- | --- |
> format-all-bullets-not-just-the-first

- projects/Mallard/src/navigation/navigators/article/transition.tsx
- projects/Mallard/src/theme/spacing.ts
When testing on iOS 14 we noticed that the article overlay is overlapping the status bar. 
This PR extends a hack we added for iOS 13 to include OS versions above 13 also. 
[**Trello Card ->**](https://trello.com/b/7LS3epPT/editions-platform)
| --- | --- |
> iOS 14 - stop article overlay overlapping status bar

- projects/Mallard/src/screens/article/slider/SliderHeaderLowEnd.tsx
There have been reports in the beta that the captions in main media image are cut off on android tablet, there has also recently been a report of a header in cartoon articles also being hidden. 
This PR increases the `HEADER_LOW_END_HEIGHT` constant which we use to apply top padding to the article header. 
This value I have changed is **only** applicable to android tablets. 
Interestingly this value was updated as part of this [PR](https://github.com/guardian/editions/pull/1059) which was a design request to reduce top padding so by increasing this constant there shouldn't be any breaking changes only increase the top space. 
[**Trello Card ->**](https://trello.com/c/TJADXMvM/1392-bug-android-headlines-images-and-captions-obscured-on-tablet)
Check a cartoon article's header or select a …
> Increase header height on android tablet 

- projects/Mallard/src/helpers/diagnostics.ts
Having this will help us tie a user in with the logging service and help us debug their problem with more accuracy.
> feat: Unique Id in Diagnostics

- projects/archiver/src/utils/backend-client.ts
- projects/aws/lib/aws-stack.ts
- projects/backend/controllers/__tests__/issue.spec.ts
- projects/backend/controllers/editions.ts
- projects/backend/controllers/issue.ts
- projects/backend/s3.ts
- projects/backend/utils/__tests__/issue.spec.ts
- projects/backend/utils/issue.ts
We don't want users to see editions which have no issues. This change modifies the two places where the /editions endpoint is generated - in the `editionsControllerGet` controller (used by Preview API) and the `editionsControllerPost` (used to update the editions list in PROOF/PROD when someone clicks the 'republish' button in the fronts tool). 
The change in itself is pretty simple - count the number of issues and check if that number is greater than 0. As part of this I had to add a new function to 'list directories' rather than keys - this essentially counts each 'date' folder (so if an issue was republished N times in one day it still only counts as 1 issue).
To confuse things, I've also modified the existing s3 functions to make them more generic - they now take an `s3Client` rather …
> Remove editions from /editions endpoint when they have 0 issues.

- projects/Mallard/src/helpers/storage.ts
- projects/Mallard/src/hooks/__tests__/use-edition-provider.altlocale.spec.tsx
- projects/Mallard/src/hooks/__tests__/use-edition-provider.spec.tsx
- projects/Mallard/src/hooks/use-edition-provider.tsx
Following a discussion, we have agreed that the editions app might in future want to know about training editions, so here I've deprecated the `EditionsEndpoint` type which dropped these and switched to using `EditionsList` everywhere. 
I've run this in the simulator and it seems ok, I'm mainly relying on typescript to shout at me if I've messed this up!
> Use EditionsList type everywhere.

- projects/Apps/common/src/index.ts
- projects/Mallard/src/components/EditionsMenu/EditionsMenu.stories.tsx
- projects/Mallard/src/components/EditionsMenu/EditionsMenu.tsx
- projects/Mallard/src/components/EditionsMenu/__tests__/EditionsMenu.spec.tsx
- projects/Mallard/src/components/EditionsMenu/__tests__/__snapshots__/EditionsMenu.spec.tsx.snap
- projects/Mallard/src/hooks/__tests__/use-edition-provider.spec.tsx
We have a bug at the moment when trying to load the editions menu. This is caused by a [call to `toLocaleDateString`](https://github.com/guardian/editions/blob/master/projects/Mallard/src/components/EditionsMenu/SpecialEditionButton/SpecialEditionButton.tsx#L49) on expiry, which turns out to not be a `Date`after all but really a string. My solution (up for debate) is that - since we are getting the editions list from a JSON endpoint with no type information - we should treat it as a string until we have explicitly converted it into a `Date`. 
The alternative I guess would be to write some kind of 'special edition parser' which does this step...
Screenshot of the bug:
This PR solves the problem indicated above, and the special editions is fairly …
> Expiry date is a string.

- projects/Mallard/src/components/layout/ui/errors/error-boundary.tsx
Adds some signposting to errors captured in Sentry for the Error Boundary. This is to help highlight the issues being thrown around the "Unable to render articles" error.
> chore: Error Boundary Signposting

- projects/Mallard/src/components/layout/header/header.tsx
- projects/Mallard/src/hooks/use-edition-provider.tsx
- projects/Mallard/src/screens/home-screen.tsx
- projects/Mallard/src/screens/issue-screen.tsx
As far as I can't tell we aren't currently using the special edition header styles when instatntiating the issue header component (IssuePickerHeader/IssueScreenHeader). This change adds a function to extract these properties out of the current selected edition if it is a special edition so that we can use them.
Before:
After:
[**Trello Card ->**](https://trello.com/c/DKRNoRMV/1569-environment-special-switch-details)
This change should have no impact on regional editions. On special editions the colours set in the fronts tool should be respected.
> Use special edition header styles in header.

- projects/Mallard/src/screens/settings/faq-screen.tsx
- projects/Mallard/src/screens/settings/privacy-policy-screen.tsx
We were missing a few newlines and one heading was in the wrong place. Reviewed together with @groakland & @prisalcalde
> Style fixes on FAQ and privacy policy.

- projects/Mallard/src/screens/settings/faq-screen.tsx
Tiny change to bring the headings in line with the other help sections
> Change heading of FAQ from h1 to h2.

- projects/Mallard/src/screens/settings/privacy-policy-screen.tsx
Privacy policy update to remove [a][b][c]
[**Trello Card ->**](https://trello.com/c/0sMZRkzb/1470-privacy-policy-update-ready-to-be-added-to-the-app)
Review copy and layout to check if anything is broken.
> Update privacy-policy (remove [a][b][c])

- projects/Mallard/src/components/EditionsMenu/SpecialEditionButton/__tests__/__snapshots__/SpecialEditionButton.spec.tsx.snap
- projects/Mallard/src/components/EditionsMenu/SpecialEditionButton/styles.ts
I've been trying to bring the new special edition in line with the designs - this hust adds some more padding
Before:
After:
Figma:
[**Trello Card ->**](https://trello.com/c/DKRNoRMV/1569-environment-special-switch-details)
This is looking pretty close to the figma design on my simulator, but we  can release to internal beta so that others can test it
> Special edition button - more padding

- projects/Apps/common/src/__tests__/fixtures/editions-fixtures.ts
- projects/Apps/common/src/__tests__/helpers.spec.ts
- projects/Apps/common/src/helpers.ts
- projects/Mallard/src/components/EditionsMenu/__tests__/EditionsMenu.spec.tsx
- projects/Mallard/src/components/EditionsMenu/__tests__/__snapshots__/EditionsMenu.spec.tsx.snap
- projects/Mallard/src/helpers/files.ts
- projects/Mallard/src/hooks/__tests__/use-edition-provider.spec.tsx
- projects/Mallard/src/hooks/use-edition-provider.tsx
Currently we have an issue where if you select a non-Regional edition then background the app, it gets overridden by the current default edition. I'm not certain what the right thing to do here is, but I *think* we should just respect whatever edition the user last selected, if they have selected one. The situation where we don't want to do that is if their selected edition is an expired  special edition, so this PR includes a check that the selectedEdition is in the editionList.
...I ended up pulling the function to turn an EditionsList into a list of ids out of the `files` file and into common as I think it'll be useful in the backend too. Have added a test for this functionality as well
[**Trello Card ->**](https://trello.com/c/0OBo4nQl/1591-special-edition-issue-menu-sometimes-has-the- …
> If selectedEdition cache set, don't override.

- projects/Mallard/src/theme/typography.ts
The byline wasn't always showing on smaller screens, particularly on opinion cards. 
This PR reduces the font size so that both the byline fits below the headline on smaller phones. 
[**Trello Card ->**](https://trello.com/c/Wq3Crctl/1589-byline-not-showing-on-smaller-screens-opinion-fronts-au-edition)
| --- | --- |
> Reduce font size for opinion cards on small phones

- projects/Apps/crosswords/package.json
- projects/Apps/yarn.lock
Updates Webpack dev server and makes it a dev dependency.
This doesn't resolve the security warning as the deep dependency hasn't been updated yet however, this is a dev dependency and shouldn't be bundled with the app so there is not much to worry about here.
> chore(deps): Update webpack dev server

- projects/Mallard/src/screens/settings/beta-programme-faqs.tsx
running our trusty HTML linting command on the Beta Programme FAQs HTML reveals a couple of nested <p> tags
[**Trello Card ->**](https://trello.com/c/owJ24Aqh)
```xmllint --noout --html -```
and ensure no errors are returned
> Beta Programme FAQ HTML - remove nested <p> tags errors flagged by linter

- projects/logging/package.json
- projects/logging/yarn.lock
`ts-node-dev` is used to run the logging service in dev mode. It is a dev dependency. I have upgraded this to include the security updates and tested it locally. All seems to be working as expected.
> chore(deps): Update ts-node-dev in Logging Service

- projects/Mallard/src/components/EditionsMenu/EditionsMenu.tsx
- projects/Mallard/src/components/EditionsMenu/RegionButton/RegionButton.tsx
- projects/Mallard/src/components/EditionsMenu/SpecialEditionButton/__tests__/__snapshots__/SpecialEditionButton.spec.tsx.snap
- projects/Mallard/src/components/EditionsMenu/SpecialEditionButton/styles.ts
Things look better when they are in alignment!
Before:
After:
> Align special edition text with regional edition text.

- projects/Mallard/src/screens/settings/faq-screen.tsx
Lint failure for FAQ HTML:
```test.html:330: HTML parser error : htmlParseEntityRef: no name <li>Go to Settings > [your name] > iTunes & App Store.</li>```
[**Trello Card ->**](https://trello.com/c/xZzfL4cp)
[**Test**]
Extract HTML string and place inside a test.html file inside a suitable <html><body>...</body></html> block and run the following:
```xmllint --noout --html test.html```
> Escaped ampersand in <li> item - 'iTunes & App Store'

- projects/archiver/package.json
- projects/archiver/yarn.lock
This fixes the dependency issue.
This is major bump, as the patch bump didn't update the required insecure package. Tested best I can locally but this directly affects the zipping process, so should be deployed and checked.
> chore(deps): Update archiver in archiver

- projects/Mallard/src/screens/settings/faq-screen.tsx
Copy change to make it clearer that the Premium tier of the Live app doesn't not give access to the Editions app.
[**Trello Card ->**](https://trello.com/c/LIaQyyOx/1600-update-faq-to-resolve-confusion-around-itunes-subscription)
Review copy and check if layout is not broken.
> Update faq-screen 

- projects/Mallard/src/components/EditionsMenu/EditionsMenu.tsx
- projects/Mallard/src/hooks/use-edition-provider.tsx
- projects/Mallard/src/screens/settings/editions-screen.tsx
Editions now have an `editionType` property so we don't need to pass the type through to this function. 
Tested in the simulator, doesn't seem to break anything!
> Simplify storeSelectedEdition function.

- projects/Apps/common/src/helpers.ts
- projects/Mallard/src/components/EditionsMenu/SpecialEditionButton/__tests__/__snapshots__/SpecialEditionButton.spec.tsx.snap
- projects/Mallard/src/helpers/files.ts
This fix should avoid the a connection error shown to user's who freshly install the app, this was happening on the android beta and also on iOS production builds. 
This PR falls back to the default regional editions list if the user's editions cache is empty. 
[**Trello Card ->**](https://trello.com/c/SjCAh4PG/1614-bug-index-unavailable-on-first-launch-on-android)
I have kicked off an internal android build to test this
On android: 
1. Freshly install the app 
2. Edition should load as expected.
> Am use default regional editions prep filesystem

- projects/Mallard/jest-setup.js
- projects/Mallard/src/components/EditionsMenu/SpecialEditionButton/SpecialEditionButton.tsx
- projects/Mallard/src/components/EditionsMenu/SpecialEditionButton/__tests__/__snapshots__/SpecialEditionButton.spec.tsx.snap
- projects/Mallard/src/helpers/date.ts
This PR fixes the date formatting on android so that it uses the device locale as expected. 
[**Trello Card ->**](https://trello.com/c/1hfFop0F/1615-android-expiry-date-isnt-respecting-locale)
Test on iOS and android that the expiry date in the special edition respects the device language/region settings 
| UK | US |
| --- | --- |
| UK | US |
| --- | --- |
> respect-locale-date-format-android

- projects/Mallard/src/screens/settings/faq-screen.tsx
A user found a mistake on the FAQs. 
Remove the wording '(screenshot)'.
Search for the word (screenshot) - it should have been removed.
> Remove (screenshots) from FAQs

- projects/Mallard/src/authentication/services/__tests__/iap.spec.ts
- projects/Mallard/src/authentication/services/iap.ts
Corner case in IAP flow when a ReceiptValidationResponse is returned with a missing **last_receipt_info** field which triggers the following 
```
undefined is not an object (evaluating 't.latest_receipt_info.find')
```
[**Trello Card ->**](https://trello.com/c/afvF50vO)
Add a new test case  - 'should return null if last_receipt_info is missing'
> IAP handle missing last receipt info from ReceiptValidationResponse

- projects/Apps/ophan/build.gradle
There is a crash which occuring for android on regular basis (small scale) and this [PR](https://github.com/guardian/multiplatform-ophan/pull/22) fixed that issue. In this PR we are just updating to the latest version of the ophan library. 
[**Trello Card ->**](https://trello.com/c/6opQniSU/1476-fix-an-ophan-crash-on-android)
TODO: need to verify android is sending all the ophan tracking (using charles or logcat) as expected.
> Updated ophan library

- projects/Mallard/src/helpers/date.ts
- projects/Mallard/src/helpers/locale.ts
This PR adds extra android specific logic for dates as `toLocaleDateString` doesn't work on android. 
The `moment` library also didn't work when just passing in a language locale so I have had to go for a less elegant solution of using "MM/DD/YYYY" for US locale only.  (We had to do something similar for the weather units on android)
[**Trello Card ->**](https://trello.com/c/1hfFop0F/1615-android-expiry-date-isnt-respecting-locale)
> Fix expiry locale

- projects/Mallard/src/notifications/notification-service.ts
We are seeing this notification registration [error](https://sentry.io/organizations/the-guardian/issues/1885775400/events/baf3646520cc4de8b89ee4e237db3c0c/?project=1519156&query=dist%3A817&statsPeriod=7d) that is occurring very frequently. This extra loggin will help us to identify what goes when it fails to register with the notification service.
> Added loggings to find out buggy notification registration

- README.md
Non-devs might not have been sent strap when they were given their laptop - this advises them to install it before running editions which should help with git, awscli and vscode setup (maybe other stuff)
Thanks @prisalcalde for good suggestion!
> add strap suggestion to readme

- projects/Mallard/src/notifications/notification-service.ts
There is an issue with missing `topics` that cause notification registration to fail. Hopefully, this will give us more info about why topics are missing.
Sentry errors:
https://sentry.io/organizations/the-guardian/issues/1885775400/events/latest/?project=1519156&query=dist%3A817&statsPeriod=7d
> More logging for notification registration bug 

- projects/Mallard/src/hooks/use-issue-summary.tsx
@jimhunty previous added some logging for IssueSummary bug that logging appears as:
`TypeError: getIssueSummary error: maxAvailableEditions: 30 & issueSummary: [object Object]`
We need to see what the `object` looks like to help us diagnose the [sentry issue](https://sentry.io/organizations/the-guardian/issues/1396286427/?project=1519156&query=dist%3A817&statsPeriod=7d)
> Better logging for issue summary bug

- projects/Mallard/src/hooks/use-edition-provider.tsx
We have observed a spike in handled exception in [crashlytics](https://console.firebase.google.com/project/guardian-daily-edition/crashlytics/app/ios:uk.co.guardian.gce/issues/478416e472734656cae0512d4a570620?time=last-thirty-days&sessionEventKey=a643b3817007440298cc839a301da292_1464828015575953598) after the last app release. It turns out due to a change in edition api usages ([PR](https://github.com/guardian/editions/pull/1556)) app makes network requests when the edition api url is null/empty.
This PR factored the edition api usages to avoid making those invalid network calls.
> Refactored edition api usages

- projects/Mallard/android/app/src/main/java/com/guardian/editions/ophan/InstallationIdHelper.java
- projects/Mallard/android/app/src/main/java/com/guardian/editions/ophan/RNOphanModule.java
- projects/Mallard/android/build.gradle
Issues have been raised with data quality and our implementation of Ophan client libs. In particular, the Editions apps is sometimes sending a `browserId` that does not matching the expected number of characters (for instance "fHSn_pnKRMs").
In the Editions Android Ophan implementation, we are still using the Firebase API to generate an id namely **FirebaseInstanceId** This is not ideal, not best practice and the Firebase dependency should be removed.
The recommended approach, as outlined by the the Android (Live) team is that we should use a **InstallationIdHelper** class to generate a unique id. 
[**Trello: FirebaseInstanceId - Cease and desist**](https://trello.com/c/P8Z0NGr3)
Ensure that Firebase SDK dependency is removed and not longer being used
For further information regarding …
> Remove FirebaseInstanceId

- projects/Mallard/src/components/article/html/components/header.ts
- projects/Mallard/src/components/article/types/article.tsx
- projects/Mallard/src/services/remote-config.ts
This fixes some pretty major bugs introduced in https://github.com/guardian/editions/pull/1555 as a result of some poorly tested last minute refactoring. The main issue is that I introduced a 'display-none' class but in header.ts was still using the classes 'byline-hidden' and 'share-hidden'. This fixes that, as well as resolving a race condition in article.tsx where setting the newly fetched shareUrl would trigger a useEffect change, resulting in the article to re-render.
[**Trello Card ->**](https://trello.com/c/jghUcUNv/925-improvement-share-functionality-10-of-content-unavailable)
I've tested this in the simulator but not on device yet
> Use correct class names for hiding/showing share button.

- projects/Mallard/package.json
- projects/Mallard/src/components/Button/__tests__/__snapshots__/ModalButton.spec.tsx.snap
- projects/Mallard/src/components/Button/__tests__/__snapshots__/ReloadButton.spec.tsx.snap
- projects/Mallard/src/components/Lightbox/__tests__/__snapshots__/LightboxCaption.spec.tsx.snap
- projects/Mallard/src/components/ScreenHeader/IssuePickerHeader/__tests__/__snapshots__/IssuePickerHeader.spec.tsx.snap
- projects/Mallard/src/components/ScreenHeader/IssueScreenHeader/__tests__/__snapshots__/IssueScreenHeader.spec.tsx.snap
- projects/Mallard/src/components/ScreenHeader/__tests__/__snapshots__/EditionMenuScreenHeader.spec.tsx.snap
- projects/Mallard/src/components/ScreenHeader/__tests__/__snapshots__/ScreenHeader.spec.tsx.snap
- projects/Mallard/src/components/article/types/article.tsx
- projects/Mallard/src/theme/color.ts
- projects/Mallard/yarn.lock
[Source](https://www.theguardian.design/) is the Guardian's design system. It attempts to unify the design process across all Guardian digital products. It replaces pasteup, which has been deleted from the dotcom-rendering repo where it lived (see guardian/dotcom-rendering#733)
The colours used here are mostly described on the [Colour Tokens](https://www.theguardian.design/2a1e5182b/p/1377a6-tokens/b/293ddb) page. A few are described on the [Light Palette](https://www.theguardian.design/2a1e5182b/p/492a30-light-palette) page
This PR is a spike to see how easy it would be to integrate Source into the Editions team's codebase and workflow. It's the start of the conversation that we have booked in on Monday 19th October
If you have any questions in the meantime, please let me know
c/c …
> Spike: introducing Source to Editions

- projects/Mallard/src/download-edition/clear-issues-and-editions.ts
- projects/Mallard/src/download-edition/download-todays-issue.ts
- projects/Mallard/src/download-edition/download-via-notification.ts
- projects/Mallard/src/helpers/__tests__/files.spec.ts
- projects/Mallard/src/helpers/fetch.ts
- projects/Mallard/src/helpers/files.ts
- projects/Mallard/src/screens/settings/dev-zone.tsx
As a precursor to refactoring downloading functionality, unused functions have been removed from **helpers/files.ts** Also names updated and typos corrected
> Remove unused functions and include readable names

- projects/Apps/common/src/index.ts
- projects/backend/capi/articles.ts
We need `displayHint` field in `Article` object to treat some image captions differently. This PR add this field so client can use it.
[**Trello Card ->**](https://trello.com/c/HnJ4aNrR/1067-caption-repeated-in-body-text)
Check this works in CODE first
> Added displayHint field to Article

- projects/Mallard/src/hooks/use-edition-provider.tsx
This bug still occuring for [android](https://console.firebase.google.com/project/guardian-daily-edition/crashlytics/app/android:com.guardian.editions/issues/8d9427f6f1bee85efaef5c4b31d7f486?time=last-seven-days&versions=2.276.560%20(14001918)&sessionEventKey=5F994840026A0001023EC57F8BE484E0_1467062173322191060) and [ios](https://console.firebase.google.com/project/guardian-daily-edition/crashlytics/app/ios:uk.co.guardian.gce/issues/478416e472734656cae0512d4a570620?time=last-seven-days&versions=7.2%20(854)&sessionEventKey=53d0ccdba85849f9a7c5ff3df405254c_1467055445463754682)
We have fixed it before but there was one more scenario where `empty api url` can occur. This PR fixes that problem.
This happens when the app completes rendering the UI before the async operation (loading url from …
> Handled empty url bug

- projects/Apps/common/src/index.ts
- projects/Mallard/src/components/article/html/article.ts
- projects/Mallard/src/components/article/html/components/images.ts
In certain articles, with `displayHint=photoEssay` caption appears twice. Once in image caption (which it should be) but also in the body text (due to legacy reason I presume). This PR removes the caption to remove the duplication.
[**Trello Card ->**](https://trello.com/c/HnJ4aNrR/1067-caption-repeated-in-body-text)
| ---- | ---|
|![Simulator Screen Shot - iPhone 11 - 2020-10-27 at 16 55 28](https://user-images.githubusercontent.com/6583174/97328966-d6918280-1876-11eb-85fc-7edc31372835.png)|![Simulator Screen Shot - iPhone 11 - 2020-10-27 at 16 54 31](https://user-images.githubusercontent.com/6583174/97329010-e0b38100-1876-11eb-9301-3691cf5c1a7b.png)|
> Hiding image caption for photoEssay type

- projects/Mallard/android/app/src/main/java/com/guardian/editions/MainActivity.java
The app is crashing on android 5, and it was due a bug underlying androidX library. This PR introduces a workaround to avoid that crash. Here is an example [stack-track](https://console.firebase.google.com/project/guardian-daily-edition/crashlytics/app/android:com.guardian.editions/issues/cbae13a9e468c10d20194a6a0f04a2ce?time=last-seven-days&sessionEventKey=5F9CA930015100012F8C960133A32140_1468013240195708960) of the crash.
Workaround details are here: https://github.com/react-native-webview/react-native-webview/issues/858
[**Trello Card ->**](https://trello.com/c/g99yyG5j/1641-android-app-is-failing-to-start-on-android-os-5)
Release it to internal android beta
> Fix: android 5 webview crash

- projects/Apps/ophan/build.gradle
As it says on the tin
The previous ophan lib (0.1.10) introduced a bug where it incorrectly creates a `dir` instead of `file` and that cause IO exception
> Updated ophan lib that fixes a bug introduced in the previous version

- projects/Mallard/src/hooks/use-edition-provider.tsx
Due to the nature of how the state variable gets updated, we were seeing lots of network calls being made with empty url. This PR fix that problem. A sample crashlytics log can be seen [here](https://console.firebase.google.com/project/guardian-daily-edition/crashlytics/app/ios:uk.co.guardian.gce/issues/478416e472734656cae0512d4a570620?time=last-seven-days&versions=7.2%20(861)&sessionEventKey=cf0db3de7e2c40869249df2600e5f5b6_1469667662878755913)
> Fix: empty url loading bug

- projects/Apps/common/src/index.ts
- projects/archiver/test/tasks/front/helpers/media.spec.ts
- projects/backend/__tests__/helpers/fixtures.ts
- projects/backend/capi/articles.ts
In order to help with some article rendering work, we need to include a unique id to each article object. This PR just does that.
This will add this new field as a child of the article object.
> Added internalId to edition api respose

- projects/Mallard/src/theme/spacing.ts
In discussions with @pradasa a loong time ago we agreed mobile cards should be a bit shorter. This PR shaves 10 pixels off the height of mobile cards, thus solving the slim border seen on iPhone SE/iPhone 5 devices.
[**Trello Card ->**](https://trello.com/c/nC1cJfBX/1300-cover-cards-image-doesnt-fit-the-full-card)
I've tested this in the simulator for an iphone 11. The worst thing I saw was this - otherwise no cropped text or dodgy borders. I think this would be fine to push to beta, but we should make sure we tell the production team to update their apps as it is a slight change to the layout.
> Reduce height of mobile cards.

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/helpers/storage.ts
- projects/Mallard/yarn.lock
The current `react-native-keychain` is failing to read/write large values for some android devices and as a side effect (I think), it triggers fingerprint dialog.
This PR updated the library to the latest version of the library (6.2.0) which resolves that problem.
Note: The new library does prevent showing fingerprint to new install but it still seems to be an issue for those users who experienced fingerprint issues before. 
[**Trello Card ->**](https://trello.com/c/qMwpMhcR/1654-fingerprint-message-android-2620-14001378)
Roll out to beta users and validate the sign-in still works as expected.
> Keychain updated to latest version

- projects/Apps/common/src/index.ts
- projects/aws/lib/aws-stack.ts
- projects/backend/README.md
- projects/backend/__tests__/application.spec.ts
- projects/backend/application.ts
- projects/backend/backend.ts
- projects/backend/controllers/render.ts
This is a very basic controller which simply calls out to apps renderinig and returns the response. We'll need to think about what headers to add and whether we want to gzip the response, but this is a starting point. 
The backend is only accessible via preview so I am confident this won't pose any problems for users. It's just a building block so that the archiver can start including html in the bundle
> Add /render endpoint to backend.

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
After release 7.2 on 23rd November 2020, increment release to 7.3 for next body of work
> bump iOS version to 7.3

- projects/Apps/common/src/index.ts
- projects/archiver/src/tasks/indexer/helpers/get-issue-summary.ts
- projects/archiver/src/tasks/zip/helpers/zipper.ts
- projects/archiver/src/tasks/zip/index.ts
- projects/archiver/test/tasks/indexer/helpers/get-issue-summary.spec.ts
To avoid duplicate `html` bundles we need a clean image directory structure without an image size prefix in it (i.e. without phone, tablet etc). This PR is for that purpose
The outcome of the PR is having a simpler folder structure, something like this:
And a new assets item in the issue summary api called `assetsSSR`, look like this:
> Generate new sets of image bundles with flat directory structures

- projects/Mallard/src/components/article/html/components/images.ts
This PR fixes 2 UI bugs:
1. Inline captions overlap on small tablet devices (namely iPad Mini). In this PR, any inline caption greater than 15 lines is truncated and an ellipsis is added. The user can click a newly added view more button below to expand to lightbox view and read the full caption. 
2. Caption arrows don't rotate to point at image. This is now resolved by checking if the image is inline on tablet. 
[**Trello Card ->**](https://trello.com/c/xoMKO1Y7)
[**Trello Card ->**](https://trello.com/c/iZV7Q7kA)
Before:
After:
> Fix: Caption Overlap and caption arrow misdirected

- projects/Apps/common/src/index.ts
- projects/archiver/src/tasks/zip/helpers/zipper.ts
- projects/archiver/src/tasks/zip/index.ts
- projects/archiver/test/tasks/indexer/helpers/get-issue-summary.spec.ts
- projects/backend/__tests__/helpers/fixtures.ts
- projects/backend/controllers/render.ts
To support users when they don't have downloaded issue on their phone we need to allow the app to directly render article with images. To do that our `<article>.html` file needs to have full web url for images. This PR made two changes:
1. Individual `article.html` now has full image path
2. Articles inside `html.zip` contain a relative image path
[**Trello Card ->**](https://trello.com/c/Od0M2r4Y/1698-editions-rendering-article-image-url-handling)
Deploy to CODE and test it on the app
> Rendered article html now has full web url for images

- projects/Mallard/src/components/article/html/components/header.ts
This PR move the headline from the main media to just below, leaving only the kicker on the image. This is due to headlines overlapping with faces on the image and therefore obscuring the image.
[**Trello Card ->**](https://trello.com/c/fkI1akxC/1693-interview-templates-headline-covers-main-media)
**Before:**
**After:**
*article used is from 15/11/2020 - Life, card 3 - "This much I know" : Jodie Turner-Smith
> Move interview headline below main media

- projects/Mallard/src/components/onboarding/new-edition.tsx
- projects/Mallard/src/helpers/words.ts
This PR updates the colour and copy of the new edition popup inline with new designs.
[**Trello Card ->**](https://trello.com/c/snUrRRLs/1695-special-edition-awareness-balloon#comment-5fd0bcf4fe5e6b1169e2ccbc)
Before:
After:
> Update style of the new edition popup bubble 

- projects/Mallard/src/helpers/words.ts
Maintain consistency with Editions and remove full stop in the new Special Editions pop-up bubble copy
Remove unnecessary backticks
> Update words.ts to remove full stop in special edition bubble copy

- projects/Mallard/src/components/article/html/components/header.ts
This PR tightens the headline on interviews in line with design. 
Example:
> Tighten the interview headline

- projects/Mallard/src/components/article/html/article.ts
- projects/Mallard/src/components/article/html/components/images.ts
This PR fixes a bug introduced in https://github.com/guardian/editions/pull/1604, whereby the view more button appears below *all* inline photo captions, rather than just on gallery. In this PR, we pass down the article type as a prop and only render the view more button below captions if it is a gallery article. 
[**Trello Card ->**](https://trello.com/c/t66sqEVh/1706-view-more-button-captions-appearing-on-inline-photos-on-ipads-and-tablets)
Before: 
After:
*articles used for screen shots are from Edition 21/12/20 and are National > The Weekend's Best Photos & World > Greece "Zak's an icon"
> Fix: 'view more' button appearing on wrong article type

- projects/backend/capi/__tests__/articleImgPicker.spec.ts
- projects/backend/capi/__tests__/byline.spec.ts
- projects/backend/capi/__tests__/imageParser.spec.ts
- projects/backend/capi/__tests__/kickerPicker.spec.ts
- projects/backend/capi/articleImgPicker.ts
- projects/backend/capi/articleTypePicker.ts
- projects/backend/capi/articles.ts
- projects/backend/capi/assets.ts
- projects/backend/capi/atoms.ts
- projects/backend/capi/byline.ts
- projects/backend/capi/decoders.ts
- projects/backend/capi/elements.ts
- projects/backend/capi/kickerPicker.ts
- projects/backend/image.ts
- projects/backend/package.json
- projects/backend/yarn.lock
We're attempting to make requests from the Editions backend directly to Apps-Rendering, so that we can leverage Apps-Rendering's functionality to build HTML documents for the articles. The Editions backend currently makes requests to CAPI's Thrift endpoint to get the data for an article, and fortunately Apps-Rendering can accept this CAPI data directly to build an article.
Unfortunately Apps-Rendering and Editions use different techniques to generate the CAPI types and encoders/decoders from the Thrift models:
- Editions uses the [`typescript-capi-thrift`](https://github.com/guardian/typescript-capi-thrift) project for the TypeScript models, and leverages CreditKarma's `thrift-server-core` library to decode them
- Apps-Rendering uses the TypeScript models generated by the …
> Migrate From `capi-ts` To `content-api-models`

- projects/Mallard/src/components/article/html/article.ts
- projects/Mallard/src/components/article/html/components/images.ts
- projects/Mallard/src/components/article/html/css.ts
This PR reverts changes introduced in  #974. These changes were brought in to move captions underneath images on gallery articles . As we are now truncating longer captions with a view more button, this fix is no longer required and all gallery captions will appear inline on tablet in both landscape and tablet. 
Whilst this PR resolves this bug, captions only appeared underneath images on *some* gallery articles, as you can see in the before screenshots. This is because some gallery articles have a type field of 'gallery' and some do not (screenshot 1 is type 'article' and screenshot 2 is type 'gallery'). This is being set in Editions in line 63 of use-article.tsx and does not reflect the CAPI article type field. More time needed to understand why this is being done.
[**Trello Card …
> FIX: Gallery captions not always inline

- projects/Mallard/src/components/article/types/article/webview.tsx
- projects/Mallard/src/helpers/settings.ts
- projects/Mallard/src/helpers/settings/defaults.ts
- projects/Mallard/src/helpers/words.ts
- projects/Mallard/src/hooks/use-config-provider.tsx
- projects/Mallard/src/screens/article/body.tsx
- projects/Mallard/src/screens/settings/dev-zone.tsx
This PR  adds a feature flag to display articles in the app using apps-rendering CODE as the backend for online articles. 
This will allow all team members to view editions rendering work in the editions app, allowing us to spot UI bugs and tweaks early.
NB - this feature flag will only work for online articles. Any offline content will not be rendered when the flag is set.
[**Trello Card ->**](https://trello.com/c/NsArA49Y/1674-article-scaffolding-for-editions-to-view-er-templates)
> Feature Flag To Serve From Apps-Rendering CODE

- projects/Mallard/src/helpers/diagnostics.ts
- projects/Mallard/src/helpers/words.ts
This PR adds additional copy to user emails to encourage users to provide more detail around bugs. 
[**Trello Card ->**](https://trello.com/c/Q8l4DiDC/1642-add-description-with-instructions-on-the-beta-emails)
> User Email In-App Copy 

- projects/backend/.gitignore
- projects/backend/README.md
- projects/backend/__tests__/application.spec.ts
- projects/backend/application.ts
- projects/backend/backend.ts
- projects/backend/controllers/appsRendering.ts
Simple Apps Rendering proxy to allow Editions app to quickly and painlessly test Apps Rendered HTML content via a simple editions endpoint. This has been optimised for delete-ability, as it may very well be an interim solution.
App -> Editions Backend -> AR PROD*
*The AR endpoint is configured in the .env file
Example Request:
```
https://editions.guardianapis.com/rendered-items/travel/2020/jan/27/rail-sail-how-to-book-perfect-holiday-without-flying
```
will be proxied to:
```
https://mobile.guardianapis.com/rendered-items/travel/2020/jan/27/rail-sail-how-to-book-perfect-holiday-without-flying?editions
```
[**JIRA Ticket | Wire-up Editions backend AR for rendered article requests**](https://theguardian.atlassian.net/browse/LIVE-1446)
> Simple Apps Rendering Proxy

- projects/backend/package.json
- projects/backend/yarn.lock
The capi thrift model had a bug that fails to decode the crossword. This PR updates to the latest version of `guardian/content-api-models` that fixes that problem.
[**Jira Card ->**](https://theguardian.atlassian.net/browse/LIVE-1679)
Deploy to CODE and test crossword appears in the Edition app
> Updated capi thrift model that fixes crossword decoding problem

- projects/Mallard/fastlane/Fastfile
- projects/Mallard/ios/Gemfile.lock
The full details are summarized in this [doc](https://docs.google.com/document/d/1nIgFJlgcnvVDg_jfzumoloauPJ7OoYE7ZB-FaNu5FfU/edit)
TLDR;
Due to some changes in the apple publishing process 2FA process has enforced upon deployment and hence Fastlane is failing to upload the ios bundle.
This PR took the simpler approach to bypass 2FA for the time being.
> Fix 2FA issue for iOS github action using latest version of Fastlane

- projects/Mallard/src/components/EditionsMenu/EditionButton/__tests__/__snapshots__/EditionsButton.spec.tsx.snap
- projects/Mallard/src/components/EditionsMenu/EditionButton/styles.tsx
- projects/Mallard/src/components/ScreenHeader/EditionMenuScreenHeader.tsx
- projects/Mallard/src/components/ScreenHeader/__tests__/__snapshots__/EditionMenuScreenHeader.spec.tsx.snap
This PR adds some styling tweaks to the edition picker button and header in preparation for the next special Edition in line with new designs, specifically the positioning of the thumbnail picture.
- Remove padding from button image and add marginRight
- Adjust the size of the image in line with new thumbnail
- Update special title font weight from regular to medium
- Reduce header padding to 100
| phone | tablet|
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/109203669-5cc5c300-779c-11eb-8e54-ca83a4a7c265.png" width="300" /> | <img src="https://user-images.githubusercontent.com/20416599/109203690-63543a80-779c-11eb-8bbf-6d7a5ff99cb2.png" width="300" /> |
| --- | --- |
> Edition Picker Menu Style Updates

- projects/Mallard/src/components/EditionsMenu/EditionButton/EditionButton.tsx
- projects/Mallard/src/components/EditionsMenu/EditionButton/__tests__/__snapshots__/EditionsButton.spec.tsx.snap
- projects/Mallard/src/components/EditionsMenu/EditionButton/styles.tsx
This PR includes two last minute UI tweaks to the edition selector button from Design to be included in time for the new special editions.
- Use neutral.46 for expiry copy
- Reduce vertical padding
| mobile | tablet|
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/109495875-c806e200-7a87-11eb-9e88-d99f8c1bd13d.png" width="300" /> | <img src="https://user-images.githubusercontent.com/20416599/109496214-4499c080-7a88-11eb-8467-84041d13a1ed.png" width="300" /> |
| --- | --- |
> Books Special Edition - Style Changes

- projects/Mallard/android/app/src/main/java/com/guardian/editions/ophan/RNOphanModule.java
There are reported issues of low page view count for the android app. There is apparently no issue with the implementation but there is a potential issue with how android stores the events in the file system to send it later. On android, it stores all the events inside the `cache` folder which is a target for the OS to clear when storage space running low and as a result ophan stored events in the file system that are waiting to be sent can be deleted.
This PR updates the storage location, instead of the `cache` folder it usages the app's normal directory to store events. 
This should also solve a recurring crash that we see in Firebase [crashlytics](https://console.firebase.google.com/project/guardian-daily-edition/crashlytics/app/android:com.guardian.editions/issues/05f91b73a87871b32a769 …
> Updated Ophan events storage directory

- projects/Mallard/src/components/article/types/article.tsx
We were losing the top of each article below the nav.
| --- | --- |
| <img src="" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/110347077-26a00300-8028-11eb-9eeb-9259f29edfbf.png" width="300px" /> |
> LIVE-1900: increase article margin-top

- projects/Mallard/package.json
- projects/Mallard/src/components/article/html/components/header.ts
- projects/Mallard/src/components/article/html/components/images.ts
- projects/Mallard/src/components/article/types/article.tsx
- projects/Mallard/src/helpers/webview.ts
- projects/Mallard/yarn.lock
In order to trigger the lightbox and share functionality we need to send and receive messages between the client and the webview. This PR updates the types used when handling these messages to match the Renditions package to support the AR served content as well as the current implementation. 
[**Jira Card (Lightbox) ->**](https://theguardian.atlassian.net/browse/LIVE-1880)
[**Jira Card (Share) ->**](https://theguardian.atlassian.net/browse/LIVE-1892)
Testing steps are as follows and need to be done for content rendered traditionally and from apps rendering:
> LIVE-1880 & LIVE-1892 :  Lightbox and Share Functionality

- projects/Mallard/CHANGELOG.MD
- projects/Mallard/src/screens/home-screen.tsx
Consistency of names on the navigation and Manage downloads screen.
Editions - Regions and special editions
Issues - Each Edition can have multiple Issues
Copy change from Recent 'Editions' to Recent 'Issues' on the header of the yellow menu.
| --- | --- |
| <img src="" width="300px" /> | <img src="" width="300px" /> |
> Copy change on menu header

- projects/Mallard/ios/Mallard/AppDelegate.m
If an iOS device is on silent, videos have no sound in the app. This differs from the behaviour of Editions on Android and of The Guardian live app on Android and iOS. This PR amends the AppDelegate so that we override the silent setting and play sound from videos.
> LIVE-1893-Add-Sound-To-Video

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/src/screens/home-screen.tsx
The issue list was broken, this fixes that issue.
A bug still exists where the `SettingsScreen` has lost its modal styling, that can be done as a separate PR.
- Add `ScreenFiller` component
> LIVE-2053: fix width

- projects/Mallard/src/components/front/items/helpers/item-tappable.tsx
Fronts cards were appearing blank when a user opened an article and closed it again. We realised this was due to the card opacity fading out as the article opened.
To fix we reinstated the mising event listener in order to fade the front card back in as the article closed.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/112477178-9cb3a200-8d6a-11eb-975f-ecdaad2ebe9c.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/112477230-ab9a5480-8d6a-11eb-8684-eb9232c17186.png" width="300px" /> |
> Live 2049 fronts card vanishing

- projects/Mallard/src/App.tsx
- projects/Mallard/src/AppNavigation.tsx
- projects/Mallard/src/navigation/NavigationModels.tsx
- projects/Mallard/src/screens/onboarding-screen.tsx
- projects/Mallard/src/screens/onboarding/cards.tsx
- projects/Mallard/src/screens/settings/gdpr-consent-screen.tsx
If a user hasn't been onboarded and consented yes/no to gdpr consent permissions, they should hit the onboarding screen before the main app. This PR adds the onboarding route back into the app as a separate stack with a switch on initial render to show user either the onboarding stack or the root stack. 
The GDPR consent screen was a nested virtualized list. This PR removes the unnecessary scrollview wrapper
> Live 1788 :  Onboarding stack

- projects/Mallard/src/screens/editions-menu-screen.tsx
The area next to the Edition and Issue menu should be tappable so the user can return to the issue. This PR adds a transparent button next to the menu to tap back if the device is a tablet.
> Live 2075 : Invisible Back Button 

- projects/Mallard/src/screens/settings/gdpr-consent-screen.tsx
This fixes a bug introduced in the previous LIVE 1788 branch leading to an invariant Violation: Rendered more hooks than during the previous render error because of a hook being below a return.
This PR also disables the vertical scroll indicator on the GDPR consent screen.
> Live 1788 onboarding stack

- projects/Mallard/ios/exports-plists/debug.plist
- projects/Mallard/ios/exports-plists/release.plist
Currently, iOS Edition app has `bitcode compile` flag enabled as a result Firebase Crahlytics can't decode the crash stack traces (because it does not have the correct dSYMs file). Live iOS app doesn't use `bitcode` feature either, so this PR disabled that flag for the Edition app so we can see a clean text stack trace in Crashlytics.
> Disabled bitcode compilation

- .github/workflows/scheduled-ios-beta.yml
To test build from non-default branch which has new Nav work we are turning off the iOS schedule beta.
> Turned off iOS schedule beta

- projects/Mallard/src/AppNavigation.tsx
- projects/Mallard/src/components/Header/Header.tsx
- projects/Mallard/src/navigation/NavigationModels.tsx
- projects/Mallard/src/screens/settings-screen.tsx
- projects/Mallard/src/screens/settings/join-beta-button.tsx
The new implementation of the modal was missing the correct animations and styles. 
This PR moves the settings menu screens to a new `Settings` stack to separate the animation styles and make things easier to read. It also fixes a few minor styling issues.
- Fix manage editions menu height and background colour
- Round off modal corners
- Update composite type definition
- Add new animations
| --- | --- |
| <img  src="https://user-images.githubusercontent.com/77005274/112977165-a6178280-914d-11eb-87d9-2448a6e5e5e1.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/112977234-b62f6200-914d-11eb-882c-82f89823876e.png" width="300px" /> |
> LIVE-2087: fix animations and modal styling

- projects/Mallard/README.md
- projects/Mallard/src/navigation/NavigationModels.tsx
- projects/Mallard/src/screens/settings/dev-zone.tsx
- projects/Mallard/src/screens/storybook-screen.tsx
The consent menu button is no longer needed for development and doesn't provide a correct representation of the consent flow so it is being removed.
> Live 2092 consent duck menu

- projects/Mallard/index.js
- projects/Mallard/src/navigation/NavigationModels.tsx
- projects/Mallard/src/screens/home-screen.tsx
Upgrading react-navigation broke the `Manage Editions` route. This PR fixes that route by navigating to the nested settings  navigator.
> Live 2114 : Manage Editions button

- projects/Mallard/src/App.tsx
- projects/Mallard/src/__mocks__/@react-navigation.tsx
- projects/Mallard/src/components/Header/Header.tsx
- projects/Mallard/src/components/ScreenHeader/IssuePickerHeader/IssuePickerHeader.tsx
- projects/Mallard/src/hooks/use-overlay-animation.tsx
- projects/Mallard/src/hooks/use-settings-overlay.tsx
- projects/Mallard/src/screens/home-screen.tsx
- projects/Mallard/src/screens/identity-login-screen.tsx
The new Modal (implemented via React-Navigation v5) doesn't add an opacity layer over the `Issue Picker` menu.
This PR adds a `SettingsOverlayContext` so allow us to activate an opacity overlay on the `Home Screen` whenever the settings menu modal is opened.
I've also added a `use-overlay-animation` hook which returns both a boolean to control whether then overlay is rendered, and a `Animation` value which can be used to control the opacity of the overlay. We need both as otherwise we're left with a transparent overlay which blocks the use of any buttons on the components below it.
- add `SettingsOverlayProvider` context
- add `use-overlay-animation` hook
- add overlay to home screen
- add `setSettingsModalOpen()` instructions to header buttons 
| --- | --- |
| <img …
> LIVE-2087: add animation hooks

- projects/Mallard/src/components/Header/Header.tsx
On Android mobile the modal wasn't picking up the correct sizing and had rounded edges.
This PR uses `flex: 1` to make it full height and removes the `borderRadius` value on mobile.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/113304746-3c88a700-92fa-11eb-916e-96ff04ad02ac.png" width="300px" />| <img src="https://user-images.githubusercontent.com/77005274/113304828-4f02e080-92fa-11eb-8982-cdbc95930915.png" width="300px" /> |
> Live 2141 rounded edges

- projects/Mallard/src/components/front/items/helpers/item-tappable.tsx
The fronts card images were transitioning back in very slowly, this PR reduces the delay and duration of those animations.
> Live 2143 front transition speed

- projects/Mallard/src/screens/home-screen.tsx
On Android, there is tiny delay as the issue picker menu slides in. 
Normally, the "loading" screen is only visible very briefly (<0.5 second) so this isn't an issue. However, if this is longer for any reason (eg poor connection) it leaves the user temporarily with a grey panel(tablet) / screen (mobile).
Updating the background colour to white, adding the editions loading dots, and fixing the header makes the transition a little smoother and provides a loading context to the user if they have bad connectivity. 
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/113740157-5e1dd000-96f8-11eb-9d78-2b27353a270d.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/113740223-6bd35580-96f8-11eb-9a16-92de0fa85bf9.png" …
> Live 2140 :  Add loading indicator to issue picker screen

- projects/Mallard/src/components/weather.tsx
- projects/Mallard/src/screens/weather-geolocation-consent-screen.tsx
The `Use Location` button isn't navigating to the correct screen as it is not being routed through the settings stack. This PR fixes this and additional styling
- Navigate to location consent page via settings stack
- Add wrap location consent page in header container for styling
> Live 2170 : Wire Up Use location Button

- projects/Mallard/src/screens/home-screen.tsx
The `manage downloads` button in the issue picker footer is being pushed below the screen. This PR adds footer styling to bring it back into view on scroll. 
Add list footer styling with padding 
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/113885055-6d178780-97b7-11eb-96f8-f6facafd84d5.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/113884044-94218980-97b6-11eb-97bc-82abcc00e69d.png" width="300px" /> |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/113885136-7ef92a80-97b7-11eb-85e1-87230c99b600.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/113884080-9c79c480-97b6-11eb-8e95-90edf89850a1.png" width="300px" /> |
> Live 2180 manage downloads

- projects/Mallard/src/screens/settings/dev-zone.tsx
IAP is specific to iOS so we are hiding this dev button on Android
> Live 2176 : Remove  IAP Dev Button on Android

- projects/Mallard/src/AppNavigation.tsx
- projects/Mallard/src/navigation/NavigationModels.tsx
We decided to remove the existing the animations for the settings modal until we can work out how to replicate the old Editions animations correctly with the new API. This PR also fixes a bug where the close button on the sign-in screen was going back to the home page rather than the settings screen.
> LIVE-2205: fix sign in route and remove animations

- projects/Mallard/src/AppNavigation.tsx
- projects/Mallard/src/components/front/items/helpers/item-tappable.tsx
- projects/Mallard/src/navigation/NavigationModels.tsx
- projects/Mallard/src/navigation/navigators/article.tsx
- projects/Mallard/src/screens/home-screen.tsx
- projects/Mallard/src/theme/color.ts
Reintroduces crosswords after they were lost during the react navigation 5 upgrade. 
Instead of using custom animation, it now uses out of the box transition to expand to full screen in a modal style, transitioning vertically
- render crosswords in a full screen modal
- add default white background to all cards
- add styling to dev button in the issue picker
| Mobile | Tablet |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/114021973-31d59100-9869-11eb-8b77-2440ffe263aa.png" width="300px" /> | <img src="" width="300px" /> |
> Live 2181 :  crosswords

- projects/Mallard/fastlane/Fastfile
After renewing the distribution certificate on iOS, the Editions build started to fail as it was still referencing the outdated provisioning profile. This is because it was relying on the code signing repo for its profile, which had a copy/reference to the outdated profile. 
To fix this, @jacobwinch suggested 2 options:  
1. Delete the 'old' profiles from the code-signing repo and allow Fastlane to create a new profile for Editions automatically.
2. Follow the `ios-live` path: manually create a profile and link it to the new cert. Tell Fastlane to download it explicitly using get_provisioning_profile as part of the build process and set skip_provisioning_profiles: true at the sync_code_signing call site. (Optionally) delete the profiles stuff from the code-signing repo to tidy up. For …
> Live 2254 :  Fastlane Signing

- projects/Mallard/src/helpers/settings/defaults.ts
To test the content/issue/bundle generated by the new mobile aws stack we need to test them in the existing mobile client to make sure it is backward compatible. This PR adds 2 new api endpoints to access content from the mobile stack.
> Added new api endpoints to access new mobile stack

- yarn.lock
During upgrading, the yarn.lock has fallen out of sync. This PR updates the yarn.lock which adds @guardian/prettier into the projects tools.
> Chore update yarnlock

- .github/workflows/scheduled-ios-beta.yml
Turn back on the scheduled iOS beta now that the navigation work has been merged into the `master` branch
> Add scheduled internal beta back in

- projects/Mallard/src/screens/article-screen.tsx
Sign in buttons on the sign in modal were not correctly routing to the sign in screen. This PR updates the navigation function to route through the settings stack to the sign in screens
> Update sign in route names to

- projects/Mallard/src/helpers/settings.ts
- projects/Mallard/src/helpers/settings/defaults.ts
The new backend stack (under mobile aws account) is running in parallel to the current stack. To test the backward compatibility properly against the new stack with the wider audience we can use our beta users who will use the new backend stack with existing apps. This PR just does that.
We can push this change to the beta users for the backward compatibility test, meaning they will have app as it it but will use new backend stack. If something goes wrong we can roll back this change and release another beta. If all goes well we will still roll back this change so that it does not go to prod users. For prod users we will make the api url change by `fastly` config.
- Change the apiUrl if a user is in beta
> Beta app points to new backend stack

- projects/Mallard/ios/Podfile
This PR re-implements a patch previously introduced [here](https://github.com/guardian/editions/pull/1755) to show images when using React-Native@0.61.5 and iOS 14 sdk with Xcode 12
> Fix:  add patch to podfile for images in iOS 14

- projects/Mallard/src/screens/home-screen.tsx
Make issue picker have full height of device screen. 
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/118457432-a665e000-b6f1-11eb-840c-28133a6aca4b.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/118457436-a6fe7680-b6f1-11eb-9246-42906ab26214.png" width="300px" /> |
> Issue list is 100% of height

- projects/Mallard/package.json
- projects/Mallard/src/helpers/diagnostics.ts
- projects/Mallard/yarn.lock
This PR updated `react-native-device-info` library that fixes some issues for android, especially around getting disk statistics
For example, it was reporting these stats for android:
Total Disk Space (Mb): 4556
Available Disk Space (Mb): 85537
Which is now fixed by this latest library
> updated rn-device-info library

- projects/Mallard/src/helpers/settings.ts
- projects/Mallard/src/helpers/settings/defaults.ts
- projects/Mallard/src/helpers/words.ts
- projects/Mallard/src/hooks/use-config-provider.tsx
- projects/Mallard/src/screens/article/body.tsx
- projects/Mallard/src/screens/settings/dev-zone.tsx
To make testing easier we are changing the default apiUrl so it points new stack and also a first option in the duck menu.
Also, removed some custom logic that determined where an article using ER or not because all article now use ER going forward.
> Updated default apiUrl

- .github/workflows/scheduled-ios-beta.yml
To facilitate ER testing (mega-pr) with internal beta users we are turning off automatic internal beta release from github action that build and deploy from `master` branch.
> Turned off schedule beta from github action

- projects/Mallard/src/components/article/types/crossword.tsx
With the react-native-webview `onMessage` is required props that allow injecting JS to the webview. The crossword page was missing that props. It was not a requirement with the old webview we had.
Docs is [here](https://github.com/react-native-webview/react-native-webview/blob/d6672c87eb61827c9b0215733a4766c14f68d01a/docs/Guide.md)
> Fixed crossword rendering

- projects/Mallard/src/screens/article/slider/SliderTitle.tsx
- projects/Mallard/src/screens/article/slider/__tests__/__snapshots__/SliderTitle.spec.tsx.snap
- projects/Mallard/src/screens/article/slider/__tests__/__snapshots__/SliderTitle.tablet.spec.tsx.snap
- projects/Mallard/src/theme/breakpoints.ts
- projects/Mallard/src/theme/spacing.ts
On iPad Air, showcase header images had an incorrect left margin, which caused sports scores components to render off the left hand side of the window.
This PR moves the tablet breakpoint in line with Source (from 800px down to 740px) and changes the article max-width to fit with this. Old iPad Airs should now be classed as tablets.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/121897626-7cb4ce80-cd1a-11eb-855b-9385326136d9.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/121897765-9d7d2400-cd1a-11eb-8747-58d91ea31de1.png" width="300px" /> |
| --- | --- |
| <img  src="https://user-images.githubusercontent.com/77005274/121898542-65c2ac00-cd1b-11eb-9f01-bbe5e05e3e03.png"  width="300px" /> | <img …
> LIVE-2583: adjust breakpoints

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/src/helpers/files.ts
Clipboard copy functionality stopped working for some users because we had an incorrect image folder structure for some Issues. The bug has been rectified on the server-side and users (in beta) who downloaded those Issues with incorrect image folder structure having issues with copying diagnostic info. This is because diagnostic info tries to create stats from the image folders. This is a temp solution for those users, it now handles the error gracefully when the folder is missing or does not match the path.
> Handled error while reading file stats

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Following the release of iOS version 7.8, bump version number to 7.9
> bump version number to 7.9

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/src/download-edition/download-and-unzip.ts
- projects/Mallard/src/helpers/files.ts
- projects/Mallard/src/services/remote-config.ts
Problem:
The new version of the app that will be released in the future once the ER work is done can only render articles if they are rendered server-side (SSR) and has corresponding changes in the zip bundles (html and images). On the release of this new version of the app, users can download new Issues and read them without any problem. But all the existing downloaded Issues on the user's device will have no SSR content and the structure of the zip bundles will be incompatible with the new version of the app.
Solution:  
The app will download SSR compatible zip bundles in parallel to normal bundles and both versions of the content (html and images) will exist on the user device. As a result, when a user updates their app to the new version the downloaed Issues will work fine. To reduce …
> Download SSR compatible bundles in parallel

- projects/Mallard/src/helpers/files.ts
A known issue reported by users that downloaded issues do not work in offline mode. From the log, it seems that it fails to parse the JSON issue summary when it read the object from the disk. Looks like there is a known issue with the react-native-fs. It can mess up the file content if the file already exists.
Open issue: https://github.com/itinance/react-native-fs/issues/700
This PR fixes that problem by removing first before writing the file.
> Work around to avoid malformed JSON file 

- projects/Apps/common/src/index.ts
- projects/Mallard/src/helpers/settings/defaults.ts
- projects/archiver/src/tasks/front/helpers/render.ts
- projects/archiver/src/tasks/front/index.ts
- projects/archiver/src/utils/backend-client.ts
- projects/backend/__tests__/application.spec.ts
- projects/backend/application.ts
- projects/backend/backend.ts
- projects/backend/controllers/render.ts
- projects/backend/fronts.ts
Implemented rendered front where backend returns a fully rendered version of a front to archiver.
Currently, when we render an article using ER it does not take into account any overrides in the fronts tool. This PR introduces a new endpoint in the backend that takes front metadata as input and returns a fully rendered version of each and every article within the front. This helps archiver lambda to process them in one go rather than making an individual request for every single article.
> Article overrides implementation

- projects/backend/controllers/render.ts
Currently `trailtext` overrides from the Fronts too are not being displayed in Editions Rendering. To resolve this we map the `trailtextOverride` field to `content.fields.standfirst`. If `trailTextOverride` is empty then we render the standfirst as usual.
No UI changes.
> Live 2717 map trailtext to standfirst

- projects/Mallard/src/components/article/types/article.tsx
The new webview doesn't have momentum style scrolling out of the box. This PR makes use of the `decelerationRate` prop. This gives the WebView the same "momentum" style scrolling as other iOS views.
| Before |
https://user-images.githubusercontent.com/20416599/124481852-a5bc0280-dda0-11eb-8306-20b7961976a4.mov
| After |
https://user-images.githubusercontent.com/20416599/124487421-9b9d0280-dda6-11eb-9b53-d0eb0860ef70.mov
> Live 2732 momentum scrolling

- projects/Mallard/src/App.tsx
- projects/Mallard/src/helpers/settings/defaults.ts
- projects/Mallard/src/helpers/storage.ts
We did an experiment with the new stack's API URL, now that we made the fastly config change and fastly now pointing to the new stack, we no longer need to keep two sets of API URLs. This PR removes those URLs and also roll back URL change for the beta user that we did for testing.
> Clean api urls

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/components/article/types/article.tsx
- projects/Mallard/src/components/article/types/article/webview.tsx
- projects/Mallard/yarn.lock
There is a known issue on android where it often fails to load file from the local file system due to a race condition.
https://github.com/react-native-webview/react-native-webview/issues/656
This PR fixed that problem along with some optimizations.
- Updated the webview to the latest version
- Fixed the article load failure by adding an event that triggers once webview is ready
- Moved some props to the top-level to reduce the redraw of the child component
> Fix: articles failed to load on android while offline

- projects/backend/controllers/render.ts
- projects/backend/fronts/issue.ts
We want to override article themes with that articles front theme. 
- Add Theme enum for type safety
- Convert current `swatch` into `Theme`
- Pass theme as query param to AR
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/125668053-13c65d57-9783-4202-afae-ef39e504eb9d.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/125667992-baceaa24-899c-4032-9d66-8eef599c05d0.png" width="300px" /> |
> Live 2787 : Pass Theme to AR

- projects/Mallard/src/components/article/types/article/webview.tsx
Disabled webview cache due to inconsistent states when Issue gets deleted from the device
Jira: https://theguardian.atlassian.net/browse/LIVE-2672
> Disabled webview cache

- projects/Mallard/src/hooks/use-issue-on-device.ts
After deleting downloaded Issues we need to remove the cache `Issue` content so that next time the app loads articles from api instead of the file system
This fixes the bug where user sees error message when try to load article after deleting Issues.
Ticket is [here](https://theguardian.atlassian.net/secure/RapidBoard.jspa?rapidView=36&projectKey=LIVE&modal=detail&selectedIssue=LIVE-2844&quickFilter=154)
> Fix: Issue deletion status update 

- projects/backend/controllers/render.ts
To render the article correctly in preview mode we need to pass the `isPreview` param to AR. This PR is just doing that.
> Added isPreview param

- projects/Mallard/src/components/article/types/article.tsx
This reintroduces some logic that makes sure the lightbox opens on the correct image. Without this logic, the lightbox opens up on the image after the one that was clicked.
> LIVE-2879 - Lightbox

- projects/Mallard/src/screens/home-screen.tsx
This [PR](https://github.com/guardian/editions/pull/1692/files) refactored few things and one of them was replacing `null` with `undefined` that breaks the `if` statement and as a result edition side menu does not expand when clicking on the Issue title.
This PR reverts that back to `null`.
The ticket is [here](https://theguardian.atlassian.net/browse/LIVE-2726)
@joecowton1 not sure what was the original intention of this change, please have a look if you still wants to keep `undefined` for any reason then we need to refactor the code further.
> Reverting a change that breaks the side menu expansion

- projects/Mallard/src/screens/editions-menu-screen.tsx
The sidebar was broken on ipads in landscape mode.
- check for landscape and apply styles
https://user-images.githubusercontent.com/77005274/128362863-21335dab-31d6-4f6a-8ba8-fdf0d995da05.mov
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/128362251-ac4d444d-621d-4064-81b6-7dc3510f6439.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/128362309-78a36a56-55e4-43a4-8037-8bd24c671f9e.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/77005274/128362615-b95a2e2d-1fd7-4e7b-839a-7778e9326959.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/128362398-0be8e064-7722-4a03-9692-0b68e4378fe5.png" width="300px" /> |
> LIVE-2662: add flex-end to styling

- projects/Mallard/src/components/onboarding/onboarding-card.tsx
- projects/Mallard/src/components/sign-in-modal-card.tsx
- projects/Mallard/src/components/sub-not-found-modal-card.tsx
Apple are rejecting our builds due to our signup copy violating its guidelines. To unblock us short term, we're removing this copy on iOS. Android remains the same. 
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/128859597-b0829a4d-ba1b-4f37-9818-b390ef7680f2.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/128859173-dbda4a46-4888-46b7-ba18-5f92ce92cc7d.png" width="300px" /> |
| <img src="https://user-images.githubusercontent.com/20416599/128859512-8b53b5a3-46d0-4432-b460-2a4aadd2c161.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/128859165-4245f7b9-adb3-4292-8066-d2a191ba3e21.png" width="300px" /> |
> Live 2913 : Apple Rejection - Remove Signup Copy

- projects/Mallard/package.json
- projects/Mallard/src/components/article/types/article.tsx
- projects/Mallard/yarn.lock
Previously we were rendering shareIcons on all articles regardless of whether or not we were able to share them.
This PR adds a handler for a ping from Editions-Rendering to alert the app that event listeners are present, then returns a ping containing the `platformType` and article share url. Editions-Rendering then hides the icon if no share url is present.
This also fixes the race condition which was effecting the platform specific icon pings.
- add `handlePlatformQuery` function 
- listen for ping from editions
- use different js injection approach
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/129018364-c9be8d24-ced0-416d-ab43-57549c676ad8.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/129018398-46f …
> LIVE-2906: add new logic

- projects/Mallard/src/components/sign-in-modal-card.tsx
Following on from [1845](https://github.com/guardian/editions/pull/1845/files), we are now removing links / callouts to the external subscription page for Android as well as it now violates Google Play policy.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/129198214-87fa6287-d5cc-496c-9dc5-ac64731d10f9.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/129198203-b68cbf8b-f7bd-4fad-aeb3-b95fd4a8520d.png" width="300px" /> |
> LIVE-2880 : Remove external links to subs

- README.md
If s3Read is all that is required we should say that so people don't think they need extra credentials.
> Be more specific about cmsFronts credentials

- projects/Mallard/src/components/sign-in-modal-card.tsx
Apple has rejected our build again due to CTA to external mechanisms to subscribe. To unblock, this PR removes the offending CTA, `Need help signing in?`.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/129533127-89806317-0a31-46f8-9b89-fc41a411f017.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/129533151-3f5c69af-ee47-4c7e-8bda-e92a8a0cb95f.png" width="300px" /> |
> Remove `need help signing in?` button

- projects/Mallard/src/App.tsx
- projects/Mallard/src/components/sign-in-modal-card.tsx
- projects/Mallard/src/helpers/settings/defaults.ts
- projects/Mallard/src/helpers/storage.ts
We introduced some custom logic for beta users during Editions stack migration. We no longer need that and this PR clean up that code.
> Some code cleanup

- projects/archiver/src/tasks/front/index.ts
Crosswords do not need rendered content to render in the apps, rendering happens within the app. 
Test:
I have created a fresh Issue on CODE and crossword works nicely in the app online and offline
https://editions-published-code.s3.eu-west-1.amazonaws.com/daily-edition/2021-07-31/2021-08-13T14%3A54%3A15.125Z/issue
Deploy:
To avoid deploying on Friday we can deploy this on Monday. No problems are expected from this PR.
> Stop request to AR for crossword front

- projects/backend/controllers/render.ts
Design.Correction is derived from a series tag. Previously, Editions BE stripped out the series tag if there was a kicker override. This PR alters the logic to add a new series tag with the overide kicker to the front of the tag array, preserving the original series tag instead of filtering it out.
| --- | --- |
| <img src="" width="300px" /> | <img src="" width="300px" /> |
> LIVE-2937 : Stop filtering out series tags

- projects/Mallard/src/components/article/types/article.tsx
Lightbox logic was crashing the app by incrementing an index where it didn't need to be incremented. In fixing this it flagged another issue where the gallery body images were opening on the index one head of where they should be. As a temporary fix, we are decrementing the index for gallery body images here and keeping all other image indexes as they are when received from AR.
> Decrement if its a gallery body image

- projects/Mallard/src/components/article/types/article.tsx
For parity with the existing production app, the Gallery main image should not open the Lightbox. This is because the Lightbox already contains the main image. As a consequence of this, the gallery image array is out of sync with the article as the article has the header image at index 0. To make sure we open the body images on the correct image, we decrement the body indexes by 1.
> LIVE-2938 : Gallery Lightbox Behaviour

- projects/backend/controllers/render.ts
Sometimes we receive article content from CAPI with an empty `standfirst` field. Editions Production have been used to the `trailtext` field filling this gap, this PR adds `trailtext` as a last resort to the `standfirst` field we pass to AR, behind the `trailTextOverride` (from Fronts tool) and `standfirst` from CAPI.
We're also adding a filter for `standfirst` fields which contain list tags: if a `standfirst` contains a list we want to pass the `trailText` to AR instead.
- add `trailText` to `standfirst` logic.
| --- | --- |
| <img src="https://user-images.githubusercontent.com/77005274/130051696-d9e9c308-5ccd-49cc-8a9f-2a5bc0c4ce55.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/77005274/130051726-dba61eee-0d2e-472b-9f91-813071f9a578.jpg" …
> LIVE-2942: add trail to standfirst

- projects/Mallard/src/components/article/types/article.tsx
Users used to be able to scale the body text in articles by their font size preferences. This reintroduces this by updating font sizes of text inside p tags within the `body-content` .
- Use `PixelRatio.getFontScale()` to access the user defined font scale. 
- inject js to calculate new `font-size` and `line-height` and update all `p` tags within the `body-content` class.
| font size | article font |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/20416599/130638254-81c4fc2d-42a5-434a-b809-65cc6ef4c46f.PNG" width="300px" /> | <img src="https://user-images.githubusercontent.com/20416599/130638240-fbefa310-ba9b-4a69-86c1-d3a767b1b41a.PNG" width="300px" /> | 
| <img src="https://user-images.githubusercontent.com/20416599/130638263-cd30e2a8-2a0a-4cc3-bb52-c6695a308ac4.PNG" …
> LIVE-2973 : Dynamic Font Scaling

- projects/Mallard/src/hooks/__tests__/use-net-info.spec.tsx
- projects/Mallard/src/hooks/use-net-info.tsx
PLEASE NOTE THAT THIS IS A HIGH RISK CHANGE
- The London Bridge problem. You have 4G but you connection is slow or non existent. The user's expectation is for the product to work seamlessly offline however, its inconsistent under these conditions
- Change `isPoorConnection` from being a check of a 2G connection to being a check of a mobile connection in general.
- This impacts authentication and getting the issue summary which it in itself provides us the map to get data. I would recommend that thorough testing and expectations are considered before merging
- We should potentially consider some automation testing around these scenarios to ensure the integrity
> feat: isPoorConnection Update

- projects/Mallard/package.json
- projects/Mallard/src/components/NetInfoDevOverlay.tsx
- projects/Mallard/src/helpers/diagnostics.ts
- projects/Mallard/src/hooks/__tests__/use-net-info.spec.tsx
- projects/Mallard/src/hooks/use-net-info.tsx
- projects/Mallard/src/screens/settings/dev-zone.tsx
- projects/Mallard/yarn.lock
To help us diagnose network issues easier
- Turning on the netinfo button essentially puts the app in network dev mode so we can test use cases for different types of connections
- Update the net info button to give the current network state of the app when on.
- Bottom sheet added to allow for custom net info controls anywhere within the app
- Overrides for network type, isConnected and isInternetReachable. This should help with the "London Bridge" scenario
- Tests to cover the new overrides
- Updated "Download Blocked" logic to take into account the overrides. This function should have tests
- I think more scenarios need testing if we had more time on this PR.
> feat: use net info devmode

- projects/Mallard/src/__mocks__/@react-native-community/netinfo.js
- projects/Mallard/src/hooks/use-net-info-provider/__tests__/utils.spec.ts
- projects/Mallard/src/hooks/use-net-info-provider/index.tsx
- projects/Mallard/src/hooks/use-net-info-provider/types.ts
- projects/Mallard/src/hooks/use-net-info-provider/utils.ts
To move `useNetInfo` from using Apollo to Context to help simplify the code base.
This just produces the Provider and logic which should match the original useNetinfo. 
This is the first PR in a series and this focusses on just the Provider and it's not hooked up to any components yet.
- Refactored the existing netinfo logic to work as a Context hook
- Separated out the functions that perform the logic and fully tested them
- The provider itself as a result is a shell state
- Types are relatively complex and are separated as a result.
> feat: useNetInfoProvider

- projects/archiver/src/services/pub-status-notifier.ts
- projects/archiver/src/services/task-handler.ts
- projects/archiver/test/services/task-handler.spec.ts
Now that there is only 1 editions stack we no longer need to identify which stack a publishing message has come from
> Remove 'mobile account' identifier in publishing logs

- projects/archiver/src/invoke/index.ts
Editions will soon be triggered by an S3 notifification rather than a cloudwatch events rule. This modifies the listener function to support this change
> Remove cloudwatch event conversion logic

- projects/Mallard/android/app/build.gradle
- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/__mocks__/react-native-iap.js
- projects/Mallard/src/authentication/services/iap.ts
- projects/Mallard/yarn.lock
Updating React Native IAP in an attempt to get a release build for Android working.
Please note this requires a firm test on iOS for the next release.
- Updates `react-native-iap` across both platforms
- Adds the required installation step for Anrdoid however, its not used on Android.
> chore: Update React Native IAP

- projects/Mallard/package.json
- projects/Mallard/yarn.lock
Removing node-fetch as it appears to not be used. This should also allow us to close a dependabot PR.
> chore: Remove node-fetch

- projects/Mallard/android/app/build.gradle
- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
- projects/Mallard/ios/Podfile
- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
Enabling Hermes on iOS and Android
https://reactnative.dev/docs/hermes
- Enabling it on both platforms
- Upgrading React Native Gesture Handler
- Disabling Flipper (which is rarely used) due to this issue: https://issueexplorer.com/issue/facebook/react-native/32333
Alerted the following in the screenshots: `https://reactnative.dev/docs/hermes`
> feat: Turn on Hermes

- projects/Mallard/src/components/EditionsMenu/EditionsMenu.tsx
- projects/Mallard/src/components/EditionsMenu/__tests__/__snapshots__/EditionsMenu.spec.tsx.snap
Since upgrading to RN66, we see the following error
- Originally Editions Menu had nested `FlatList`, this move it all into one.
> fix: Editions menu error

- projects/Mallard/package.json
- projects/Mallard/yarn.lock
iOS pipeline seems to be breaking when publishing to github. This looks like its relating to the node module that was removed as it was not used in the project. 
- Put back `node-fetch` as a PR revert was not possible.
> fix: iOS Pipeline github step

- projects/Mallard/src/components/EditionsMenu/EditionsMenu.tsx
- projects/Mallard/src/screens/settings/help-screen.tsx
Due to the upgrade of RN66, we had some issues around nested flatlists. The help menu has this problem.
- Removed the use of `List` for `Row` and `Separator`
| --- | --- |
| <img src="https://user-images.githubusercontent.com/935975/142995447-c6391863-c2ed-4a4a-8188-ac7bcc087fa6.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/935975/142995498-7102d8e3-da7e-4ec6-896c-aceab233a51e.png" width="300px" /> |
> fix: Help Menu Error

- projects/Mallard/src/apollo.ts
- projects/Mallard/src/helpers/location-permission.ts
- projects/Mallard/src/helpers/weather.ts
As part of our move away from Apollo, this removes the need to store the permission result there. It also makes the function a bit simpler.
- Refactored the permission logic to be simpler and closer to the standards of the project
- Removed the location permission resolver.
> chore: Location Permission Refactor

- projects/Mallard/ios/Mallard/AppDelegate.h
- projects/Mallard/ios/Mallard/AppDelegate.m
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
We are currently investigating a drop in push notification registration. The drop seems to have occured in the following time period: https://github.com/guardian/editions/compare/5846cbb1..0971f5ff
One thing that stuck out was a version bump on `react-native-push-notifications`: https://github.com/guardian/editions/commit/7250ebe39347e79ac5ab5108bc4060a8ec91986d
This in itself, looking at the docs says you need to preinstall `@react-native-community/push-notification-ios`: https://github.com/zo0r/react-native-push-notification#ios-manual-installation.
Looking at the installation steps (https://github.com/react-native-push-notification/ios) there were some steps missing in our native iOS code.
- Bumped the underlying push notification library for iOS
- Added in the missing code
> fix: iOS Push Notifications

- projects/Mallard/src/App.tsx
- projects/Mallard/src/helpers/settings.ts
- projects/Mallard/src/helpers/settings/defaults.ts
- projects/Mallard/src/helpers/settings/resolvers.ts
- projects/Mallard/src/helpers/settings/setters.ts
- projects/Mallard/src/helpers/storage.ts
- projects/Mallard/src/helpers/weather-hider.ts
- projects/Mallard/src/hooks/__tests__/use-edition-provider.altlocale.spec.tsx
- projects/Mallard/src/hooks/__tests__/use-edition-provider.spec.tsx
- projects/Mallard/src/hooks/use-config-provider.tsx
- projects/Mallard/src/hooks/use-edition-provider.tsx
- projects/Mallard/src/screens/issue-screen.tsx
- projects/Mallard/src/screens/settings-screen.tsx
- projects/Mallard/src/screens/weather-geolocation-consent-screen.tsx
As part of our ongoing purge from Apollo, this removes the Weather from that particular area of the code.
- Kept the functionality as it was.
- Removed the Weather Apollo implementation and moved the state management to the config provider
- Moved persistence from being set in "settings" and moved to "storage" while maintaining the keys
- Removed the need to emit an event on the home screen to check for Weather
> chore: Remove Apollo from Weather

- projects/Mallard/src/App.tsx
- projects/Mallard/src/helpers/weather-hider.ts
- projects/Mallard/src/hooks/use-config-provider.tsx
- projects/Mallard/src/hooks/use-edition-provider.tsx
- projects/Mallard/src/hooks/use-weather-provider/index.tsx
- projects/Mallard/src/screens/issue-screen.tsx
- projects/Mallard/src/screens/settings-screen.tsx
- projects/Mallard/src/screens/weather-geolocation-consent-screen.tsx
In an attempt to remove the Weather resolver, there was a lot of logic still left over. To move it across would have meant putting it in an already bloated config provider. So it made sense to create a weather provider, move the previous setting changes across ready for the additional logic to come in.
- Move the `isWeatherShown` settings from the config provider to a new weather provider
- Add weather provider to the App
- Update the usage throughout the app
- Added a useCallback on the setting as a minor performance improvement.
This should all work as before.
> chore: useIsWeatherShown refactor

- projects/Mallard/src/authentication/helpers.ts
Currently I am unable to access the developer menu in production as I do not have a guardian email address. This allows access as long as I have a subscription. So this can be easily revoked via a PR or via the subscription platform
- Added my organisation suffix to those that are allowed.
> chore: Enable Dev menu for external organisation

- projects/Mallard/src/helpers/settings.ts
- projects/Mallard/src/helpers/settings/defaults.ts
- projects/Mallard/src/helpers/settings/resolvers.ts
- projects/Mallard/src/helpers/settings/setters.ts
- projects/Mallard/src/helpers/storage.ts
- projects/Mallard/src/hooks/use-article.tsx
- projects/Mallard/src/hooks/use-config-provider.tsx
- projects/Mallard/src/hooks/use-settings.ts
- projects/Mallard/src/screens/home-screen.tsx
- projects/Mallard/src/screens/settings-screen.tsx
- projects/Mallard/src/screens/settings/dev-zone.tsx
Another one on the Apollo cull list to be removed. This setting decides whether or not to show the duck menu
- Shift across `isUsingProdDevTools` across to the context pattern.
N.B: There are some repeating patterns in the config provider now and it's causing a fair amount of duplicate code. Something that needs to be addressed in a follow up PR. Its a good thing as it suggests we are using the config provider to store configuration (i.e. simple switches) so it has that single responsibility.
> chore: Refactor isUsingProdDevTools

- projects/Mallard/src/hooks/use-edition-provider.tsx
The editions endpoint was being requested with an additional `ediitions` due to the function resolving twice, rather than the value being used.
- Use the value
> Fix: Editions Endpoint URL

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/authentication/services/__tests__/iap.spec.ts
- projects/Mallard/src/authentication/services/iap.ts
- projects/Mallard/yarn.lock
Google now enforces the minimum play billing library to be version 3.0 or above. This `react-native-iap` updated library fulfills that requirement.
Needs to adjust some of the tests before we merge @jimhunty
> Updated `react-native-iap` to support minimum google play billing

- projects/Mallard/src/helpers/files.ts
There is a theory that in this piece of code, we were receiving a piece of XML back in the case of a status code that was a 200. So our original check assumed there was an issue summary, however the content was different. This adds in a bit more defensive coding.
- Adds a status check to the function that fetches the issue summary
> fix: Issue Summary Status Check

- projects/Mallard/src/App.tsx
- projects/Mallard/src/hooks/use-issue-provider/index.tsx
- projects/Mallard/src/hooks/use-issue.ts
- projects/Mallard/src/screens/home-screen.tsx
In our effort to move towards a consistent state management solution, this removes the cacheOrPromise set for the menu and moves to a context model.
- Adds in an issue provider. This changes when an issue is either first loaded or changed to.
- Update the menu to maintain its functionality whilst using context.
> feat: Remove cacheOrPromise from menu

- projects/Mallard/src/helpers/fetch/cached-or-promise.ts
- projects/Mallard/src/hooks/use-issue-provider/index.tsx
- projects/Mallard/src/hooks/use-issue.ts
- projects/Mallard/src/screens/article/body.tsx
- projects/Mallard/src/screens/home-screen.tsx
Again to align our state management into one. This removes `cacheOrPromise` state management from the articles and uses the issue hook
- Essentially this adds `getArticle` which does some fetching of data from the issue that is in state.
- Removes some of the `cacheOrPromise` helpers that are now not used.
> Feat: Remove cop from articles

- projects/Mallard/src/screens/home-screen.tsx
Noticed on iPad that the issue changes in the background when you choose a new one. Before the `cacheOrPromise` removal, this wouldnt change until you chose the front.
We will move back to this way but this requires some further investigation around multiple issueIds and also keeping a local one. I also think we can manage how fronts are shown on the menu better.
In the meantime, the current experience is quite slow and looks broken. This change maintains that slowness but makes it look less broken. 
Ideally we dont release until we solve the performance issue, however, this PR at least makes the app releasable. 
- Update the global state when an issue is chosen so that the images load in the background
> fix: Show Image Menu Change (Temporary)

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/authentication/services/__tests__/iap.spec.ts
- projects/Mallard/src/authentication/services/iap.ts
- projects/Mallard/yarn.lock
Reverts guardian/editions#1966
It has been found that IAP doesnt work with this version on a users device, so reverting this PR.
> Revert "Updated `react-native-iap` to support minimum google play billing"

- projects/Mallard/react-native.config.js
This one is a bit of a "Hail Mary". This attempts to disable the installation of the React Native IAP module for Android. This is based on the following links:
https://stackoverflow.com/questions/61939769/ignore-a-react-native-library-for-android-only-when-using-autolinking
https://github.com/react-native-community/cli/blob/master/docs/dependencies.md
> chore: Attempt to disable IAP for Android

- projects/Mallard/src/screens/article/slider/index.tsx
When in preview mode, the buttons at the bottom of the article failed to work. Upon investigation this appeared to be iOS only.
They did not work as they were looking for a FlatList reference. A while ago we moved to the ViewPager only solution and therefore it was updating a reference to something that didn't exist. 
- Removed the FlatList reference
- Allowed all platforms to subscribe to the view pager reference.
> fix: Preview Article Nav Buttons

- projects/Mallard/src/hooks/use-issue-provider/index.tsx
- projects/Mallard/src/screens/article/body.tsx
Users are seeing that the app has crashed when loading. While we are not sure of the issue causing it, it is related to the `getArticle` function as this is the only place that provides the wording that is seen in the screen shots.
Within the function we are throwing errors when we don't have certain pieces of data. But as this data is asynchronous, there will be times when we don't have it (e.g. a slow connection). 
So rather than throwing, we now set an error inside the article with the retry button. This means the whole app doesnt fall over, but just the article section. This may lead to new complaints around not being able to read articles in certain circumstances, but we need to find out what those are.
The logic in this function needs to be looked at in more detail
> fix: Stop throwing in article

- projects/Apps/common/src/index.ts
- projects/Mallard/src/screens/issue-screen.tsx
Production are complaining that scroll position is moving around. I have noticed if we scroll during the initial load, the issue screen will scroll back to the top.
We memoise the data used for this screen, but one of the conditions whether to run this again is an array of objects. In other projects I have seen this be ignored as it doesn't seem to do a deep equal. In our case perhaps there is a change of reference here (something to check out).
For the time being I have pushed that check down to what I believe is a uuid on the first front in the edition.
- Update memoised value based on the first fronts uuid
- Add this as a type in the common types
> fix: Prevent Scrolling on load

- projects/Mallard/src/hooks/use-issue-provider/index.tsx
- projects/Mallard/src/screens/issue-screen.tsx
Allowing the app to restart when the reload button is pressed in preview, to aid with memoisation issues.
> fix: Alternative Reload Button Fix

- projects/Mallard/src/hooks/use-issue-provider/index.tsx
- projects/Mallard/src/screens/issue-screen.tsx
Looks to fix the preview issue reloading.
The thinking behind it... When the API Url changes, or the edition changes, it would not **force** an update from the API. This will now do this. The code is a bit duplicated here, but I wanted to keep it verbose to be easier to read as the fetching is already fairly abstracted.
We will always look to the file system first when someone changes their issue within an edition as this shouldn't require a new fetch.
The restart on the reload button has been removed as this is what takes you to the latest edition. 
- Force fetch from the API in API Url change and Edition change scenarios
- Remove full app restart from retry button
> Fix: Issue reloading

- projects/Mallard/src/hooks/use-issue-provider/index.tsx
When you have a downloaded edition, and you are reading an article, if the you go offline, you cannot read the articles anymore as you are shown an error.
This PR fixes this.
However, this is not the most optimal solution. It fixes the biggest issue of offline reading, however, if you go from online to offline and you are reading an article, and its not downloaded, it will disappear, even though you had it before. I think this can be solved with more fine grained control, but was keen to fix the bigger issue first.
- Added `isConnected` check to the issue provider so that we can force a change to the `origin`
> fix: Offline Articles

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/src/hooks/use-edition-provider.tsx
- projects/Mallard/src/hooks/use-issue-provider/index.tsx
- projects/Mallard/src/hooks/use-issue-summary-provider.tsx
This fixes a number of issues:
1. When going from UK to Aus to UK edition, it would not load the last edition.
2. Event emitter being called but nothing listening to it
3. Conditionally fetching the issue when the API url changes.
1. In the issue summary provider, moved the `selectedEdition` condition on its own so that it doesn't conditionally try and fetch. Essentially this was causing a race condition where the app would fetch and then block via `isLoading`. This change means that we do the logic without any blocking.
2. Event emitter removed. This was used in the old `CacheOrPromise` and is now not used.
3. In the issue, removed the need to fetch when the edition changes. This is because the id changes when we choose a new edition, which in turn causes a fetch of the issue. So it was …
> fix: Changing Editions

- projects/Mallard/src/hooks/use-issue-provider/index.tsx
- projects/Mallard/src/hooks/use-issue-summary-provider.tsx
- projects/Mallard/src/screens/issue-screen.tsx
When pressing reload, nothing would happen. It now shows changes as a result of this change. 
- Force the issue summary to be fetched as part of the reload process. Otherwise when you added a new issue, it wouldn't show.
- Removed the memoisation on the Issue Screen and the data manipulation for the fronts. As a result, overall performance of the app will drop. However, we have a point at which to improve on.
> Fix: Production reload issues

- projects/Mallard/src/screens/issue-screen.tsx
Currently when the reload button is pressed, the production user is taken to the latest issue. This hack maintains the previous point of navigation the user was on and navigates back to it.
Its a hack because we should really be managing the state and rerenders better so that the whole issue isnt realoaded.
- Get the latest route before reloading and then navigating back to that route.
> fix: Reload Hack

- projects/Mallard/src/screens/editions-menu-screen.tsx
When opening the sidebar and changing orientation, it would often disappear.
Essentially the width values were being calculated outside the component, so brought them inside so that they are recalculated on rerender which happens when the orientation changes. 
- Move styles inside component so they recalculate on rerender
> fix: Menu orientation issue

- projects/aws/editions-buckets.yaml
Recently the 1001st issue of the Daily Edition was previewed but then broke preview.
Old editions could be updated and previewed, but new editions didn't appear in the list of available issues to preview because we can't read beyond 1000 in part of the production chain.
To mitigate this issue from happening again this change puts an expiration policy on objects in the s3 buckets.
I chose 365 days as the expiration policy but let me know whether we think that is too long/short.
Also, the cloudformation of the buckets lives outside of cdk. I wasn't sure whether it was worth moving this stack into cdk, for now I've just updated the existing cloudformation yaml.
- Set lifecycle configuration rule for the proofed and published buckets
N/A
> Delete objects in s3 older than 1 year

- projects/backend/controllers/render.ts
One of the pain points of the edition workflow has been knowing what standfirst will appear on both a front and an article. The editions team identified a specific problem:
- Composer piece has both a standfirst and a trail
- Editions fronts tool allows the production team to override the trail text
- Trail override appears on the front, original standfirst appears on the article
The editions team would like more consistency in this approach:
- Composer piece has both a standfirst and a trail
- Editions fronts tool allows the production team to override the trail text
- Trail override appears on the front and on the article
- If no override is made to the trail text in the editions fronts tool then both the front and the article should display the trail text (not the standfirst defined in …
> Reorder standfirst override

- projects/Mallard/src/components/front/collection-page.tsx
- projects/Mallard/src/components/front/index.tsx
Previously the card used to animate out to the article screen. This was removed to simplify the code going forward for maintenance mode.
This is some leftover calculations that are not needed.
- Remove the animation code in the Collection wrapper
- Tidy up types
> chore: Removal of Front Animations

- projects/Mallard/src/screens/home-screen.tsx
- projects/Mallard/src/screens/issue-screen.tsx
If you are an Tablet user (as most of our users are) and you are looking at the list of issues, by default it gives you 7. If you have this set to 14 or 30, you are in portrait mode, and you cold start the app, you will see 7 and then have to scroll slightly for the rest to load.
This change sets the initial number to the users setting. If they have not changed it, it already defaults to 7.
- Add `maxAvailableEditions` to the initial number rendered in the menu FlatList.
> chore: Max Editions UX improvement

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/components/front/image-resource.tsx
- projects/Mallard/yarn.lock
Fast Image is a library that will do some native caching of images and make virtualised lists of images load a lot... faster
https://github.com/DylanVann/react-native-fast-image
This has been attempted a few years ago, however, the library didnt cope well with locally stored images. This appears to have been resolved
- Implemented `FastImage` into the `ImageResource` component.
> feat: Fast Image

- projects/Mallard/src/components/front/index.tsx
- projects/Mallard/src/screens/issue-screen.tsx
Improve the Issue Screen (Home) Performance
Each time the Flatlists re-render, they were having to recreate the functions that they were using. These have been brought outside of the render so they should only be created once. In the cases where the function doesn't need to be recalculated each time, I have added optimisations to them.
Please note: Some of the types here are a bit funky. Would be worth looking at these as a maintenance task.
> chore: Issue Screen Flatlist Performance

- projects/Mallard/src/screens/issue-screen.tsx
This puts back the optimisation that was removed as it was causing the production team a lot of bother. This work around dramatically reduces re-renders for users and improves performance, whilst still giving the Production team flexibility over viewing content.
- Bring the changes back and store a memoised value. Only use this value outside of Preview.
- In preview mode, do no memoisation
> Fix: Issue Screen perf

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/patches/react-native-pager-view+5.4.24.patch
- projects/Mallard/src/screens/article/slider/index.tsx
- projects/Mallard/yarn.lock
When scrolling through articles on Android, users tend to accidentally scroll to the next article rather than scroll down the article. This is an issue with ViewPager2 in Android.
This is a fix to help reduce the sensitivity as described in this PR: https://github.com/callstack/react-native-pager-view/issues/164#issuecomment-965032619
Tested on Simulator and device. It seems better, but could be done with being tested on an Android tablet.
- Update the Viewpager to the latest
- Add `patch-package` and apply the appropriate patch
> fix: Android ViewPager Sensitivity

- README.md
`gu-strap` has been deprecated and we ask folk to use plain `strap` and install the gu dev tools from Homebrew themselves.
Updates the `README.md`
[Preview link](https://github.com/guardian/editions/blob/update-setup-instructions/README.md)
> Update setup instructions to reflect gu-strap deprecation

- projects/Mallard/src/hooks/use-issue-summary-provider.tsx
On Android, the connection value seems to default to false on first load. This meant we tried to fetch the issue summary when there was "no connection" and as its the first install, there was no issue summary on the device.
The `isLoading` was then subsequently blocking the attempt to get a new issue summary when the connection value became `true`. Therefore it became stuck.
- Remove the loading from the function that gets issue summary and manages its state
- Make sure loading doesn't affect the initial render
- Apply loading only to scenarios where external changes happen. Not too worried about blocking here as we should always have a stored issue summary in this instance.
> fix: Android first load

- projects/Mallard/package.json
- projects/Mallard/src/AppNavigation.tsx
- projects/Mallard/src/components/Button/Button.tsx
- projects/Mallard/src/components/front/image-resource.tsx
- projects/Mallard/src/components/front/index.tsx
- projects/Mallard/src/helpers/platform.ts
- projects/Mallard/src/helpers/words.ts
- projects/Mallard/src/navigation/NavigationModels.tsx
- projects/Mallard/src/screens/external-subscription.tsx
- projects/Mallard/src/screens/issue-screen.tsx
- projects/Mallard/yarn.lock
To allow iOS devices under iOS 16 to see the External Subscription modal required for Reader Apps.
- Add the modal based on the iOS specification
- Add the modal into the navigation.
- Updated the React Native types to take into account the `colourScheme` hook
> feat: External Subscription Modal

- projects/Mallard/ios/Podfile.lock
This PR: #2090 updated the Webview package but didnt update the associated Podfile.lock
I found this while investigating my build issue. However, it has not fixed it.
> chore: Missing update to Podfile.lock

- projects/Apps/ophan/build.gradle
To fix the build locally and in CI. Essentially I believe the last release had dependencies that have now deprecated to such a degree that it caused the build to fail.
- Update multiplatform Ophan version to 0.2.0
> chore: Upgrade the Ophan version

- projects/Mallard/src/screens/issue-screen.tsx
Production team reported that when a Crossword front is created without any data in, it would cause the app to crash. On further investigation @groakland saw that this was due to "empty cards".
Testing this hypothesis locally I can confirm this is the case and that the following fix solves this issue.
- Render null Fronts if there are no cards
> fix: Empty Cards causing crash

- projects/Mallard/src/helpers/words.ts
- projects/Mallard/src/screens/settings/subscription-details-screen.tsx
Removing the heading on the subscription details pages as requested
> chore: Remove subscription details headings

- projects/Mallard/src/helpers/words.ts
Changes the error wording when an Article cannot be retrieved
> chore: Error wording

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Bump to 9.10 for iOS to get ready for the next release
> chore: 9.10 bump

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/components/EditionsMenu/EditionsMenuButton/__tests__/__snapshots__/EditionsMenuButton.spec.tsx.snap
- projects/Mallard/src/components/Lightbox/__tests__/__snapshots__/LightboxCaption.spec.tsx.snap
- projects/Mallard/src/components/ScreenHeader/IssueScreenHeader/__tests__/__snapshots__/IssueScreenHeader.spec.tsx.snap
- projects/Mallard/src/components/icons/__tests__/__snapshots__/AppLogo.spec.tsx.snap
- projects/Mallard/src/components/icons/__tests__/__snapshots__/BurgerMenu.spec.tsx.snap
- projects/Mallard/src/components/icons/__tests__/__snapshots__/Editions.spec.tsx.snap
- projects/Mallard/src/components/icons/__tests__/__snapshots__/EditionsMenu.spec.tsx.snap
- projects/Mallard/src/components/icons/__tests__/__snapshots__/Newspaper.spec.tsx.snap
- projects/Mallard/src/components/icons/__tests__/__snapshots__/Quote.spec.tsx.snap
- projects/Mallard/src/components/icons/__tests__/__snapshots__/SettingsCog.spec.tsx.snap
- projects/Mallard/yarn.lock
Reverts guardian/editions#2126
Currently quote marks are showing incorrectly on Fronts. Reverting back removes the issue. However, the issue still needs to be fixed forward, but this can get us to release.
> Revert "chore: Update React Native SVG"

- projects/Mallard/src/screens/article/slider/index.tsx
ViewPager on Android was reverting back to position one after it had loaded. This fixes that and replicates code that was originally removed. Performance seems better for it as well.
> fix: Initial Load of View Pager on Android

- projects/Mallard/src/screens/article/slider/index.tsx
Small change to update the number of max items rendered per batch. Unlikely to have too noticeable an effect, but worth a try.
> chore: Minor Flatlist optimisation

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
Reinstated Masked View, which is a requirement for React Navigation 5. This was previously removed as it was seen to be being not used.
This is being reinstated due to a few crashes happening around Reanimated which is a dependency of React Navigation.
> fix: Reinstate Masked View

- projects/Mallard/src/screens/article/slider/index.tsx
Reinstates `getItemLayout` which was lost due to some poor branching. This fixes the crash when selecting an article at the bottom of the fronts
> fix: Article Slider

- projects/Mallard/src/screens/article/slider/index.tsx
Lower powered devices appear to be having a worse experience with the new slider than the old. This change will move those lower powered devices to use the old slider
If this does not achieve the desired effect, we may need to change the threshold on what is considered lower powered.
> chore: Lower Powered iOS devices Article Slider

- projects/Mallard/package.json
- projects/Mallard/src/components/issue/issue-row.tsx
- projects/Mallard/src/helpers/files.ts
- projects/Mallard/yarn.lock
`Please report: Excessive number of pending callbacks: 501` warning is showing when accessing the menu. This is due to each edition being checked if their associated folders exist. This shows the "download complete" indicator if correct.
The warning results in worse performance (and possibly crashes?) so this reduces the number of async calls by a factor of 5. It does make an assumption on folder structure, which is not what we have done elsewhere, however, due to the maintenance state of the project, file locations are unlikely to change and therefore the performance benefit outweighed the desire for more maintainable code.
- Updates circular progress
- Make one async request instead of 5 per edition and use JS to determine the folder's existence
> fix: Please report: Excessive number of pending callbacks: 501

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/App.tsx
- projects/Mallard/src/constants.ts
- projects/Mallard/src/helpers/rate.ts
- projects/Mallard/src/helpers/storage.ts
- projects/Mallard/src/hooks/use-rating.tsx
- projects/Mallard/src/screens/article/slider/index.tsx
- projects/Mallard/src/screens/settings/dev-zone.tsx
- projects/Mallard/src/services/remote-config.ts
- projects/Mallard/yarn.lock
Based on a number of interactions (article views in our case) reaching a particular threshold (5), an action sheet will be shown giving three options:
1. Rate the app, which when clicked on shows the native modal. This will only show 3-4 times per user and if it fails, the user should be taken to the App Store/Play store
2. Remind the user later, essentially resetting the number of interactions.
3. Dont remind the user, disabling the functionality.
This is all behind a remote feature flag in Firebase.
Tooling has been added to the dev zone to aid with testing and expectations.
- Rating and Action sheet, along with their native dependencies, added to the project. Action Sheet required a top level provider
- Remote Feature Flag added
- `useRating` hook added with additional exports to be …
> feat: Rating in background

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/components/EditionsMenu/EditionsMenuButton/__tests__/__snapshots__/EditionsMenuButton.spec.tsx.snap
- projects/Mallard/src/components/Lightbox/__tests__/__snapshots__/LightboxCaption.spec.tsx.snap
- projects/Mallard/src/components/ScreenHeader/IssueScreenHeader/__tests__/__snapshots__/IssueScreenHeader.spec.tsx.snap
- projects/Mallard/src/components/icons/__tests__/__snapshots__/AppLogo.spec.tsx.snap
- projects/Mallard/src/components/icons/__tests__/__snapshots__/BurgerMenu.spec.tsx.snap
- projects/Mallard/src/components/icons/__tests__/__snapshots__/Editions.spec.tsx.snap
- projects/Mallard/src/components/icons/__tests__/__snapshots__/EditionsMenu.spec.tsx.snap
- projects/Mallard/src/components/icons/__tests__/__snapshots__/Newspaper.spec.tsx.snap
- projects/Mallard/src/components/icons/__tests__/__snapshots__/Quote.spec.tsx.snap
- projects/Mallard/src/components/icons/__tests__/__snapshots__/SettingsCog.spec.tsx.snap
- projects/Mallard/yarn.lock
As recommended by the Snyk report.
This was previously attempted, however, there was an issue with quote marks. I have upgraded this today and the quotes appear to be the same as in Production. Please see screenshots below.
Here was the previous revert: #2145
- Upgraded React Native SVG
- Updated Snapshots
> chore: Upgrade React Natve SVG

- projects/Mallard/src/screens/article/slider/index.tsx
Makes the time to stop scrolling faster on an article after a user complained about "settle time"
- Adds a fast deceleration rate.
> chore: Article Scroll stop faster

- projects/Mallard/src/helpers/files.ts
`every` is returning `true` when no folders exist. Therefore during the error that I experienced yesterday, I was not able to attempt to download again, or default back to the API.
This change fixes it
- Adds an empty check
> Fix: Download Tick showing when no folders present

- projects/Mallard/src/hooks/use-net-info-provider/index.tsx
The majority of users on a cold start are online. As a result, we change the default state to match this. This reducers the number of re-renders setting state for something we already know about.
- Update net info default state
> chore: Assume Online

- projects/Mallard/src/components/article/types/article.tsx
- projects/Mallard/src/hooks/use-image-paths.ts
- projects/Mallard/src/hooks/use-issue-provider/index.tsx
- projects/Mallard/src/screens/home-screen.tsx
React struggles to understand what has changed with objects in the dependency arrays in `useEffect` and `useCallback`. By defining the properties, we give React more information and it reduces the number of unnecessary re-renders.
- Broken down `issueId` into its subsequent parts in dependency arrays.
> chore: Issue Id Effects

- projects/Mallard/src/hooks/use-config-provider.tsx
As we are not supporting iOS9 devices anymore, and that the original setting was 4 years ago, we can safely assume that the majority of devices accessing the app have over 1GB of memory. As a result i've updated the default state which will mean one less state change for the majority of users.
> chore: Assume Large memory

- projects/Mallard/src/helpers/storage.ts
Logging was removed a while ago, but the cache remained. This removes it.
> chore: Remove Logging Cache

- projects/Mallard/src/hooks/use-issue-summary-provider.tsx
Focusses just on the edition key changing rather than attempting to detect changes in the entire editions object.
> chore: Issue Summary Edition Perf

- projects/Mallard/fastlane/Fastfile
In our last App Submission, we were told:
`ITMS-90725: SDK Version Issue - This app was built with the iOS 16.0 SDK. Starting April 2023, all iOS apps submitted to the App Store must be built with the iOS 16.1 SDK or later, included in Xcode 14.1 or later.`
- Updates Xcode in Fastlane based on the info here: https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#xcode
> chore: Update Xcode Version

- projects/backend/capi/articles.ts
Correct the logic that filters scheduled content. We don't think we should be relying on the existing schedule date to determine what value '30 days in the future' should be.
Just the one, as above.
N/A
> Correct schedule filter logic

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
XCode 14.3 causes a bug in our version of React Native which causes it not to build. More information available here: https://github.com/facebook/react-native/issues/36739
Builds locally as expected with the patch version bumped.
- Bumped the patch version
> Fix: XCode 14.3 Fix

- projects/Mallard/src/hooks/use-issue-summary-provider.tsx
"When reading an edition from the past (let’s say yesterday’s edition) and you follow a link outside the app , when you return to the edition you were in then you get ‘page not found’.
Retry does nothing and when you try to get back to page view using the down arrow at the top of the screen it throws you back to today’s edition. You then have to navigate your way back to where you were."
- Coming from the background gets the latest issue summary but also sets the latest issue id and front key. This causes the refresh and the break to the users reading flow. This change allows the user to get the latest issue in that (and other edge case scenarios) without setting the issue. This makes it available from the menu without interrupting the user.
> fix: Issue change when going to the background

- projects/Mallard/src/App.tsx
- projects/Mallard/src/components/issue/issue-row.tsx
- projects/Mallard/src/components/sign-in-modal-card.tsx
- projects/Mallard/src/helpers/analytics/__tests__/index.spec.ts
- projects/Mallard/src/helpers/analytics/index.ts
- projects/Mallard/src/helpers/analytics/types.ts
- projects/Mallard/src/navigation/helpers/base.tsx
- projects/Mallard/src/screens/article/slider/index.tsx
- projects/Mallard/src/screens/issue-screen.tsx
- projects/Mallard/src/screens/settings/manage-editions-screen.tsx
- projects/Mallard/src/services/__tests__/ophan.spec.ts
- projects/Mallard/src/services/ophan.ts
As we are bringing in Firebase Analytics, it seems prudent to abstract Ophan under Analytics so we can use the same methods for both.
This aims to define and test an API that will be compatible for both and apply it throughout the code where it has been previously.
- New Analytics abstraction and test suite
- Convert Ophan to promise based architecture to actually match what is happening in the module.
- Apply abstraction throughout the code base
> feat: Ophan Abstraction

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
I noticed last week that there was a patch version of React Native so I have updated that based on the following: https://react-native-community.github.io/upgrade-helper/?from=0.70.8&to=0.70.9
- Updated `package.json`
- Updated lock files
> chore: Update React Native to 0.70.9

- projects/Mallard/src/screens/article/slider/index.tsx
On Android, when selecting an article, it occasionally goes to the top article. This is doe to a bug in the Android View Pager package we use.
However, there is currently no fix for it. Due to the use of a Webview inside the slider, we cannot use Flatlist due to inconsistent scrolling. There is also no other alternative.
As a result the following fix has been made.
- Checks to see if its the first article chosen and forces the article chosen to be navigated to.
| --- | --- |
| <img src="https://github.com/guardian/editions/assets/935975/145bc188-591f-4b1b-9af9-0ea19319ff2e" width="300px" /> | <img src="https://github.com/guardian/editions/assets/935975/32fd7a22-34fc-44cf-ba8a-c3db355a2302" width="300px" /> |
> fix: First article press navigates correctly

- projects/Apps/crosswords/package.json
- projects/Apps/crosswords/scripts/bundle-html.js
- projects/Apps/crosswords/webpack.config.js
- projects/Apps/yarn.lock
Bundling of Crosswords was failing when running in Node 18. This is because the `stderror` was outputting a non error causing the process to stop.
Also, the older versions of the dependencies didn't meet certain security requirements (around an SSL bug) and was causing the bundling to error.
- Update dependencies
- Remove stderror
> fix: Bundle Crosswords for Node 18

- projects/Mallard/android/app/src/main/java/com/guardian/editions/MainApplication.java
Removes the debugger we added the other day as I feel that Crosswords should be fixed and having the debug on by default feels like an "open window"
> chore: Remove Android debug Webview

- projects/Mallard/src/hooks/use-rating.tsx
Noticed the ratings hook used Sentry direct rather than through the abstraction. 
- Removes the direct call to Sentry and calls the abstracted `captureException` instead
> chore: Use error service instead of Sentry direct

- build_apk.sh
With the new WAF rules, we are unable to update the Editions Android TeamCity build pipeline. When attempting to update the Build APK step, the size of the POST request is too large. Therefore, as advised by DevX, this configuration step should be migrated to an external bash script and then called from TeamCity. This PR introduces a new build_apk.sh script which allows us to deploy the APK to either BETA or RELEASE channels dependent on the supplied argument
Original android-beta-deploy Build Step:
```
#!/usr/bin/env bash
npm cache clean -f
npm install -g n
n 16.16
PATH="$PATH"
echo "NEW NODE VERSION"
node --version
npm install -g yarn npx --force
cd projects/Mallard
make beta-android
```
The original android-release-deploy Build Step:
```
#!/usr/bin/env bash
npm cache clean -f
npm …
```
> Create external shell script for building the Android APK using TeamCity

- projects/Mallard/src/helpers/settings/defaults.ts
- projects/Mallard/src/hooks/use-gdpr.tsx
- projects/Mallard/src/screens/settings/gdpr-consent-screen.tsx
- projects/Mallard/src/services/remote-config.ts
Final cleaning up of Logging. Due to the mention of Logging on the GDPR screen, we need to ask for consent again when a user updates the app. This will happen automatically.
> chore: Further Logging Cleanup

- projects/Mallard/package.json
Remove handlebars from the Mallard project, which is not being used.
This resolves this critical dependabot warning: https://github.com/guardian/editions/security/dependabot/65
> chore: Remove Handlebars

- projects/Apps/crosswords/package.json
- projects/Apps/crosswords/webpack.config.js
- projects/Apps/yarn.lock
This looks to resolve a large number of vulnerabilities. 
- Updated Webpack config using this migration guide: https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md
- Updated the packages to latest
- Tested that crosswords still work locally.
> chore: Update Webpack in Crosswords

- projects/Apps/common/package.json
- projects/Apps/common/src/logging.ts
- projects/Apps/yarn.lock
1.  Looking to resolve this security issue which is from an old Sentry package: https://github.com/guardian/editions/pull/2059
2. Logging is on the way out
3. Package is only used for a type, so recreated it and updated the file not to break everything.
> Chore: Remove Sentry from Common

- projects/Mallard/package.json
- projects/Mallard/src/hooks/__tests__/use-edition-provider.spec.tsx
- projects/Mallard/src/services/__tests__/content-auth-service.spec.ts
- projects/Mallard/yarn.lock
`fetch-mock` hasnt been updated in around 3 years and contains vulnerabilities. Its not required for what we do. To remove it we do have to sacrifice a test. Looking at that test, I don't feel it offers much value
> chore: Remove fetch mock

- projects/Mallard/ios/Podfile.lock
Error =  `It seems like you've changed the version of the dependency `hermes-engine` and it differs from the version stored in `Pods/Local Podspecs`.
You should run `pod update hermes-engine --no-repo-update` to apply changes made locally.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [beta-ios] Error 1
Error: Process completed with exit code 2.`
After cleaning out my Pods, this error appears. This PR updates the `Podfile.lock` to take into account the update to React Native
> chore: Hermes Pod fix

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/components/article/types/article/webview.tsx
- projects/Mallard/yarn.lock
Standard dependency update as it was a couple of major versions out of date
> chore: Update React Native Webview

- projects/Mallard/src/components/EditionsMenu/EditionsMenuButton/EditionsMenuButton.tsx
- projects/Mallard/src/components/EditionsMenu/EditionsMenuButton/__tests__/__snapshots__/EditionsMenuButton.spec.tsx.snap
- projects/Mallard/src/components/ScreenHeader/IssueScreenHeader/IssueScreenHeader.tsx
- projects/Mallard/src/components/ScreenHeader/IssueScreenHeader/__tests__/__snapshots__/IssueScreenHeader.spec.tsx.snap
- projects/Mallard/src/services/remote-config.ts
Due to Australia Edition being discontinued, we are experimenting disabling the edition button to test the appetite 
- Add the feature flag to remote config setup
- Apply that to the Issue Screen Header
- Add disabled prop to Editions button to make it not give a clickable feedback.
> feat: FF to disable the editions button

- projects/Mallard/src/components/front/image-resource.tsx
- projects/Mallard/src/components/front/items/items.tsx
Cover Card Images on Android are extremely zoomed in.
- FastImage seems to be the cause here. There seems to be some need to rerender, but with the complexities of our image caching, flipping this to React Native's Image solves the problem
- However, `ImageResource` controls image on all the Cards, so we limit this to just Android Cover Cards.
> fix: Android Cover Card Images

- projects/Mallard/src/components/Modals/SignInModal.tsx
Fix the break when a user tries to sign in via the crosswords
- Instead of taking the user back to the Article when they choose to sign in, we take them back to the issue screen. Does mean once they log in, they will need to find the article they want to read again, but the front should be in the same place.
> fix: Crossword Sign In Crash

- projects/Mallard/src/download-edition/prepare-and-download-issue.ts
Testing in production, we seem to kick off a download for todays edition on open. But we are also kicking off cleanup tasks, including the download folder.
The clean up tasks should happen, then the download, but despite the async code, they are happening synchronously.
As a result, I have added a 5 second delay before the download kicks off. Which I think will reduce the problem, but on slower devices, this may not solve it.
Need to look at the libraries and why they are not working async.
- Delay added to Download today.
> feat: Today download delay

- projects/Mallard/fastlane/Fastfile
iOS build has been failing due to 
`fastlane An attribute value has invalid phone number. - The format of the phone number is invalid - contactPhone`
The suggestion is that the format is invalid
- Change the phone number to international format
> fix: Update phonenumber to fix iOS build

- projects/Mallard/src/hooks/use-okta-sign-in.tsx
Okta plugin appears to not work on older Android devices. Despite the support level.
- Push users on less than Android 8.1 to use subscriber id
> fix: Older Android Okta Sign in

- projects/Mallard/src/notifications/push-tracking.ts
- projects/Mallard/src/screens/settings/dev-zone.tsx
Make it easier to see notifications received that have been stored in the Push Tracking
- Looks through Push Tracking persisted data and just displays that as per the screenshot below.
> chore: Notifications in Dev Menu

- .github/workflows/android-beta.yml
- projects/Mallard/fastlane/Fastfile
This PR disables the skip_upload_apk option in fastlane to start uploading beta builds to the play console.
We had to introduce a workaround to make it work though. We started getting this error [in the logs](https://github.com/guardian/editions/actions/runs/6220846084/job/16881668455)
```
[10:06:57]: Google Api Error: Unauthorized - Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.
```
And it turns out this is actually a problem with the google API, as reported here:
https://github.com/fastlane/fastlane/issues/21507
Fastlane just shipped update 2.215.1 [with a workaround]( https://github.com/fastlane/fastlane/pull/21518) …
> Ship first android beta from GHA

- projects/Mallard/fastlane/Fastfile
We intend to ship a production version on Wednesday, and this change is a pre-requisite for that.
> Allow apks to be uploaded to the release track in the play store

- .github/workflows/validate-app.yml
We're using versions of these actions that are deprecated, and I think may have contributed to some occasional failures we've been getting, like this one https://github.com/guardian/editions/actions/runs/6186617779
> Bump github actions versions

- projects/Mallard/src/helpers/rate.ts
Adds the Amazon package name to the Rate options
> chore: Amazon Package name for Rate

- projects/Mallard/src/helpers/files.ts
- projects/Mallard/src/helpers/storage.ts
- projects/Mallard/src/screens/settings/dev-zone.tsx
Moves the Issue Summary from the file system to async storage to improve reliability.
- Create Async Storage cache
- Replace file system approach with Async Storage
- Added a button to manually clear cache in dev menu
> feat: Move Issue Summary to Async Storage

- projects/Mallard/src/download-edition/download-and-unzip.ts
- projects/Mallard/src/helpers/files.ts
The current theory as to why users see a blue tick, but the downloaded issue doesnt show, is that due to the unreliability of `async...await` in the RNFS library, we are downloading the data package and then clearing it before its had a chance to unzip.
- During the download script, check if the data package files are there. If at the end they are not then download again.
- Update the check to take a param of files.
> fix: Reattempt Data Download

- projects/Mallard/src/download-edition/download-and-unzip.ts
Currently the existence of issues on device is tightly coupled to a piece of internal state and listeners around downloading. To update state, we would need to check everytime the menu is open which would hamper performance.
We know at the moment that sometimes when a download completes, it appears that the data.zip doesnt appear to have been unpacked into the issue folder. 
As a result, I have added an additional check at the end of a successful download, that double checks the issue folder that everything is in there as expected.  This is essentially a silent fail check.
- Checks the filesystem at the end of a download
- Updates the listeners which control the "tick" dependent on how successful that download is
We hope this gives a more accurate view of what has downloaded.
A further …
> chore: Final Download Check

- projects/Mallard/package.json
- projects/Mallard/yarn.lock
Initiall to resolve: https://github.com/guardian/editions/security/dependabot/329. Which is a dependency of `jsdom`.
This was added as a resolution to something we dont use anymore. The other type resolutions have been updated and are no longer used. Therefore they are all removed.
- Removed resolutions
- Quick smoke test on iOS and all appears to be working
> chore: Remove Mallard Resolutions

- projects/Mallard/package.json
- projects/Mallard/yarn.lock
Update `patch-package` to remove its `semver` vulnerability
Please note the `semver` vulnerability is in the latest version of a lot of core libraries and therefore wont be resolved as a result of this PR
- Updated `patch-package`
- Package is successfully patched
> chore: Bump Patch Package

- projects/Mallard/package.json
- projects/Mallard/yarn.lock
Originally to remove this vulnerability: https://github.com/guardian/editions/security/dependabot/283
However, it appears the `aws-sdk` dependency is not used.
- Remove `aws-sdk` from Mallard
> chore: Remove AWS SDK from Mallard

- package.json
- yarn.lock
Initial to resolve this vulnerability: https://github.com/guardian/editions/security/dependabot/268
However I noticed a number of dependencies that dont appear to be used in the top level `package.json`. So they have been removed.
- Remove dependencies
- Ran validate scripts and they all passed
> chore: Remove top level unused dependencies

- projects/backend/yarn.lock
To fix this vulnerability: https://github.com/guardian/editions/security/dependabot/333
- Reinstall `chai` to pick up the patched deep dependency of `get-func-name`
- Tests pass
> chore: ReDoS fix

- projects/archiver/package.json
- projects/archiver/yarn.lock
- projects/backend/package.json
- projects/backend/yarn.lock
Update Moment to solve this vulnerability: https://github.com/guardian/editions/security/dependabot/136
- Update Moment in backend and archiver
Tests still pass
> chore: Update Moment

- .github/workflows/amazon-release.yml
A fix for the Amazon release where it looks to just install the `Mallard` project rather than the whole ecosystem
- Install `Mallard` only
> fix: Amazon Release

- .github/workflows/snyk.yml
Snyk is currently failing with 
```
Server returned unexpected error for the monitor request. Status code: 413
```
Which means
```
The HTTP 413 Content Too Large response status code indicates that the request entity is larger than limits defined by server;
```
I'm not sure exactly what the root cause is for this, but I think it's related to `snyk monitor` picking up around 85 independent projects in this repo, many of them from the android app. It points towards snyk not understanding how to scan the android app properly, and not being able to discern what are actual independent projects and just dependencies included by the main project.
This patch forces `snyk monitor` to not scan anything in the Mallard folder. Ideally we would just ignore android as I believe it's the source of the …
> Exclude Mallard to get snyk to work

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/authentication/services/iap.ts
- projects/Mallard/src/screens/in-app-purchase-screen.tsx
- projects/Mallard/yarn.lock
Goole Play's billing library V4 is being decommissioned and as a result, apps containing it need to remove it.
In App Purchase in this app is a legacy feature and was only available on iOS. No new subscriptions are sold in this way. Therefore the IAP functionality is iOS only.
As a result, this is difficult to test and has not been updated for a long time. However, the situation above forces our hand.
- Update the IAP library to the minimum version (9). From https://www.npmjs.com/package/react-native-iap : `Version 9.0.0 The module migrates android sdk to play billing library v5.`
- Needs to be tested n Beta
> chore: Upgrade react-native-iap to minimum version

- projects/Mallard/src/components/issue/issue-row.tsx
- projects/Mallard/src/download-edition/__tests__/download-and-unzip.spec.ts
- projects/Mallard/src/download-edition/download-and-unzip.ts
- projects/Mallard/src/helpers/words.ts
When a download fails, it does so silently, and then gives the user feedback that is was successful. This PR checks at the end of a download that we have everything we need, and if we dont, uses the `toast` to let the user know of the failure. The "blue tick" is not shown in that instance
- Check at the end of the download
- Download promise returns a boolean to dictate its success state
- Toast functionality added for failure, with some wording
- Test updated to reflect the promise change
Both of these have a forced failed in the code to replicate a particular part of the download not unzipping as expected.
| --- | --- |
| ![2023-11-03 08 57 28](https://github.com/guardian/editions/assets/935975/ba273ceb-f212-45b0-8b70-e48adb52decd) | ![2023-11-03 08 40 …
> fix: Better user feedback when a download fails

- projects/Apps/common/src/index.ts
- projects/archiver/src/tasks/front/helpers/media.ts
- projects/backend/capi/__tests__/articleImgPicker.spec.ts
- projects/backend/capi/articleImgPicker.ts
- projects/backend/capi/articles.ts
- projects/backend/capi/elements.ts
- projects/backend/package.json
- projects/backend/yarn.lock
This adds support in the cartoon element, a multi-image element which displays different sets of images (which roughly correspond to cartoon panels) at different breakpoints.
Cartoon elements are only permitted in the Picture content type and come through in the main media, so support for this element has been limited to that scenario only.
The majority of the rendering logic resides in DCR which can be seen in the companion pr here: https://github.com/guardian/dotcom-rendering/pull/9416
- Bumping CAPI libs to include Cartoon element definition
- Add `cartoonImages` to the fronts - this allows us to use the lightbox feature
https://github.com/guardian/editions/assets/33927854/5727405b-a769-4e6d-b3f4-2ddd51baed5e
> Cartoon element

- projects/Apps/scripts/package.json
- projects/Apps/scripts/src/fetch-dev-env.js
- projects/Apps/yarn.lock
AWS Sdk v2 is being phased out. This applied V3
- Used this to aid the change: https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html#using-codemod
Please note: I am unable to test this. I am able to see the script runs and be unsuccessful, but I am unable to test the happy path
> chore: Scripts S3 Upgrade

- yarn.lock
To remove all know security dependencies listed here: https://github.com/guardian/editions/security/dependabot?q=is%3Aopen+manifest%3Ayarn.lock
- Refreshed the top level yarn.lock to push through the patch updates
> chore: Update top level yarn.lock

- .github/CODEOWNERS.md
An aim to get the reviewers auto populated for each PR as per: https://stackoverflow.com/questions/46340474/set-a-default-reviewer
- Add CODEOWNERS file
> chore: Add CODEOWNERS

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
React Native SVG is outdated so this brings it up to speed
- Updated the package and build the app to test it. All fine.
> chore: Update React Native SVG

- projects/Mallard/android/build.gradle
Aim to focus on modern Android devices. 
- Restrict install to Android 11 and above
- Tested on Android 10 sim (failed to install as expected) and Android 11 sim (installed as expected)
> chore: Only allow Android 11 and above

- projects/Apps/common/src/editions-defaults.ts
- projects/Mallard/src/components/EditionsMenu/__tests__/__snapshots__/EditionsMenu.spec.tsx.snap
- projects/Mallard/src/hooks/__tests__/use-edition-provider.altlocale.spec.tsx
- projects/Mallard/src/hooks/__tests__/use-edition-provider.spec.tsx
- projects/Mallard/src/hooks/use-edition-provider.tsx
This has not been published since 1st April 2023. There may be an appetite to bring it back in future.
- The regional editions are determined by the `/editions` endpoint. Which in turn is controlled in an S3 bucket. To change this there would change all versions of the app, and is arguably a quicker but potentially more destructive approach
- This change allows us to control via app release.
- Filter out australia edition wherever we set the editions list
- Remove the auto edition to locale feature as there is only one now.
Please note, to reinstate this edition in future would require our readers to update the app
https://github.com/guardian/editions/assets/935975/ed644e49-97f5-48bd-b037-99a007dd9dc2
https://github.com/guardian/editions/assets/935975/e101bc8a-56ca-43c4-b35f-1bd0775413c2
> chore: Temporary remove Australia edition

- projects/Apps/crosswords/package.json
- projects/Apps/yarn.lock
Resolves this vulnerability: https://github.com/guardian/editions/security/dependabot/343
- Updated `parcel`
- Tested that crosswords continued to build
> fix: msgpackr vulnerability

- projects/Mallard/src/helpers/files.ts
`Include diagnostics` is not currently working.
This was a result of removing the issue summary file, which we did in this PR: https://github.com/guardian/editions/pull/2299. We are looking for a file that now doesnt exist and it causes the function to throw. That in itself is inside a `try...catch` meaning we dont call the `mailto` function.
I have tidied this diagnostic function so that we dont check for the file that wont exist
- Removed code attempting to find the file
- Tested it works on both iOS and Android
https://github.com/guardian/editions/assets/935975/791af6c3-3782-40a7-96dc-47353061b933
> fix: Diagnostics include

- projects/Mallard/src/hooks/use-issue-summary-provider.tsx
- projects/Mallard/src/screens/home-screen.tsx
Adds pull to refresh on the issue list.
- Add in the `RefreshControl` to the `FlatList`
- Use the primary blue to colour it
- Call the function to get the latest issue summary, but don't reset the users issue to latest as to not disturb their reading.
https://github.com/guardian/editions/assets/935975/be95b4aa-9f8c-424c-98a1-1db0bd2a5480
https://github.com/guardian/editions/assets/935975/6eadc218-b40d-4cb6-b271-b1e074e9e510
> feat: Pull to Refresh on Issue List

- projects/Mallard/src/components/Header/Header.tsx
- projects/Mallard/src/components/Modals/MissingIAPModal.tsx
- projects/Mallard/src/components/Modals/SignInFailedModal.tsx
- projects/Mallard/src/components/Modals/SignInModal.tsx
- projects/Mallard/src/components/Modals/SubFoundModal.tsx
- projects/Mallard/src/components/Modals/SubNotFoundModal.tsx
- projects/Mallard/src/components/ScreenHeader/IssuePickerHeader/IssuePickerHeader.tsx
- projects/Mallard/src/components/ScreenHeader/IssueScreenHeader/IssueScreenHeader.tsx
- projects/Mallard/src/components/article/types/article.tsx
- projects/Mallard/src/components/layout/slide-card/header.tsx
- projects/Mallard/src/components/weather.tsx
- projects/Mallard/src/hooks/use-login-overlay.tsx
- projects/Mallard/src/hooks/use-okta-sign-in.tsx
- projects/Mallard/src/navigation/NavigationModels.tsx
- projects/Mallard/src/screens/editions-menu-screen.tsx
- projects/Mallard/src/screens/external-subscription.tsx
- projects/Mallard/src/screens/home-screen.tsx
- projects/Mallard/src/screens/issue-screen.tsx
- projects/Mallard/src/screens/lightbox.tsx
- projects/Mallard/src/screens/onboarding/cards.tsx
- projects/Mallard/src/screens/settings-screen.tsx
- projects/Mallard/src/screens/settings/already-subscribed-screen.tsx
- projects/Mallard/src/screens/settings/api-screen.tsx
- projects/Mallard/src/screens/settings/cas-sign-in-screen.tsx
- projects/Mallard/src/screens/settings/dev-zone.tsx
- projects/Mallard/src/screens/settings/editions-screen.tsx
- projects/Mallard/src/screens/settings/gdpr-consent-screen.tsx
- projects/Mallard/src/screens/settings/privacy-policy-screen.tsx
- projects/Mallard/src/screens/weather-geolocation-consent-screen.tsx
As part of the React Navigation update, a few `any` types were added in. These look to resolve these with stricter types
- Update previously added `any` types with stricter types
- Some routes have props and can be undefined. There is no change to the route, just how the type is consumed with the latest update
Passing type check determines the success of this PR
> chore: Updated Navigation Types

- projects/backend/yarn.lock
Looking to resolve this vulnerability: https://github.com/guardian/editions/security/dependabot/34
- Update to `path-parse`
> fix: path-parse vulnerability

- projects/archiver/yarn.lock
Vulnerability fix for this: https://github.com/guardian/editions/security/dependabot/210
- Updated `yarn.lock`
Tests pass, able to build it.
> fix: minimatch vulnerability

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
When identity sign-in was removed, this was forgotten. This is not being used anywhere so makes sense to remove it.
- Remove the Apple Sign-in package
Sign-in through Okta appears to be working as expected.
> chore: Remove Apple signin

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
Netinfo is currently 2 major versions out of date. V10 and V11 breaking changes do no affect our current setup, so seemed prudent to keep this up to date.
- Update to the latest version
> chore: Netinfo update

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
Minor updates to the Webview packahe
- Update `react-native-webview`
Continues to work:
> chore: Update webview

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/components/layout/ui/errors/error-message.tsx
- projects/Mallard/src/helpers/diagnostics.ts
- projects/Mallard/src/helpers/files.ts
- projects/Mallard/src/paths/index.ts
- projects/Mallard/src/screens/settings-screen.tsx
- projects/Mallard/src/screens/settings/dev-zone.tsx
- projects/Mallard/yarn.lock
A few fixes around a few issues I found through the code base.
- `Clipboard` is deprecated in React Native, so the community plugin has been added. I have tested this and it all seems ok
- Fix the error: `[Error: The folder “media” doesn’t exist.]`. This was because the folders had changed to a new structure, but the diagnostics which checks through the folders hadn't been updated. This now reflects correctly as shown in the screenshot below
- Remove `mediaRoot` as its not used
- Settings screen has a required key. Not ideal to use an `index` but the closest to a uid we have. 
| --- | --- |
| <img src="https://github.com/guardian/editions/assets/935975/ff3e8b47-0001-4857-8dc2-b34328a5bf8f" width="300px" /> | <img …
> fix: Misc code fixes

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
A new major version of `react-native-svg` has been released: https://github.com/software-mansion/react-native-svg/releases/tag/v15.0.0
This looks to update it
- Update the package
- Test the SVGs in the app, as show in the header in the screenshots
> chore: Update react-native-svg

- projects/Mallard/src/authentication/services/__tests__/iap.spec.ts
- projects/Mallard/src/helpers/date.ts
- projects/Mallard/src/notifications/__tests__/helpers.spec.ts
Moment is deprecated and as a result, we need to move away from it. However, dates are a key part of the app. 
This PR looks to remove `moment` from the tests in Mallard
- Replaced `moment` with `date-fns` 
- Import the `date-fns` functions from the date abstraction to make it easier to maintain in future
- Tests are passing.
> chore: Remove moment from tests

- projects/Mallard/src/helpers/date.ts
- projects/Mallard/src/hooks/use-edition-provider.tsx
1. Specials could not show as we were filtering the default list with no specials in it, rather that what was on the server
2. New `isBefore` abstraction that now works to a consistent "london time" rather than where you are located
Tested by fiddling with dates with the current expiry
> fix: Editions list and dates

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
Update `react-native-device-info` to an updated minor version
- Update the version
- Test it runs as expected
> chore: Update React Native Device Info

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Bump next version of Mallard (iOS) to 9.39
> Bump version to 9.39

- projects/Apps/common/src/index.ts
- projects/backend/package.json
- projects/backend/yarn.lock
Editions currently cannot render the new Key Takeaways article format. AR has been updated to support this, but I believe Editions backend also needs to know about the new model so that it can correctly pass it to AR.
> Bump CAPI models libraries to version that includes new list element

- projects/Mallard/src/helpers/date.ts
- projects/Mallard/src/helpers/files.ts
- projects/Mallard/src/helpers/issues.ts
Please note that this merges into #2408
This looks to move `londonTime` over to `moment`
- `londonTime` uses date-fns zoned time function
- helper methods for specific date formats
- Updated the code where its used
> chore: londonTime to date-fns

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
Patch update for the current React Native version we are using
- Followed this: https://react-native-community.github.io/upgrade-helper/?from=0.72.11&to=0.72.12
> chore: Update RN to 0.72.12

- projects/Mallard/src/helpers/__tests__/date.altlocale.spec.ts
- projects/Mallard/src/helpers/__tests__/date.spec.ts
- projects/Mallard/src/helpers/date.ts
Still moving away from Moment towards a date abstraction that is supported by date-fns.
`localDate`'s job was to format the date passed in based on its locale.
- Makes the required formatting changes via `date-fns`
- Unfortunately, couldnt mock by changing the constant and had to add tests by setting up two files.
- Tests pass
> chore: localDate moved to datefns

- projects/Mallard/src/helpers/date.ts
- projects/Mallard/src/notifications/__tests__/helpers.spec.ts
- projects/Mallard/src/notifications/helpers.ts
Removes `moment` from the push notificaiton helpers and replaces it with the date abstraction
- As above
Tests pass
> chore: Remove Moment from Push Helpers

- projects/Mallard/ios/Podfile.lock
Build is currently failing: https://github.com/guardian/editions/actions/runs/8433181999.
This is due to the Podfile not fully updating when the RN upgrade happened
- Updated the Podfile
Builds as expected
> chore: Updated Podfile

- projects/Mallard/src/components/RenderHTML/RenderHTML.tsx
When viewing any of the `RenderHTML` pages in dark mode on Android, you will see white text on a white background. This fixes it.
Please note that the bug ticket specifically states the Credits screen, which has subsequently been removed.
- Added a text colour to the body of the styles used in this component
| --- | --- |
| <img src="https://github.com/guardian/editions/assets/935975/f74f9c51-b184-4e15-88ca-45782acb514d" width="300px" /> | <img src="https://github.com/guardian/editions/assets/935975/fc9d8365-bcff-4c24-b0d8-844a6d7d9720" width="300px" /> |
> fix: Android Darkmode Render HTML text

- projects/Mallard/src/components/Spacer/Spacer.tsx
- projects/Mallard/src/components/Spacer/__tests__/Spacer.spec.tsx
- projects/Mallard/src/components/Spacer/__tests__/__snapshots__/Spacer.spec.tsx.snap
- projects/Mallard/src/helpers/words.ts
- projects/Mallard/src/hooks/use-gdpr.tsx
- projects/Mallard/src/screens/settings/gdpr-consent-screen.tsx
"Reject all" is a requested feature, that allows you to easily reject all GDPR options.
- Removed unused getters and setters from the `use-gdpr` hook
- Added a `Spacer` component utility
- Added a way to modify all settings, and changed continue into a helper method, whilst alos adding reject to do the same
- Added the reject all button to the GDPR consent content
- Removed the text passthrough on GDPR constent content, and passed in a `withContinue` boolean to manage to text and functionality
- Removed the text from the component and added it to the language file.
https://github.com/guardian/editions/assets/935975/7018ebf6-edb6-43ba-a8fe-4145e9e05d35
> feat: Reject All GDPR

- projects/backend/capi/articleTypePicker.ts
At the moment, [some pieces](https://composer.gutools.co.uk/content/6634f2188f080b5e6ba920f8) in Journal are correctly styled as Opinion, and some [aren't](https://composer.gutools.co.uk/content/663244088f084fb5cf82ab94). The former example works because it is in the News pillar. The latter is in Opinion, and because it has a series tag, it receives an `articleType` of as `Article`, rather than `Opinion`. The logic is [here.](https://github.com/guardian/editions/blob/513fcd293627aa07c03778c8ce5a0dad3ab9cbad/projects/backend/capi/articleTypePicker.ts#L88)
At the moment Editions must recreate the piece without the series tag  to work around this problem.
This PR raises the check for the comment tag above the check for the series tag when picking article type for pieces with the …
> Ensure pieces with Comment tag are of ArticleType.Comment in Journal pillar

- .github/workflows/amazon-release.yml
- .github/workflows/android-beta.yml
- .github/workflows/android-release.yml
In the latest RN Update, we moved from Java 11 to Java 17. This is now reflected in the CI
- Changed 11 to 17
> chpre: Update Java in github workflows

- projects/backend/capi/articleTypePicker.ts
[#opinion](https://github.com/guardian/editions/pull/2429) causes problems where Editorial pieces, which carry `tone/comment` tags, are mistakenly given a type of `Opinion`.
This PR fixes. I've run the logic past Katy Vans, and the other tags underneath `Comment` (Obits, Analysis) should be fine.
> Ensure Editorial articles don't get Comment tone

- projects/backend/package.json
- projects/backend/yarn.lock
Editions currently cannot render the new Timeline article format. [AR has been updated to support this](https://github.com/guardian/dotcom-rendering/pull/11576), but I believe Editions backend also needs to know about the new model so that it can correctly pass it to AR.
See: https://github.com/guardian/content-api-models/releases/tag/v23.0.0
> Bump `content-api-models` to version that includes new timeline element

- projects/Apps/yarn.lock
- projects/Mallard/yarn.lock
Two `High` vulnerabilities that have turned up within the app code:
https://github.com/guardian/editions/security/dependabot/355
https://github.com/guardian/editions/security/dependabot/356
This fixes them
- Updated `yarn.lock` files
The dependency relates to tooling (Jest/ESlint). Ran validation and it was all good. Quick test on iOS and no obvious regressions
> fix: Braces vulnerability

- projects/Apps/crosswords-bundle/package.json
- projects/Apps/crosswords/scripts/bundle-html.js
- projects/Apps/crosswords/scripts/manifest.js
- projects/Apps/crosswords/src/html-bundle-info.json
- projects/Apps/yarn.lock
- projects/Mallard/html/manifest.js
- projects/Mallard/src/components/article/types/crossword.tsx
- projects/Mallard/src/html-bundle-info.json
Integrates the new crossword bundle into the app
- Uses the newly published npm module
- Updates manifests to work with different ports and scripts
- Removes the need for `html-update` (script to be removed in a future PR)
- Removes the scroll bounce in the crosswords as it makes scrolling the clues in Landscape mode on Tablet more difficult
> feat: Crossword Bundle Mallard Integration

- projects/Mallard/yarn.lock
This fixes the following vulnerabilities
https://github.com/guardian/editions/security/dependabot/361
https://github.com/guardian/editions/security/dependabot/360
- Updated the `yarn.lock` file
This is a deep dependency of both React Native and Metro. Tested by running the app locally, all worked fine.
> chore: WS vulnerability fix

- .github/workflows/server-side-build.yml
The `crosswords-bundle` has a deep dependency that requires node 16. The backend services are currently stuck on 14, and awaiting upgrade. This excludes the `Apps` monorepo from the installation process.
The server side services only use the `common` package, which is a set of types. This only needs dependencies installed for its validation, which is skipped in this instance.
- Skip `Apps` from the install and validation
> chore: Attempt server side fix build

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/App.tsx
- projects/Mallard/src/components/layout/ui/row.tsx
- projects/Mallard/src/screens/lightbox.tsx
- projects/Mallard/src/screens/onboarding-screen.tsx
- projects/Mallard/yarn.lock
`SafeAreaView` has some inconsistencies in older version of Android. This gives better support across both across both platforms
- Updated `react-native-safe-area-context` 
- Added the provider
- Added the Safe Area View
> chore: Safe Area Context

- projects/backend/package.json
- projects/backend/yarn.lock
https://github.com/guardian/editions/security/dependabot/359
https://github.com/guardian/editions/security/dependabot/357
https://github.com/guardian/editions/security/dependabot/349
- Updated express as per the suggestion within the notice above
- Allowed the packages to resolve to the newer versions of `ws` and `braces`
- Run locally with no errors
- Tests passed
- Validation passed
- Built with no errors
> chore: Backend vulnerability fixes

- .github/workflows/snyk.yml
- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
To fix the Snyk security job
- Downgrades the Clipboard as its incompatible with RN. We upgraded it on the failed RN upgrade but didnt downgrade the Clipboard again. This was throwing a warning causing the Snyk action to fail
- Removed the missing lock file. The comment suggested it was needed to "run gradle". It seems like a fix has been put in place as removing this now passes the job.
All actions should now pass.
> fix: Snky Security

- projects/backend/package.json
- projects/backend/yarn.lock
Editions currently cannot render the new Mini profiles article format. AR will first need to be updated to support it (https://github.com/guardian/dotcom-rendering/pull/11724), but Editions backend also needs to know about the new model so that it can correctly pass it to AR.
See: https://github.com/guardian/content-api-models/releases/tag/v25.0.0
> Bump `content-api-models` to version that includes new list element fields

- projects/backend/utils/__tests__/crossword.spec.ts
- projects/backend/utils/crossword.ts
QUICK is a substring of QUICK_CRYPTIC so matches. check that the type is inside a pair of /s as well to be sure we've matched the full type name
Get Quick cryptic headlines to display as that, instead of Quick
> Correctly match crossword type from inside the path

- projects/crosswords-bundle/package.json
- projects/crosswords-bundle/scripts/watch-html.js
- projects/crosswords-bundle/yarn.lock
A recent update to remove a vulnerability in crosswords, now being proliferated into Mallard
- Update Crosswords
- Fix to `watch-html` as it was pointing to an incorrect path.
> chore: Crosswords update 2.0.1

- projects/crosswords-bundle/package.json
- projects/crosswords-bundle/yarn.lock
Updating crosswords to 2.0.2 to include the recent updates to its dependencies and some tidy up.
- Updated package.json
> chore: Updating crosswords to 2.0.2

- projects/Mallard/yarn.lock
- projects/scripts/package.json
- projects/scripts/yarn.lock
- yarn.lock
Fixes these: https://github.com/guardian/editions/security/dependabot?q=is%3Aopen+manifest%3Aprojects%2Fscripts%2Fyarn.lock%2Cprojects%2FMallard%2Fyarn.lock%2Cyarn.lock
- Upgrads to the `yarn.lock` and one package update.
All checks passing.
> Chore: dependency high vulnerabilities

- projects/Mallard/src/components/layout/ui/row.tsx
Fix the broken layout on the settings screen
- Removed `SafeAreaView` from the `Heading` component. It seems the behaviour of this as changed, and I dont think its usage in this component longer applies. I have checked its usage across the app and everything looks fine.
`Heading` is used as a spacer, which cant be very accessible. Something for the list to change
| --- | --- |
| <img src="https://github.com/user-attachments/assets/7684584e-8e47-462c-891f-1a86d137c11e" width="300px" /> | <img src="https://github.com/user-attachments/assets/3fe3edeb-b599-4e40-bb0f-a528bac74142" width="300px" /> |
> fix: Settings screen

- docs/11-yarn-modern.md
- projects/crosswords-bundle/package.json
- projects/crosswords-bundle/yarn.lock
Looking to fix this: https://github.com/guardian/editions/security/dependabot/365.
The outdated package is in `react-scripts` which surprisingly has not seen an update in 2 years. Which is a concern considering its a core package of CRA.
This forces a resolution to a higher package. We bundle the CSS outside of this project, so I dont foresee too much of an issue.
- package json resolution
> chore: nth check vulnerability

- projects/Mallard/yarn.lock
- projects/archiver/yarn.lock
- projects/backend/yarn.lock
- projects/common/yarn.lock
- projects/crosswords-bundle/yarn.lock
- yarn.lock
Fixes:
- https://github.com/guardian/editions/security/dependabot/387
- https://github.com/guardian/editions/security/dependabot/385
- https://github.com/guardian/editions/security/dependabot/384
- https://github.com/guardian/editions/security/dependabot/383
- https://github.com/guardian/editions/security/dependabot/382
- https://github.com/guardian/editions/security/dependabot/381
- Patch updates to Micromatch
This mostly affects `Jest` but seems to run fine. Quick App test and it seems ok
> Fix: micromatch vulnerability

- projects/crosswords-bundle/package.json
`Snyk` job is currently failing on `main`: https://github.com/guardian/editions/actions/runs/10662023825/job/29548498279
This looks to resolve it.
- Remove the duplicate import of `kill-port` from crosswords
Can confirm it works: https://github.com/guardian/editions/actions/runs/10662738956
Has no effect on showing crosswords in dev.
> fix: Snyk kill-port

- projects/crosswords-bundle/yarn.lock
Looks to fix: https://github.com/guardian/editions/security/dependabot/386
- Updated the package through `yarn.lock`
Crosswords build as expected
> fix: Webpack vulnerability

- projects/Mallard/android/app/src/main/java/com/guardian/editions/MainActivity.kt
We are getting reports of crashes on Android due to React Native screens. One of the suggestions was to check the installation steps. During the last upgrade, the override was missed. So trying this.
- Add the override as per: https://github.com/software-mansion/react-native-screens#android
I wasn't able to make it crash previously, but can confirm that this continues to run.
> fix: Attempted fix for Android crashes

- projects/Mallard/src/App.tsx
- projects/Mallard/src/components/Button/BugButtonHandler.tsx
- projects/Mallard/src/helpers/storage.ts
- projects/Mallard/src/hooks/use-gdpr.tsx
- projects/Mallard/src/screens/settings/gdpr-consent-screen.tsx
- projects/Mallard/src/screens/settings/help-screen.tsx
Changing the GDPR settings to reflect the current state of the app and to make Firebase Analytics essential
- Remove the "functionality" GDPR setting content block
- Remove the associated functionality settings as login is through Okta now where there is a privacy policy.
- Enable analytics recording when the user opens the app rather than from behind the performance flag
- Upped the consent version to force a consent check
- Removed Sentry as its not being used.
https://github.com/user-attachments/assets/93b0136e-9f22-445e-8ba9-3db72f5c326b
> feat: Firebase Analytics

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
Required for the next React Native upgrade
- Installs a patch version of the package with the latest architecture changes
I was able to run the app on both platforms successfully.
> chore: Upgrade background fetch

- projects/Mallard/src/screens/lightbox.tsx
For some reason, `credit` and `displayCredit` have stopped be passed through with every image. As a result, i've added defaults
- Added sensible credit defaults
Wasnt quick enough before the republish to get a video. The experience isnt great but at least it doesnt crash the app
> fix: Missing credit

- projects/Mallard/src/AppNavigation.tsx
- projects/Mallard/src/components/Modals/IAPAppMigration.tsx
- projects/Mallard/src/components/iap-app-migration-modal-card.tsx
- projects/Mallard/src/components/onboarding/onboarding-card.tsx
- projects/Mallard/src/helpers/storage.ts
- projects/Mallard/src/helpers/words.ts
- projects/Mallard/src/navigation/NavigationModels.tsx
- projects/Mallard/src/screens/issue-screen.tsx
- projects/Mallard/src/screens/settings/dev-zone.tsx
- projects/Mallard/src/services/remote-config.ts
- projects/Mallard/src/theme/color.ts
Adds a message to In App Purchase users about the app migration
- Adds a new modal route
- New Copy
- Looks to reuse the modal cards, and follows their approach, but need to implement different styling
- Once dismissed, this is persisted so it doesnt show again
- Dev menu button to clear persistence for testing.
> feat: IAP Migration Message

- projects/Mallard/src/helpers/words.ts
Replaces the hyphen with an endash after "soon"
| --- | --- |
| <img src="https://github.com/user-attachments/assets/37e6204c-5a9e-410d-8093-1e03c4b05877" width="300px" /> | <img src="https://github.com/user-attachments/assets/a056a341-3f85-4e7b-a8fd-be4615dd3b01" width="300px" /> |
> chore: Add missing endash

- projects/Mallard/src/AppNavigation.tsx
- projects/Mallard/src/components/Modals/AppMigration.tsx
- projects/Mallard/src/components/app-migration-modal-card.tsx
- projects/Mallard/src/helpers/storage.ts
- projects/Mallard/src/helpers/words.ts
- projects/Mallard/src/navigation/NavigationModels.tsx
- projects/Mallard/src/screens/issue-screen.tsx
- projects/Mallard/src/screens/settings/dev-zone.tsx
- projects/Mallard/src/services/remote-config.ts
Adding in a migration message for all users. Replaces IAP message following the same patterns
- Removes the IAP message as this is now not needed.
- Replaces it with App Migration message
- Updated copy
- Updated logic
- Updated helpers
- Replaced IAP Message storage with App Message storage
> feat: App Migration Message
