guardian/editions

- projects/pwa/src/App.tsx
- projects/pwa/src/helper/urlBuilder.ts
- projects/pwa/src/route/Article.tsx
- projects/pwa/src/route/Front.tsx
- projects/pwa/src/route/Issue.tsx
- projects/pwa/src/route/Product.tsx
thanks @AWare !
This PR also changes `urlBuilder` to take named parameters instead of relying on order, makes the function resilient to URLs changing in the future
> Rename edition to issue

- projects/pwa/package.json
- projects/pwa/src/@types/index.d.ts
- projects/pwa/src/component/Elements.tsx
- projects/pwa/src/component/elements/Text.tsx
- projects/pwa/src/fixtures/article.ts
- projects/pwa/src/hooks/useArticle.ts
- projects/pwa/src/react-app-env.d.ts
- projects/pwa/src/route/Article.tsx
- projects/pwa/yarn.lock
- upgrades pasteup to grab typography tokens
- adds article data fixture (copy-pasted from [dotcom-rendering](https://github.com/guardian/dotcom-rendering/blob/master/fixtures/article.ts))
- implements an Elements renderer (only text elements are currently supported)
- some super simple styling, yo (don't judge... well, judge a little bit)
- tangential: delete some more CSS Modules boilerplate
We can improve styling if the general approach here is 👌
> Article barebones

- projects/Mallard/android/app/build.gradle
- projects/Mallard/android/app/src/main/java/com/mallard/MainApplication.java
- projects/Mallard/android/settings.gradle
- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
- projects/Mallard/package.json
- projects/Mallard/src/components/article/index.tsx
- projects/Mallard/yarn.lock
Block data from CAPI contains HTML, so we need to bust articles out of the native layer into a Webview.
[**Trello Card**](https://trello.com/c/2esfv0D9/104-display-article-basic-news-articles-for-each-pillars)
* install `react-native-webview`
* Inject HTML from CAPI directly into webview
> Article webview

- projects/Mallard/Makefile
- projects/Mallard/ios/fastlane/Fastfile
- projects/Mallard/package.json
The iOS beta release process is currently missing a few steps. This fills in some gaps and improves some naming.
[**Trello Card ->**](https://trello.com/c/vsA7DzZB/182-editions-build-pipeline-ios)
* improved names of yarn scripts
* automatically increment beta build version, so we don't have to keep it up to date in git
* prevent CI from waiting for app to process in TestFlight, to save 5 minutes of waiting on the TeamCity build agent
> Improve iOS beta pipeline

- projects/Mallard/package.json
- projects/Mallard/src/App.tsx
- projects/Mallard/yarn.lock
I had a bit of a read and this is free performance and a best practice. Basically it maps the views to the underlying os's screen system instead of just using a single screen (think of screens like pages in a website)
> Use screens

- projects/Mallard/src/components/front/front.tsx
- projects/Mallard/src/screens/issue-screen.tsx
instantiating react components is expensive and `react-navigation` waits until the whole view is ready before showing it. This PR allows us to do a two-pass render by only showing the stuff that's on screen during the page transition and then bringing everything else right after
> Lazy load fronts

- projects/Mallard/src/hooks/use-fetch.ts
The existence of this `alert` call is breaking the build. From what I've gathered, the `hooks/` directory should not contain any `react-native`-specific constructs, so I'm going to remove it altogether.
> Remove alert from clearLocalCache

- projects/Mallard/src/components/front/card-group.tsx
- projects/Mallard/src/components/front/index.tsx
- projects/Mallard/src/components/header/index.tsx
- projects/Mallard/src/navigation/index.ts
- projects/Mallard/src/screens/issue-screen.tsx
I wanted to build a custom header for `react-navigation` but as it turns out that is WORK so that's still gonna happen but it'll happen later and as a stop gap measure I've put the pretty header we actually want below the `react-navigation` one and it looks like this
> Styled issue header

- projects/Mallard/src/App.tsx
- projects/Mallard/src/components/front/card-group.tsx
- projects/Mallard/src/components/front/cards.tsx
- projects/Mallard/src/navigation/index.ts
- projects/Mallard/src/screens/article-screen.tsx
- projects/backend/common.ts
- projects/backend/controllers/article.ts
- projects/backend/fronts.ts
Populate the cards and prepopulate the articles when data is present. Otherwise stub until we can discuss with tools.
https://trello.com/c/s9nKCTmR/174-consume-templated-editions-model-from-front-tools
This makes navigation potentially undefined until we find a better way of handling it while retaining the type data on the NavigationProps.
> Serve articledata from fronts

- projects/Mallard/src/helpers/settings.ts
- projects/Mallard/src/hooks/use-settings.tsx
- projects/Mallard/src/screens/settings-screen.tsx
- projects/Mallard/src/screens/settings/api-screen.tsx
Just like most drawers in my closet, our settings menu is chock full of scary internal things that nobody else needs or wants to know about. This PR hides all of that
If you do wanna get to the settings (you can just scroll down enough and tap the duck emoji. This will unlock the danger zone. This is a bit overengineered but I'll admit it was fun.
We can only store strings to local storage so there's some basic type conversion (JSON <3) going on in the background
> Clean up settings

- .eslintrc.js
- package.json
- projects/Mallard/src/App.tsx
- projects/Mallard/src/components/article/index.tsx
- projects/Mallard/src/package.json
- projects/Mallard/tsconfig.json
- yarn.lock
these are super handy for `useEffect` and such
> Lint for hooks, use absolute paths

- projects/Mallard/android/app/build.gradle
This will auto increment the android version every deploy (matching iOS) so google play can recognize the build as being updated
> Use timestamp as android version

- projects/Mallard/src/components/front/card-group.tsx
- projects/Mallard/src/components/front/card-group/card.tsx
- projects/Mallard/src/components/front/card-group/row.tsx
- projects/Mallard/src/components/front/card-group/text-block.tsx
- projects/Mallard/src/components/front/index.tsx
- projects/Mallard/src/components/layout/errors/error-message.tsx
- projects/Mallard/src/components/layout/errors/flex-error-message.tsx
- projects/Mallard/src/screens/article-screen.tsx
- projects/Mallard/src/theme/appearance.ts
This adds the sports yellow thingy and the arts+culture square in there. They aren't wired to the article type logic yet so, for now, they all default to the arts & culture square thing.
Also, and totes out of scope but felt like a good time to do this - The UI to display errors was copypasted around the app so I've tucked it away into it's own `<ErrorMessage/>` (inline) and `<FlexErrorMessage/>` (centered block) component
> Photo cards V1

- projects/aws/lib/aws-stack.ts
- projects/backend/capi/articles.ts
- projects/backend/controllers/fronts.ts
- projects/backend/fronts.ts
- projects/backend/utils/try.ts
Originally, this was an attempt to add sorting to 
https://github.com/guardian/editions/pull/109
but after discussing with @blishen we will need to use multiple capi sources until we get rid of print sent (especially for crosswords)...
and then discussing https://github.com/guardian/editions/pull/110 with @LATaylor-guardian I realised there was a better way of using the `Attempt<T>` pattern...
> Many capis

- projects/Mallard/fastlane/Fastfile
I broke the iOS beta deploy with a careless [merge](https://github.com/guardian/editions/pull/90/commits/8d05eff6a56402e99e7143ebc3b85e4c43f416c5) commit. This PR fixes the problem. 
* Fix Fastfile formatting
> Fix iOS Beta Deploy

- projects/Mallard/package.json
- projects/Mallard/src/helpers/settings.ts
- projects/Mallard/src/screens/settings-screen.tsx
- projects/Mallard/yarn.lock
As per the error message `AsyncStorage` will be being moved out of react native core. This changes our dependency to the supported version and removes an error message.
> Update async storage to use community version

- package.json
This runs all validators on teamcity against all pull requests, which should now show build status.
> Run all validators on build

- projects/Mallard/src/components/layout/clipFromTop/clipFromTop.tsx
- projects/Mallard/src/navigation/index.ts
- projects/Mallard/src/navigation/interpolators.ts
> Bouncy cards, hide btn that cycles article styles

- projects/Mallard/src/components/article/index.tsx
- projects/backend/capi/articles.ts
- projects/backend/fronts.ts
- projects/common/src/index.ts
We will eventually need to to support the rendering of gallery articles in the app. This provides the data in the expected response format to do that.
> Support returning gallery articles from the API.

- projects/backend/capi/assets.ts
- projects/backend/controllers/image.ts
- projects/backend/image.ts
- projects/backend/index.ts
- projects/common/src/index.ts
By having the backend generate and sign redirect resizes we can store the images for an edition in s3 and zip them up nicely.
As far as integrations with content, this now pulls out master assets and I'll start pulling out some kind of asset object instead of urls in the CAPI response.
> Add redirects for images

- projects/backend/capi/articles.ts
- projects/backend/fronts.ts
this fixes the capi query to not ignore the last entry and logs when a collection fails
> Alert on failures in collections and fix CAPI query.

- projects/Mallard/src/App.tsx
- projects/Mallard/src/helpers/files.ts
- projects/Mallard/src/screens/settings/download-screen.tsx
some file system checks failed if the issues dir wasn't present, this makes the app a bit more eager to create it
> Fix first app load on iOS

- projects/Mallard/fastlane/Fastfile
To make the android beta build properly.
`gradle(` needs an argument of `task` so I moved the properties block to the assemble task
> Fix fastfile

- projects/backend/capi/articles.ts
We were using the webTitle instead of the headline which means often the kicker is repeated in the headline, more than it does already.
> Swap to using the headline rather than the webTitle

- projects/Mallard/src/components/front/collection-page/collection-page.tsx
- projects/Mallard/src/components/front/index.tsx
- projects/Mallard/src/components/layout/ui/errors/error-message.tsx
- projects/Mallard/src/helpers/fetch.ts
- projects/Mallard/src/screens/home-screen.tsx
- projects/Mallard/src/screens/issue-screen.tsx
Not having this was making debugging a bit painful. Click on them to copy the text.
> Show the url for fetch errors and allow them to be copied

- projects/backend/capi/articles.ts
- projects/backend/controllers/issue.ts
- projects/backend/fronts.ts
- projects/backend/s3.ts
- projects/common/src/collection/card-layouts.ts
- projects/common/src/index.ts
The backend currently crashes on content without images and deletes things it can't display. So this will just send a response without an image and a placeholder  for now.
> Make API a little less crash happy

- projects/Mallard/src/components/icons/Quote.tsx
- projects/Mallard/src/components/icons/__tests__/Quote.spec.tsx
- projects/Mallard/src/components/icons/__tests__/__snapshots__/Quote.spec.tsx.snap
For the Opinion header we need a quote Icon.
* Add quote icon in a centralised way using React Native SVG with sensible defaults
* Simple snapshot test
> feat: Quote Icon

- projects/backend/capi/articles.ts
- projects/backend/capi/kickerPicker.ts
In order to avoid the kicker being repeated across content and duplicating parts of the headline, we have established editorial rules for displaying a given kicker for an article.
> Implement editorial rules for displaying kicker.

- projects/Mallard/src/screens/issue-screen.tsx
Currently when you select a different issue it does not display it. This fixes that.
> Fix: Allow user to select and display different issues.

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
- projects/Mallard/ios/Mallard/Mallard.entitlements
This should fix the iOS debug build. iCloud was turned on in https://github.com/guardian/editions/pull/164 but was not configured and this has been preventing the debug build from running.
> Fix debug build

- projects/Mallard/package.json
While looking at the build agent with @LATaylor-guardian I noticed that metro would continue to run after the build had finished. As there are two agents running on the build mac, and each one has a working directory it seems plausible that we could bundle an old version of the app when building. 
Todo: update tc build to kill metro on finishing.
> fix multi metro

- projects/Mallard/src/components/header/index.tsx
- projects/Mallard/src/components/issue/index.tsx
- projects/Mallard/src/components/layout/ui/issue-row.tsx
- projects/Mallard/src/components/weather.tsx
- projects/Mallard/src/screens/home-screen.tsx
- projects/Mallard/src/theme/spacing.ts
Fixes weather layout on wider screens using the previously named `IssueRowSplit`, I've renamed to `GridRowSplit` for the time being to be more generic.
[**Trello Card ->**](https://trello.com/c/opEncVf0/286-clean-up-design-debt-first-set-of-snags-timebox)
> Ensure weather is split right on all screens

- projects/Mallard/src/components/article/article-standfirst.tsx
- projects/Mallard/src/components/layout/slide-card/index.tsx
- projects/Mallard/src/components/multiline.tsx
- projects/Mallard/src/components/styled-text.tsx
- projects/Mallard/src/theme/appearance.ts
- projects/Mallard/src/theme/color.ts
Fixing article layout using both the _snagging_ fixes and things missed from the _delivered_ templates:
[**Trello Card ->**](https://trello.com/c/opEncVf0/286-clean-up-design-debt-first-set-of-snags-timebox)
> Fix up article spacing, colors

- projects/Mallard/src/components/front/collection-page/collection-page.tsx
The current leading card (_the one with the massive image ™️_) requires some tooling to make the image actually suitable. For now we're reverting back to the square-imaged card.
> Revert to superhero card for time being

- projects/Mallard/src/components/article/article-standfirst.tsx
- projects/Mallard/src/components/styled-text.tsx
- projects/Mallard/src/theme/appearance.ts
- projects/backend/fronts.ts
We have different (temporary) names for fronts which meant that colours weren't coming through where they should have been. Additionally, I've added a way to get the correct tone colour for an article. This is used here in the kicker and byline.
> Add patch for pillar colours, and hook to use them

- projects/Mallard/src/screens/issue-screen.tsx
As this is readonly, index should be fine. This will hopefully fix glitchy rendering on some issues that have the same front names (although quite how that .
> Ensure duplicate front names don't cause shonky rendering

- projects/backend/.gitignore
- projects/backend/jest.config.js
The `jest.config.js` was not being added which means people can't run tests!
`.js` in a `.gitignore` seems a bit broad so have removed. The only `.js` that gets output in this project goes into `dist`, which is already ignored from the root `.gitignore`.
> Allow .js in backend

- projects/common/src/index.ts
this removes the /issue from all the paths that aren't the issue index
this will allow the archviers zip to be extracted
(testing on code)
> Don't use /issue for fronts so we can archive it.

- projects/backend/controllers/__tests__/issue.spec.ts
- projects/backend/controllers/issue.ts
- projects/backend/jest-matchers.ts
- projects/backend/types/jest.d.ts
Because we only _want_ 7 issues on the issues list! I've also promoted the most recent issues to the top.
> Ensure we only pick `n` issues from backend

- projects/Mallard/src/components/article/types/crossword.tsx
- projects/editions-crossword-renderer-app/src/index.js
- projects/editions-crossword-renderer-app/src/js/components/CrosswordView.jsx
The webview's injected javascript is always gonna run after our page's javascript. Knowing this I've updated the injected javascript to call a function exposed by the page that will render the crossword.
> Fix crosswords not loading

- projects/Mallard/src/screens/home-screen.tsx
> always link to settings, even when there's an error

- projects/Mallard/src/helpers/response.ts
- projects/Mallard/src/hooks/use-api.ts
- projects/Mallard/src/hooks/use-response.ts
- projects/Mallard/src/screens/home-screen.tsx
- projects/Mallard/src/screens/issue-screen.tsx
This means we don't need a reload button and new issues will always come in.
I added some extra methods to `withRequest` to allow it to display stale data during an error or a refresh so there's no spinners flashing around
> Refresh issue list when opening the issue menu

- projects/Mallard/src/components/article/article-byline/__tests__/__snapshots__/article-byline.spec.tsx.snap
- projects/Mallard/src/components/article/article-byline/index.tsx
- projects/Mallard/src/components/article/article-header/__tests__/__snapshots__/long-read-header.spec.tsx.snap
- projects/Mallard/src/components/article/article-header/__tests__/__snapshots__/news-header.spec.tsx.snap
- projects/Mallard/src/components/article/article-header/__tests__/__snapshots__/opinion-header.spec.tsx.snap
- projects/Mallard/src/components/article/article-header/long-read-header.tsx
- projects/Mallard/src/components/article/article-header/news-header.tsx
- projects/Mallard/src/components/article/article-header/opinion-header.tsx
- projects/Mallard/src/components/article/article-headline/__tests__/__snapshots__/article-headline.spec.tsx.snap
- projects/Mallard/src/components/article/article-headline/__tests__/article-headline.spec.tsx
- projects/Mallard/src/components/article/article-headline/index.tsx
- projects/Mallard/src/components/article/article-kicker/__tests__/__snapshots__/article-kicker.spec.tsx.snap
- projects/Mallard/src/components/article/article-kicker/__tests__/article-kicker.spec.tsx
- projects/Mallard/src/components/article/article-kicker/index.tsx
- projects/Mallard/src/components/article/article-standfirst/__tests__/__snapshots__/article-standfirst.spec.tsx.snap
- projects/Mallard/src/components/article/article-standfirst/index.tsx
- projects/Mallard/src/components/article/index.tsx
- projects/Mallard/src/components/article/styles.ts
- projects/Mallard/src/components/front/collection-page/collection-page.tsx
- projects/Mallard/src/components/front/collection-page/row.tsx
- projects/Mallard/src/components/front/helpers.ts
- projects/Mallard/src/components/front/index.tsx
- projects/Mallard/src/components/front/item/item.tsx
- projects/Mallard/src/components/front/item/text-block.tsx
- projects/Mallard/src/components/icons/Quote.tsx
- projects/Mallard/src/components/icons/__tests__/__snapshots__/Quote.spec.tsx.snap
- projects/Mallard/src/hooks/use-article.tsx
- projects/Mallard/src/screens/article-screen.tsx
- projects/Mallard/src/theme/appearance.ts
- projects/common/src/index.ts
Instead of `articleAppearance` being a weird mix of low-level and high-level css now you can get an article type and and the pillar colors and do whatever with them
> Remove article appearance, just get pillar colours instead

- package.json
Common was never getting installed on any of our build agents so it broke all of our builds. @AWare - this seems like it should work?
> Add install for common

- projects/Mallard/.env.production.js
- projects/Mallard/Makefile
- projects/Mallard/package.json
- projects/Mallard/scripts/helpers/helpers.js
Add two scripts to fetch `.env` files for either `DEV` or `PROD` environments. As can be seen in the code, the prod config will be fetched on `pre-bundle` and the dev config on `pre-run`. This means that the dev config is fetched quite a lot (every time we run) but it seemed safer to do it this way. Additionally, the error should be pretty obvious for people who try this offline.
(I've added two files to s3 for this too).
@AWare - it looks like `aws` isn't on the boxes so it looks like this _isn't_ how this is done in the wild - let's do this idiomatically.
> Add scripts for fetching env files

- projects/Mallard/.env.production.js
- projects/Mallard/.gitignore
- projects/Mallard/package.json
- projects/Mallard/scripts/helpers/helpers.js
This adds a way to build our `sentry.properties` on Team City rather than commit them to git.
> Add in builders for sentry config files

- projects/Mallard/src/helpers/fetch.ts
- projects/Mallard/src/helpers/push-notifications.ts
Backend change means that we need to update the topic for the push notifications.
Tested and working.
[**Trello Card ->**](https://trello.com/c/Bc4mhrks/386-push-notifications-topic-change)
> feat: Topic Update

- projects/archiver/local.ts
- projects/archiver/main.ts
- projects/aws/lib/aws-stack.ts
- projects/backend/capi/articles.ts
- projects/backend/controllers/fronts.ts
- projects/backend/controllers/issue.ts
- projects/backend/fronts.ts
- projects/backend/index.ts
- projects/backend/issue.ts
- projects/backend/preview.ts
- projects/backend/s3.ts
- projects/common/src/index.ts
- riff-raff.yaml
~~the backend can now be called with an id of form `${id}_${source}` where source is a published version or `'preview'`~~
~~when it is preview, the preview edition is fetched
when it is any string we look in the published bucket for that json file
when it is not present behavior is unchanged~~
The backend must now be called with `source/id` instead of `id`. There is a second backend set of endpoints accessed as before which access preview. 
The s3 buckets can now be used as an endpoint in the app. Will raise as separate PR. 
the archiver now takes a source and publishes to s3 without that source in the path (as if we didn't have specific sources) this better matches the intent of the tools part of the api 
~~⚠️ This will break the app when it goes live ⚠️~~
This introduces a third lambda …
> Preview support in backend

- projects/Mallard/fastlane/Appfile
- projects/Mallard/fastlane/Fastfile
- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
- projects/Mallard/ios/Mallard/Info.plist
In order to get Push Notifications (and some of the Auth) working to its fullest potential, we need to use the production iOS bundle id.
[**Trello Card ->**](https://trello.com/c/QkO169QG/402-change-the-ios-bundle-id)
* Change the bundle id
* Update the fastlane files to manage the build
* Move from timestamp build numbers to sequential to follow the existing pattern.
> feat: ios bundle id change

- projects/archiver/summary.ts
- projects/backend/controllers/__tests__/issue.spec.ts
- projects/backend/controllers/issue.ts
This takes the 7 issue cap off the `issues` endpoint because we need to see everything that's available for now and we need a better way of limiting this.
> All the issues (for now)

- projects/Mallard/.env.production.js
- projects/Mallard/android/app/build.gradle
- projects/Mallard/android/app/src/main/java/com/guardian/editions/MainApplication.java
- projects/Mallard/android/settings.gradle
- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
- projects/Mallard/package.json
- projects/Mallard/src/authentication/__tests__/credentials-chain.spec.ts
- projects/Mallard/src/authentication/__tests__/fixtures.ts
- projects/Mallard/src/authentication/credentials-chain.ts
- projects/Mallard/src/authentication/helpers.ts
- projects/Mallard/src/authentication/storage.ts
- projects/Mallard/src/constants.ts
- projects/Mallard/src/services/iap.ts
- projects/Mallard/yarn.lock
To allow users to login with existing IAP credentials from the previous daily edition app. I'm going to leave this as draft as it will require a fair bit of testing before I know that this works. The essence of the PR is good. The specifics might not be quite right.
Things still to consider:
Nothing to see here ...
> First pass at IAP provider

- projects/Mallard/src/hooks/use-form-field.ts
- projects/Mallard/src/screens/settings/cas-sign-in-screen.tsx
This adds the ability to see errors for CAS inputs. I'd like to add tests for the form field hooks but testing hooks in RN seems more than my life is worth ... having tried it last week.
Also `number-pad` is not going to work for a subscriber id as they have chars in them 🙄 - additionally (i.e., they haven't put anything in). So I got rid of it while I was there ...
> Add errors

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
- projects/Mallard/ios/Podfile
- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/services/iap.ts
- projects/Mallard/yarn.lock
The method that was being used here before was looking for local receipt data and otherwise going off to apple to find it (and required a user to login to their app store account). This is more of a 'restore purchase' flow. This new method will just try and find a receipt locally, and if it's not there then carry on trying to authenticate with any other methods that may follow it.
> Access receipt data from local store only

- projects/Mallard/src/navigation/index.ts
- projects/Mallard/src/screens/settings-screen.tsx
- projects/Mallard/src/screens/settings/already-subscribed-screen.tsx
To match the UX flows.
The 'Restore app subscription' gets hidden from view on Android.
> Add 'I'm already subscribed' screen to settings.

- projects/Mallard/package.json
- projects/Mallard/scripts/fetch-dev-env.js
- projects/Mallard/yarn.lock
This has been winding me up. Now if you don't have `frontend` creds but do have a `.env` file locally then this will not fail but warn instead.
> Don't fail build when .env file exists

- projects/Mallard/src/App.tsx
- projects/Mallard/src/components/layout/header/header.tsx
- projects/Mallard/src/components/layout/slide-card/index.tsx
- projects/Mallard/src/components/layout/ui/modal-for-tablet.tsx
- projects/Mallard/src/navigation/index.ts
- projects/Mallard/src/navigation/navigators/header.tsx
- projects/Mallard/src/navigation/navigators/modal.tsx
- projects/Mallard/src/screens/settings-screen.tsx
- projects/Mallard/src/theme/spacing.ts
I love react-navigation now.
This updates the settings and the inline settings menu in the onboarding so they both use modals with custom headers (which are no longer ugly)
This PR also hides the dev menu a bit better, relevant parties like CP will need a shout. To bring up the dev menu.
1. Go to settings
2. Tap seven times on the version number
3. Confirm that you want to delete all your data (this is a lie)
The idea for this is that this is, I think, well enough hidden for the production app, should we need it for some cases
> New settings headers

- projects/Mallard/package.json
- projects/Mallard/src/components/layout/header/header.tsx
- projects/Mallard/src/components/reloadButton.tsx
- projects/Mallard/src/helpers/settings/defaults.ts
- projects/Mallard/src/screens/article-screen.tsx
- projects/Mallard/src/screens/issue-screen.tsx
- projects/backend/fronts.ts
- projects/backend/fronts/issue.ts
Publication requires ability to refresh issue.
I think these emoji express what it is to refresh.
This also shows a number when on preview.
> Show a refresh button when we are on a preview backend

- projects/Mallard/src/authentication/auth-context.tsx
- projects/Mallard/src/authentication/helpers.ts
- projects/Mallard/src/authentication/storage.ts
- projects/Mallard/src/screens/identity-login-screen.tsx
- projects/Mallard/src/screens/settings-screen.tsx
Sign out will now only sign you out of an identity account and not delete CAS codes. I've also renamed all functions that implemented this behaviour to make it more obvious.
> Change reset credentials to sign out

- projects/Mallard/src/components/article/article-header/types.ts
- projects/Mallard/src/screens/article-screen.tsx
- projects/backend/capi/articleTypePicker.ts
- projects/backend/capi/articles.ts
- projects/common/src/index.ts
- Provides logic for deciding article type on backend (will need further tweaks on review)
- Wires article display in app up to article type to render correct header/article design.
- This PR does not change front card based on article type (which will be necessary)
> Provide article type to articles on the app.

- projects/Mallard/src/authentication/credentials-chain.ts
- projects/Mallard/src/authentication/helpers.ts
- projects/Mallard/src/authentication/storage.ts
> Cache receipt and update caches on fetch

- projects/Mallard/src/App.tsx
- projects/Mallard/src/helpers/__tests__/issues.spec.ts
- projects/Mallard/src/helpers/files.ts
- projects/Mallard/src/helpers/issues.ts
Checks what is on the device vs last seven days of issues. Runs on app startup.
[**Trello Card ->**](https://trello.com/c/YHeTsHE5/473-deleting-old-zips)
* Date functions didn't have necessary preceding zeros 🤦‍♂ 
* Compares the `issues` in the file system and their keys to those that are in the last seven days. The difference between then are removed from the file system.
> feat: Last seven days deleted from device

- projects/Mallard/src/App.tsx
- projects/Mallard/src/helpers/fetch.ts
- projects/Mallard/src/helpers/files.ts
Push Notifications are notorious for not always being delivered. In the cases where its not, this will download the latest issue when starting up the app. This follows the same methodology as the current Editions app 
[**Trello Card ->**](https://trello.com/c/ygsvhVz5/474-check-and-download-zip-on-app-start)
* Helper function to check URL exists
* Above function used to check the Zip is on the server
* General workflow = Get Todays as key -> Check if issue is on device -> If not then check the issue is available on the zip -> If it is, then download it.
> feat: Download todays issue when the app starts

- projects/Mallard/src/helpers/push-notifications.ts
A user who has the app in the background but doesnt use the app will potentially download days and days worth of issues without opening the app. This means the clearing of issues will never happen and has a potential to fill up their device.
This clears old issues when a push is received to keep it to a maximum.
> feat: Clear issues on push

- projects/Mallard/src/components/article/html/render.ts
- projects/Mallard/src/components/article/index.tsx
This will fix links opening inside a webview and will also allow atoms to render in PROD (hopefully)
[**Trello Card ->**](https://trello.com/c/IUbglrrE/175-atoms-embeds-render-video-atom)
> Fix opening links and embeds not loading

- projects/Mallard/src/components/button/button.tsx
- projects/Mallard/src/components/button/close-modal-button.tsx
- projects/Mallard/src/components/login/login-layout.tsx
- projects/Mallard/src/components/modal-button.tsx
- projects/Mallard/src/components/onboarding/onboarding-card.tsx
- projects/Mallard/src/components/sign-in-modal-card.tsx
- projects/Mallard/src/components/sub-not-found-modal-card.tsx
- projects/Mallard/src/screens/onboarding/cards.tsx
- projects/Mallard/src/theme/typography.ts
> Move onboarding & consent screens closer to various designs.

- editions.code-workspace
- projects/Mallard/src/components/article/html/render.ts
- projects/Mallard/src/components/front/index.tsx
- projects/Mallard/src/hooks/article/dev-tools.tsx
- projects/Mallard/src/hooks/use-article.tsx
- projects/Mallard/src/navigation/navigators/article.tsx
- projects/Mallard/src/screens/article-screen.tsx
- projects/Mallard/src/screens/article/body.tsx
- projects/Mallard/src/screens/article/dev-tools.tsx
- projects/Mallard/src/screens/issue-screen.tsx
- projects/common/src/index.ts
This picks up the article type from the backend and also refactors the devtools so they disappear completely if not in dev mode (less overhead) and the props just pass through
> Get the right article types and present them

- projects/Mallard/src/screens/article/body.tsx
Fixes a bug where login modals were not clickable on android
> Allow modal to be clickable on Android

- projects/Mallard/src/components/front/helpers/helpers.ts
- projects/Mallard/src/components/front/index.tsx
- projects/Mallard/src/components/front/items/item.tsx
- projects/Mallard/src/components/layout/animators/clipFromTop.tsx
- projects/Mallard/src/components/layout/animators/fader.tsx
- projects/Mallard/src/components/layout/slide-card/header.tsx
- projects/Mallard/src/components/layout/slide-card/index.tsx
- projects/Mallard/src/components/layout/ui/modal-for-tablet.tsx
- projects/Mallard/src/components/modal.tsx
- projects/Mallard/src/components/slider/draw/lozenge.tsx
- projects/Mallard/src/components/slider/index.tsx
- projects/Mallard/src/components/spinner.tsx
- projects/Mallard/src/components/toast/toast.tsx
- projects/Mallard/src/helpers/math.ts
- projects/Mallard/src/navigation/navigators/article.tsx
- projects/Mallard/src/navigation/navigators/article/transition.tsx
- projects/Mallard/src/navigation/navigators/modal.tsx
- projects/Mallard/src/navigation/navigators/underlay.tsx
- projects/Mallard/src/navigation/navigators/underlay/transition.tsx
- projects/Mallard/src/screens/article-screen.tsx
- projects/Mallard/src/screens/issue-screen.tsx
Transition interpolations will crash at runtime if they get any values that aren't finite numbers. This is rare but can happen.
This fixes that by checking if they are finite numbers and if they aren't returning an empty interpolation - this means this crash will never happen but in certain scenarios where it would have happened transitions might get a bit weird? which is better I think
> Stabilise transitions

- projects/Mallard/.env.production.js
- projects/Mallard/src/constants.ts
- projects/Mallard/src/services/iap.ts
Currently, when upgrading from the old app to the new app in TestFlight, IAP subscriptions don't persist.
I _think_ this is down to the fact that we were using the `__DEV__` flag to check which verify endpoint to use. The old DE app (correctly) used the sandbox endpoint. Currently, the new DE app uses the live endpoint due to `__DEV__` being `false` in the beta build.
This adds an environment variable to override back to sandbox for some build.
I've set these variables in TC for both android and iOS beta build.
> Allow a switch for builds to use iap sandbox

- projects/Mallard/scripts/helpers/helpers.js
This fixes our builds and allows empty string to be set by environment variables.
> Allow empty strings in .env

- projects/Mallard/src/App.tsx
- projects/Mallard/src/components/layout/ui/row.tsx
- projects/Mallard/src/components/login/login-layout.tsx
- projects/Mallard/src/helpers/words.ts
- projects/Mallard/src/navigation/index.ts
- projects/Mallard/src/screens/settings/credits-screen.tsx
- projects/Mallard/src/screens/settings/faq-screen.tsx
- projects/Mallard/src/screens/settings/gdpr-consent-screen.tsx
- projects/Mallard/src/screens/settings/help-screen.tsx
- projects/Mallard/src/screens/settings/privacy-policy-screen.tsx
- projects/Mallard/src/screens/settings/terms-and-conditions-screen.tsx
This PR encompasses the following:
- Updates the respective titles of the following setting screens:
- FAQ
- Help
- Privacy Policy
- Privacy Settings
- Terms and Conditions
- Updates the GDPR screen to be consistent with apps and reflect the nature of our requirements.
- Makes GDPR consent screen in onboarding flow consistent with UX flows. 
- Updates consent screen in onboarding to have dismissable header that slides down.
- Updates consent screen to force you to make your consent choices prior to moving into the app.
> Settings & Onboarding Changes.

- projects/Mallard/src/components/onboarding/onboarding-card.tsx
- projects/Mallard/src/components/sub-not-found-modal-card.tsx
- projects/Mallard/src/screens/onboarding/cards.tsx
Links: 
Privacy policy opens in browser, going here: 
Cookie policy opens in browser, going here:
> Add Cookie and Privacy policy links to onboarding screen.

- projects/Mallard/src/screens/settings/gdpr-consent-screen.tsx
Done - Users should be able to close the screen after choosing their preferences for performance and functionality. By tapping close, they should be taken to the home screen of the app.
Done - On Settings > Privacy settings (not from onboarding), the button should be "Enable all", not "Enable all and continue"
> Tweaks to consent management screens.

- projects/Mallard/src/components/sign-in-failed-modal-card.tsx
- projects/Mallard/src/screens/identity-login-screen.tsx
This adds a new type of modal card for a failed sign in that will _only_ show after the sign in to Identity has failed. The existing one (with a bit more stuff about the digital pack) will show on any subsequent views.
[**Trello Card ->**](https://trello.com/c/H32H2eUN/464-update-paywall-screen-for-when-a-user-is-signed-in-but-do-not-have-a-subscription-ios-version-check-on-android-as-well)
> Create and use sign in failed card

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
- projects/Mallard/ios/Mallard.xcodeproj/xcshareddata/xcschemes/Mallard.xcscheme
- projects/Mallard/ophan/build.gradle
We have a problem trying to build the iOS app under its "Release" scheme. This scheme currently involves building the app for no fewer than **four** CPU architectures, two that are applicable to real iPhones: `arm64` and `arm7` (32-bit), and two that are for simulators: `x86_64` and `i386` (32-bit). This is a problem because the `ophan` Kotlin module is only currently set up to produce a framework for one of these architectures at a time and it cannot easily produce a framework for the `i386` architecture at all.
* Modified the "Valid architectures" settings such that only the 64-bit simulator architecture gets built, this shouldn't be a big limitation to us as far as I can tell. 
(Note: Xcode/`xcodebuild` will still build both 64-bit and 32-bit versions for real devices)
* The changes in …
> Fix iOS build using a "universal" ophan framework

- projects/Mallard/android/app/src/main/java/com/guardian/editions/ophan/RNOphanModule.java
- projects/Mallard/ios/Mallard/Ophan/Ophan.swift
- projects/Mallard/ophan/src/commonMain/kotlin/ophan/Ophan.kt
- projects/Mallard/ophan/src/iosMain/kotlin/ophan/Ophan.kt
To fill in some of the missing details we need to send to Ophan to properly attribute page views and other tracking calls.
Subsequent PRs will be required to fill in the details marked **TODO** in the table below.
[**Trello Card ->**](https://trello.com/c/Gk4RDfwf/525-ophan-initialiser)
Field | Android value | iOS value
--- | --- | ---
App version | `BuildConfig.VERSION_NAME` (which takes value from `defaultConfig.versionName` in app/build.gradle) | `Bundle.main.infoDictionary?["CFBundleShortVersionString"]` and `Bundle.main.infoDictionary?["CFBundleVersion"]` (not sure where these values come from)
App family | Fixed: `"Android Editions"` | Fixed: `"iOS Editions"`
App OS version | `Build.VERSION.RELEASE`  | `UIDevice.current.systemVersion`
App edition | Fixed: `Edition.UK` | Fixed: …
> Supply app/os/device details when initialising Ophan

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
- projects/Mallard/ophan/build.gradle
Fixes the build by using only the required architectures in the right places.
> Make universal framework only support iPhoneOS OR iPhoneSimulator

- projects/editions-crossword-renderer-app/package.json
- projects/editions-crossword-renderer-app/src/js/components/CrosswordView.jsx
- projects/editions-crossword-renderer-app/yarn.lock
We own the crossword renderer now (github.com/guardian/react-crossword) and I've published it with the fix!
> Fix crosswords on iPad forever

- projects/backend/capi/articleTypePicker.ts
Based on review with Ana P this is to address some issues with articleType being set sub-optimally.
[**Trello Card ->**](https://trello.com/c/Puvf7hXs/592-incorrect-articletype-assigned-to-stories)
* Removed the need for immersive to be applied to select longread and letters
* Changed the application logic for each 'pillar' to meet design
* Added additional templates to some 'pillars' that were previously excluded.
> Changing the pecking order of template application

- projects/Mallard/android/app/src/main/java/com/guardian/editions/ophan/RNOphanModule.java
- projects/Mallard/ios/Mallard/Ophan/Ophan.m
- projects/Mallard/ios/Mallard/Ophan/Ophan.swift
- projects/Mallard/ophan/build.gradle
- projects/Mallard/ophan/src/commonMain/kotlin/ophan/Ophan.kt
- projects/Mallard/ophan/src/iosMain/kotlin/ophan/Ophan.kt
- projects/Mallard/src/services/ophan.ts
So that tracking calls made by Ophan can be properly attributed to signed-in users.
[**Trello Card ->**](https://trello.com/c/Gk4RDfwf/525-ophan-initialiser)
* Add `setUserId` function to both Android and iOS versions of the Ophan native module. This function takes a single string argument which is the new user ID to be used for subsequent tracking calls, and returns a promise which is either resolved with that ID (?) or rejected with an error.
* This function is not used from React Native land yet, but it should be called:
1. when the user logs in, and
2. immediately on app start, if the user is already logged in.
> Add setUserId function for Ophan

- projects/Mallard/android/app/src/main/java/com/guardian/editions/ophan/RNOphanModule.java
- projects/Mallard/ios/Mallard/Ophan/Ophan.swift
So that events sent to Ophan are each attributable to a particular device.
[**Trello Card ->**](https://trello.com/c/Gk4RDfwf/525-ophan-initialiser)
* On iOS set the `deviceId` to `UIDevice.current.identifierForVendor`
* On Android set the `deviceId` to `FirebaseInstanceId.getInstance().getId()`
> Properly set Ophan deviceId

- projects/backend/capi/articleTypePicker.ts
Adds Letters and Opinion to all cases since we have instances of news etc being applied to opinion content.
In testing it is common for letters being categorised in the case of 'news' so we need to apply the templates a little more aggressively. We've added in all cases as there isn't a reason not to.
> Seed the Letters and Opinion templates in all cases

- projects/Mallard/src/components/issue/issue-row.tsx
Nothing in the React tree actually depends on `isConnected`, we only care about it when the download callback runs. However, because we had a hook, every connection status change would force a re-render of the `IssueRow`.
This change removes the hook that causes the update and uses `fetch` to get the status in the callback.
> Don't re-render after netinfo update

- projects/Mallard/src/components/front/index.tsx
React seems to crap out when the length of dependencies change, this change fixes the length of dependencies to 1 so that React doesn't error, while preserving the same semantics.
> Fix dep length to 1

- projects/Mallard/ios/Mallard.xcodeproj/xcshareddata/xcschemes/Mallard.xcscheme
When building locally, the build runs in `RELEASE` mode rather than `DEBUG`. @jimhunty this came in in cfd3d4e7c89e86dd58c786ad6eb4a47698c081ec - is there any reason this was committed or was it a mistake?
> Change scheme back to debug

- projects/Mallard/src/App.tsx
- projects/Mallard/src/components/link.tsx
- projects/Mallard/src/helpers/words.ts
- projects/Mallard/src/navigation/index.ts
- projects/Mallard/src/navigation/routes.ts
- projects/Mallard/src/screens/onboarding-screen.tsx
- projects/Mallard/src/screens/onboarding/cards.tsx
- projects/Mallard/src/screens/settings/gdpr-consent-screen.tsx
- projects/Mallard/src/screens/settings/privacy-policy-screen.tsx
- Open privacy policy in a webview to prevent link being opened via deep linking by app.
- Make card slide up from bottom on ios.
- Remove cookie policy link (we don't have cookie policy, nor do we use cookies so removing for now)
> Improve privacy policy in onboarding.

- projects/Mallard/src/screens/home-screen.tsx
There's a small menu detailing issues on the device. This is for debug purposes and not on the designs.
* Make this menu only appear in dev mode
> chore: Hide downloaded issues menu

- projects/Mallard/src/authentication/auth-context.tsx
Rather than _always_ removing authentication from a user when they sign out, we should try to re-authenticate a user if their successful authentication was down to their identity account. I.e., rerun the credential provider chain (knowing the identity part will fail) and see if they authenticate with either CAS or IAP (or any new methods of auth added in future). Only if they fail will they be unauthenticated.
> Potentially re-authenticate after identity sign out

- projects/Mallard/src/components/sign-in-failed-modal-card.tsx
Modals weren't closing when clicking the close button after a failed sign in. This fixes that.
> Enusre modal is closed after failed sign in

- projects/Mallard/src/components/front/index.tsx
Should fix the iOS bug where cards stop appearing at the expense of android being a bit slower - I wish i could tell you WHY, I just know it does it :(
> Render more cards

- projects/Mallard/src/components/article/html/render.ts
- projects/Mallard/src/components/article/types/article.tsx
Only render images and media atoms when we're online (currently, for images, we don't adjust the URLs for offline viewing, this will be done in a separate PR in future).
This may also fix the `NSUrlError -1009` as it may stop the webkit trying to load anything when offline. It _seems_ to work but I want to test this in beta.
[**Trello Card 1 ->**](https://trello.com/c/tL8jQm02/664-inline-images-not-rendered-in-offline-mode)
[**Trello Card 2 ->**](https://trello.com/c/lKYpO1J5/640-bug-offline-mode-not-all-content-rendered)
> Don't display inline media offline for now

- projects/Mallard/src/screens/identity-login-screen.tsx
- projects/Mallard/src/screens/log-in.tsx
As pre Trello card, simple link to the "Already subscribed" route.
[**Trello Card ->**](https://trello.com/c/5x4IGQX8/586-activation-flow-add-a-link-to-im-already-subscribed-to-both-sign-in-screens)
> Add link to already subscribed

- projects/Mallard/src/components/layout/header/header.tsx
- projects/Mallard/src/components/weather.tsx
- projects/Mallard/src/screens/home-screen.tsx
- projects/Mallard/src/screens/log-in.tsx
- projects/Mallard/src/theme/breakpoints.ts
- projects/Mallard/src/theme/typography.ts
This PR makes some small improvements to font sizes at the breakpoint targeting smaller phones in order
avoid the design of the app on such devices looking obviously broken. This is not exhaustive.
This PR also sets the minimum breakpoint within the app to point to smaller phones by default as opposed to larger phones.
Also:
- Add missing degree icon to weather.
- Change issue picker title to 'Recent Editions'
Some Screenshots on a 5S:
> Improve rendering of app on small phones.

- projects/Mallard/src/components/article/article-image.tsx
Credits not showing on Article image on Android
[**Trello Card ->**](https://trello.com/c/bPElWriT/451-make-sure-credits-are-displayed-on-main-media-in-article)
> fix: Android fix credit

- projects/Mallard/src/components/article/types/article.tsx
- projects/Mallard/src/components/article/wrap/wrap.tsx
When heights were being updated the `Wrap` component would call `onWrapLayout` which would force re-renders. This will not not call the handler if the measurements are the same.
> Optimize onWrapLayout calls

- projects/Mallard/src/App.tsx
- projects/Mallard/src/components/BugButton.tsx
- projects/Mallard/src/helpers/diagnostics.ts
- projects/Mallard/yarn.lock
This adds a bug button to be displayed in beta. It will use the action card to ask whether or not to include diagnostics (as with the help buttons in the help menu)
[**Trello Card ->**](https://trello.com/c/nXsogFxn/532-add-a-floating-bug-report-tool-like-we-have-on-the-live-app-betas)
> Add bug button in beta

- projects/Mallard/ios/Mallard/Ophan/Ophan.m
Yellow warning box complains about Ophan. This fix is what is suggested in the RN docs.
> fix: remove the warning for Ophan in iOS

- projects/Mallard/src/screens/settings-screen.tsx
👇 
[**Trello Card ->**](https://trello.com/c/N483mVka/677-remove-the-section-about-daily-edition-from-the-bottom-of-the-settings-menu)
> chore: Remove about content from settings screen

- projects/Mallard/ios/Mallard/Info.plist
iOS Beta Build is broken because we need to set iPad to full screen. This disables multitasking. If multitasking is a required feature, then it should be looked at after launch
> fix: iOS beta build

- projects/Mallard/src/components/article/html/render.ts
- projects/Mallard/src/components/article/types/article.tsx
Render articles on Android 😱 
This seems to work on the test device I have ... it may not work on others but it definitely seems like an improvement. If this gets ok'd I'll ship it and will be looking for feedback!
After looking into the lack of Android rendering, this it seemed to be down to resource consumption and rendering issues on Android. Removing elements from a broken article caused the article to render successfully. Crucially, as long as a certain amount of content was removed it didn't matter _which_ elements where removed so that ruled out having some problematic character etc. Additionally, you could still select text on a broken article, it was just invisible, which again pointed to a rendering bug rather than something before that like invalid input.
In order to keep the …
> Use FlatList to split webviews for BlockElements

- projects/Mallard/src/components/article/html/render.ts
- projects/Mallard/src/components/article/types/article.tsx
> Revert "Use FlatList to split webviews for BlockElements"

- projects/archiver/src/indexer/summary.ts
- projects/common/src/index.ts
For downloads, we want to read from the assets object in the issue summary. This currently under each breakpoint has an array of paths. After discussion with @AWare, it was clear that this wont be an array but be one path. It makes more sense to make this change at the type level and it means we wont need logic to manage arrays.
> chore: Issue Summary type change

- projects/Mallard/Makefile
- projects/Mallard/android/build.gradle
beta was not building
- This adds a version required by react-native-inappbrowser-reborn to work with androidx. 
- This adds more memory to gradle and notes that the makefile targets are "phony" as they do not relate to filenames.
> Fix android beta build

- projects/Mallard/src/helpers/settings/defaults.ts
- projects/aws/lib/aws-stack.ts
The main aim of this is to use a guardian owned domain rather than baking cloudfront domains into the app. At present this completely removes cloudfront from the loop but this could be added again later.
[**Trello Card ->**](https://trello.com/c/a9oY1ITn/652-proper-domain-names-for-backend) 
* Take preview domain and ACM cert as parameters
* Create custom domain and attach to API gateway endpoint
> Add a custom domain to the preview API gateway

- projects/Mallard/src/helpers/settings/defaults.ts
#466 is now out and working as expected in CODE. This changes the PROD preview to point to a guardianapis.com domain too.
[**Trello Card ->**](https://trello.com/c/a9oY1ITn/652-proper-domain-names-for-backend)
* Change PROD preview cloudfront location to use the API gateway custom domain
> Update PROD preview endpoint to use guardian domain name

- projects/Mallard/src/components/front/index.tsx
- projects/Mallard/src/screens/article/slider.tsx
- projects/Mallard/src/screens/issue-screen.tsx
Fixes the the attached trello card.
[**Trello Card ->**](https://trello.com/c/qpmxzFNN/622-issue-invisible-until-scroll-then-incorrect-issue-date-visible)
If this degrades performance then it seems to be to do with how the custom `transitionConfig` in underlay is working here: https://github.com/guardian/editions/blob/65465eaccd54dac4524135a7e5d5d4b617ae0627/projects/Mallard/src/navigation/navigators/underlay.tsx#L108
I'm assuming that the custom animation is causing the articles to be considered "clipped" in some way and the scrollview isn't detecting when the translation back on screen.
> Render issue when revisiting the issue

- projects/Mallard/src/components/front/index.tsx
This fixes issues rendering the wrong things on the wrong date. This now makes the loading of a new issue a bit gross as if they're both in the cache you get a moment where you see the old one. TBC how to fix this.
[**Trello Card ->**](https://trello.com/c/bw4bCapf/591-wrong-edition-shown-for-selected-issue-date)
> Fix bad memoisation

- package.json
- projects/archiver/package.json
- projects/backend/package.json
- script/make
The build relies on GNU make but only ever tries to use `make` rather than `gmake`, which is where GNU make lives when brew installed opn macOS. 
This script tries both and prints a helpful error if you don't have `gmake` but are on macOS.
> Deal with the difference between make and gmake

- script/make
Change the make script to fallback to using make regardless of whether we think it should be new enough.
> Fix make script to try make regardless

- projects/Mallard/src/App.tsx
- projects/Mallard/src/__mocks__/@react-native-community/netinfo.js
- projects/Mallard/src/authentication/auth-context.tsx
- projects/Mallard/src/components/article/types/article.tsx
- projects/Mallard/src/components/toast/net-info-auto-toast.tsx
- projects/Mallard/src/hooks/use-net-info.tsx
While debugging some Android issues I noticed that the `useNetInfo` hook forces a re-render on mount for any component that uses it. This changes fixes that by storing the `NetInfoState` in one place in the context and as such ensures that this re-render only happens on app load and never again.
> Stop net info re-renders on mount

- projects/Mallard/src/components/article/types/article/webview.tsx
- projects/Mallard/src/components/layout/header/header.tsx
- projects/Mallard/src/hooks/use-issue-id.tsx
- projects/Mallard/src/hooks/use-issue.ts
- projects/Mallard/src/screens/home-screen.tsx
- projects/Mallard/src/screens/issue-screen.tsx
Prior to this change `useIssueCompositeKey` would only return the key from the navigator. This wasn't necessarily the key that was being displayed, as we may not have a key in the navigator but our fetch strategy went and decided on an issue anyway.
This ensures that `useIssueCompositeKey` is the sole place where "issue picking' takes place. Then both our fetcher and consumers of the hook have the same value.
This could definitely do with a refactor but, given the fetching primitives that exist for this data are largely wrapped in hook-like constructs, it will take a bit longer than I'm prepared to give it right now.
I've also remove some unused issue dependencies from some components.
* Change 1
* Change 2
> Ensure we always have an issue id in context

- projects/Mallard/src/navigation/navigators/underlay.tsx
In an effort to improve performance, im looking through some of the warnings. This warning came up a lot on iOS and it was particularly focused on this piece of code that has been removed.
It looks like its never used, but would like @walaura to check.
Checked on both iOS and Android and there is no visual regression.
> fix: Shaddow Warning

- projects/backend/__tests__/fronts.spec.ts
- projects/backend/capi/__tests__/articleImgPicker.spec.ts
- projects/backend/capi/articleImgPicker.ts
- projects/backend/capi/articles.ts
- projects/backend/capi/assets.ts
- projects/backend/controllers/fronts.ts
- projects/backend/fronts.ts
- projects/common/src/index.ts
This PR changes no behaviour. Instead we restructured some image selection code during work to understand its behaviour. As part of this a number of tests were also added.
Suggest that this gets merged now prior to us starting to actually change the code here.
[**Trello Card ->**](https://trello.com/c/Y9de0IDo)
* Resturcture and add tests
> (SH & MK) media handling changes and tests

- projects/Mallard/ios/ReleaseStream.m
Remove the noise in the warnings.
> fix: Remove yellow box warning for ReleaseStream

- projects/Mallard/android/app/src/main/AndroidManifest.xml
Splash screen activity added as a result of a tutorial meant a duplicate icon. Activity removed and down to one icon.
For reference: https://stackoverflow.com/questions/47823186/why-there-are-show-two-icon-after-installed-in-the-android
> fix: Double Android Icon

- projects/Mallard/src/hooks/use-issue-id.tsx
- projects/Mallard/src/screens/home-screen.tsx
Fix a regression where the back button on the issue list would always take you to the most recent issue.
[**Trello Card ->**](https://trello.com/c/Ievsx3zu/749-issue-picker-if-one-clicks-the-shevron-and-goes-back-doesnt-go-back-to-the-ediotion-that-someone-was-previously-looking-loads-th)
> Fix back button on IssueList

- projects/Mallard/src/components/article/article-header/types.ts
- projects/archiver/media.ts
- projects/backend/capi/__tests__/byline.spec.ts
- projects/backend/capi/byline.ts
- projects/common/src/index.ts
When a cutout is overriden or set by the fronts tool `thumbnail` is not available. Also, `thumbnail` is not used. Finally it is largely a legacy field in CAPI that isn't really used by dotcom either. This removes it from our code base.
[**Trello Card ->**](https://trello.com/c/Y9de0IDo)
* Remove `thumbnail` from `bylineImages`
* Add extra filter to only look for images that have a cutout
> Remove unused thumbnail which makes it easier to override cutout

- projects/Mallard/src/components/front/items/image-items.tsx
The opinion cards were mistakenly bringing in the main media when they should show contributor cutouts. Note that this doesn't have a fallback which results in many cards not having an image at all.
[**Trello Card ->**](https://trello.com/c/Y9de0IDo)
* Switch to use byline cutout
**Before**:
**After**:
> Switch to use the byline image for opinion

- projects/Mallard/src/helpers/settings/defaults.ts
- projects/archiver/media.ts
- projects/archiver/src/frontTask.ts
- projects/archiver/src/generateIndexTask.ts
- projects/archiver/src/indexer/summary.ts
- projects/archiver/src/issueUploadTask.ts
- projects/archiver/src/upload.ts
- projects/archiver/zipper.ts
We need to introduce a CDN in the path between app and S3 bucket for perfomance/cost reasons but primarily so that we can point the app at a domain we control rather than directly at a bucket.
The `maxAge` we have selected here is one week for everything except the `issues` index in the root which is one minute. One minute might prove to be frustrating so happy to lower this (or send a PURGE when we write it). One week should be fine as the paths all contain a version which is unique and will never be modified.
[**Trello Card ->**](https://trello.com/c/a9oY1ITn)
* Add CacheControl field to all locations we use s3 upload in archiver
* Add mime type to the zip uploader as it was missing
> Add cache control headers to files uploaded to S3

- projects/backend/capi/articleTypePicker.ts
To support the application of the review template on article's whose pillar is news.
> Support Review article headers on news pillar articles

- projects/Mallard/src/components/front/items/image-items.tsx
- projects/Mallard/src/components/front/items/items.tsx
- projects/Mallard/src/components/front/items/super-items.tsx
In #553 PR we introduced `trailImage` (to be used on fronts) as distinct from `image` (to be used in content). This PR switches to use `article.trailImage` on fronts cards instead of  `article.image`.
[**Trello Card ->**](https://trello.com/c/Y9de0IDo)
example:
> (SH & MK) switch to use trailImage on fronts cards

- projects/Mallard/src/theme/typography.ts
Reverting the change to the small headline size. 
* Change 1
* Change 2
> tweaked sizes back

- projects/Mallard/src/helpers/settings/defaults.ts
- projects/archiver/src/generateIndexTask.ts
- projects/archiver/src/indexer/summary.ts
- projects/archiver/src/upload.ts
Follow up to #464 that switches the PROD API endpoint to use the new domain and CDN.
[**Trello Card ->**](https://trello.com/c/a9oY1ITn)
* Reduce `/issues` max age from `60` to `5`
* Switch PROD endpoint to own domain name
> Switch PROD backend host and decrease index cache

- projects/Mallard/src/helpers/files.ts
- projects/Mallard/src/helpers/settings.ts
- projects/Mallard/src/helpers/settings/defaults.ts
The zip prefix is currently hardcoded but doesn't need to be and restricts how we arrange the file space by doing so. Not having that gives more flexibility.
> Remove hardcoded zip prefix

- projects/Mallard/fastlane/Fastfile
Reverts guardian/editions#579 - nothing to see here ... 🙄
> Revert "Change android release to supply beta"

- projects/Mallard/src/screens/issue-screen.tsx
When we opened / closed the issue picker we would always re-render the whole issue screen. There are many sub-issues here - not least of which, issue screen could probably be quicker to render than it is (more memoization of the most often rendered components would help here).
Not sure this will totally fix the issue but it'll definitely help as we were re-rendering the issue screen when _opening_ the issue picker, which probably caused issues on slower devices.
> Don't re-render on all nav changes

- projects/Mallard/src/components/front/collection-page.tsx
- projects/Mallard/src/components/front/helpers/helpers.ts
- projects/Mallard/src/components/front/index.tsx
- projects/Mallard/src/helpers/debug.ts
This ensures cards render only once (instead of twice previously) on a normal issue load.
Additionally added a helper for debugging prop diffs.
Because of `Context`, things may still be re-rendering further down in the tree but will check this separately from this PR.
> Memoize cards and add debug helper

- projects/Mallard/src/components/front/index.tsx
The main fix here is `initialNumberToRender`, without this number set, for some reason it was rendering 6 cards for each front, essentially making the FlatList redundant 🤷‍♂ 
Also, `windowSize` should well be odd as means the amount of things rendering are the window (which is equal to one of the 5 units) plus `n` either side.
`maxToRenderPerBatch` seems fine at 2 but can push that back up if needs be
and `extraData` would cause a re-render of this list every single time as it compares by reference equality. It's essentially a sentinel as to whether to change or not, comparing by reference equality.
> Slight tweaks to flatlist

- projects/Mallard/src/helpers/diagnostics.ts
After speaking with Gwyn on the user help team, it was deemed more helpful to have the Build number rather than commit id in the subject.
> Change subject for diagnostics

- projects/archiver/src/generateIndexTask.ts
- projects/backend/common.ts
- projects/common/jest.config.js
- projects/common/package.json
- projects/common/src/__tests__/helpers.spec.ts
- projects/common/src/helpers.ts
- projects/common/yarn.lock
The issue index file can under some circumstances list indexes out of order. This mainly happened if an old issue was republished. This PR sorts the issues just prior to generating the index file.
This was broken by a change in #520 which introduced a sanity check for the newly published edition and as a side effect reordered the index.
[**Trello Card ->**](https://trello.com/c/Gb2i39HP)
* Add test framework to common
* Add sorting helper for issue summaries
* Sort issues when generating index
> Sort all of the issue summaries prior to generating the index file

- projects/Mallard/src/components/front/index.tsx
This stops re-renders for changes further up the tree that are irrelevant. As a proxy for re-renders, the headline of each article on renders once on a load as opposed to 3/4 times yesterday.
> Memoize fronts

- projects/Mallard/ios/Mallard/Info.plist
- projects/Mallard/src/constants.ts
I've created a new app id in the Guardian FB account. This change goes along with that to move the app over to that new id for authentication. It seems to work ...
> Change fb app id to new Editions app

- projects/Mallard/src/components/front/collection-page.tsx
Largely this is to solve images overflowing the card but it will stop anything overflowing a card which seems like a 👍 
[**Trello Card ->**](https://trello.com/c/84Y6zDQf/742-cover-card-depth-issues)
> Hide card overflow

- projects/Mallard/src/hooks/use-api.ts
As an interim solution, we do not use the cache to get the issue summary. This way we always get the latest. This screen will now not work offline.
> feat: Always fetch Issue Summary

- projects/Mallard/src/App.tsx
We don't want react navigation to handle _any_ deep links. As a precaution I'm explicitly turning it off as it _may_ have caused some of the social sign in issues we had earlier today.
As per the docs: https://reactnavigation.org/docs/en/deep-linking.html#disable-deep-linking
> Disable react navigation URL handling

- projects/backend/utils/crossword.ts
This fixes the images on fronts for crossword cards which was broken when `trailImage` was introduced in #565. The crossword card images are explicitly set in the backend but were overriding `image` instead of `trailImage`.
[**Trello Card ->**](https://trello.com/c/nN2ql7qK)
> Populate trailImage instead of image with crossword card images

- projects/Mallard/src/components/article/types/gallery.tsx
- projects/Mallard/src/paths/index.ts
There was some concern that image asset handling would not always get images from the correct location - in particular that it might fetch an asset directly from the image resizer.
An audit revealed that the `mediaBackend` field is no longer used 🍾 but that the `GalleryImage` component would not correctly load images when offline 😞
This PR removes the unused field and migrates GalleryImage to use ImageResource which deals with figuring out where an image should be loaded from.
[**Trello Card ->**](https://trello.com/c/hILDsCZK)
* Remove unused field from `APIPaths`
* Change `GalleryImage` component to use `ImageResource`
> Finish up image fetching

- projects/Mallard/scripts/watch-html.command
- projects/Mallard/scripts/watch-html.js
This prevents `watch-html` from endlessly spawning terminals.
> Dont spawn lots of windows

- projects/Mallard/src/components/article/html/images.ts
- projects/Mallard/src/components/article/html/line.ts
they were over the line and now they aren't
> Fix image alignments on new webviews

- projects/Mallard/src/components/article/index.tsx
- projects/Mallard/src/helpers/settings.ts
- projects/Mallard/src/helpers/settings/defaults.ts
- projects/Mallard/src/screens/settings/dev-zone.tsx
Roll out the non-wobbly headers to everybody as a default - this doesn't remove any of the old code, just flips the switch to on as a default (and renames it so everybody will get it as on in the next upda)
> Everybody gets the new headers

- projects/archiver/src/services/status.ts
- projects/archiver/src/tasks/indexer/helpers/get-published-version.spec.ts
- projects/archiver/src/tasks/indexer/helpers/get-published-version.ts
- projects/archiver/src/tasks/indexer/helpers/local.ts
- projects/archiver/src/tasks/indexer/helpers/summary.ts
- projects/archiver/src/tasks/indexer/index.ts
To review if we are picking the most recent valid issue version while publishing
This PR ads test coverage for that
- adding unit tests for `getPublishedVersion` function
- small renames and refactor
> test coverage for picking most recent valid issue version

- projects/Mallard/src/hooks/use-api.ts
- projects/archiver/src/tasks/indexer/index.ts
- projects/backend/index.ts
- projects/common/src/index.ts
The AUS and UK editions are in our rear view mirror but we currently have only one issue index location. Having one index for each separate edition makes more sense so this makes that change.
For backwards compatibility we put a copy of the index in the old location for now so that we don't unnecessarily break clients.
An issue will need to be republished to create the new index after deployment.
> Move the index file to be namespaced ready for multiple editions

- projects/backend/index.ts
#602 dealt with supporting existing clients for published endpoints but not preview endpoints. This ensures that existing clients will continue to work.
> We also need to provide the legacy index location for preview

- projects/Mallard/src/components/front/index.tsx
- projects/Mallard/src/screens/issue-screen.tsx
we were rendering a lot of offscreen views with a ton of images, this keeps them under check. In lower-end devices it means there will be a bit of a stutter'' when scrolling, this is good – it means the main thread is unloading images behind the scenes and freeing up memory!
on an iPad 4 this is the difference bw crashing after a minute and running smoothly
> Fix fronts memory leeks

- projects/backend/index.ts
- projects/backend/package.json
- projects/backend/types/express-list-endpoints.d.ts
- projects/backend/yarn.lock
I want to easily check which endpoints are supported by Editions backend 
For documentation and testing purposes
* adding `express-list-endpoints` library
* making root path `/` as Editions backend docs (endpoints lists)
You can run app locally and access: http://localhost:3131/docs
> making Editions backend self documenting API

- projects/backend/README.md
that will simplify the procedure of running backend locally, so that command which set env variables can be copy pasted and executed in one line
> backend README simplifying for copy paste lovers

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/components/front/image-resource.tsx
- projects/Mallard/src/hooks/use-image-paths.ts
- projects/Mallard/yarn.lock
Team, turns out we were using HUGE images all over the place
With this PR we now scale images before sending them off to RAM, not doing so was hurting older end devices, especially iPads with their huge screens. The resizer scales them down to the exact width (accounting for retina displays) that they will be displayed at. This all happens on device so we don't get network gains or anything, we just free up ram.
There's a tradeoff involved: scaling down the images causes a super minor CPU spike and calculating the width means that we will, in the best case scenario, miss a frame when rendering images. In real world use the CPU spike is insignificant compared to everything else going on in first load (plus its native code so uses a different thread) and the frame dropped is insignificant …
> Massive memory gainz

- projects/Mallard/src/components/article/types/crossword.tsx
This stops crosswords from rendering the data from the previous crossword.
> Remount crosswords on change

- projects/Mallard/src/screens/issue-screen.tsx
The `overflow: hidden` broke scrolling on Android. @walaura I'm assuming this was put in to try and solve the performance issues, but I'm assuming `renderClippedSubviews` will more than account for this so it seems safe to remove.
> Remove overflow

- projects/Mallard/src/helpers/files.ts
- projects/Mallard/src/helpers/screen.ts
- projects/Mallard/src/hooks/use-image-paths.ts
- projects/Mallard/src/paths/index.ts
The `<Image>` component on android needs a uri and not a path. 
With #637 we can just get a uri off the returned resize object instead of manually synthesizing one.
Also `fs.mv` only supports files on android and cannot move/rename directories. 
So this pr now uses the current breakpoint to fetch local images. 
This now persists the breakpoint in Asyncstorage.
> Fix downloaded images on android

- projects/archiver/src/tasks/zip/helpers/zipper.ts
- projects/archiver/src/tasks/zip/index.ts
we were fetching all the breakpoints with tablet.
this should significantly reduce tablet bundle size (well, yes)
> dont add tablet.* to tablet.zip

- projects/Mallard/src/components/article/html/render.ts
> Bring video caption style inline with images.

- projects/backend/__tests__/application.spec.ts
- projects/backend/application.ts
- projects/backend/controllers/__tests__/issue.spec.ts
- projects/backend/controllers/fronts.ts
- projects/backend/controllers/image.ts
- projects/backend/controllers/issue.ts
- projects/backend/fronts.ts
- projects/backend/index.ts
- projects/backend/issue.ts
- projects/backend/package.json
- projects/backend/utils/__tests__/issue.spec.ts
- projects/backend/utils/issue.ts
- projects/backend/yarn.lock
We want to be able to support multiple types of editions like (Daily Editions, American Edition, Australian Edition ...)
This PR makes edition type as a path param
and use this in downstream function calls
[**Trello Card ->**](https://trello.com/c/qSmpzrIJ/128-backend-to-support-multiple-editions)
* making edition type as path param
* adding contract tests that ensures if expected endpoints are registerd
> Editions backend: support multiple editions

- projects/aws/lib/aws-stack.ts
- projects/aws/lib/step-function.ts
For the purpose of debugging issues it's useful to ensure all of the lambdas are tagged. This adds tags to the backend lambdas and lines up all tags to be consistent.
> Add tags to backend lambdas and make all tags consistent

- projects/Mallard/src/hooks/use-image-paths.ts
Because the resizer does not support [http urls](https://github.com/bamlab/react-native-image-resizer/blob/master/android/src/main/java/fr/bamlab/rnimageresizer/ImageResizer.java) on android. So any attempt to show a remote image on android was causing an exception. This reverts remote images only to being shown at their native size.
> Don't resize remote images.

- projects/backend/capi/articles.ts
- projects/backend/utils/crossword.ts
CAPI appears to return a string for the crossword type - you can see this when using teleporter on a crossword. However, we fetch the CAPI data as a thrift format. Internally, Thrift enums are represented as numbers and only thanks to [this line](https://github.com/guardian/content-api/blob/801ae0b3bc0554cee18d4e56f1e88757628e5799/porter/src/main/scala/com.gu.contentapi.porter/model/codecs.scala#L79) in CAPI do they get converted to strings. We don't have a codec for doing this in the TS / Thrift infra that we use so we, confusingly, receive the number.
The fix was easier than the find here ...
> Fix crossword types

- projects/Mallard/src/components/article/types/crossword.tsx
- projects/editions-crossword-renderer-app/src/index.js
- projects/editions-crossword-renderer-app/src/js/components/CrosswordView.jsx
Previously every single crossword was getting the same cache key (probably '') because we weren't passing an `id` into the crossword component. Doing that keeps persistence for different crosswords but ensures it only loads on the _right_ ones 👏
> Pass id down for persistence

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
We are getting warnings in Google Play console about a Path Traversal Vulnerability. This is caused by `react-native-zip-archive`. 
There is an open issue around this at the moment, and as a result, is not resolved in the latest version. However, there is a suggestion to downgrade to remove the error. https://github.com/mockingbot/react-native-zip-archive/issues/170
This is what this PR does.
[**Trello Card ->**](https://trello.com/c/MXoqBEpK/844-security-warning-on-android-playstore)
> fix: Path Traversal Vulnerability

- projects/archiver/src/invoke/index.spec.ts
- projects/archiver/src/invoke/index.ts
- projects/archiver/src/invoke/parser.spec.ts
- projects/archiver/src/invoke/parser.ts
- projects/archiver/src/tasks/front/index.ts
- projects/archiver/src/tasks/indexer/helpers/get-issue-summary.ts
- projects/archiver/src/tasks/upload/index.ts
- projects/archiver/src/tasks/zip/index.ts
- projects/archiver/src/utils/s3.ts
- projects/aws/lib/aws-stack.ts
- projects/backend/common.ts
We want to be able to publish multiple types of editions like:
- Daily Edition
- American Edition
- Australian Edition
- Training Edition
Now we support only Daily Edition
This PR enable that in archiver step functions tasks invoker
[**Trello Card ->**](https://trello.com/c/qSmpzrIJ/128-backend-to-support-multiple-editions)
* support multiple editions on invoker (invokes archiver step functions)
* Tag added to this lambda function
* unit tests for invoker
* more logs for assurance
> support multiple editions in Invoker

- projects/archiver/src/tasks/issue/index.ts
We want to fail fast archiver step functions if issue have no fronts with relevant error message 
* Add throw error
- before
- after
> Archiver: Stop issue tasks if there is no fronts in issue

- projects/Mallard/src/components/article/types/gallery.tsx
This was triggering a warning (and is indeed broken) if no `key` is provided. This fixes that, though using `index` we don't provide proper reconciliation. I think it's fine though as I expect this list of elements not to be changing dynamically.
* add `key` in render function of `Gallery`
No warning shows up on the page where I was getting it initially:
> gallery.tsx: add missing 'key' in rendered collection

- projects/archiver/src/invoke/parser.ts
- projects/archiver/src/services/editions-mappings.ts
- projects/archiver/src/services/pub-status-notifier.ts
- projects/archiver/src/services/status.ts
- projects/archiver/src/services/task-handler.spec.ts
- projects/archiver/src/tasks/indexer/helpers/get-issues.ts
- projects/archiver/src/tasks/indexer/helpers/summary.ts
- projects/archiver/src/tasks/notification/helpers/device-notifications.ts
- projects/backend/controllers/issue.ts
- projects/backend/utils/__tests__/issue.spec.ts
- projects/backend/utils/issue.ts
- projects/common/src/index.ts
We want to be able to publish multiple types of editions like:
- Daily Edition
- American Edition
- Australian Edition
- Training Edition
This PR makes Edition parameter type typeSafe
> making edition parameter type safe in archiver

- projects/Mallard/ios/Podfile
- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/screens/article/slider.tsx
- projects/Mallard/yarn.lock
React Native is giving warning that this component will be getting out of core and into the community group. This switches the ViewPager to the `@react-native-community/viewpager` one so that we don't have to think about it before next React Native upgrade.
* `yarn add @react-native-community/viewpager`
* `react-native link @react-native-community/viewpager`, then I had to fix the Java file by hand.
* Change slider.tsx to use the new component.
> ArticleSlider: switch to the community-scoped ViewPagerAndroid

- projects/Mallard/src/components/layout/slide-card/header.tsx
- projects/Mallard/src/components/layout/slide-card/index.tsx
This is an intermediate fix for swiping down early on when viewing an article closing the article - even when not at the top.
This happens because the `UIWebView` version of the webview does not send scroll events until after the scroll has finished (https://stackoverflow.com/a/46542445/609907). This is fixed in the WebKit version of the webview. However, changing our webview at this late stage seems a bit dangerous so as an intermediate fix we've opted to only be able do dismiss from the top.
You can tell when we think a browser is at the top of an article by when the little grey line under the slide appears. When a user is at the top of the article it is invisible, when the user scrolls down, just as the inertia stops, the bar appears, which means our webview has reported a scroll …
> Only allow dismiss at the top of the card

- projects/Mallard/src/screens/issue-screen.tsx
This speeds up scroll back to previous speed.
> Remove deceleration rate

- projects/Mallard/src/components/layout/slide-card/header.tsx
This stops the pan responder from becoming the active one when the user taps. This allows the gesture to bubble up to the `TouchableWithoutFeedback` above that will then dismiss the card.
> Don't handle taps with the swipe pan responder

- projects/Mallard/src/screens/settings/default-info-text-webview.tsx
Display wasn't very good, this adds some padding after the title, and at the left of bullet points (see screenshot)
[**Trello Card ->**](https://trello.com/c/bota9ToR/432-settings-menu-terms-conditions-faq)
> default-info-text-webview.tsx: fix margin for header and bullet list

- projects/backend/capi/articleTypePicker.ts
In previous PR we forgot that these are arranged by pillar not by front.
Demoted Obit below series everywhere.
Other lives have typically terrible images supplied, so we push them to the standard template by making series trump obits. (Other lives is a series).
> Made series trump obit everywhere.

- projects/Mallard/ophan/src/commonMain/kotlin/ophan/Ophan.kt
* Set `useDebug` flag to `false` which means data is sent to https://ophan.theguardian.com/mob instead of https://ophan.theguardian.com/mob-loopback
I made a debug build with this change, ran it on an emulator and @rtyley confirmed it was received and processed succesfully https://github.com/guardian/ophan/pull/3449#issuecomment-541094306 🎉
> Send traffic to live Ophan endpoint

- projects/Mallard/src/helpers/push-notifications.ts
Follow on from my previous PR.
If for any reason the download is unsuccessful and causes an error (e.g. not enough space) then this will now finish the background process on iOS rather than leave it open.
> fix: If error, end the background process on iOS

- projects/Mallard/src/screens/issue-screen.tsx
The Chevron was occasionally disappearing on Android. This fix makes sure we don't hide the Chevron on devices that don't use the overlaid card at the bottom of the issue picker. This includes all Android devices.
> Always show chevron for some devices

- projects/Mallard/src/screens/issue-screen.tsx
_Some_ janky behaviour in the vertical scrolling was caused by not accounting for the height of the slider in the `getItemLayout` prop. This fixes that jank.
> Account for sliders in FlatList

- projects/Mallard/src/helpers/__tests__/issues.spec.ts
- projects/Mallard/src/helpers/files.ts
- projects/Mallard/src/helpers/issues.ts
Yesterday the chance to `matchSummmaryToKey` meant that when downloading "todays" issue, we were not able to match the key as this was a date - not a date prefixed.
There is a test to cover this change.
> fix: Download Today's Issue

- projects/Mallard/src/helpers/files.ts
Given that when we run our background notifications on iOS, we await the download and then send a message to the OS that we've finished with our download, it seems like a good idea to chain the unzip part of the process into the download promise, so that the promise doesn't resolve until it's unzipped.
This may not matter in practice but currently iOS notifications are being received but the issues are not appearing on the device, so this seems like a worthwhile change.
> Ensure download promise waits for unzip

- projects/Mallard/src/components/front/items/image-items.tsx
- projects/Mallard/src/components/stars/stars.tsx
Stars [are missing on front page](https://trello.com/c/1FHZrJg0/649-reviews-show-stars-on-fronts-card). This is the first step towards having these show up, starting with the small image+text blocks.
A follow up diff will add support for star ratings on full-width image blocks, like the one showing up generally on the first page of the Culture front.
Android, no ratings:
Android, with ratings:
iOS/iPad, no ratings:
iOS/iPad, with ratings:
> front/items: display rating stars on top of image items

- projects/Mallard/src/authentication/services/iap.ts
- projects/Mallard/src/constants.ts
This is redundant and broke the first release. This isn't required to fix the next build (simply removing the env variable from our TC deploy will fix this).
> Remove dependency on env variable

- projects/Mallard/src/helpers/push-notifications.ts
To give us more confidence pushes are being received in testflight.
This adds Messaging API tracking higher up and some junk Ophan tracking.
> fix: Faster push tracking

- projects/Mallard/src/hooks/use-screen.ts
this fixes this issue:
https://trello.com/c/iEtMz9TH/867-video-stretched-on-ios-and-android-crash-on-orientation-change
this means we will never relayout on smaller screens. For now this is ok
because our screen size assumptions are a 1:1 match with iphone/ipad and
a good enough™ match on android
a more elegant fix would be to detect when a full screen video/photo
is playing, basically anything that enables rotation when
things below it should not rotate, and not relayout then.
i've literally dumped this as a comment cuz it's not ideal AT ALL but itll do
> Play landscape videos

- README.md
- projects/aws/lib/aws-stack.ts
- projects/backend/s3.ts
This will allow the CODE stack to read from the PROD editions, which will allow more thorough testing. 
To switch, the frontsStage param will need to be changed to PROD and the frontsARN changed to the PROD one. (unless we add prod read to the code role)
> Allow CODE to read from PROD fronts.

- projects/Mallard/src/helpers/issues.ts
All the other months are full-length, doesn't make sense for these to be abbreviated (or we should abbreviate September, for ex.)
Trivial change, just content.
> issues.ts: remove abbreviation for Jan and Feb

- projects/Mallard/src/helpers/date.ts
- projects/Mallard/src/helpers/issues.ts
Edition title was wrong. We were using `moment()` incorrectly by setting the timezone after parsing, which would convert the local midnight to the London. Instead, we need to parse the original date as **being** in London timezone, then `date()` and other functions on the object will correctly return a London-based interpretation.
https://trello.com/c/GQ1diW9N/767-name-of-editions-in-the-editions-picker-are-incorrectly-affected-by-the-users-time-zone
1. On Android, go to Settings app, System, set timezone to something such as China/Shanghai.
2. Open Daily editions app
3. Observe title: it correctly shows today's date (in London)
4. Open list of editions: it correctly shows the edition titles.
> issues.ts: fix timezone usage

- projects/Mallard/src/components/article/html/components/header.ts
CSS oneliner. Checked that the image info button works (cuz its a button)
@paperboyo will be thrilled about this
> Prevent clicks on byline links

- projects/Mallard/src/components/article/html/article.ts
- projects/Mallard/src/components/article/html/components/header.ts
- projects/Mallard/src/components/article/html/components/media-atoms.tsx
- projects/Mallard/src/components/article/html/css.ts
- projects/Mallard/src/components/article/types/article/helpers.tsx
We want to show [videos when available as the main header media of an article](https://trello.com/c/xzHCTsMr/590-video-as-main-media).
1. Open the Wed 23 October edition, then open 1st Top Stories articles (*"MPs reject Boris Johnson's attempt [...]"*).
2. Observe: video shows up correctly.
3. Press and play the video, notice it plays correctly.
4. Navigate away, come back, observe it still works.
5. Close app, go in Aeroplane mode, open app.
6. Open the same article, notice that the video fails to load. (Maybe we need some design here? Should we not show the video? What if people reconnect when reading the article? etc.) **This could be changed and improved on later on, so I'd recommend we ship this as-is for now and discuss with relevant parties.**
7. Notice in-article videos are still …
> Render main media atom in articles when available

- projects/Mallard/src/navigation/helpers/base.tsx
- projects/Mallard/src/navigation/navigators/underlay.tsx
- projects/Mallard/src/navigation/navigators/underlay/positions.tsx
- projects/Mallard/src/navigation/navigators/underlay/transition.tsx
- projects/Mallard/src/screens/issue-screen.tsx
Wow that's a mouthful. This makes the drawer (iPad and iPhone) 'swipeable' (it doesn't actually respond to swipes but it responds on touch down. Happy to add swipes later).
This PR also removes some of the button hiding code on the issue header because the logic for showing it is a bit of a mess and the reason I hid it in the first place was to not give the impression that area is tappable when it's not. Now it is!
[**Trello Card ->**](https://trello.com/c/ye9waNmn/917-fix-the-design-of-the-drawer-on-archive-so-users-can-swipe-it-up)
- On iPhone+iPad, open the issue list, tap or swipe on the visible parts of the issue to bring back
- On iPhone+iPad, open the issue list, tap or swipe elsewhere and confirm rest of buttons respond
- On android, verify behaviour remains identical, verify …
> Swipe on the issue from the issues menu to close the menu

- projects/archiver/src/tasks/front/index.ts
- projects/archiver/src/tasks/image/index.ts
Having images in the front task output was causing step function to fail due to output being too large.
> Move image download to image task

- projects/Mallard/src/helpers/push-notifications.ts
Remove the badge number as raised by a number of customer complaints. 
My hope is setting to 0 will clear it as there is no clear method in the library. I believe @alfavata has a device that has this existing issue.
> feat: Reset the notification badge number

- projects/Mallard/src/screens/settings-screen.tsx
As per the trello card.
There is a function that returns a version which was being used previously. This is being used in a number of places and is not consistent with this. However, this is used more for diagnostics including a commit hash. It seemed sensible to keep that as it was.
[**Trello Card ->**](https://trello.com/c/CT3FVgpV/912-android-ios-can-we-get-version-number-in-the-settings-to-match-the-version-number-in-the-google-play-store-apple-store)
Go to settings screen and look at `Version` which appears under `Credits`
> fix: Show a more readable version in the settings

- projects/Mallard/src/screens/settings/default-info-text-webview.tsx
- projects/Mallard/src/screens/settings/privacy-policy-screen.tsx
Put back proper links into our webview, in this case the Privacy Policy. We got rid of them because they would open in the webview itself, with no navigation control. This changeset makes it so it opens externally (ex. the system browser).
1. Open the Privacy Policy page
2. Click on the "privacy policy" link (the one for the website).
3. Observe: it opens in the browser
4. Repeat steps 1-3 for Android and iOS.
> DefaultInfoTextWebview: open links outside of webview

- projects/Mallard/src/App.tsx
**Please review #774 first**
This reworks how we clear issues and download todays issue. Rather than only happening once from a "killed" state, this is now moved to an "active" state. So every time the app is "for-grounded" it will look to clear old issues, wait until that is completed, then check the cache clear, and if thats ok then download an issue.
This makes the file system access more synchronous meaning less room for error.
> Fix: Download todays edition

- projects/Mallard/src/helpers/push-notifications.ts
Improve may be a strong word here...
We are not sure why Push Notifications are not doing the whole job. This PR adds more tracking points so we can see what is going on.
Additionally, this removed the early return which may be blocking the download if for some reason the notification is being triggered twice.
> chore: Improve push notifications

- projects/backend/capi/articles.ts
- projects/common/src/index.ts
Having the web URL allows sharing for a majority of articles. It might be sufficient to have sharing only for this general case and not work on the print-only article case for now.
1. `yarn preview`
2. Open `http://localhost:3131/daily-edition/2019-10-14/preview/front/National`, check a few articles for having the correct `webUrl`
> backend: expose webUrl for non-print articles

- projects/Mallard/src/components/issue/issue-row.tsx
Previously we showed the tick in the issue list when the folder was there. This first occurs when the text is downloaded and unzipped. There is now another check for when the media file exists in that folder. That only exists after images have downloaded and been unzipped.
[**Trello Card ->**](https://trello.com/c/K33qHBL8/927-download-of-an-edition-the-icon-should-only-change-once-both-content-and-images-have-been-downloaded-completly)
> fix: Set the tick in the issue screen when we have images

- projects/Mallard/package.json
- projects/Mallard/src/components/article/html/components/images.ts
- projects/Mallard/src/components/front/image-resource.tsx
- projects/Mallard/src/components/front/items/image-items.tsx
- projects/Mallard/src/components/front/items/items.tsx
- projects/Mallard/src/components/front/items/trail-image-view.tsx
- projects/Mallard/src/hooks/use-image-paths.ts
- projects/Mallard/src/paths/__tests__/index.spec.ts
- projects/Mallard/src/paths/index.ts
- projects/archiver/src/tasks/front/helpers/media.spec.ts
- projects/archiver/src/tasks/front/helpers/media.ts
- projects/archiver/src/tasks/front/index.ts
- projects/archiver/src/tasks/zip/helpers/lister.ts
- projects/archiver/src/tasks/zip/helpers/zipper.ts
- projects/archiver/src/tasks/zip/index.ts
- projects/archiver/src/utils/backend-client.ts
- projects/backend/__tests__/application.spec.ts
- projects/backend/application.ts
- projects/backend/controllers/image.ts
- projects/backend/image.ts
- projects/backend/index.ts
- projects/backend/package.json
- projects/backend/yarn.lock
- projects/common/src/index.ts
Part 2 of https://github.com/guardian/editions/pull/658 
Replaces #673 which had a rebase accident.
- Adds a 'thumbs' directory for `thumb` and `large-thumb`
- Changes resizer parameters based on `use`
- Puts these new paths into s3 / zips
- Uses these new paths in the Image path code
- Uses the use from the backend to choose the image rendered in the card.
- Picked image sizes based on fractions of full sized images
Performance: 
This saves a small amount of RAM, but noticeably decreases image load time on android.
> Smaller thumbnail trail images

- projects/Mallard/src/screens/issue-screen.tsx
Small fix as I noticed that we were calling Ophan too many times when updating the weather. This is probably more to do with the fact that we're calling `sendPageViewEvent` in render when perhaps they should be added to either `useEffect(() => ..., [])` or even hooked into the navigation at some point rather than in re-renders @jimhunty ... not crucial but will probably need a fix for more accurate stats relatively soon.
I fixed it this was because it solved the immediate issue and the lack of a full re-render on the issue screen seemed worthwhile too.
> Move weather hook to stop full re-render of issue

- projects/Mallard/src/helpers/push-notifications.ts
- projects/Mallard/src/helpers/push-tracking.ts
- projects/Mallard/src/screens/settings/dev-zone.tsx
Adding a verbose logging strategy to get to the bottom of what is happening when push notifications are being received.
Additional "clear" button in case it all gets a bit much. Should only happen once a day so shouldnt get too long. 
This is meant to exist in the app on a temporary basis.
[**Trello Card ->**](https://trello.com/c/Edbegw8h/968-more-push-notification-tracking)
> feat: Push Tracking Logging to Dev Centre

- projects/Mallard/src/helpers/files.ts
- projects/Mallard/src/helpers/push-notifications.ts
Increasingly inconsistent results. This PR tracks the whole chain of the download based on @RichieAHB latest changes.
I have also moved the clearing of old editions as part of the process in case there is read/write blocking.
> chore: Additonal push download tracking to debug

- projects/Mallard/src/components/toast/net-info-auto-toast.tsx
Fixes a bug we are currently seeing when opening an edition where this shows erroneously.
> Prevent 'no internet connection' message showing if the connection status is unknown to us.

- projects/Mallard/src/components/weather.tsx
Accommodate for longer town names. @jimhunty  noticed it was broken since my previous changes. This fixes that.
I tried with a long name, see screenshot, which now shows correctly without overflowing over the weather icons or onto the left. I also added the ellipsis if it's too long. I checked the rendering is unaffected for usual names such as "London".
> fix weather layout

- projects/Mallard/src/components/article/html/article.ts
A check was being added that when we were offline, we wouldn't show article images. This was in place when the inline images fix wasn't in place. Its now been fixed and this is now blocking showing of images.
This also ensures that videos stop being shown.
> fix: Show images offline

- projects/Mallard/src/screens/article-screen.tsx
Fixes the bug that the same article appears twice in an edition and to show the one that was chosen.
[**Trello Card ->**](https://trello.com/c/rq5cLUOp/996-bug-an-article-that-appears-in-two-containers-can-cause-the-navigation-to-be-incorrect)
As described in the ticket
> fix: An article that appears in two fronts can break nav

- projects/Mallard/src/components/weather.tsx
Tiny fix for width, I set it too narrow last time and it caused "12pm" to be cut off.
I replaced the time by "12pm", which is the largest possible text, to check it was showing properly:
> nit: fix weather item width

- projects/Mallard/src/helpers/settings/resolvers.ts
- projects/Mallard/src/helpers/settings/setters.ts
Apollo doesn't cache separate fields for any particular query, because it's designed around the idea you want all fields to be in-sync with each other, so fetched as a single batch. This can mean sometimes some settings are "fetched" twice. We can remediate this by caching promises.
Make sure settings work correctly, ex. switch on/off weather, and GDPR consent flags.
> keep track of settings promises

- projects/Mallard/src/components/weather.tsx
- projects/Mallard/src/helpers/__tests__/weather.spec.ts
- projects/Mallard/src/helpers/weather.ts
- projects/common/src/index.ts
If we can't fetch the weather right now, but already have some weather showing up from some time ago, even stale, then don't fetch again. I removed the `WeatherUpdate` object, instead we just check the "lastUpdated" field on the weather object.
On iOS:
1. Disconnect network, open app from fresh. Notice weather doesn't appear.
2. Background the app, enable network, then come back. Notice weather shows up.
3. Background, come back. Weather's not updated.
4. Wait 1 hour (you can change value in code to smth smaller), background, come back. Weather's gotten updated.
> weather: don't clear the weather when offline

- .eslintrc.js
- projects/Mallard/src/authentication/AccessContext.tsx
- projects/Mallard/src/components/article/types/article.tsx
- projects/Mallard/src/helpers/issues.ts
- projects/Mallard/src/hooks/use-image-paths.ts
- projects/Mallard/src/screens/article/body.tsx
- projects/Mallard/src/screens/article/slider.tsx
From experience and from observation of our project: 'warnings' are useless. They hang around and they pollute the output and rarely actioned upon. They don't get fixed before code is merged because they don't block CI. Let's get rid of lint warnings by either having them as errors, or disabling specific rules we don't need.
This changeset disable the rule about the type `any`, because we use it in many places and because I reckon it doesn't warrant an error. This is because it's already something explicit: by writing `any` in the code, the developer already knows they are circumventing the type system. (On the other hand, TypeScript already prevents implicit `any`s.)
This changeset also makes `react-hooks/exhaustive-deps` an error. I think it's an important one, because on the other hand …
> cleanup eslint rules

- projects/Mallard/src/components/weather.tsx
- projects/Mallard/src/helpers/__tests__/weather.spec.ts
- projects/Mallard/src/helpers/weather.ts
Add "Set Location" button according with design. For now behind the dev-only mode, because I still have to implement the consent screen, something I'll do in a separate PR to keep them nice and small.
[**Trello Card ->**](https://trello.com/c/Ii5WqyrA/895-make-weather-in-app-use-geolocation-data-lat-long-rather-than-ip-address)
1. Open app, notice `Set Location` button.
> show Set Location button

- projects/Mallard/src/helpers/storage.ts
Everytime I start the app, React Native complains about this. Let's just clean it up by having a no-op on Android.
Install and open the app. No warning shows up about *"Settings is not yet supported on android"*
> do not call the Settings module on android

- projects/Mallard/index.js
- projects/Mallard/src/App.tsx
- projects/Mallard/src/helpers/settings.ts
- projects/Mallard/src/services/__tests__/errors.spec.ts
- projects/Mallard/src/services/errors.ts
We want settings to be accessed only through Apollo, so that we have a unified model. This changes `ErrorService` to do so.
I also altered the code so that it still keep tracks of errors into an array if consent is off and log them if consent switches to on. I think in practice that's a very unlikely scenario to happen, but on the other hand it simplifies the code quite a lot to do that, because we don't have to make a special case about the "initialisation" phase. I'm happy to discuss this though.
Additionally, as part of this change, this changes the classes and the automated tests to be simpler with a lot less boilerplate code (check out the deleted line count). Mocking modules instead of doing dependency-injection (DI) is quite common in Jest, if not idiomatic, and leads to cleaner …
> ErrorService: refactor to remove dep on setting callback mechanism

- projects/Mallard/src/components/article/index.tsx
- projects/Mallard/src/components/article/types/crossword.tsx
- projects/Mallard/src/screens/article-screen.tsx
- projects/Mallard/src/screens/article/header.tsx
- projects/Mallard/src/screens/article/slider.tsx
I broke this when implementing the auto-hide (#810). This adds the header when in full-screen for the basic card.
This is quick fix, but I think we need to reconsider how this is designed long-term.
Additionally, I had to add an arbitrary padding at the bottom, otherwise the view overflows the screen and it's impossible to read the last definitions of the crosswords. I'm not sure what's the root cause. It needs more investigation but I think we need a quickfix for now so that we can ship the next release.
Both iOs and Android, open a crosswords, verify there is a back button. Verify other articles are unnaffected.
> bring back header on crosswords

- projects/Mallard/src/components/weather.tsx
It causes time to be cut off if it's too long, for example "10pm" would get cut off. It doesn't change overall width because width is set separately.
Check it renders correct as ususal.
> easy: remove extra padding in weather

- projects/Mallard/src/helpers/__tests__/weather.spec.ts
- projects/Mallard/src/helpers/location-permission.ts
- projects/Mallard/src/helpers/weather.ts
Refresh weather explicitly if permissions change.
1. Open app, sign-in, enable dev mode
2. Press "Set Location" on weather
3. Accept, then allow permission
4. Observe: weather is cleared up and displays again with fresh data (it's still not using real location yet, I'll add this in the next and final PR)
> refresh weather on permission change

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/components/weather.tsx
- projects/Mallard/src/helpers/__tests__/weather.spec.ts
- projects/Mallard/src/helpers/location-permission.ts
- projects/Mallard/src/helpers/weather.ts
- projects/Mallard/yarn.lock
Finally! This is pretty much the last step for weather… show the actual location.
https://trello.com/c/Ii5WqyrA/895-make-weather-in-app-use-geolocation-data-lat-long-rather-than-ip-address
I also took this opportunity to remove the "available" field: if not available, we simply make the field `null`. That's easier to manage at Apollo level.
1. Open app, see "Set Location" button
2. Press button, accept conditions
3. Accept location permission request
4. Notice the weather updates accordingly (ex. in the emulator it shows me location and weather in San Francisco)
I also tested various other combinations, like going to app-specific system settings, blocking or removing the permissions, going back to the app, noticing the "Set Location" button comes back as expected, etc.
> weather: show real location

- projects/Mallard/src/navigation/navigators/underlay/transition.tsx
- projects/Mallard/src/screens/home-screen.tsx
This allows you to actually click `Manage editions`! 🎉 
https://trello.com/c/ItF4cfIn/1021-manage-edition-padding
> Add padding at bottom of issue list

- projects/Mallard/src/authentication/authorizers/IAPAuthorizer.ts
- projects/Mallard/src/authentication/services/__tests__/iap.spec.ts
- projects/Mallard/src/authentication/services/iap.ts
Adds a 3 day grace period for all IAP receipts, in a hope to avoid missing receipts and, from that, failed IAP sign-ins.
An attempted fix for the below two cards:
https://trello.com/c/ejl8Xr8Y/933-itunes-subs-becoming-unavailable-in-the-app-for-no-apparent-reason
https://trello.com/c/nxDT0KDw/1017-users-having-to-repeatedly-sign-back-into-subscription
> Add grace period of three days for IAP receipts

- projects/Mallard/src/screens/article/slider.tsx
The slide was holding an interpolation in state that had previously been
divided by the width. Not that width has been updated, the animated
value here needs an update but wasn't getting it. If we want perf
improvements we can think about `useMemo`.
> Fix update on rotate for slider

- projects/Mallard/src/components/slider/draw/lozenge.tsx
This fixes [this issue](https://trello.com/c/HAgMQ2Uq/1019-infinite-scroll-transitions-can-be-incomplete-on-an-article-page) by making the transition from the title to the single char _very_ quick. It's not perfect but given we're changing this design anyway I'm not going to be too fussy as you can only notice the issues if you scroll verrrrry slowly.
> Fixes half transition for longer sections

- projects/Mallard/src/hooks/use-net-info.tsx
This fixes a race condition where the `useNetInfo` `Provider` may subscribe too late to receive the first subscription notification.
Additionally it removes a redundant performance optimisation.
> Ditch optimisation / ensure subs called on subscribe

- projects/Mallard/ios/Mallard/Info.plist
> TMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more …
> Add NSLocationAlwaysUsageDescription in iOS plist file

- projects/Mallard/src/screens/issue-screen.tsx
Crosswords are "fullscreen" with no slider so we don't want to be able to slide onto them. This changeset removes them from the "articleNavigator" (a bit of an odd name for what is just the slide-able list of fronts) collection.
1. Open close to thelast article of the slidable articles, ex. last article of Sports. Verify sliding left and right works. Verify it's not possible to slide beyond the last Sports article (or whichever last Front it right before Crosswords).
2. Verify opening the Crosswords works as expected.
> prevent sliding onto crosswords

- projects/Mallard/android/app/src/main/java/com/guardian/editions/MainApplication.java
In order to install Sentry, it goes through a "Wizard" which requires some "linking" which is not necessarily required in our version of React Native.
Removing this line fixes the build
> fix: Android Sentry

- projects/Mallard/src/screens/article/slider.tsx
Using the current article's pillar to render all article would cause articles to re-render when swiping from one pillar to the next, reinjecting fresh HTML, breaking scrolling, and displaying the article incorrectly all-in-all.
Verified that swiping from a Culture to a Jounal article doesn't re-render the article.
> use the correct pillar to render articles

- projects/Mallard/src/hooks/__tests__/use-net-info.spec.tsx
- projects/Mallard/src/hooks/use-net-info.tsx
Keep async things async https://blog.izs.me/2013/08/designing-apis-for-asynchrony (also stops an extra render re-render)
> Don't call subscribers synchronously

- README.md
- projects/Apps/package.json
- projects/Mallard/README.md
- projects/archiver/README.md
- projects/aws/README.md
- projects/backend/README.md
Add a bunch of things that should have been in the readmes to the readmes.
@aug24 
@jimhunty 
@jeanlauliac 
@philmcmahon
> Updates to readmes.

- projects/Mallard/src/components/front/image-resource.tsx
This puts https://github.com/guardian/editions/pull/755 into action. Merge after 6th Nov.
> Actually use the use param

- projects/Mallard/src/helpers/files.ts
Sometimes, particularly with large weekend editions, the download and unzip process doesnt complete. It seems to always fail at the large media download.
When doing the data and media download, we set a flag to create a iOS background task. We do the data before the media asynchronously. I _think_ the push is received, creating a background task. After multiple processes (which also include a seperate download that doesnt create a background task) we do a data download, this creates another background tasks this happens before the media.
My theory is that is completes, and there is a race condition where the completion kills the background tasks and sends the app back to sleep. If the media download starting is fast enough to create another background task it doesnt fall asleep.
Then we …
> fix: Background Download

- projects/Mallard/src/helpers/files.ts
Since removing the background task from push summaries, we experienced issues with it not existing. I have added the background task across all download elements of the push download. Let's see what happens.
> fix: Attempted background download fix

- projects/Mallard/android/app/src/main/AndroidManifest.xml
Facebook log-in was not working at all on Android because the deep link would not redirect to the app. This fixes the config to register for the actual scheme used by the Facebook log-in callback deeplink.
Log-in with Facebook on Android. It works.
> fix facebook handler scheme on Android

- projects/Mallard/src/hooks/use-issue-summary.tsx
Mitigates https://trello.com/c/RmhNdT2c/1022-offline-reading-images-disappear-when-you-offline-back-to-online
We should probably never force-change the current issue when the app is being actively used.
It still doesn't completely clears things out, because for example someone might foreground the app while an article is open. In that case, this will still cause the photos to disappear. This is kind of a separate bug: why would images disappear just because the current issue changes in the background? An article's an article, no matter the issue. Sounds like a bug in the data layer.
My going online while the app is in the foreground, this doesn't cause the issue to change anymore. By going foreground after going back online, on the other hand, still causes the last issue to be navigated …
> only switch issue on foreground event

- projects/Mallard/src/components/missing-iap-modal-card.tsx
Makes the title smaller
[**Trello Card ->**](https://trello.com/c/O1EogvDP/551-usability-feedback-message-if-existing-app-store-subscription-is-not-found)
> fix: Text size on IAP feedback message

- projects/Mallard/src/components/front/items/items.tsx
Thumbnail cover card images cease to exist. Therefore moving this back to `full-size` until we can determine the cause of the problem.
[**Trello Card ->**](https://trello.com/c/LMWH01yG/1041-cover-cards-and-image-on-national-dont-render-build-594)
> fix: Cover Card Images

- projects/Mallard/src/helpers/__tests__/files.spec.ts
- projects/Mallard/src/helpers/files.ts
A change a short while back affected how we delete issues. This has resulted in old issues not being deleted and these sentry errors:
https://sentry.io/organizations/the-guardian/issues/1351093667/?project=1519156&query=is%3Aunresolved
The fix? Make sure we have the correct path otherwise it errors and deletes nothing. This issues path is for a file we don't want to delete.
> fix: Delete Issues

- projects/aws/lib/aws-stack.ts
This removes the default stage for fronts access, sets allowed values and removes the old editions store bucket from the list of outputs. 
This should fix riffraff continually overwriting prod on code.
> Don't set default stage as riffraff blats over the selected with default

- projects/archiver/package.json
- projects/backend/package.json
I set up ncc wrong, and accidentally bundled the aws-sdk. This should massively cut our bundle size and thus riffraff costs.
> Remove aws-sdk from lambda bundles

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/src/components/issue/issue-row.tsx
- projects/Mallard/src/components/issue/issue-title.tsx
- projects/Mallard/src/components/layout/header/header.tsx
- projects/Mallard/src/screens/home-screen.tsx
- projects/Mallard/src/theme/color.ts
- projects/Mallard/src/theme/spacing.ts
Add the list of fronts below the current opened issue. When pressing a front, navigate to that front on the main page of the app.
I had to readjust a number of layout styles and structure to fit the design, so that fronts are properly aligned, so that press "highlights" show up correctly with a good padding.
A lot of the complexity also comes from the scrolling behavior: when pressing an Edition, we scroll the view to that edition+fronts, but this requires computing the right offsets and sizes for each cells ahead-of-time. Note that even without using `FlatList`, we'd have to do that to know the exact offset, but having the full correct `getItemLayout` implementation is good for when we'll have a long list of editions (ex. 30 days) in the future. …
> add fronts navigation

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/src/navigation/index.ts
- projects/Mallard/src/navigation/routes.ts
- projects/Mallard/src/screens/settings-screen.tsx
Add 'manage editions' to the settings page - it makes sense for this page to allow users to configure everything rather than having to do something else for managing editions. 
Looks like this:
https://trello.com/c/SIuLaurt/1025-manage-editions-show-it-on-settings-along-with-the-current-display-in-recent-editions
> Add manage editions to settings page.

- projects/Mallard/src/components/article/html/components/header.ts
(Have checked it doesn't break other sharing icons)
> Set correct colour for share icon on obit headers.

- projects/Mallard/src/screens/home-screen.tsx
Because it does indeed happen in practice, `scrollToIndex` would crash when provided with the large number. I removed this logic so that we just do nothing if we didn't find the list item matching the details we have.
I don't understand how that can actually happen yet, because we always fetch the issue matching both `localId` and `publishedId`, and actually I can't repro locally, but this at least this changeset avoids the crash which is the worst experience.
Verified navigating to one issue to another works as expected.
> home-screen.tsx: do not scroll to index outside of bounds

- projects/Mallard/src/screens/home-screen.tsx
If it's zero then it's valid as well and we need to take it into account to compute sizes in `getItemLayout`
> [easy] home-screen: fix erroneous integer comparaisons

- projects/backend/capi/articleTypePicker.ts
This PR maps Obits to the standard article template, while we look for a better solution around scaling images. At the moment the issue of the Obit template leads to often inappropriate images. 
See Trello: https://trello.com/c/CxtGa0vu/1029-crop-positioning-for-immersive-templates
> Stopgap: Mapping Obits to standard article template

- projects/Mallard/src/components/issue/issue-row.tsx
Fix font/spacing in accordance with what was discussed with design/UX, in particular Fronts list items need to be bigger (to be easier to press), font needs to be consistent with Fronts font in issue display, and titles shall not be centered as per design, so we just put a top padding. Top padding is set as percentage of item size so that we depend on the responsive font size itself.
https://trello.com/c/VhXCFcQU/924-navigation-quick-access-to-fronts
check design:
> Editions page: adjust Fronts font and spacing

- projects/Mallard/src/helpers/files.ts
- projects/Mallard/src/helpers/push-notifications.ts
- projects/Mallard/src/helpers/push-tracking.ts
After not receiving downloads on an iPad over the weekend, i attempted to recreate the issue.; However, using CODE environments, everything works perfectly....
The current internal tracking is non blocking at the moment. As a result we don't always get the full picture. This PR makes it blocking which should give us more of an idea when things stop.
> Chore: Blocking push tracking

- projects/Mallard/src/hooks/use-issue-summary.tsx
As suggested in a previous PR, this will help reduce memory leaks and improve performance.
@jeanlauliac 
[**Trello Card ->**](https://trello.com/c/dtdqVf3K/1060-move-listeners-outside-of-useeffect-on-issue-summary)
> chore: Listener cleanup on Issue Summary

- projects/Mallard/src/components/issue/issue-row.tsx
Offline banner mistakenly displays when clicking the download button again because its in progress. This PR separates both conditions.
[**Trello Card ->**](https://trello.com/c/3ltbJkXK/1056-yellow-you-are-offline-banner-keeps-appearing-even-when-online)
> fix: Offline banner only when offline

- projects/Mallard/src/helpers/files.ts
Editions are being blocked when downloading as we always return something from `getDownloadBlockedStatus`.
This PR checks for the appropriate status returned and adds some additional tracking if its blocked.
_Please note:_ If someone chooses to download only over wifi, they will not download overnight or when the first open the app
> fix: Download Edition

- projects/Mallard/src/components/issue/issue-row.tsx
This adjust the space so that we have 44px-high rows for Fronts on iPhone. We still want to have a relative size to as to depend on font size (it's like using padding and letting the row get the size of the font, except we need the total size upfront for the flatlist's `getItemLayout`)
https://trello.com/c/VhXCFcQU/924-navigation-quick-access-to-fronts
Check it out, verified the rows are indeed 44px (there are 88px in the screenshot, consistent with a device pixel density of 2).
> adjust Front spacing

- projects/Mallard/src/screens/settings-screen.tsx
Button was un-clickable - now clickable.
[**Trello Card ->**](https://trello.com/c/cYykXAgz/1065-edition-management-the-manage-edition-button-on-settings-is-unclickable)
Click on the Manage Editions button in Settings
> chore: Fix Manage Editions Button

- projects/Mallard/src/components/article/html/article.ts
- projects/Mallard/src/components/issue/issue-row.tsx
- projects/Mallard/src/helpers/transform.ts
- projects/Mallard/src/hooks/use-article.tsx
Design specifies a custom palette: https://trello.com/c/VhXCFcQU/924-navigation-quick-access-to-fronts
This changeset codifies that. I also took this opportunity to merge some duplicate code that was going around for getting a pillar's colors.
Open edition list, check it looks as expected:
> adjust colors for Fronts in editions list

- projects/Mallard/src/components/issue/issue-row.tsx
- projects/Mallard/src/components/styled-text.tsx
- projects/Mallard/src/helpers/Loaded.ts
- projects/Mallard/src/hooks/use-issue.ts
- projects/Mallard/src/screens/home-screen.tsx
If we have the list of issues but we couldn't fetch an issue's content, we'd show a black screen instead of the list of issues (https://trello.com/c/1ABS0oJg/1059-blank-editions-list-when-you-go-offline). This fixes this by having a more robust data structure being passed down the hierarchy, in particular accounting for loading and error state. In case of error we show a message specifically below the current issue instead showing an entire black screen.
I added some code in `getIssueResponse` to return an error artificially, then verified that the issue-specific error message shows up correctly in the Issue list view:
I also verified that when being completely offline we show a message and not a black screen either.
> avoid black screen for missing issue

- projects/Mallard/src/screens/issue-screen.tsx
I'm looking into the misalignment issues when navigating to a front (https://trello.com/c/VhXCFcQU/924-navigation-quick-access-to-fronts) and noticed the code is seemingly doing 2 `find` instead of 1 for no particular reason.
Just checked the Fronts navigation from the Editions menu.
> tiny cleanup of navigate-to-front logic

- projects/archiver/src/tasks/indexer/helpers/get-issues.ts
- projects/archiver/src/tasks/indexer/helpers/summary.ts
- projects/archiver/src/tasks/indexer/index.ts
Bugfix: Previous release did not read the data to construct the index from the correct bucket.
See contents of issues file in editions-store-prod bucket.
> Read correct bucket for index creation

- projects/Mallard/src/navigation/navigators/underlay.tsx
- projects/Mallard/src/navigation/navigators/underlay/transition.tsx
- projects/Mallard/src/screens/home-screen.tsx
After several discussions we decided the card entirely out of the way: https://trello.com/c/CL9ChL1y/1070-drawer-should-slide-down-fully-offscreen-for-recent-editions-screen-on-phones
This is to leave quite a bit more space to be able to see more Fronts at a glance instead of having to scroll.
Verify both on iPad and iPhone that the transition is correct. Android is unaffected as it uses a pretty different transition mechanism.
<div>
</div>
> underlay transition: slide card fully out of the way

- projects/Mallard/src/hooks/use-net-info.tsx
- projects/Mallard/src/screens/settings/dev-zone.tsx
The NetInfo button used to virtually disable the connection can be useful sometimes but the rest of the time it's taking up space and overlaps some items such as toasts. Let's hide it by default and allow to enable it in the Dev menu?
Checked toggling on and off the button.
> hide NetInfo button by default

- projects/Mallard/src/hooks/use-image-paths.ts
Image resizer appears to be occasionally failing according to Sentry errors. This wraps a `try/catch` and returns the larger path if there is a failure. 
Effort to reduce the noise in Sentry.
Image Resizer Docs: https://github.com/bamlab/react-native-image-resizer
Sentry Error: https://sentry.io/organizations/the-guardian/issues/1352200928/?project=1519156&query=is%3Aunresolved+dist%3A612&statsPeriod=14d
> fix: Image Resize Failure

- projects/Mallard/src/hooks/use-issue-summary.tsx
If there isn't a new issue we can assume people already know about it whichever issue there currently are on.
Part of fixes on https://trello.com/c/KVRmctcK/1016-more-logical-issue-selection-for-accessing-editions
1. Open app, open Editions list, open older edition, select Front, background the app.
2. Foreground the app. Notice it doesn't force-update edition.
(3. I didn't find a clear approach to test when there **is** a new edition. Shall we add a unit test? Looking for some opinions on this.)
> use-issue-summary: update to latest issue only if there is a new one

- projects/Mallard/src/hooks/use-aspect-ratio.ts
- projects/Mallard/src/hooks/use-image-paths.ts
- projects/Mallard/src/hooks/use-screen.ts
When components are dismounted, we should discard setters. It causes tons of React warning and that's problematic because we don't see and/or ignore new warnings as a result.
On the other hand it's sad to see that lots of these happen on startup, which mean there are several re-renders on start, probably not necessary. But that's another, separate issue.
Load the app, navigate to a specific Front, navigate to another Edition, open article. Notice there is no more warnings showing up related to "setting state on unmounted component".
> add hook cleanups to avoid warnings

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
When downloading large editions, it sometimes doesnt complete. This could be to do with the zip library, so giving it an update
> chore: Update unzip library

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
We use RNFetchBlob to download zips. Some large image zips are not always completing their downloads. This updates the library to see if that makes any improvements.
> chore: Update Zip Fetch

- projects/Mallard/scripts/fetch-dev-env.js
Chalk was failing on this internal dev script due to the upgrade it received a little while ago. This fixes it.
> fix: Chalk in fetch-dev-env

- projects/Mallard/src/helpers/files.ts
Couldn't find push download failures in Sentry. This is because we catch the error. This ensures this is sent to Sentry
> chore: Record Download Failures

- projects/Mallard/src/hooks/use-issue-summary.tsx
Since the new backend has gone live, in the new beta when you change the max available editions, that was not being reflected in the issue picker.
This now listens for changes in the max available editions and then goes to grab the issue summary forcing it to update.
- Click on issue picker
- Choose 'Manage editions'
- Change number of 'Available Editions'
- Close 'Manage editions'
- See number reflected on the issue picker.
> fix: Get the editions when the max available editions changes

- projects/Mallard/src/screens/settings/manage-editions-screen.tsx
> Fix case of title on 'Manage Editions' page.

- projects/Mallard/src/components/article/html/components/header.ts
Bylines should show as alternative text colour to background - not matching as before.
> Fix byline color on longreads.

- projects/Mallard/src/helpers/words.ts
- projects/Mallard/src/navigation/index.ts
- projects/Mallard/src/screens/settings/manage-editions-screen.tsx
If the 'manage editions' screen is shown from the settings menu, the back arrow on the left hand side of the header should show.
If the 'manage editions' screen is shown from the issue picker menu, the close icon on the right hand side of the header should show.
> Ensure header buttons on 'manage editions' screen display correctly given their context

- projects/Mallard/src/components/issue/issue-row.tsx
- projects/Mallard/src/screens/home-screen.tsx
1. account for hairline being 0.5px, not 1px (virtual pixels), by using `StyleSheet.hairlineWidth`.
2. do not trigger the `scrollToIndex` call on first render. This effectively fixes https://trello.com/c/srUOr8rq/1093-android-10-issue-list-bug.
Open Android 10 emulator, enable 30 days for issue list, open an issue far in the list. Notice it scroll to the exact, pixel-perfect position. Close the edition list, then open it again. Notice it is scrolled to the exact, correct position again.
> Issues list: fix getItemLayout sizes and scrolling behavior

- projects/archiver/src/tasks/indexer/index.ts
Following from an incident where we overwrote the issues list file with an empty file, this change adds a simple check around the issues file upload process to check that there is at least 1 element in the list of issues before uploading.
[**Trello Card ->**](https://trello.com/c/MvVMGXb3/1092-publishing-should-check-that-there-is-at-least-one-issue-in-the-issues-list-before-overwriting-stuff-in-s3)
This is actually a very small change, but github has decided to make it look a lot bigger than it is. The main bit is `if (allSortedEditionsIssues.length > 0)`
> Check issues list has at least one element in it before uploading.

- projects/Mallard/src/components/article/html/components/media-atoms.tsx
There have been reports of ads showing up on videos in the app. I think this change should prevent that from happening, though we should wait till we've got an example we can test it against. But this definitely works when loading a video in the browser:
with ad: https://embed.theguardian.com/embed/atom/media/aa2a0b93-12b2-475c-811b-688e6f57a95e
no ad: https://embed.theguardian.com/embed/atom/media/aa2a0b93-12b2-475c-811b-688e6f57a95e#noadsaf
This query string thingy comes from [commercial features](https://github.com/guardian/frontend/blob/c4d8d8c44d05060c30910027665ac8c7dc1907cc/static/src/javascripts/projects/common/modules/commercial/commercial-features.js#L29) in theguardian.com frontend. 
[**Trello Card ->**](https://trello.com/c/A2DM1SKj/1024-remove-ads-from-videos)
- Find video …
> Add #noadsaf to embed url to block ads on videos.

- projects/Apps/common/src/index.ts
- projects/backend/utils/crossword.ts
Currently `shouldHaveSolution` doesn't return correctly as it tries to compare crossword.type which is a number with CrosswordType.EVERYMAN - which is a string. I've not quite got to the bottom of this but I think it's due to some weirdness with typescrip string enums.
It looks like whoever wrote this function initally was aware of the problem as they make the parameter `type` available - which is a string - to deal with this issue. This change gets us using that parameter.
[**Trello Card ->**](https://trello.com/c/v3IM9DtK/930-crossword-shouldnt-reveal-the-answers-for-prize-crosswords)
Check that everyman (sunday) and prize (saturday) crosswords don't have the 'reveal all' button
> Use string crossword type variable in patchCrossword.

- projects/Mallard/src/App.tsx
- projects/Mallard/src/apollo.ts
- projects/Mallard/src/hooks/use-issue-summary.tsx
I propose we move forward with unifying around Apollo for storing state. This changeset would switch `useIssueSummary` to Apollo to store the issue summary data, so that we leverage the query mechanism, which allows for a fine-grained selection of fields a component depends on, instead of having whole React Context containing blobs of state.
The high-level product logic is unchanged.
Open app, notice it loads correctly the edition, open the Editions list, change the number of editions (ex. 14 days), notice it correctly updates.
> use-issue-summary: switch to Apollo

- projects/Apps/common/src/index.ts
- projects/Mallard/src/components/article/html/article.ts
- projects/Mallard/src/components/article/html/components/header.ts
- projects/Mallard/src/components/article/index.tsx
- projects/Mallard/src/components/article/types/article.tsx
- projects/Mallard/src/components/article/types/article/webview.tsx
- projects/Mallard/src/helpers/fetch.ts
- projects/Mallard/src/hooks/use-image-paths.ts
- projects/Mallard/src/hooks/use-issue.ts
- projects/Mallard/src/screens/article/body.tsx
This changeset remove calls to `useImagePath` from within article HTML rendering code. This is erroneous because it uses `useIssueSummary` in turn, which grab the current issue ID, but not necessarily the ID of the issue the article is in. That in turn was causing images to "disappear". This is replaced by a synchronous `getImagePath` function that assumes either all images are local (FS), or all images are remote (API).
To do this we pass down additional information: the issue ID (instead of using `useIssueSummary`, which can be wrong as said), and the "origin" (whether get the images from API or FS).
Supersedes #936.
Addresses https://trello.com/c/RmhNdT2c/1022-offline-reading-images-disappear-when-you-offline-back-to-online-or-u-swap-out-of-the-app-and-come-back-in-offline-mode
* Open …
> replace useImagePath with synchronous alternative in article rendering

- projects/Mallard/src/components/article/html/components/pull-quote.ts
Let's just disable automatic hyphens as the web browser is too aggressively generating them for the small-width use case (see screenshots). I propose we do that, audit how it goes, and if really there are need for hyphens occasionally, manually add these using the [unicode Soft Hyphen](https://en.wikipedia.org/wiki/Soft_hyphen). We could implement some simple rules based on RegExps that automatically add these for specific cases, either backend-side or client-side.
https://trello.com/c/Qs8jHkO1/693-pullquote-design-fixes#comment-5e05cebfad96b57468354560
See below the version with hyphen versus without. I think we can arguably say the one without is cleaner and more legible.
> disable auto hyphens in pullquotes

- projects/Mallard/src/components/article/html/components/header.ts
This fix assumes the author's name will always be wrapped in a `<a>` tag. I think it's fairly safe to assume so for now. It will still show up if it's not wrapped, just not with the exact correct styling, however I think it's better to support the base case than not support anything.
We can't control styling very precisely because the byline is in an HTML format, and this HTML comes from CAPI. Getting the author's name and "additional context" separate would require backend change, and maybe CAPI, which perhaps isn't necessary for the time being if this simple CSS fix proves to be enough.
https://trello.com/c/puPnKeDv/899-css-can-we-use-the-same-rules-for-bylines-on-non-standard-templates
Compare before (left) and after (right). Notice the "Diplomatic Editor" in the byline has now the …
> fix analysis header style

- projects/Mallard/package.json
- projects/Mallard/yarn.lock
Currently if you open the issues list then select a section the app crashes. We suspect this is caused by the react native upgrade - https://github.com/guardian/editions/pull/975
Upgrading the react-native-gesture-handler library appears to fix the issue
Open the app on iOS, try navigating to a section from the issue sidebar
> Bump react-native-gesture-handler version

- projects/Mallard/src/helpers/__tests__/push-tracking.spec.ts
- projects/Mallard/src/helpers/clear-download-issue.ts
- projects/Mallard/src/helpers/push-tracking.ts
We only really need a few days logs, anything beyond that is a bit pointless. I have limited this functionality to 7 days.
This runs with all the cleanup tasks
[**Trello Card ->**](https://trello.com/c/vZSzRPrJ/1112-add-functionality-to-clear-out-old-push-notification-older-than-7-days-from-users-device)
1. Check your push logs before
2. Run this branch
3. Check the reduced push logs after.
> feat: Clean push logs

- projects/Mallard/ios/Podfile.lock
This should have been included in https://github.com/guardian/editions/pull/979
> Update podfile.lock following gestures upgrade.

- projects/Mallard/src/hooks/use-issue-summary.tsx
Sometimes we get strings, but we can also get `Error` objects if thrown by the `fetch` function for example, in which case let's just forward the message.
Change API endpoint as localhost in the Dev menu, then reload the app. Observe fetch timeout error message.
> use-issue-summary: forward message of Error objecrs

- projects/Mallard/src/navigation/navigators/sidebar.tsx
- projects/Mallard/src/screens/home-screen.tsx
We want to enable the sliding sidebar on android too. I'm wary of enabling below 29 for now until further testing. I propose we just do it on 29+ for now and lower this in a further PR once we test it. More explanations in code comments.
https://trello.com/c/tk2ri1qn/1110-nav-burger-open-and-close-animation-android
Both on iOS + Android:
Open app, press hamburger, check editions show up with sidebar animation, navigate to an edition, notice closing sidebar animation.
> enable sidebar on Android (>29), and make anim faster-feeling

- projects/Mallard/package.json
- projects/Mallard/yarn.lock
- projects/archiver/package.json
- projects/archiver/yarn.lock
- projects/backend/package.json
- projects/backend/yarn.lock
Attempting to resolve the handlebars security warnings by forcing a resolution in the project.
Handlebars in our case is a dependency of Commander, which is a dependency of React Native CLI projects used by React Native. Therefore should have no negative impact.
> Chore: Resolve handbars security warning

- projects/Mallard/src/App.tsx
Noticed that when starting the app on a cold start, the issue was not downloading. This should ensure this happens on the first mount.
1. Cold start the app
2. Check the download of the days edition has started.
> chore: Run clean and download on first mount

- projects/Mallard/src/screens/home-screen.tsx
Scrollbar appears in the middle, because the flatlist get instantiated during the animation. Doesn't seem to happen on Android.
> mitigate scrolling bug on iOS

- projects/Mallard/src/helpers/files.ts
When an issue was first accessed, its origin is set as API. However, once an issue has been downloaded, this origin doesn't change. This means when a user goes offline, the images are attempted to fetch from the API. No internet access = no images. So when we download the issue, we need to invalidate the cache
[**Trello Card ->**](https://trello.com/c/CoZYS8Fn/1119-latest-ios-build-images-disappear-at-article-level-in-offline-mode-for-todays-edition-only)
> fix: Invalidate Issue Cache when download an issue

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/components/front/image-resource.tsx
- projects/Mallard/src/components/front/items/helpers/opinion.tsx
- projects/Mallard/src/hooks/use-config.ts
- projects/Mallard/src/screens/issue-screen.tsx
- projects/Mallard/yarn.lock
A couple of optimisations here:
1. Use Fast Image package to aggressively cache our images. This saw an instant improvement in scrolling
2. Only apply flatlist optimisations when the device has less than 1GB of memory.
As a result, smoother scrolling across all supported devices.
> feat: Smoother scrolling images

- projects/Mallard/src/components/article/types/article.tsx
- projects/Mallard/src/helpers/webview.ts
Previously we couldn't use the upgraded Webview due to our usage of custom fonts. A bit of investigation shows that actually we didn't have the correct path.
These things happen.
> feat: Move Article Webview to Webkit

- projects/Mallard/ios/Podfile.lock
Two Pods need the same dependency but different versions. As a result, I downgraded the patch version. Hopefully this will build as it's currently failing.
> chore: Podfile Dependency fix

- projects/Mallard/src/components/article/types/article.tsx
In the updated webview, you cannot access outside of the filesystem. We would need to think of a different way to show images.
> chore: Revert webview

- projects/Mallard/src/helpers/diagnostics.ts
- projects/Mallard/src/helpers/locale.ts
- projects/Mallard/src/screens/settings/dev-zone.tsx
We are aiming to use Device Locale to show content specific to that locale. This gets the basics in and allows us to experiment cross country.
Adds locale to the dev menu and to the diagnostics.
> feat: Add device locale to dev settings and diagnostics

- projects/Mallard/src/screens/article/slider.tsx
Window size takes the height of the viewport multiplied the number stated. by dropping this, we assume that users will be reading not fast scrolling for no reason.
removeClippedSubviews removes offscreen content to improve performance.
Tested on iO9 on device and latest iOS in an emulator.
> chore: Improve article list perf

- projects/Mallard/src/components/layout/animators/fader.tsx
The `Fader` adds animations when closing an article. This piece of code checks to see if its a low end device and if so, then it will not use the animation.
> chore: Fader - no animation on low end device

- projects/Mallard/src/hooks/use-image-paths.ts
Tweak the settings on the Image Resizer to get more efficient cached images. This involves settings a max height based on the screen size, dropping quality to 70% and using WEBP images on Android.
> chore: Improve Cached Images

- projects/Mallard/src/components/article/html/article.ts
- projects/Mallard/src/components/article/html/helpers/css.ts
- projects/Mallard/src/components/article/types/article.tsx
- projects/Mallard/src/components/article/types/article/webview.tsx
Theme is something that is calculated higher up the render tree and only used in generating the HTML. This gives more opportunities for re-renders and adds complications.
This small refactor puts this code where it is used. This will aid future refactoring of the articles.
> chore: Move theme further down render tree

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/components/article/types/article.tsx
- projects/Mallard/src/components/article/types/article/webview.tsx
- projects/Mallard/src/screens/settings/default-info-text-webview.tsx
- projects/Mallard/yarn.lock
Reverts guardian/editions#1005
This is due to the newer versions of `react-native-webview` not supporting images from the file system.
> Revert "chore: Small update to Webview"

- projects/Mallard/src/App.tsx
- projects/Mallard/src/components/article/html/article.ts
- projects/Mallard/src/components/article/html/components/icon/native-arrow.tsx
- projects/Mallard/src/components/article/html/components/images.ts
- projects/Mallard/src/components/article/html/components/native-arrow.tsx
- projects/Mallard/src/components/article/types/article.tsx
- projects/Mallard/src/components/button/close-modal-button.tsx
- projects/Mallard/src/helpers/webview.ts
- projects/Mallard/src/navigation/routes.ts
- projects/Mallard/src/screens/lightbox.tsx
- projects/Mallard/src/screens/use-lightbox-modal.tsx
NOTE: currently includes this revert https://github.com/guardian/editions/pull/1003 - best not to review till that's been untangled
This PR is just to get my work on the lightbox into master so it doesn't get mega out of sync. I've removed the actual component from App.tsx and removed the onclick handler from images.ts so this should have no impact on the app itself.
It looks like this at the moment - getting there....
TODO:
- center image for landscape images
- add instagram style navigation
- fix blank pages loading if you scroll too fast
- animation on open
- check landscape mode on iPad
- check it works on android
- caption should only be visible when the photo is tapped
- fix flash as the image resizes when you open the lightbox
- find a way of passing in the pillar colour - …
> Add basic lightbox (disabled)

- projects/Mallard/src/screens/article/slider/SliderHeaderLowEnd.tsx
Don't do the header animation on a device less than iOS12
> chore: -iOS12 remove the slider header animation

- projects/Mallard/src/App.tsx
- projects/Mallard/src/helpers/clear-download-issue.ts
Multiple observations suggest that upon opening the app for the first time that day, there is some slowdown. This is because of the download that is kicked off in the background.
This PR looks to turn this off for low powered devices to make that first experience better.
The downside of this is that offline reading will be purely reliant on push notifications or manual download by a user for low powered devices.
> chore: Only download on open on large Ram devices

- projects/Mallard/src/components/front/items/helpers/item-tappable.tsx
Bit of creative license here...
When tapping on an article, there is no way to know if you have tapped on it particularly on slower devices. There is no feedback. This is how it will look, top left tapped (very subtle)
> chore: Front feedback on touch

- projects/Mallard/src/components/front/items/helpers/sizes.ts
- projects/Mallard/src/components/front/items/helpers/text-block.tsx
This change aims to reduce the amount of empty space on the editions fronts by increasing the font size. It should only affect 2 and 3 story cards. On mobile, as well as increasing the font size we reduce the size of the image to make space.
[**Trello Card ->**](https://trello.com/c/MEa6tI8e/1010-story-density-first-cut)
Phone 2 story before/after
Phone 3 story before/after:
Tablet 2 story before/after:
Tablet 3 story before/after
This builds on some of the work in [this change](https://github.com/guardian/editions/pull/977). 
Verify larger headlines on 2/3 story cards. No other cards should be affected.
> Larger headlines on 2/3 story cards

- projects/Mallard/src/App.tsx
- projects/Mallard/src/helpers/weather-hider.ts
This is a "run once" script that checks if you are on a low powered device and turns the weather off for it. The user is able to turn it back on in the settings.
The hope is less requests and less need for rendering on the lower powered devices.
> feat: Weather Hider

- projects/Mallard/src/components/front/items/helpers/sizes.ts
- projects/Mallard/src/components/front/items/helpers/text-block.tsx
- projects/Mallard/src/components/front/items/image-items.tsx
This change shouldn't actually change anything - just simplifies the logic we're using to determine font/image size on fronts.
As far as I can tell we aren't using the 'starter' image size at the moment so I've removed it. 
I've also tried to use `==` rather than `>=` where there's actually only one value we're targeting.
Verify that no changes occur when this is released.
> Simplify front image/font size logic

- projects/Mallard/src/components/front/index.tsx
- projects/Mallard/src/screens/issue-screen.tsx
When on devices with less RAM, this will reduce the amount we load in the background. Gives a faster load time.
> feat: Optimising the issue screen

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/authentication/AccessContext.tsx
- projects/Mallard/src/authentication/lib/AccessController.ts
- projects/Mallard/src/hooks/__tests__/use-net-info.spec.tsx
- projects/Mallard/src/hooks/use-net-info.tsx
- projects/Mallard/yarn.lock
Currently we have a bug where users can get 'signed out' if they use the app with a poor network connection. This change:
- Bumps the version of netinfo that we're using
- Uses info from 'isInternetReachable' to determine connectivity
- Adds a new 'isPoorConnection' property to indicate a 2G connection - in this scenario we will assume offline for the purposes of authentication
Since I made these changes I've not reproduced this bug, I'm not 100% confident though!!
[**Trello Card ->**](https://trello.com/c/0Du77n0C/1058-poor-connectivity-can-cause-you-to-be-signed-out)
This shouldn't happen:
**Steps**
0. Be signed into the app (see fig 1)
1. Find an area with very poor connectivity (3rd floor mens toilets works, or on android settings>connections>mobile networks>network mode>2g, or london …
> (try) fix signout bug on poor connections

- projects/Apps/common/src/collection/card-layouts.ts
Modify dense layout so that we start with 3 story cards wherever suitable and enable the dense layout for national and world containers.
These changes only affect the backend app, and are behind a server side switch.
[**Trello Card ->**](https://trello.com/c/MEa6tI8e/1010-story-density-first-cut)
This change is currently on CODE so can be viewed by changing the backend API to 'CODE published'
> Dense layout changes (3 story start card, enable national/world)

- projects/Apps/common/src/collection/card-layouts.ts
Allow cover cards on all sections except: National, World, Financial which use dense layout. Crosswords remain a special case. Life and Culture are unchanged using thirdPageCoverLayout. Sport unchanged on default.
Frequently there are 'Specials' that can benefit from cover cards. This PR attempts to lessen the restriction on where cover maybe used.
This needs testing - just a github edit, by a Product Manager :-(
> Allow cover cards on more sections

- projects/Mallard/src/components/article/html/components/header.ts
- projects/Mallard/src/screens/issue-screen.tsx
- projects/Mallard/src/screens/issue/use-size.tsx
- projects/Mallard/src/theme/spacing.ts
The main aim of this change is to fix a bug with the 'jump to section' nav where we end up in the wrong place - because we're assuming the container header is narrower than it actually is. 
This also removes all references to `sliderRadius` from the codebase now that the slider has been removed. 
[**Trello Card ->**](https://trello.com/c/8kg9Axpc/1140-bug-section-name-is-not-always-at-the-top-of-screen)
I already tested it!
> Fix section jump navigation on new slider

- projects/Mallard/src/App.tsx
Android is crashing based on the last changed to React Navigation. This lead to this recent thread:
https://github.com/software-mansion/react-native-screens/issues/309
For now, I have gone with the final suggestion but it seems our dependencies are a bit wonky on what is proving a quite unstable plugin.
> fix: Android crash with React Navigation

- projects/Mallard/src/components/front/helpers/wrapper.tsx
Dots were sitting next to the cards on the fronts. Given them a little room.
> fix: Better dot to card spacing for Android

- projects/Mallard/src/components/article/html/components/header.ts
- projects/Mallard/src/components/weather.tsx
- projects/Mallard/src/screens/article/slider/SliderHeaderHighEnd.tsx
- projects/Mallard/src/screens/article/slider/SliderHeaderLowEnd.tsx
- projects/Mallard/src/screens/article/slider/SliderTitle.tsx
- projects/Mallard/src/screens/article/slider/__tests__/__snapshots__/SliderTitle.android.spec.tsx.snap
- projects/Mallard/src/screens/article/slider/__tests__/__snapshots__/SliderTitle.android.tablet.spec.tsx.snap
- projects/Mallard/src/screens/article/slider/__tests__/__snapshots__/SliderTitle.ios.spec.tsx.snap
- projects/Mallard/src/screens/article/slider/__tests__/__snapshots__/SliderTitle.ios.tablet.spec.tsx.snap
- projects/Mallard/src/screens/issue-screen.tsx
This tweaks some of the font sizes and spacing in the new slider:
- Reduced height of the weather component/weather empty space (mainly removing empty space underneath
- Reduce height of the slider title on article pages (by an arbitrary amount)
- Update font sizes on tablet fronts/phone article pages
[**Trello Card ->**](https://trello.com/c/ysLk7D4B/1153-font-size-of-the-titles-and-the-dots-and-space-between-weather-and-top-stories-reduce-them-on-ipad-only)
Looks like this now:
Have a look at the above screenshots and see what you think!
> Design tweaks for new slider design

- projects/Apps/common/src/collection/card-layouts.ts
Reverts guardian/editions#1029
An unintended consequence of this change was that there were different card designs unleashed in Journal which were very unhelpful for Production. This PR reverts that change. There is a separate ticket in Trello for us to work out how to unleash the beauty of cover cards throughout the edition.
> Revert "Allow cover cards on more sections"

- projects/Mallard/src/components/front/helpers/wrapper.tsx
- projects/Mallard/src/screens/article/slider/SliderDots.tsx
- projects/Mallard/src/screens/article/slider/SliderTitle.tsx
- projects/Mallard/src/screens/article/slider/__tests__/SliderTitle-BaseTests.tsx
- projects/Mallard/src/screens/article/slider/__tests__/__snapshots__/SliderTitle.android.spec.tsx.snap
- projects/Mallard/src/screens/article/slider/__tests__/__snapshots__/SliderTitle.android.tablet.spec.tsx.snap
- projects/Mallard/src/screens/article/slider/__tests__/__snapshots__/SliderTitle.ios.spec.tsx.snap
- projects/Mallard/src/screens/article/slider/__tests__/__snapshots__/SliderTitle.ios.tablet.spec.tsx.snap
Separates dots out into its own component to reduce complexity. 
Has new logic to only show dots if its greater than 1 card
Updated tests for this logic
[**Trello Card ->**](https://trello.com/c/LEvjyTHl/1158-new-slider-crosswords-shouldnt-display-dots)
- Scroll down to Crosswords, see no dots
> feat: No Dots on a Single Card

- projects/Mallard/src/components/front/index.tsx
- projects/Mallard/src/screens/article/slider/SliderTitle.tsx
- projects/Mallard/src/screens/article/slider/__tests__/SliderTitle-BaseTests.tsx
- projects/Mallard/src/screens/article/slider/index.tsx
- projects/Mallard/src/screens/article/slider/slider-helpers.ts
We will need to prepare the fronts tool/future issues to be ready for the new subtitle/container title design implemented in #1028
This change adds an editionDate parameter (extracted from the edition id) so that we can prevent the subtitle from showing on issues published before a certain date.
Replaces https://github.com/guardian/editions/pull/1032
Test Plan
Check FIRST_SUBTITLE_DATE in SliderTitle.tsx. Subtitles should not be showing on issues published before this date.
> Add editionsDate param to determine subtitle visibility

- projects/Mallard/src/hooks/use-issue-summary.tsx
- When on poor connections e.g. `G` this will now read the issue summary from the filesystem.
- Read the Issue Summary from the filesystem if an error is thrown retrieving the issue summary
> fix: Issue Summary Connection Issues

- projects/Mallard/src/hooks/use-issue-summary.tsx
The App crashes because Apollo finishes loading but has no data. This causes a little connection error, but this gets bigger based on the connection fixes in #1044 
This wraps the solution in a `try... catch` to suppress the error.
But this needs further investigation
> fix: App Crash Bug

- projects/Mallard/src/helpers/files.ts
Randomly, when loading the app you will see a flash of error text along the lines of `Failed to fetch valid issue summary`. This is because RNFetchBlob has some underlying issues which causes it to fail.
As everything seems to work even when it fails, it makes sense not to throw an error when this happens but suppress it.The error is still being captured in Sentry.
Instead of throwing this error, we read from the local file store instead to ensure a valid issue summary is delivered.
> fix: Error flash on App Load

- projects/Mallard/src/screens/article-screen.tsx
This prop was causing the crossword not to load on iOS9.
Its effect is to clip items outside of the view to enable performance. So we need to see the effect on the article pages.
> fix: Crossword working on iOS9

- projects/Mallard/src/screens/issue/use-size.tsx
- projects/Mallard/src/theme/spacing.ts
This removes the smaller card size for 'shorter' tablets, which originates in this PR https://github.com/guardian/editions/pull/280 - though I can't work out what the original motivation was
I've had a play with the fronts UI on a few tablet simulators of different sizes and this change doesn't seem too problematic. In the process it resolves the trail text disappearing bug we had - which is the result of the landscape view being seen as a 'short tablet' so that when rotating back there isn't enough space for the trail text
[**Trello Card ->**](https://trello.com/c/EjTyZN2v/1157-trail-disappears-in-the-first-two-containers-after-rotating-the-ipad)
Test fronts on ios9 and any iPad available - when rotating the trail text should always remain at the bottom of the card and never disappear
> Remove short tablet size.

- projects/Mallard/src/screens/article/slider/SliderTitle.tsx
The SliderTitle height has changed - possibly as part of  https://github.com/guardian/editions/pull/1038. We need to update the SLIDER_FRONT_HEIGHT constant accordingly as this is used in the `getItemLayout` bit of the flatlist 
[**Trello Card ->**](https://trello.com/c/CoRBlCi9/1170-top-edge-of-fronts-is-not-consistently-positioned-when-navigated-to-via-menu)
Load app on phone/tablet/ios/android. Nav should take you accurately to the right place
> Fix subsection navigation alignment.

- projects/Mallard/src/components/front/helpers/front-wrapper.tsx
- projects/Mallard/src/components/front/index.tsx
- projects/Mallard/src/components/weather.tsx
On tablet view the weather spreads out more horizontally, making it shorter. We should reflect this in the fixed height of the weather component to avoid having lots of empty space between the weather and 'Top Stories'
I've also given the component that wraps fronts a slightly more descriptive name.
[**Trello Card ->** - (sort of)](https://trello.com/c/ysLk7D4B/1153-font-size-of-the-titles-and-the-dots-and-space-between-weather-and-top-stories-reduce-them-on-ipad-only)
Before:
After:
> Reduce space under weather on tablet

- projects/Mallard/src/components/front/collection-page.tsx
- projects/Mallard/src/theme/spacing.ts
There's a bit too much space between cards on the fronts at the moment. I think this comes as a side effect of this change https://github.com/guardian/editions/pull/1040 - turns out 1.35 was a magic number used in more than one place. I've put the magic number stuff into metrics and simplified it a bit (1.35*1.5 is almost 2) 
[**Trello Card ->**](https://trello.com/c/VQA96zue/1180-extra-padding-seems-to-be-between-sub-sections-on-fronts-and-between-slider-and-content-in-article-see-screenshot)
Before
After
> Reduce space between front containers

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
iOS12 keeps displaying that the user is offline. Which is a new behaviour.
Bumping the version _appears_ to stop this in local testing. But an update cant hurt too much...
> chore: Bump netinfo

- projects/Mallard/src/components/front/helpers/front-wrapper.tsx
- projects/Mallard/src/components/weather.tsx
- projects/Mallard/src/screens/article/slider/SliderDots.tsx
- projects/Mallard/src/screens/article/slider/SliderHeaderHighEnd.tsx
- projects/Mallard/src/screens/article/slider/SliderHeaderLowEnd.tsx
- projects/Mallard/src/screens/article/slider/SliderTitle.tsx
- projects/Mallard/src/screens/article/slider/__tests__/__snapshots__/SliderTitle.android.spec.tsx.snap
- projects/Mallard/src/screens/article/slider/__tests__/__snapshots__/SliderTitle.android.tablet.spec.tsx.snap
- projects/Mallard/src/screens/article/slider/__tests__/__snapshots__/SliderTitle.ios.spec.tsx.snap
- projects/Mallard/src/screens/article/slider/__tests__/__snapshots__/SliderTitle.ios.tablet.spec.tsx.snap
This PR aims to reduce padding
- between weather and the header on tablet
- between the slider and the article across the board (mobile/tablet/ios/android)
- between the dots on the slider and the section name
Note: I haven't changed the ios9 header height - pending on being in the office to have an ipad to test on. 
Note that this might still not quite match the designs - I've just aimed for making things a bit better - we've got so many moving parts design wise at the moment I'm not sure it makes sense to try and get it perfectly accurate till things have settled down
[**Trello Card ->**](https://trello.com/c/ysLk7D4B/1153-font-size-of-the-titles-and-the-dots-and-space-between-weather-and-top-stories-reduce-them-on-ipad-only)
Here are some screenshots, but this should be checked fairly …
> Padding reduction in header/weather

- projects/Mallard/src/components/front/items/helpers/sizes.ts
- projects/Mallard/src/components/front/items/helpers/text-block.tsx
- projects/Mallard/src/components/front/items/image-items.tsx
- projects/Mallard/src/components/front/items/super-items.tsx
- projects/Mallard/src/theme/spacing.ts
- projects/Mallard/src/theme/typography.ts
The fronts cards currently don't match the designs - the most notable issue being that they're too long. 
This change
- Adds a lot of specificity to the image height calculator function - along with documentation explaining what each set of magic numbers means. 
- Changes the height of images for loads of cards
- Adds more specificity to the getFontSize calculator - and changes a load of font sizes, including...
- Introduces a new `0.9` headline typography level which is used in secondary stories on tablet view so that we can have a size 22 font (up from 21). This non-design-systemy font size is needed to get the maxmimum density without the text running off the edge of the card
- Adds new `2.5` titlepiece font size - this is design system sanctioned, just unused in editions till now. 
- …
> [Needs design review] Design realignment/megatweak

- projects/Mallard/src/screens/article/slider/SliderDots.tsx
- projects/Mallard/src/screens/article/slider/SliderTitle.tsx
- projects/Mallard/src/screens/article/slider/__tests__/__snapshots__/SliderTitle.android.spec.tsx.snap
- projects/Mallard/src/screens/article/slider/__tests__/__snapshots__/SliderTitle.android.tablet.spec.tsx.snap
- projects/Mallard/src/screens/article/slider/__tests__/__snapshots__/SliderTitle.ios.spec.tsx.snap
- projects/Mallard/src/screens/article/slider/__tests__/__snapshots__/SliderTitle.ios.tablet.spec.tsx.snap
In the latest master build the section nav is broken - I think because all the cards got shorter. This remedies that, though 
The navigation should succesfully jump to 'Sport'
Before:
After:
> Fix section nav, add padding under dots

- projects/Mallard/src/components/article/html/components/icon/native-arrow.tsx
- projects/Mallard/src/components/article/html/components/images.ts
- projects/Mallard/src/components/article/types/article.tsx
- projects/Mallard/src/screens/lightbox.tsx
To display the images in the gallery mode we have implemented the Lightbox gallery feature. The original design has changed little bit to have a consistent design for portrait and non-portrait images. Please see the screenshot.
Note: there is a known issue (maybe existed prior to this work) with the current gallery. When there are more images then progress dots the animation of the dots stops after the last dot. There is also another issue, on tablet/iPad after rotating the device a few times when Lightbox/Gallery is open then clicking on the `X` button leads you to the home front instead of the gallery article.
[**Trello Card ->**](https://trello.com/c/cHzA5VHs/940-fullscreen-gallery-slideshows)
> Lightbox: View images in the gallery 

- projects/Mallard/src/components/article/types/article.tsx
To support sharing `title` and `url` of the Article we needed to pass more params to `share` function. This is is just for that.
[**Trello Card ->**](https://trello.com/c/UXtfgVbs/1097-share-include-the-title-of-the-article-followed-by-the-article-link-itself)
Tested on android and ios. Below are the example screenshots of the share feature on twitter, before and after the fix.
| --- | --- |
|![IMG_0101](https://user-images.githubusercontent.com/6583174/76417481-da7a9e00-6394-11ea-95ad-0f1bc74acfb9.PNG)|![Image-1](https://user-images.githubusercontent.com/6583174/76417493-dea6bb80-6394-11ea-8989-fb02cc295a2e.jpg)|
> Added more fields to the share function to support wide range of sharing clients

- projects/Mallard/src/components/front/items/helpers/text-block.tsx
- projects/Mallard/src/theme/typography.ts
Requests from Ana - some very tiny tweaks to the design of fronts cards.
- less space between  the quote and headline on journal cards
- shorter line height of trail text (this should really be font size * 1.15 everywhere but we've tended to round it up)
before
after
before
after
Trail text
before 
after
> Reduce space between quote/text on journal. Tighter trail line height.

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/yarn.lock
We've seen a return of the bug where users can get signed out when they use the app with poor/no connectivity. This bumps the netinfo version in the hope that our problem has something to do with a [recent fix they made](https://github.com/react-native-community/react-native-netinfo/commit/4e3e981) related to the internet reachability property.
[**Trello Card ->**](https://trello.com/c/kuJzY3KU/1201-ios-671-build-has-signed-me-out-when-i-opened-it-in-the-tube)
Try using app in places with bad internet, make sure we don't get signed out
> Bump netinfo to 5.6.2

- projects/Mallard/src/components/front/index.tsx
Complaint that midtier devices are crashing. This could be due to the flatlist performance.
I have left the vertical scroll the same, but this may need to be paired back as well.
> chore: Update to horizontal scroll perf

- projects/Mallard/src/screens/settings-screen.tsx
Due to a change in identity, names were taken out of the sign in response unless a user has expressly stated to share it. We are displaying these names as part of the sign in.
As a result we are changed this for the email address.
This will require further work to complete the ticket.
[**Trello Card ->**](https://trello.com/c/JkkpLZQ6/1208-change-the-information-we-display-on-the-sign-in-are-when-users-are-signed-in-from-name-username-to-email)
> chore: Replace sign in name with email

- projects/Mallard/src/helpers/files.ts
The way the rn-fetch-blob library we're using works, it downloads the zip files of issues to files called something like RNFetchBlobTemp_*. We then unzip these files to the 'issues' directory. After the unzip completes, we [delete the zip file](https://github.com/guardian/editions/blob/master/projects/Mallard/src/helpers/files.ts#L94). However, if something goes wrong (e.g. connection loss) during this time the 'delete' never happens, and we end up with orphaned files (which can be big if it's the images zip). 
This PR is a fairly hacky fix for this issue but in my head it makes sense as it feels like this is a state we can always get into no matter how carefully we write the download code - the app could crash for any reason during the download, resulting in orphaned files. 
This change …
> Clear temp files when deleting all downloads.

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
- projects/Mallard/ios/Mallard.xcodeproj/xcshareddata/xcschemes/Mallard-tvOS.xcscheme
- projects/Mallard/ios/Mallard.xcodeproj/xcshareddata/xcschemes/Mallard.xcscheme
- projects/Mallard/ios/Podfile.lock
Xcode11 migration in preparation for Apple sign-in integration. 
Initial migration was a challenge as directly migrating through xcode led to tons of dependancy errors. In the end the trick was to wipe all configs and build files completely and allow xcode11 to decide settings and such. From there I reran the build and this PR was the net result. 
Looking at the actual config changes I dont think the build system will have a problem. I expect the build system might fail when we introduce a lib that actually depends on Xcode11 (expo apple sign-in). 
Because of the above we will do this in two steps. We will test to see if this works first. If it works fine then lets merge it. The next step will be to introduce unimodules and the expo package into the app without implementation and see if …
> xcode11 migration

- projects/Mallard/Makefile
We need to move to xcode 11 for apple sign in and because apple is gonna force us to. This updates the makefile to tell teamcity which xcode installation to use
[**Trello Card ->**](https://trello.com/c/vmDa7pQl/1210-xcode-11-upgrade)
Check that we can build/release the app. I've run the ios-debug-deploy config in teamcity which was succesful
> Update DEVELOPER_DIR to xcode 11.

- projects/Mallard/src/components/article/types/article/webview.tsx
This brings back the bounce on the article screen for higher end devices.
This was originally removed as a performance improvement. But now we have a better way to differentiate between low and high end devices.
Trello: https://trello.com/c/H4OdxtJ9/1207-end-of-article-is-abrupt-and-not-clean-and-like-traditional-scrolling
> Feat: bring back the bounce

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Bumps us to `6.1` for a future release
> chore: Bump iOS Marketing Version

- projects/Mallard/src/components/front/items/items.tsx
Adds an accessibility label to the cover cards to be picked up with screen readers.
> chore: Accessible cover cards

- projects/Mallard/Makefile
- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
- projects/Mallard/ios/Mallard.xcodeproj/xcshareddata/xcschemes/Mallard-tvOS.xcscheme
- projects/Mallard/ios/Mallard.xcodeproj/xcshareddata/xcschemes/Mallard.xcscheme
- projects/Mallard/ios/Podfile.lock
This reimplements https://github.com/guardian/editions/pull/1092 and https://github.com/guardian/editions/pull/1094 once we've got the teamcity build working again. I reverted these to reduce the number of possible changes that could have resulted in a broken build on teamcity - though suspect that they aren't the cause
> Reimplement xcode 11 change

- projects/Mallard/src/helpers/files.ts
- projects/Mallard/src/screens/home-screen.tsx
Currently when we are in the same edition, we do a lot of "expensive" navigation when clicking on a sibling sub nav item.
This small change just puts as back to the previous view and removes a lot of required processing.
I imagine this is the largest use case of the sub navigation.
> Fix: Subnav speed boost

- projects/Mallard/src/components/toast/net-info-auto-toast.tsx
Increases the timeout before checking to show the message. This is likely a race condition, so this gives older devices the opportunity to catch up a bit.
Hopefully its not too long.
[**Trello Card ->**](https://trello.com/c/U6FT6QaB/1172-ios-12-ios-9-no-connection-popping-up)
> chore: Increase Netinfo Timeout

- projects/Mallard/src/components/spinner.tsx
This revives the dots to be animated on higher performing devices. A little bit of duplication here to maintain a separate implementation.
Based on this commit: https://github.com/guardian/editions/commit/ccaa7bddd094cc9b2105e655dd88a548844112bc#diff-122fbd8305d1772cbbf83eef6f64dd02
[**Trello Card ->**](https://trello.com/c/6KDYH45v/1176-return-animation-to-dots-splash-screen)
> Feat: Revive Animated Dots (spinner)

- projects/Mallard/src/components/front/index.tsx
This one is Shraddha's favourite.
Here we look for a change in the data for the flatlist. If it occurs we scroll back to the start.
[**Trello Card ->**](https://trello.com/c/bNpXGpgU/1118-not-for-ios-9-current-build-625-ios-switching-between-editions-sub-section-it-keeps-the-position-from-earlier-issue)
- Scroll on a front on the issue screen
- Change editions, all should be reset.
> feat: Reset the front scroll when the edition changes

- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/apollo.ts
- projects/Mallard/src/components/front/image-resource.tsx
- projects/Mallard/src/hooks/use-image-paths.ts
- projects/Mallard/yarn.lock
During the testing of Storybook, the main reason it wasn't working was down to the Image Resizer. I experimented with removing it and saw speed improvements on loading images in iOS9 and iPad Pro latest OS. Which was a surprise.
I tested my iOS9 device and it didn't seem to cause any crashes. This is likely down to using `phone` images on low end devices and therefore the resize was doing nothing other than eating up memory.
There may be an edge case device where it helps so we will need to keep an eye out on our error logging services.
> feat: Remove image resizer

- projects/Mallard/src/components/front/image-resource.tsx
Cover cards disappeared when removing the image resizer. This puts them back.
> Fix: Missing cover cards

- projects/Mallard/README.md
The latest version of cocoapods is 1.9 when we're currently using 1.7. This readme change encourages people to install the version of cocoapods we're currently using
> Include specific version of cocoapods in readme

- projects/Mallard/android/app/build.gradle
I needed to add this to get android builds working on the teamcity ubuntu boxes. If we get any failed builds I'd be tempted to push this higher (as the agents should have 8G available) but this setting has worked 3 times in a row now..!
Any changes to this value should be kept in sync with https://github.com/guardian/editions/blob/master/projects/Mallard/android/gradle.properties#L7
> Bump javaMaxHeapSize in build.gradle

- projects/Mallard/src/helpers/files.ts
This change https://github.com/guardian/editions/pull/1076 made incorrect use of the [isDir](https://github.com/joltup/rn-fetch-blob/wiki/File-System-Access-API#isdirpathstringpromise) function provided by RNFetchBlob - it actually returns a promise! This mistake results in errors that look like this when you run the app:
This change remedies the situation. cc @mohammad-haque
> Fix call to RNFetchBlob.isDir - deal with it being a promise.

- projects/Mallard/src/theme/typography.ts
On small screens (common on android phones but also iPhone 5s) the font for single story cards is smaller than that of 2 story cards - I think because the 'small phone' font size hasn't been updated inthe various other changes we've made. This rectifies that situation following a request from Ana. 
[**Trello Card ->**](https://trello.com/c/Od8HjK1o/1184-density-work-mobile-summary-of-image-and-text-sizes)
Test on android device with small screen or iPhone 5s - text of 1 story cards should be a bit bigger:
Before
After
> Increase 1.5 headline font size on small phones to 24

- projects/Apps/common/src/collection/card-layouts.ts
This reimplements https://github.com/guardian/editions/pull/1029 with a restriction that the Journal front should stay the same - the goal is to 'Allow cover cards on all sections except: National, World, Financial which use dense layout.' 
[**Trello Card ->**](https://trello.com/c/pKeo62Sc/1165-allow-any-card-to-be-a-cover-card)
We should check a few issues going forwards. This change will only become visible when fronts are newly published or republished - so we'll need to check either on CODE or just wait for new editions to go out whilst testing internally
> Allow splash/cover cards on more fronts (not Journal).

- projects/Mallard/android/app/src/main/AndroidManifest.xml
- projects/Mallard/android/app/src/main/java/com/guardian/editions/MainActivity.java
This PR enables landscape orientation for android tablet devices.
[**Trello Card ->**](https://trello.com/c/8J0Vn47y/1072-android-orientation-what-are-the-possibilities)
**Screenshots**:
| Tablet Port | Tablet Land |
| --- | --- |
|![Screenshot_1586362550](https://user-images.githubusercontent.com/6583174/78808778-d22a7880-79bd-11ea-8678-28560dbe6efc.png)|![Screenshot_1586362536](https://user-images.githubusercontent.com/6583174/78808789-d787c300-79bd-11ea-9597-54479a732e9e.png)|
> Enabled rotation for android tablet devices

- projects/Mallard/android/app/src/main/AndroidManifest.xml
Changed the soft keyboard adjustment so uses Pan rather than window adjust
When a user tries to enter subscription details the soft keyboard pops up and the input field pushed outside of the visible window. This PR change soft keyboard behaviour to fix this issue. 
[**Trello Card ->**](https://trello.com/c/QDIpoJPL/1226-android-unable-to-signin-using-subscriber-id-keyboard-missing)
**Screenshots**:
| --- | --- |
|![Screenshot_1586862760](https://user-images.githubusercontent.com/6583174/79247319-48255880-7e72-11ea-9cf7-d86280c16578.png)|![Screenshot_1586880006](https://user-images.githubusercontent.com/6583174/79247463-7c991480-7e72-11ea-95b7-89edd775413e.png)|
> Fix: Input field pushed out of window in android

- projects/Mallard/android/app/build.gradle
- projects/Mallard/android/gradle.properties
- projects/Mallard/android/gradlew
...in an attempt to fix our teamcity builds let's throw loads of memory at this. The machines teamcity runs on have [16gb of memory](https://www.ec2instances.info/?region=eu-west-1&cost_duration=annually&reserved_term=yrTerm1Standard.allUpfront)
> Increase javaMaxHeapSize to 6 GB in builds

- projects/Mallard/src/hooks/use-deprecation-screen.ts
Local builds do not have an actual build number that PROD build has (generated by TC). This PR updated the deprecation logic so it does not apply to dev build.
> Avoid deprecation logic does for dev build

- projects/Mallard/package.json
Removes Storybook server from start up. Its not required as we use standalone server.
Tested with a clean install and all seemed fine.
> fix: Remove storybook server

- projects/backend/capi/__tests__/imageParser.spec.ts
- projects/backend/capi/elements.ts
Links on gallery items were not previously working. 
This is a small change to leave the caption formatted as it is in CAPI which contains the link. 
[**Trello Card ->**](https://trello.com/c/t8cJ1HfW/946-gallery-links-dont-work)
I have added two fashion gallery articles to the "Life" section on the 9th April code edition, the image captions should now have working links.
> Fix-Gallery-Links

- projects/Mallard/android/app/build.gradle
This PR implements a simple auto versioning for the android app.
App version schema:
`major.minor.patch`
For the android app this PR propose this:
`major`: we will update this manually possibly after a big release
`minor`: auto-increment after every 2nd build
`patch`: auto-increment after every TeamCity build
Android app's current version number (not the version name) is 13412887 !!!
This version number is being generated from this line:
`def vcode = (int)(((new Date().getTime()/1000) - 1451606400) / 10)`
It does not make sense to me why we went with this kind of magic number in the first place. Unfortunately, we can't change this now.
> Implemented app versioning for android

- projects/Mallard/src/components/article/html/components/header.ts
This fixes a bug found in the internal beta where gallery articles were showing "undefined" as their standfirst. This adds a check to ensure the standfirst exists before adding it as a string in the standfirst. 
[**Trello Card ->**](https://trello.com/c/VYkl25RG/1247-standfirst-appears-to-be-replaced-by-undefined)
The gallery article in the ticket can be found in the National section of Wednesday 22nd issue.
> am-fix-undefined-standfirst

- projects/Mallard/src/components/layout/header/header.tsx
When accessing an article, going into the background and then returning to the issue screen, the header would go a bit wonky. This fixes it.
> fix: Header Overflow

- projects/Mallard/src/helpers/files.ts
- When a user has a download blocked, then we log this as an error to Sentry. This maybe a bit overkill and may need removing in future.
- When a zip file fails to unzip, we now log this as a Sentry error. This will help highlight if this is a problem in the push download process.
> chore: File Sentry Logging

- projects/Mallard/src/components/layout/header/header.tsx
- projects/Mallard/src/navigation/navigators/article/transition.tsx
`transform -> scaleX` is having the strange effect that it maintains its zoomed state when used and the user puts the app in the background. For example a user clicks on an article. `scaleX` becomes 0.9. Go into the background and back again. `scaleX` is still 0.9, but to some degree its reset as 1 in ios13. So when you then close the article, scaleX has the visual appearance of 1.1. This can build up to a point where it stops getting bigger. Ultimately, the animation is calculated by props passed into it from `React Navigation` which seems to lose state when it goes into the background on ios13.
A plan B approach is to avoid using scale for iOS13 - but you then lose the nice animation 😢
> fix: Alternative article animation for iOS13

- .github/workflows/main.yml
Since we're buildiing on every merge to master it doesn't make sense to also run a scheduled build every day
> Stop scheduled build

- projects/Apps/common/src/logging.ts
- projects/logging/application.ts
Following from discussion - this change modifies the log service to make the endpoint more specific to mallard rather than elasticsearch, and updates the endpoint path in line with this. 
I've removed the nested `metadata` type to simplify things on the client side.
> Remove ELK specific syntax from log format.

- projects/Mallard/src/components/article/html/components/images.ts
- projects/Mallard/src/components/article/html/css.ts
This PR improves the appearance of gallery links on dark themed articles. 
[**Trello Card ->**](https://trello.com/c/t8cJ1HfW/946-gallery-links-dont-work)
Go to Saturday 2nd May edition and go to the LifeStyle section and open the article "The edit...Softly does it: 10 of the best lilac pieces"
| --- | --- |
> am-style-gallery-links

- projects/Mallard/src/services/logging.ts
A PR change that wasn't pushed.
This removes the unnecessary string => parse => string.
> chore: Logging missing update

- projects/Mallard/src/App.tsx
- projects/Mallard/src/screens/settings/gdpr-consent-screen.tsx
- projects/Mallard/src/services/__tests__/logging.offline.spec.ts
- projects/Mallard/src/services/__tests__/logging.spec.ts
- projects/Mallard/src/services/logging.ts
- Adds in new logging consent wording
- Uses the GDPR performance consent flag
- If set, will allow the use of log. Off by default
- Tests to cover consent.
Please note: `log()` is considered our only public function in the class, but the others remain public for mocking.
> feat: Consent for Logging

- projects/Mallard/src/helpers/settings.ts
- projects/Mallard/src/navigation/index.ts
- projects/Mallard/src/screens/onboarding/cards.tsx
- projects/Mallard/src/screens/settings/gdpr-consent-screen.tsx
This was partially implemented by @LATaylor-guardian.
When changing the `CURRENT_CONSENT_VERSION` the user will be required to consent again.
Changes:
- Reset now visible when in a simulator on the privacy settings page to make it easier to reset GDPR flags.
- Check that what we have in Async Storage matches the current version. If not then re-consent. As we haven't been saving this you will be asked to re-consent. As will all users.
> feat: Require consent on version change

- projects/Mallard/src/components/article/html/article.ts
- projects/Mallard/src/components/article/html/components/header.ts
This PR includes: 
- Adding standfirsts to gallery articles 
- Removing unused byline space when there is no text or share button 
- Fixes a bug on gallery articles which meant that the share button was hidden
[**Trello Card ->**](https://trello.com/c/yE4bf7oX/868-no-byline-version-of-standard-article-and-mappings)
I have attached screenshots of gallery articles from the coronavirus front on April 29th edition. 
| --- | --- |
> Am add standfirst to gallery

- projects/Mallard/src/App.tsx
- projects/Mallard/src/services/logging.ts
If we have an issue sending logs, there could be a large backlog of logs stored on a users device taking up precious space.
This will attempt to push those logs on a cold start of the app. If it fails, then we clear them.
> feat: Delete logs on first startup

- projects/Mallard/src/components/BugButton.tsx
- projects/Mallard/src/components/article/article-image.tsx
- projects/Mallard/src/components/article/html/components/header.ts
- projects/Mallard/src/components/issue/issue-row.tsx
- projects/Mallard/src/components/weather.tsx
- projects/Mallard/src/screens/home-screen.tsx
Adding accessibility labels and hints for users who use screen readers.
[**Trello Card ->**](https://trello.com/c/KlhS5zcI/1214-accessibility-voice-over-not-describing-buttons-and-skipping-special-containers-on-the-front)
> Accessibility of buttons

- projects/aws/lib/logging-stack.ts
This is a a typo/mistake - API_KEY is referred to elsewhere in the code using all CAPS, let's be consistent else it won't work!!
> Correct name for API_KEY env. var.

- projects/Mallard/src/components/front/index.tsx
This fixes a bug introduced by https://github.com/guardian/editions/pull/1104/files where if a front has zero stories the app crashes with an error "Invariant Violation: scrollToIndex out of range: requested index 0 but maximum is -1"
This is a problem in the preview environment where there are often empty fronts as they haven't been worked on yet. 
[**Trello Card ->**](https://trello.com/c/bChIrA4i/1277-preview-mode-on-vpn-broken-on-builds-post-675)
- check that the 'scroll to top' functionality still works with this change
- check that preview now works
> Only jump to start of front if it has > 0 stories.

- projects/Mallard/src/services/__tests__/logging.android.spec.ts
- projects/Mallard/src/services/__tests__/logging.offline.spec.ts
- projects/Mallard/src/services/__tests__/logging.spec.ts
- projects/Mallard/src/services/logging.ts
As pointed out by @mohammad-haque, our tests were not running independent of each other as they should. This now creates a clean logging instance for each test.
> chore: Logging Test Independence

- projects/Apps/common/src/logging.ts
- projects/Mallard/src/App.tsx
- projects/Mallard/src/helpers/async-queue-cache.ts
- projects/Mallard/src/helpers/push-tracking.ts
- projects/Mallard/src/services/__tests__/logging.offline.spec.ts
- projects/Mallard/src/services/__tests__/logging.spec.ts
- projects/Mallard/src/services/errors.ts
- projects/Mallard/src/services/logging.ts
This includes:
- Better test coverage
- Number of attempts feature
- Split out of async cache methods into their own class, which is then used in Logging
- Removal of now not needed `console.log`
- Add logging to the error service
> chore: Refactor Logging service

- projects/backend/capi/__tests__/articleImgPicker.spec.ts
- projects/backend/capi/articleImgPicker.ts
- projects/backend/capi/articleTypePicker.ts
- projects/backend/capi/articles.ts
- projects/backend/controllers/fronts.ts
The work in https://github.com/guardian/editions/pull/1150 missed out any immersive images used on 'Interview' content - as this content is immersive in editions despite not having a `displayHint` set. This change passes `ArticleType` through to the `getImageRole` function so that it can be used to determine the image role, I've also added a comment above the  `isImmersive` function in the article type picker as this isn't the only thing that triggers immersive style articles. 
In my testing this definitely improved the quality of interview content. There may still be some more work needed on this card for cartoons, but I think this is good to ship for now.
[**Trello Card ->**](https://trello.com/c/n7kMZP7I/935-immersives-images-are-pixelated-on-ipad-and-android)
This is a backend only …
> Improving immersive qualiity: Use ArticleType to determine image role

- projects/backend/capi/articleTypePicker.ts
Moves isLetter above isSeries in the Journal front. This allows the brief letters series to get the no byline treatment.
Consistent templating for letters.
[**Trello Card ->**](https://trello.com/c/yE4bf7oX/868-no-byline-version-of-standard-article-and-mappings)
Untested - edited in Github.
> Tiny change to make letters trump series in the Journal.

- projects/Mallard/src/components/BugButton.tsx
- projects/Mallard/src/components/article/article-image.tsx
- projects/Mallard/src/components/article/html/components/header.ts
- projects/Mallard/src/components/issue/issue-row.tsx
- projects/Mallard/src/components/weather.tsx
- projects/Mallard/src/screens/home-screen.tsx
- projects/Mallard/src/screens/settings-screen.tsx
- projects/Mallard/src/screens/settings/manage-editions-screen.tsx
This work aims to make the switches accessible. I've added the following tags to the <Switch> on Manage editions screen and also Display weather on the Settings.
`accessible={true}`
` accessibilityLabel="Switch button"`
` accessibilityHint="Double tap to toggle setting"`
**Manage editions screen:**
The switch on Wifi-only is reading "zero button" when turned off and "one" when turned on
**Settings:**
The switch to display or hide the weather is not being read at all.
PS: This first work might not inform the statuses ON/OFF yet. We might need to add extra code for that
[**Trello Card ->**](https://trello.com/c/PGNlmNad/1283-accessibility-make-switches-accessible-to-screen-readers)
1. Turn on VoiceOver/TalkBack on accessibility settings on iOS/Android.
2. Try to use the switches in the app …
> Add accessiblity properties to some more components

- .github/workflows/scheduled-ios-beta.yml
- .github/workflows/upload-build.yml
We need to bundle this key with the app otherwise logging won't work!
> Add logging api key as env. var to ios build.

- projects/Mallard/src/components/article/html/components/header.ts
As found in the beta, the byline is tappable when there is a link. 
This commonly happens when there is a profile name with a link to a profile that the app cannot open. 
This is a small change to ensure that the byline text cannot be tapped by the user and avoids an error screen being shown. 
[**Trello Card ->**](https://trello.com/c/WEcQlMvl/1291-ensure-byline-text-cannot-be-tapped)
Open an article which has a profile name in the byline, ensure it doesn't respond to touch events and doesn't show an error page.
> remove-touch-from-byline-text

- projects/Mallard/src/screens/settings/subscription-details-screen.tsx
This PR contains a swap of username to email in the subscription details. An identity account is not guaranteed to have a username set but it will have an email address.
[**Trello Card ->**](https://trello.com/c/r9zLNZr0/1221-replace-the-username-on-the-subscription-details-screen-to-email-address)
> Update username to email on subscription details

- projects/backend/capi/__tests__/articleImgPicker.spec.ts
- projects/backend/capi/articleImgPicker.ts
Following from https://github.com/guardian/editions/pull/1173 this PR exploits the 'role' field some more in order to increase the quality of picture images.
The main motivation here is to work around cartoons being blurry on ios9. Having lower quality images is a compromise that we accepted to get memory usage down on ios9 - we force them onto phone quality images in [screen.ts](https://github.com/guardian/editions/blob/master/projects/Mallard/src/helpers/screen.ts#L61)
We got a lot of complaints about blurry cartoons when we released to ios9 so it seems a good idea to try do something about it. Furthermore, there aren't very many cartoons in a given edition, so it seems safe to make them a special, higher quality case, as the overall impact on bundle size should be small. 
So this …
> Serve 'immersive' images for all picture content.

- projects/logging/application.ts
This change just adds an extra log line to the logging service to help diagnose why logs are currently failing.
> Logs for the log service in the event of api key mismatch

- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
Bump version number since we've just released to production, should fix automated beta builds.
> chore/ bump ios version number

- projects/Mallard/src/helpers/__tests__/push-tracking.spec.ts
- projects/Mallard/src/helpers/push-tracking.ts
Push downloads rely on being connected. To help diagnose false bugs, having this as part of the push tracking stored locally will give us more information on if this was a factor in the process of downloading an edition.
[Trello Card ==>](https://trello.com/c/Eb0vUhj3/1249-add-network-status-in-push-tracking)
> feat: Add NetInfo state to the push tracking

- projects/backend/capi/__tests__/articleImgPicker.spec.ts
- projects/backend/capi/articleImgPicker.ts
Reverts guardian/editions#1179 - I suspect this has caused crashing problems in ios9. Perhaps there's more 'picture' type content than we previously thought.
> Revert "Serve 'immersive' images for all picture content."

- projects/Mallard/src/helpers/files.ts
Looking at Sentry, we get a fair amount of `failed to open zip file`. This adds a little more information on that error to give us a bit more insight,
[Sentry Error ==>](https://sentry.io/organizations/the-guardian/issues/1634734859/?project=1519156&query=is%3Aunresolved)
> chore: More info on Unzip Errors for Sentry

- projects/aws/lib/logging-stack.ts
- projects/logging/application.ts
This fixes the log line in https://github.com/guardian/editions/pull/1187 - adding the logs in the right place this time. I've also dropped the memory and max. execution time for the service as over several thousand invocations it hasn't gone over 100MB memory usage so far.
> More logging around logging service 

- projects/Mallard/src/helpers/files.ts
This one is a long running error. This seems to be because the `fetch` method on `RNFetchBlob` doesn't have a `json` method on the resolved promise. 
Also trying to read the written file using `readFile` always gives an empty object.
What I think is happening is **every** time someone goes to fetch the `IssueSummary` we are actually being pushed into the `catch` block and returning the file read from the file system. Which happened to be what was initially written.
So we were always throwing errors but also having the latest `IssueSummary`
This now doesn't attempt to return JSON from the RNFetchBlob but just read from the file system once RNFetchBlob has finished. This may have been initially caused by an update to `RNFetchBlob`
[**Sentry Error …
> fix: Issue Summary read error

- projects/Mallard/src/helpers/files.ts
There are multiple errors in Sentry that state that the issue summary cannot be read due to a `JSON.parse` error. This will capture that error and provide a bit more information.
This isnt a fix, but an attempt to get more feedback.
> chore: More info on Issue summary error

- projects/logging/application.ts
Due to an issue fixed by this PR: https://github.com/guardian/editions/pull/1196 the currently released version of the app doesn't have a logging API key bundled with it so we're throwing away all logging data before sending it to ELK. 
This change disables the requirement for there to be an apikey included in requests to the logging service.
If we're switching this off it raises the question 'why bother with an api key at all'? Anyone would be able to decompile the app to get hold of the api key if they wished.
The motivation is that having an api key of some kind allows us to potentially rotate the key should we experience an incident on the logging endpoint. At the moment that would mean breaking logging for all current users of the app, but potentiall some kind of remote config …
> Disable api key for logging service

- projects/aws/lib/logging-stack.ts
- projects/logging/application.ts
This limits the logging service to serve a maximum of 5 million requests per day. We currently have around 50,000 users, so this allows for 100 requests per user.
This would lead to a maximum no. requests of 150 million per month. 
Based off the [api gateway pricing](https://aws.amazon.com/api-gateway/pricing/) $165
For [lambda](https://aws.amazon.com/lambda/pricing/) we pay $0.2 per million invocations plus a small amount per 100ms of execution time which I think adds up to around  $40.
The cloudwatch logs pricing is $0.57 per gb of data ingested. Assuming a log request size of 5KB, 150 million requests would cost 150*5/1000000 = $407. This is the most worrying number which we should keep an eye on. I am hoping in practice this will be a lot lower with fewer and smaller requests. …
> Add usage plan to logging service, move api key into api gateway

- projects/aws/lib/logging-stack.ts
- projects/logging/application.ts
- projects/logging/package.json
- projects/logging/yarn.lock
Following from https://github.com/guardian/editions/pull/1200 this sets a limit on the max size of log data, to keep costs down (as api gateway requests can be up to 10MB in size).
It also modifies the backend to automatically override the app,stack,stage params as these should be consistent with the logging endpoint used (currently we are logging uk.co.guardian.gce as the app, which doesn't work very well for filtering in ELK - which isn't too into full stops I think)
> Only log requests below a certain size. Override app,stack,stage params.

- projects/backend/capi/__tests__/articleImgPicker.spec.ts
- projects/backend/capi/articleImgPicker.ts
Reverts guardian/editions#1190 - maybe this wasn't what was causing the app to crash on ios9 after all.
Testing
=====
I did some testing on last weekend's editions.
Sat 16th May mobile zip before: 40.0MB after: 40.3MB
Sun 17th May mobile zip before: 36.8 after: 36.8MB
> Reimplement higher quality picture content

- projects/logging/application.ts
OOPS! Doh. @jimhunty spotted a lot of 413 errors in Sentry which were probably caused by this. We are blocking requests BELOW a certain size rather than above.
Backend only change
> Fix less than sign wrong way round

- projects/Mallard/src/services/logging.ts
Following from https://github.com/guardian/editions/pull/1200 we are now using the api key functionality built into [API Gateway usage plans](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-api-usage-plans.html)
This expects the key to be included in a header called `x-api-key`
Currently we don't require an api key so no change expected, but this supports us being able to switch on requiring a key in feature.
> change header name for logging api key.

- projects/logging/application.ts
As detailed [here](https://github.com/guardian/cloudwatch-logs-management#shipping-lambda-logs-to-elk) the cloudwatch logs management service automatically adds a timestamp field based off the server-side time of the log message. I think it would be useful to store both server and client side timestamps, so let's move the client side timestamp into a separate field.
> Logging: Rename timestamp field coming from client.

- projects/Mallard/src/services/logging.ts
Currently if we try to post some logging data to the log service and it returns an error code (anything non 200) we 'queue' the message to send again in future. The downside of this is that it can result in a 'loop' where a log fails and gets queued again repeatedly if e.g. the backend service is down. 
I'm not certain this is the best way to fix this but is a quick way to make us more resilient to backend failures (which willl always happen at some point). Happy to do something else too.
This should have no noticeable user facing change but should reduce the number of logging related errors we see in Sentry
> Don't requeue failed logs.

- projects/logging/application.ts
I'm interested to see the size of requests we're getting in as there are still some errors in sentry (though much lower than before). This should give us a good idea.
> Add error logging when size too big.

- projects/Mallard/src/services/errors.ts
We keep hitting our sentry quota. This will help alleviate this problem by only posting 20% of error events to Sentry. Looking at the [dashboard](https://sentry.io/organizations/the-guardian/issues/?project=1519156&query=&statsPeriod=14d) most events happen thousands of times so this won't reduce our ability to spot bugs (should help it as it won't go dark all the time!)
Release this, check that Sentry logging still works (and event count has gone down)
> Add 20% sample rate to sentry client.

- projects/Mallard/src/helpers/files.ts
RNFtechBlob's fetch causes us a lot of I/O errors. This will reduce the reliance by returning what we get back from the API rather than trying to read a file in a write state. The promises in this library seem a bit wonky so this will help.
> fix: Reduce reliance on RN Fetch Blob

- projects/Mallard/src/screens/article/slider/index.tsx
It has been noticed that we are not recording all Article views in Ophan. This change will record an article view when a user swipes across to the next article.
> feat: Ophan Page View on Article Swipe

- projects/Mallard/src/helpers/settings.ts
- projects/Mallard/src/screens/settings/gdpr-consent-screen.tsx
Update functionality consent to include Apple and the new wording.
I have also made the app re-consent as this will change for users.
[**Trello Card ->**](https://trello.com/c/1zUv505q/1338-add-apple-sign-in-on-the-consent-screen-under-functional)
> chore: Apple Functionality Consent

- projects/Mallard/android/app/build.gradle
- projects/Mallard/android/app/google-services.json
- projects/Mallard/android/build.gradle
- projects/Mallard/ios/GoogleService-Info.plist
- projects/Mallard/ios/Mallard.xcodeproj/project.pbxproj
- projects/Mallard/ios/Mallard/AppDelegate.m
- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/App.tsx
- projects/Mallard/src/components/Lightbox/__tests__/LightboxCaption.spec.tsx
- projects/Mallard/src/components/article/html/__tests__/images.spec.ts
- projects/Mallard/src/components/article/types/article.tsx
- projects/Mallard/src/screens/log-in.tsx
- projects/Mallard/src/services/remote-config.ts
- projects/Mallard/yarn.lock
This attempts to implement [firebase remote config](https://rnfirebase.io/remote-config/usage) for apple sign in and lightbox. 
I've copied a lot of stuff from @mohammad-haque 's [crashlytics pr](https://github.com/guardian/editions/pull/1142) to get this working. This is currently pointed at our CODE firebase environment - you should be able to see and set the config values [here](https://console.firebase.google.com/u/0/project/guardian-daily-edition-code/config)
I'm not sure whether to modify this to point at our PROD firebase setup in this PR or to try and support both via the debug/release tags in xcode - any thoughts @mohammad-haque ?
Not sure the approach I've gone for the lightbox disable/enable is the best it could be but it does the job - happy to change it though. 
The default …
> Remote config for apple sign in, lightbox

- projects/Mallard/src/components/Stars/Stars.tsx
- projects/Mallard/src/components/Stars/__tests__/Stars.spec.tsx
- projects/Mallard/src/components/Stars/__tests__/__snapshots__/Stars.spec.tsx.snap
- projects/Mallard/src/components/front/items/small-items.tsx
- projects/Mallard/src/components/front/items/trail-image-view.tsx
- projects/Mallard/src/components/stars/Stars.stories.tsx
This was white when it should have been yellow.
Also after discussion with Ana, I have changed the API a bit so that it is based on positioning rather than type. This is a bit literal for my liking but will help with understanding in the future.
> fix: Correct the Star background colour

- projects/Mallard/src/services/__tests__/logging.spec.ts
- projects/Mallard/src/services/logging.ts
We should try to keep log messages reasonably small unless we find it's particularly valuable to have big blobs of json there. This replaces https://github.com/guardian/editions/pull/1214 with a more general solution
After release check logs in elk to verify that critical info is still coming through
> Add limit to log message length.

- projects/Mallard/src/screens/identity-login-screen.tsx
When a user types in invalid login credentials we ought to show an error message. For some reason we're not doing that at the moment. This change fixes that.
[**Trello Card ->**](https://trello.com/c/15kppWd2/1347-incorrect-password-error-no-longer-shown-on-the-sign-in-screen-for-email)
Try signing in using identity with invalid credentials. You should see something like this:
> Show error message when login fails.

- projects/Mallard/android/app/src/main/AndroidManifest.xml
- projects/Mallard/ios/Mallard/Info.plist
- projects/Mallard/ios/Podfile.lock
- projects/Mallard/package.json
- projects/Mallard/src/App.tsx
- projects/Mallard/yarn.lock
The previous implementation as feared did not work.
This appears to have done the trick but we shall need to keep an eye on it. 
This "temporarily" disables analytics data collection which can then be turned on later using JS rather than the nuclear option. This gives us room in the future for collection via consent.
I have also added the JS library to ensure it is turned off when the app starts up.
> fix: Disable Analytics Belt and Braces

- projects/Mallard/android/app/build.gradle
This PR removes the old firebase analytics (core) library declared in build.gradle. We now have a new analytics library declared in package.json
> Removed old firebase analytics lib(core)

- projects/Mallard/fastlane/Fastfile
Build is not processing because it is trying to build with 750, we'll force it to 751 temporarily.
> Set build number to 751

- projects/Mallard/fastlane/Fastfile
This reverts commit a55d0df8fe5d6d007452b396405ba1b1bbddd3e6.
The build number should be incremented from the latest testflight build.
> Revert "Set build number to 751 (#1242)"

- projects/Mallard/android/app/build.gradle
This change bumps the base version code to the current value of the android release APK. This will allow us to release beta/internal test versions to users.
> Bump android seed version code

- projects/Mallard/src/__mocks__/@react-native-firebase/remote-config.js
- projects/Mallard/src/__mocks__/helpers/locale.ts
- projects/Mallard/src/authentication/authorizers/__tests__/identity-authorizer.spec.ts
- projects/Mallard/src/authentication/lib/__tests__/AccessController.spec.ts
- projects/Mallard/src/components/Lightbox/__tests__/LightboxCaption.spec.tsx
- projects/Mallard/src/components/article/html/__tests__/images.spec.ts
- projects/Mallard/src/download-edition/__tests__/clear-issues.spec.ts
- projects/Mallard/src/download-edition/__tests__/download-and-unzip.spec.ts
- projects/Mallard/src/download-edition/download-todays-issue.ts
- projects/Mallard/src/helpers/__mocks__/locale.ts
- projects/Mallard/src/helpers/__tests__/fetch.spec.ts
- projects/Mallard/src/helpers/__tests__/files.spec.ts
- projects/Mallard/src/helpers/__tests__/issues.spec.ts
- projects/Mallard/src/helpers/__tests__/settings.spec.ts
- projects/Mallard/src/helpers/files.ts
- projects/Mallard/src/helpers/issues.ts
- projects/Mallard/src/helpers/settings.ts
- projects/Mallard/src/helpers/settings/__tests__/defaults.android.spec.ts
- projects/Mallard/src/helpers/settings/__tests__/defaults.ios.spec.ts
- projects/Mallard/src/helpers/settings/defaults.ts
- projects/Mallard/src/paths/__tests__/index.spec.ts
- projects/Mallard/src/paths/index.ts
- projects/Mallard/src/push-notifications/__tests__/push-notifications.spec.ts
- projects/Mallard/src/push-notifications/__tests__/push-tracking.spec.ts
- projects/Mallard/src/services/__tests__/errors.spec.ts
- projects/Mallard/src/services/__tests__/logging.offline.spec.ts
- projects/Mallard/src/services/__tests__/logging.spec.ts
On first startup, it detects the users locale and sets that to the default edition. Defaults to UK if locale is not compatible
Also looks to remove hard coded `daily-edition` and bring in universal use of `getSetting('edition')` to support the edition switch in the dev settings.
[**Trello Card ->**](https://trello.com/c/yBUPC5Bi/1361-detect-regional-edition-by-locale)
- Set your locale to something different
- Clean install
- See region based edition
> feat: Default Locale will set Edition

- projects/aws/lib/logging-stack.ts
- projects/logging/application.ts
Until we get a release out errors thrown by the logging backend will result in client side errors in the app which can cause performance issues. This change allows us to sent an environment variable to set the logging service up to always return 200 messages so we can reduce the client side performance impact of this issue.
Hopefully the next release will solve this problem as we'll be reducing the amount of data we log, and not retrying failed requests to the log service.
This is a backend only change - you can see the dashboard (frontend AWS account) for the logging service [here](https://eu-west-1.console.aws.amazon.com/apigateway/home?region=eu-west-1#/apis/2ryhgnliu1/dashboard)
> Add switch to disable logging service

- projects/Mallard/src/components/EditionsMenu/RegionButton/RegionButton.stories.tsx
- projects/Mallard/src/components/EditionsMenu/RegionButton/RegionButton.tsx
- projects/Mallard/src/components/EditionsMenu/RegionButton/__tests__/RegionButton.spec.tsx
- projects/Mallard/src/components/EditionsMenu/RegionButton/__tests__/__snapshots__/RegionButton.spec.tsx.snap
- projects/Mallard/storybook/storyLoader.js
In the spirit of breaking things down, this delivers the Region button for the Editions Menu. It has a selected state and also uses local state to manage to pressed style.
> feat: Edition Menu Region Button

- projects/Mallard/src/helpers/webview.ts
The article's body font size is too small for android. This PR updated the size and line by a small amount for android only.
@prisalcalde are they looking good to you?
Trello card is [here](https://trello.com/c/ItKc90zA/1264-android-increase-font-size-and-line-height)
Screenshots:
| Phone - Before | Phone - After |
|  ---      | ---    |
| ![Screenshot_20200611_124850_com guardian editions](https://user-images.githubusercontent.com/6583174/84401979-cea0b100-abfb-11ea-925e-c40f453a24af.jpg)|![Screenshot_20200611_124813_com guardian editions](https://user-images.githubusercontent.com/6583174/84402219-16273d00-abfc-11ea-9d59-b27b54dad578.jpg)|
| Tab - Before | Tab - After |
|  ---      | ---    |
|![Screenshot_1591894891](https://user-images.githubusercontent.com/6583174/84417661-e1bc7c80-ac0 …
> Updated font size for android in article page

- projects/Mallard/src/helpers/diagnostics.ts
- projects/Mallard/src/screens/settings/help-screen.tsx
To help users to provide us diagnostic info an option is added to the help section to copy diagnostic info into the clipboard.
@prisalcalde please see this screenshot let me know if you want to design/ux change.
> Added an option to copy diagnostic info to clipboard

- projects/Mallard/src/components/article/html/article.ts
- projects/Mallard/src/components/article/html/components/images.ts
- projects/Mallard/src/components/article/types/article.tsx
After further testing of lightbox, I noticed that cartoon images were not opening. 
This is because the index was undefined and therefore the message was not being parsed correctly, this provides a default value if the index isn't defined.
[**Trello Card ->**](https://trello.com/c/d6XXQPgW/1203-lightbox-bugs)
Find a cartoon article, usually found within the "Comment" section and ensure it opens in lightbox.
> enable lightbox for cartoons

- .github/workflows/validate-app.yml
This adds a workflow to validate and text the Mallard project, with a view to potentially moving this check from teamcity into github actions permanently.
Pros: all viewable within github, no VPN blah blah
Cons: 2 minutes slower
Try this out for a bit and see if the slowness is annoying
> Add validate-app github actions workflow

- projects/Mallard/src/services/remote-config.ts
I noticed an 'unhandled promise rejection' in the android simulator for remote config initialisation. This might prevent that from happening.
> Handle remote config promise rejection.

- projects/Apps/common/src/index.ts
- projects/Mallard/src/components/EditionsMenu/SpecialEditionButton/SpecialEditionButton.stories.tsx
- projects/Mallard/src/components/EditionsMenu/SpecialEditionButton/SpecialEditionButton.tsx
- projects/Mallard/src/components/EditionsMenu/SpecialEditionButton/__tests__/SpecialEditionButton.spec.tsx
- projects/Mallard/src/components/EditionsMenu/SpecialEditionButton/__tests__/__snapshots__/SpecialEditionButton.spec.tsx.snap
- projects/Mallard/src/components/EditionsMenu/SpecialEditionButton/styles.ts
- projects/Mallard/src/components/front/image-resource.tsx
- projects/Mallard/storybook/storyLoader.js
Component build of the Special Edition Button:
- Takes in a paired down style object which will be given to it by tools
- `devUri` in `ImageResource` is to help with showing images that are not on the device in Storybook
- Default styles for the button are provided in case for any reason we have an issue with the style object from the endpoint (belt and braces). This has been confirmed with Ana.
- Provides shared types in `common` to help put together a contract for the data required for this component
- Expiry takes a Date object and turns that into whatever the local date is for the device.
> Feat: Special Edition button

- projects/Mallard/src/services/errors.ts
When there is an error with posting a log, we send it to the error service. Which then trys to log the error in the logging service, which then sends an error to the error service..... and so on!
No need to log errors in the logging service.
> chore: Remove the logging from the Error service

- projects/backend/capi/articleTypePicker.ts
> Interviews now pull the article template

- projects/Mallard/src/services/__tests__/logging.offline.spec.ts
- projects/Mallard/src/services/__tests__/logging.spec.ts
- projects/Mallard/src/services/logging.ts
- projects/Mallard/src/services/remote-config.ts
This adds a switch to enable/disable the client side logging to editions-logging.guardianapis.com. 
I think this could be useful as a temporary thing for when the backend service is messed up (hopefully rare but more likely at the moment till it stabilises), but also more permanently even when the backend is reliable as it might allow us (if we switch firebase analytics back on) to e.g. switch off logging on ios9 devices, since we're never going to fix any issues we see in the logs. 
Release, verify that logs are still getting posted according to firebase switch
> Add remote config switch around logging.
